### ISSUE TITLE
Add support for Dart analysis server

### ISSUE THREAD

**Issue by AdrienLemaire** [dense-analysis/ale#1005]
Related issue: https://github.com/w0rp/ale/issues/1002 (dartanalyzer is too slow)

The analysis server is about 10 times faster than the command-line analyzer (hence latency should go from 9+s to ~0.9s).
Specifications of the protocol: https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html

Recommendation initially given by @wilkerson at https://github.com/dart-lang/sdk/issues/31108#issuecomment-336928324

**Comment by w0rp** [comment]
I'll close this as ALE supports a Dart [language server](https://github.com/natebosch/dart_language_server) which wraps the analysis server.

**Comment by natebosch** [comment]
As a heads up - `dart_language_server` is going to stop getting updates. The Analysis server that ships with the SDK now supports a `--lsp` flag to run in LSP mode. It should be a mostly drop in replacement, though it's not quite up to feature parity yet.

**Comment by w0rp** [comment]
Okay, I'll reopen this, and someone can add support for that. Closing issues often gives people a nudge to do something about them.

**Comment by jmdevin** [comment]
How difficult would it be to add support for this? I'm relatively new to coding in general, but I am interested in getting analysis server support with dart. I spent a little while looking at at, but I'm not sure how I would add the '--lsp' flag to the command to start the server. Would this be something someone inexperienced could tackle?

**Comment by w0rp** [comment]
Have a look at existing linter definitions. It shouldn't be difficult.

**Comment by jmdevin** [comment]
@natebosch Is there an estimated date when [dart_language_server](https://github.com/natebosch/dart_language_server) will stop receiving updates? It seems like I managed to get ALE working with the analysis server, but I'm having more difficulty with another [plugin](https://github.com/neoclide/coc.nvim).

**Comment by w0rp** [comment]
Open a pull request when you have something that will work, and I'll have a look.

**Comment by natebosch** [comment]
`dart_language_server` should be relatively stable for the time being, but it won't be getting further updates. I'd recommend switching to the analysis server as soon as possible - I've switched over all my personal usage.

Here is some vimscript that finds the right command to start up the analysis server with the `--lsp` flag: https://github.com/natebosch/vim-lsc-dart/blob/8edbb6f49a3014ac3cf4c28965bc6722618ee9b0/ftplugin/dart.vim#L6-L19
