### ISSUE TITLE
[Request] Groovy linter

### ISSUE THREAD

**Issue by cmlaverdiere** [dense-analysis/ale#1089]

**Comment by alex-shamshurin** [comment]
is it http://codenarc.sourceforge.net/ ?

**Comment by nafarlee** [comment]
I am not familiar with any Groovy specific linters, but the output of `groovyc` itself is fairly good at identifying syntax errors.

**Comment by nafarlee** [comment]
I might submit a PR for this if I get a chance. Haven't written much VimL yet, but writing a checker plugin doesn't seem too difficult.

**Comment by w0rp** [comment]
It's not too difficult. The easiest way is to look at one of the existing ones and the tests for it, and create new files that are similar to what has been written before.

**Comment by nafarlee** [comment]
Actually, quite surprisingly, nothing in the default Groovy installation has something that would work well as a linting command:
- Neither `groovy` nor `groovysh` have an option that causes parsing without executing the file if no errors exist
- `groovyc` doesn't attempt to execute the file, but it potentially generates a ton of `.class` files in the same directory if no errors exist

`groovyc` does have an argument that allows setting the output directory for the `.class` files, so maybe these could be redirected to `tmp` or something. However, this does cause quite a few unnecessary writes. Does any other current "linter" have this issue?

At this point, it might make more sense to just implement the aformentioned `codenarc`.

**Comment by alinoekialo** [comment]
A groovy language server exists: https://github.com/prominic/groovy-language-server maybe it could help to speed up the implementation.

**Comment by lithammer** [comment]
https://github.com/nvuillam/npm-groovy-lint is a decent linter for Groovy.

**Comment by peterzhu1992** [comment]
Seeing this PR is opened right now:
* https://github.com/dense-analysis/ale/pull/4495

**Comment by rafaelrojasmiliani** [comment]
seems that this issue can be closed now.
