### ISSUE TITLE
Consider shotening long filenames in the quickfix window

### ISSUE THREAD

**Issue by w0rp** [dense-analysis/ale#1160]
Long filenames in the quickfix window can be annoying. Long filenames could be shortened with a `BufEnter` function or something similar for the quickfix filetype, and a bit of search and replace. This may or may not be a good idea.

**Comment by deltaskelta** [comment]
would it just truncate part of the path based on the current directory? If so, how would it work when the `cwd()` is changed while the window is open?

**Comment by w0rp** [comment]
I'd probably truncate `/very/long/filenames/and/such` `/like...so`. That's probably the best you can do.

**Comment by deltaskelta** [comment]
How about just letting the user define the formatting with vim filename-modifiers?

**Comment by w0rp** [comment]
That might work.

**Comment by w0rp** [comment]
Running the paths through `fnamemodify` will be the best option for this. You can use search and replace with `fnamemodify`, and from there you can do anything to the strings.

**Comment by w0rp** [comment]
I'm going to close this as I won't be implementing it.
