### ISSUE TITLE
Implement support for NeoVim's more robust hightlighting API

### ISSUE THREAD

**Issue by da-x** [dense-analysis/ale#1274]
I am not sure whether it is a limitation of VIM or ALE, so I hope anyone can clarify.

The problem is the following:

Steps:
1) Suppose I'm editing on any file type, and ALE has marked lines 1, 4, and 5 as warnings
2) I remove line 2. Now, ALE should move the highlights of 4 and 5 to line 3 and 4, immediately, and before even re-running the linter. However, it does not happen.

Depending on the file type and on other configs, I need to save or not save the file I'm editing for ALE to relint the file. Depending on the linter, it may take some time to for ALE to update the highlights (suppose a second or so).

The most troubling scenario is where I have, say - 10 lines consisting of 'imports' relevant to the programming language I am editing, and a few of them are marked 'unused imports'. If I go about and try to delete the unused imports starting from the top, I mess up deleting the wrong lines, because the highlights do not move only until I let ALE relint the file.

This issue also applies to intra-line highlights.

The bottom question is: Shouldn't ALE immediately update highlights according to removed added/removed text regarding-less of the linting process?

**Comment by w0rp** [comment]
No, the linters have to be run again to update the highlights.

**Comment by da-x** [comment]
I also want that linters will run again - my suggestion does not preclude that. I only wished for the highlights to point at the old places until the short time the linters finish running. How hard would it be to make this change? Maybe I will look into this myself. Would a pull request be accepted?

**Comment by w0rp** [comment]
Give it a try yourself. I don't think it's possible to implement this.

**Comment by da-x** [comment]
For future reference, in Neovim, the use of Neovim's highlights API (e.g. `nvim_buf_add_highlight`) solves this.

    Nvim allows plugins to add position-based highlights to buffers. This is
    similar to |matchaddpos()| but with some key differences. The added highlights
    are associated with a buffer and adapts to line insertions and deletions,
    similar to signs. It is also possible to manage a set of highlights as a group
    and delete or replace all at once.

**Comment by w0rp** [comment]
Nice, I didn't know about this API which is specific to NeoVim. I'll re-open this issue and someone can have a look at adding support for this newer API, just for NeoVim.

**Comment by w0rp** [comment]
This has been implemented now thanks to @andreypopp.

**Comment by w0rp** [comment]
I'm reopening this. The code for this caused problems mentioned here: #2505

We can close this issue after it works in a stable manner.

**Comment by w0rp** [comment]
A pre-requisite for trying to add this again must include updating the Docker image to run a version of NeoVim new enough to use the new API, and tests which include highlights with lines outside of the range of lines in the given buffer text.
