### ISSUE TITLE
Add support for other TSLint config formats like tslint.yaml

### ISSUE THREAD

**Issue by JulioJu** [dense-analysis/ale#1342]
1.Create a TypeScrit project with a package.json, tsconfig.json and a tslint.yaml and **without** file tslint.json.

If our behaviour is to use tslint.yaml, there is actually no simple customisations. It's annoying for those who use not tslint.json, and only yaml files.

If we replace `tslint.json` by `tslint.yaml` at the line [60 of ale_linters/typescript/tslint.vim](https://github.com/w0rp/ale/blob/a3329ef3fc44a04a2617941eb46deef6c184f4af/ale_linters/typescript/tslint.vim#L60), it resolves the problems. We could load simply the file tslint.yaml if it's in an ancestor directory !

`:let g:ale_typescript_tslint_config_path = 'tslint.yaml'` isn't very useful in the case, because it looking for the exact path were the tslint config file is located.  

Maybe it could be cool to add a new variable. It could be named `ale_typescript_tslint_config_name` "   
```
g:ale_typescript_tslint_config_name       *g:ale_typescript_tslint_config_name*
                                          *b:ale_typescript_tslint_config_name*
  Type: |String|
  Default: `'tslint.json'`

ALE will first discover the ${ale_typescript_tslint_conig_name} path in an ancestor directory.
```
 So maybe we must change the line [60 of ale_linters/typescript/tslint.vim](https://github.com/w0rp/ale/blob/a3329ef3fc44a04a2617941eb46deef6c184f4af/ale_linters/typescript/tslint.vim#L60) by this variable.

**Comment by w0rp** [comment]
I'll close this and other TSLint issues I find, as TSLint is deprecated. I recommend switching to ESLint. https://github.com/palantir/tslint/issues/4534
