### ISSUE TITLE
Add support for Perl 6 / Rakudo Perl 6

### ISSUE THREAD

**Issue by 7ojo** [dense-analysis/ale#1397]
Short in short.. adding support for Perl 6 / Rakudo Perl 6 would be great!

**Comment by nospam2998** [comment]
It seems Perl6 support was added back in [September 2018](https://github.com/dense-analysis/ale/commit/2b2e766dc6df4d05e58c106f51b5444be4efbcea). Could this ticket be closed, or should it have it's title rephrased to clarifying it meaning something more specific?

**Comment by hsanson** [comment]
Thanks for noticing. If there is something missing I think opening a new issue is better.  We have already many issues that are no longer relevant making difficult to see the important ones.
