### ISSUE TITLE
.prettierignore file not used when fixing on save

### ISSUE THREAD

**Issue by cmvanb** [dense-analysis/ale#1425]
## Information
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 14 2018 23:02:54)
MS-Windows 64-bit console version

Operating System: Windows 10 64bit

### :ALEInfo
 Current Filetype: javascript
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_flow_use_home_config = 0
let g:ale_javascript_jscs_executable = 'jscs'
let g:ale_javascript_jscs_use_global = 0
let g:ale_javascript_jshint_executable = 'jshint'
let g:ale_javascript_jshint_use_global = 0
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
let g:ale_javascript_xo_executable = 'xo'
let g:ale_javascript_xo_options = ''
let g:ale_javascript_xo_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'javascript': ['prettier']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(finished - exit code 0) 'cmd /s/c "prettier --version"'
(finished - exit code 0) 'cmd /s/c "cd C:\Projects\evision-test\apiserver && prettier --stdin-filepath C:\Projects\evision-test\apiserver\server.js --stdin < C:\Users\Casper\AppData\Local\Temp\VISCBE6.tmp\server.js"'
(finished - exit code 1) 'cmd /s/c "eslint -f unix --stdin --stdin-filename C:\Projects\evision-test\apiserver\server.js < C:\Users\Casper\AppData\Local\Temp\VITCDFA.tmp\server.js"'

<<<OUTPUT STARTS>>>

Oops! Something went wrong! :(

ESLint: 4.18.2.
ESLint couldn't find the plugin "eslint-plugin-react". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-react is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-react@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.

<<<OUTPUT ENDS>>>

(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(finished - exit code 1) 'cmd /s/c "eslint -f unix --stdin --stdin-filename C:\Projects\evision-test\apiserver\server.js < C:\Users\Casper\AppData\Local\Temp\VIUD195.tmp\server.js"'

<<<OUTPUT STARTS>>>

Oops! Something went wrong! :(

ESLint: 4.18.2.
ESLint couldn't find the plugin "eslint-plugin-react". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-react is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-react@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.

<<<OUTPUT ENDS>>>

(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(finished - exit code 1) 'cmd /s/c "eslint -f unix --stdin --stdin-filename C:\Projects\evision-test\apiserver\server.js < C:\Users\Casper\AppData\Local\Temp\VIVDD3E.tmp\server.js"'

<<<OUTPUT STARTS>>>

Oops! Something went wrong! :(

ESLint: 4.18.2.
ESLint couldn't find the plugin "eslint-plugin-react". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-react is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-react@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.

<<<OUTPUT ENDS>>>

(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo

## What went wrong
Prettier (set as a fixer in ALE for javascript) is being run on files that are supposed to be ignored by 

`.prettierignore`
```
apiserver/
```

When I save a file contained in apiserver/ I expect ALE not to format it with prettier, but it does.

## Reproducing the bug

Steps for repeating the bug:

1. Configure ALE to fix on save with prettier for javascript.
2. Create .prettierignore file in project directory and insert an ignore statement.
3. Edit and save a file in the ignored directory.
4. Observe the ignored file is now formatted by prettier.

The following issue appears to be the same problem, but is marked as resolved for prettier ^1.6.0. My prettier version is 1.10.2.
https://github.com/w0rp/ale/issues/1095

**Comment by flybayer** [comment]
Same problem here, even with `let g:ale_javascript_prettier_use_local_config = 1`

**Comment by heisian** [comment]
Any updates to this??

**Comment by w0rp** [comment]
No, there are no updates. Don't comment asking for updates on GitHub. When someone feels like looking into the bug, they will, and they'll leave a comment or close the issue when a commit has been merged to master.

**Comment by heisian** [comment]
Sure, how about performing triage, then, or is that going to be deferred indefinitely?

Relatedly, I've given up on `.prettierignore` since the `eslint-prettier-plugin` does not support `.prettierignore` at all, which is what we've been using as a part of the eslint fixer. So this actually is not an ALE issue anyways.

**Comment by heisian** [comment]
For anyone finding this thread using `eslint-plugin-prettier`:
https://github.com/prettier/eslint-plugin-prettier/issues/88

**Comment by entropitor** [comment]
@w0rp The bug is supposedly fixed in eslint-plugin-prettier but I'm still having the same issue

**Comment by gadzhimari** [comment]
Still not working. I'm using vim 8.0 and eslint-plugin-prettier 3.0.1. My ale configuration:
```
let g:airline#extensions#ale#enabled = 1

let g:ale_linters = {
\ 'javascript': ['eslint', 'flow'],
\ 'typescript': ['tsserver', 'tslint'],
\ 'typescript.tsx': ['tsserver', 'tslint'],
\}

let g:ale_fix_on_save = 1
let g:ale_sign_column_always = 1
let g:ale_fixers = {
\ 'javascript': ['prettier', 'eslint'],
\ 'scss': ['prettier'],
\ 'css': ['prettier'],
\ 'typescript': ['prettier', 'tslint'],
\}
```

**Comment by w0rp** [comment]
It's still not working because no one has fixed it yet.

**Comment by gadzhimari** [comment]
> It's still not working because no one has fixed it yet.

Ok. Got it. Is it problem with prettier itself or ale side?

**Comment by w0rp** [comment]
I'm not sure. Someone who is familiar with prettier can look into it. Maybe the working directory needs to be set differently.

**Comment by ballercat** [comment]
For anyone still having this problem.

AFAIK it's always been possible to pass specific CLI flags to prettier through ALE. I use this in my `.vimrc` to handle special configs in special projects:

```vim
autocmd BufNewFile,BufRead ~/special/* let g:ale_javascript_prettier_options = "--config ~/special/.prettierrc"
```

to extend this to use a specific `.prettierignore` use the `--ignore-path` flag

```vim
autocmd BufNewFile,BufRead ~/special/* let g:ale_javascript_prettier_options = "--config ~/special/.prettierrc --ignore-path=~/special/.prettierignore"
```
I guess it's not a _direct_ fix to ALE itself, but it seems like it already supports this functionality. I kind of assumed this is how you're supposed to do it.

**Comment by Draiken** [comment]
I don't believe this is an ALE issue. Like other tools, they follow an ignore file but will allow command line arguments to override those.

Adding `file.js` to my `.prettierignore` will ignore it when running `prettier` with no args but will not ignore it when passing the file as a CLI argument `prettier file.js`.
You can observe the same behavior with some git pre-hooks that run things on specific files.

Since ALE likely (not familiar with the internals) calls the CLI with whatever file is in the buffer, it will override any configured ignores.

I have this exact same problem with rubocop.

**Comment by w0rp** [comment]
Okay, that makes sense. I'll close this issue, in that case. If you want to ignore specific files in Vim, you can use buffer variables to change which files are affected by fixing files.
