### ISSUE TITLE
Strip shebangs when stdout is used

### ISSUE THREAD

**Issue by Taluu** [dense-analysis/ale#1445]
When trying to lint php files, which uses the `stdout` buffer (And thus the `read_buffer` mode), if there's a shebang in the file and a `declare`, `namespace` directive in the php file, it triggers a lint error.

According to https://bugs.php.net/bug.php?id=74783, it's not really considered a bug, because on executable php scripts, it should be ignored by the interpreter - and it is, because it uses bash / zsh / ... So on `php -l file.php`, it is not an error, but it is one on `cat file.php | php -l`.

So, we should either strip shebangs from the input if `read_buffer` is `1` (or at least add an option for that ?), or change the mode for php validation ? But then, IIRC, it wouldn't be able to syntax check on real-time...

WDYT ?

**Comment by w0rp** [comment]
The way to fix this is to throw the error away.

**Comment by w0rp** [comment]
This can be fixed for the PHP linter by adding `'< ' . ale#Escape(l:temporary_filename)` to the command, and creating the temporary file with the shebang line removed. The line numbers will have to be changed when the line is removed.

**Comment by Taluu** [comment]
But what if the file is not saved yet ? The strength of the stdout is that the file is not saved yet, so errors are fixed before it's saved ?

I just tried `:!php -l %t`, and it appends `t` to the filename. Unless you meant `php -l %` ?

**Comment by w0rp** [comment]
`%t` is a special formatting marker replaced with a temporary file containing the contents of the buffer.

Turns out, that doesn't work anyway, so editing a temporary file before piping it in will work better.

**Comment by Jorengarenar** [comment]
From what I see, the problem no longer occurs.
I tried the aforementioned PHP as a file, as a not written to disk buffer `file.php` and as buffer which I've manually `setf php`.
In each case linting was working normally.

@Taluu, could you verify?

**Comment by Taluu** [comment]
It's been since I used Ale, but according to https://github.com/php/php-src/commit/c5f1b384b591009310370f0b06b10868d2d62741 it was fixed in 2019

**Comment by Jorengarenar** [comment]
@Taluu Ah, then I think you can close the issue?

**Comment by Taluu** [comment]
Sure, done :)
