### ISSUE TITLE
Flow-typed ignored in vim

### ISSUE THREAD

**Issue by thanasis00** [dense-analysis/ale#1467]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May  8 2017 15:44:54)
MacOS X (unix) version

Operating System: macOS High Sierra 10.13.3

### :ALEInfo

```
Current Filetype: javascript
Available Linters: ['eslint', 'flow', 'jscs', 'jshint', 'standard', 'xo']
  Enabled Linters: ['flow']
 Linter Variables:
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_flow_use_home_config = 0
 Global Variables:
let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%linter% says %s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['flow']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%linter% says %s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = 'X'
let g:ale_sign_info = '?'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = 'X'
let g:ale_sign_style_warning = '?'
let g:ale_sign_warning = '?'
let g:ale_statusline_format = ['X %d', '? %d', '']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - success) /Users/thanasis/grnet/agora-ui/node_modules/.bin/flow
(started) ['/bin/zsh', '-c', '''/Users/thanasis/grnet/agora-ui/node_modules/.bin/flow'' --version; echo']
(finished - exit code 0) ['/bin/zsh', '-c', '''/Users/thanasis/grnet/agora-ui/node_modules/.bin/flow'' --version; echo']
(finished - exit code 0) ['/bin/zsh', '-c', '''/Users/thanasis/grnet/agora-ui/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/Users/thanasis/grnet/agora-ui/src/catalogue/index.js'' < ''/var/folders/8g/n8578x4j7hvfq69nz_h66hyr0000gn/T/vDgQLqa/5/index.js''; echo']
<<<OUTPUT STARTS>>>
{"flowVersion":"0.69.0","jsonVersion":"1","errors":[{"kind":"infer","level":"error","suppressions":[],"message":[{"context":"import { Switch, Route } from 'react-router-dom';","descr":"Cannot resolve module `react-router-dom`.","type":"Blame","loc":{"source":"/Users/thanasis/grnet/agora-ui/src/catalogue/index.js","type":"SourceFile","start":{"line":4,"column":31,"offset":67},"end":{"line":4,"column":48,"offset":85}},"path":"/Users/thanasis/grnet/agora-ui/src/catalogue/index.js","line":4,"endline":4,"start":31,"end":48}]}],"passed":false}
<<<OUTPUT ENDS>>>
```

## What went wrong

I use ALE with flow to check for flow errors, and I receive the following error:

flow says Cannot resolve module `react-router-dom`.

I tried installing flow-typed, and adding the missing library with `flow-typed`, but ALE flow still sees the library as missing.

## Reproducing the bug

Steps for repeating the bug:

1. Create a react project
2. Use the library `react-router-dom`
3. Check the error inside vim about the missing module
4. Install `flow-typed` and run the command `flow-typed install react-router-dom@4.1.1` to install the missing library definition
5. Vim still ignores the definition

If I run `flow check` the results are clean, so flow-typed works with flow to check for these definitions.

Sorry if a similar question has been asked before, but I searched and didn't find anything related.

**Comment by jcelliott** [comment]
I think this might have something to do with flow handling the `check-contents` command different than the `check` command. I have a similar problem where running flow manually reports no errors, but using ALE I get the `Cannot resolve module` error. I manually ran the `check-contents` command reported in `ALEInfo` and got the same error I was seeing from ALE.

**Comment by halvves** [comment]
I am experiencing the same. ALE shows `Cannot resolve module` errors for any import. If I run `flow check` all is golden, but when running the `check-contents` command found in `ALEInfo` I get the same errors.

I found some slightly relevant discussion on `check-contents` in this issue: https://github.com/flowtype/flow-for-vscode/issues/26

**Comment by w0rp** [comment]
The solution for `flow` might be not use it, and switch to using the flow language server instead, and fix this bug, which makes the flow language server unusable: https://github.com/facebook/flow/issues/7009

**Comment by hsanson** [comment]
Related: #2649

**Comment by hsanson** [comment]
Flow is deprecated #3859 #2649
