### ISSUE TITLE
Use CursorHold for LSP hover messages

### ISSUE THREAD

**Issue by w0rp** [dense-analysis/ale#1532]
ALE now supports an `:ALEHover` command for displaying information at the cursor, but we can take this to the next level with the following changes.

1. Re-use the truncated echo function from `ale#cursor` to implement a truncated echo message to avoid interrupting editing.
2. Add support for calling the hover function so it will use the truncated echo.
3. Add support for setting `CursorHold` to trigger the truncated echo version of `:ALEHover`, using the first line of output.
4. Avoid replacing the messages about diagnostics ALE echoes, so problems take priority over basic information. (Detect if the feature is turned on.)

With the series of changes described above, it should be possible to create a version of hover messages where messages display when you move your cursor over things and actually "hover."

**Comment by af** [comment]
A longer-term feature that would be super cool: support neovim's [floating windows](https://github.com/neovim/neovim/pull/6619) if/when they're merged, to show the hover messages right above the cursor!

**Comment by andreypopp** [comment]
> Avoid replacing the messages about diagnostics ALE echoes, so problems take priority over basic information. (Detect if the feature is turned on.)

That’s not always desirable as one can use :ALEHover to fix the problem — the workflow I have when working with Merlin/OCaml — I go to the line with an error and query for types under the cursor to get the proper understanding of the problem.

**Comment by w0rp** [comment]
If you want to see the message, you can type `:ALEHover` anyway. This would be in addition to that.

**Comment by andreypopp** [comment]
> If you want to see the message, you can type :ALEHover anyway. This would be in addition to that.

Ok, I mistakenly thought this applies to :ALEHover too. It makes sense to me then, sorry for the noise.

**Comment by mlwarner** [comment]
I have a naive version of this at https://github.com/mlwarner/ale/compare/master...mlwarner:lspHover but probably can't get to it until this weekend. Still needs

1. To not override the diagnostic CursorHold
2. Unit tests + refactoring to move the truncated message out of the cursor

otherwise it meets the first 3 points required

**Comment by jandudulski** [comment]
> A longer-term feature that would be super cool: support neovim's floating windows (if/when they're merged), to show the hover messages right above the cursor!

it seems that this feature has been released :tada:

**Comment by wizardlink** [comment]
Will this ever be implemented? I have been looking to have similar behavior from `Shougo/echodoc`, and I saw that `:ALEHover` had that already, but only manually.

**Comment by w0rp** [comment]
I have implemented this now at last. I tested it during my day job, and the messages are subtle enough that I turned the new `g:ale_hover_cursor` setting on by default.
