### ISSUE TITLE
(from benmosher/eslint-plugin-import)  packageDir should be relative to eslint config file not cwd

### ISSUE THREAD

**Issue by timhwang21** [dense-analysis/ale#1546]
I ran into the issue described [here](https://github.com/benmosher/eslint-plugin-import/issues/1061), was wondering if you'd consider this a wontfix or not. I ran into this due to `set autochdir` which I'm aware is known to cause breakage. Thanks!

## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 25 2018 22:19:32)
macOS version

Operating System: macOS

## What went wrong

As per the [original issue](https://github.com/benmosher/eslint-plugin-import/issues/1061): `packageDir` is resolved relative to cwd instead of wherever the eslint config is.

## Reproducing the bug

1. In a project using ES6 imports and the `eslint-plugin-import` plugin, open some file in a different dir than `.eslintrc` or wherever the config is; see that imports are resolved correctly
2. Change dir to that of the open file (`set autochdir`, etc.)
3. See that you now get missing import error

**Comment by w0rp** [comment]
Maybe we should prefix the eslint commands with `cd ...`. We'd just have to make sure doing that wouldn't somehow break anything. I wouldn't be surprised if it does.

**Comment by w0rp** [comment]
I'll close this, as the way to get the eslint-plugin-import plugin to work is to create `.js` configuration files with `packageDir` set with `__dirname`. That way, you always get a directory relative to where the configuration file is. It's mentioned in the documentation for this option: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md
