### ISSUE TITLE
Add some fancy GIFs for showing off ALE features

### ISSUE THREAD

**Issue by w0rp** [dense-analysis/ale#1558]
It would be nice to record some fancy GIFs for showing off ALE features in the README. We might want to update the main GIF too.

It might be good to use `git gc` or whatever for removing older binary files from the history, to make cloning fast enough, and consider hosting the images outside of the git repo.

**Comment by gagbo** [comment]
My 2 cents : the balloon feature in gvim with rls ( #1556 ) . If it's worth it I can make a slightly better one (with all tooltips included in the frame).

Maybe the tooltip would be prettier with Gnome DE (I'm on KDE), and the code is not really mine, but seems to be under MIT so we should be good ( https://github.com/nybblesio/rusty-kong )

![peek_gvim_7156ad4](https://user-images.githubusercontent.com/10496163/39944506-350163ec-5567-11e8-9f0a-0a214136a086.gif)

**Comment by w0rp** [comment]
Nice GIF! I'll consider something like that. If you feel like making a new series of GIFs for all of the features, go for it. If I can get a series of smallish GIFs showcasing each thing, I'll use the lot. I'd just want them to have the same general look at feel, maybe with other plugins turned off, so it doesn't look like ALE is showing off things that aren't part of it.

**Comment by w0rp** [comment]
I'm going to link an MP4 I'll add to the description here to the README.
