### ISSUE TITLE
prettier-eslint can not find eslint dependency installed locally

### ISSUE THREAD

**Issue by roneyrao** [dense-analysis/ale#1648]
## Information

**VIM version**

PASTE JUST THE FIRST TWO LINES OF `:version` HERE.
VIM - Vi IMproved 8.1 (2018 May 17, compiled May 24 2018 14:10:12)
macOS version

Operating System: WHAT OS WERE YOU USING?
macOS
### :ALEInfo

PASTE OUTPUT OF `:ALEInfo` HERE. YOU CAN TRY `:ALEInfoToClipboard`.
(finished - exit code 7) ['/bin/bash', '-c', 'cd ''/Users/roneyrao/web/react_demo/src/configs'' && ''prettier-eslint'' --eslint-config-path ''/Users/roneyrao/web/react_demo/.eslintrc'' --stdin-filepath ''/Users/roneyrao/web/react_demo/src/configs/menus.js'' --stdin < ''/var/folders/qt/yllps6vs68986j5t3jx_16c80000gn/T/vyHKVFm/998/menus.js''']

## What went wrong

WRITE WHAT WENT WRONG HERE.
The actual error is locally installed eslint plugin can not be found. The reason is `prettier-eslint-cli` finds `--eslint-config-path` based on where itself is located.

## Suggestion
`--eslint-config-path` is redudant here, `prettier-eslint` will handle this correctly.

## Reproducing the bug

Steps for repeating the bug:

1. Write a list of steps.
eslint and plugins are installed locally in a project, then these plugins will not be found when call `ALEFix`.

2. Otherwise nobody will fix the bug.

**Comment by w0rp** [comment]
What's the bug? Have you installed `prettier-eslint` globally and a plugin locally? You should install both of them locally, or both of them globally.
