### ISSUE TITLE
Auto Imports on Typescript

### ISSUE THREAD

**Issue by FabioAntunes** [dense-analysis/ale#1677]
Does ALE has something similar to [this](https://github.com/Quramy/tsuquyomi#create-es6-import-declaration) 

And here's a [video](http://www.behaveonrails.com/wp-content/uploads/2016/08/tsu-import.webm?_=2) of it in action

Been trying to find in the documentation but can't find it anywhere, so not sure if it exists.

**Comment by w0rp** [comment]
This issue is related: #1466 This can be implemented by adding support for "code fixes" for tsserver. The equivalent is "code actions" support for LSP servers.

**Comment by mboughaba** [comment]
Hi this could be very useful for me. For what I use everyday, ALE does everything that Tsu does except the typescript imports. Now I am left with both plugins...

**Comment by DGmip** [comment]
> Hi this could be very useful for me. For what I use everyday, ALE does everything that Tsu does except the typescript imports. Now I am left with both plugins...

same here - I really want to just use ale, though and this is the only missing feature

**Comment by w0rp** [comment]
I look forward to your pull request. :)

**Comment by geoyws** [comment]
FYI this is already working https://github.com/dense-analysis/ale#2iii-completion

**Comment by w0rp** [comment]
Thanks! I'll close this.
