### ISSUE TITLE
Add support for Microsoft's python-language-server

### ISSUE THREAD

**Issue by w0rp** [dense-analysis/ale#1741]
**Name:** Microsoft's python-language-server
**URL:** https://blogs.msdn.microsoft.com/pythonengineering/2018/07/18/introducing-the-python-language-server/

Microsoft have created a new language server for Python which will be used in VSCode. Once the stand alone component is released, it should be superior to the existing language server tool for Python.

**Comment by meunierd** [comment]
It looks like this has been released: https://github.com/Microsoft/python-language-server

**Comment by petr-k** [comment]
This would be a wonderful addition. Is it a big undertaking to add a new linter?

**Comment by w0rp** [comment]
It should be easy to do.

**Comment by baubler** [comment]
@w0rp apologies if you've answered this before, but why do language servers need to be 'supported'? Isn't the point that the protocol means any client can integrate with any LSP?

**Comment by petr-k** [comment]
I guess the "support" involves invoking the particular language server daemon in the first place?

**Comment by baubler** [comment]
I would imagine that could be left up to user configuration by allowing us to specify the executables per language e.g. `let g:ale_python_language_server = ....`

**Comment by w0rp** [comment]
@baubler Here are the important points.

1. ALE doesn't need to exhaustively list all language servers, you can define how to connect to them yourself. You can do it in vimrc, in your own plugin files, or at any other time. ALE just does that part for you, to save you the hassle of figuring out how to run the servers yourself. The top of the documentation for `:help ale-lint` directs you to `:help ale#linter#Define()`, which describes how to do this.
2. Different servers use different subsets of the protocol, and some implement the protocol incorrectly, and then ALE has to deal with those servers not implementing the protocol correctly. I think the PHP language server for some time would send diagnostics before you even had the chance to send an `initialize` request, and it wouldn't respond to `initialize`. Because people want to actually use that language server, you have to handle that.
3. Because different servers use different parts of the protocol, and the only way to accurately test different features is for people to use them, different servers require different levels of support in ALE. If a Go language server implements more completion functionality than other language server, more work has to be done in ALE to support LSP completion, and so on. The list of language servers ALE supports helps with supporting all language servers in general.

Generally, by supporting language servers, ALE actually does a better job at supporting the language servers that aren't on the list than it would if it pretended to be agnostic to how they work. It's the difference between effectively targeting something and shooting in the dark.

**Comment by astier** [comment]
If I want to define the [python-language-server](https://github.com/palantir/python-language-server) I need to write the following in my init.vim?
```
let g:ale_linters = {'python': ['python-language-server']}
let g:ale_fixers = {'python': ['python-language-server']}
```

Defining in such a way the linter doesn't lint anything and calling _:ALEFix_ says that python-language-server is not a fixer. Also commands like _ALEGoToDefinition_ aren't doing anything.

Could somebody give a simple example how to set the [python-language-server](https://github.com/palantir/python-language-server)?

**Comment by w0rp** [comment]
I'll close this issue. ALE supports Pyright now, another Python language server by Microsoft for Python with type checking, and I think it's the best Python language server available.
