### ISSUE TITLE
quickfix list support for ALEFindReferences and commands for navigating through references

### ISSUE THREAD

**Issue by dimbleby** [dense-analysis/ale#1759]
If I've got a list of references then there's a decent chance that I'll want to cycle through them.

Suggest using the quickfix list on the grounds that: that's what `cscope` and `YouCompleteMe` both do in analogous situations, so it's probably what people are used to.

**Comment by w0rp** [comment]
It's not a good idea. The quickfix list can be used by ALE for displaying problems, and the quickfix list is used by many other plugins for many other reasons. It's better to use a custom buffer in the preview window to avoid any conflicts.

**Comment by dimbleby** [comment]
A command for cycling through the references would do, I guess.  Shall we just re-purpose this issue or would you like a fresh one?

I'm not convinced you're right about using the quickfix list being a bad idea though - so I'm going to take a slightly fuller run at persuading you.

* ALE doesn't use the quickfix list for displaying problems by default.  There's a perfectly sensible and default usage where the location list is used for problems and the quickfix list is used for references
  * It is true that ALE makes use of the location list configurable, and that if you give users enough rope then some of them will hurt themselves...
* The quickfix is indeed used by many plugins for many purposes - and one of them is exactly this!
  * 'Other plugins use the quickfix list' is I think just not convincing.  I mean other plugins use the location list too
  * As above, the use of the quickfix list that I propose here is actually rather standard

Perhaps, at least, an option to use the quickfix list for this purpose??

**Comment by w0rp** [comment]
Okay, I think ALE can support two features.

1. New commands for jumping between results for references.
2. An option to show find references results in the quickfix list.

You could enable both the options for showing problems and references in the quickfix list, but then that will be your problem. The command for jumping around references should be designed so it always works, even when the references are put in the quickfix list.

**Comment by w0rp** [comment]
If someone wants to create a pull request for implementing this, go for it. I might implement this eventually if it seems like it's fun enough.

**Comment by chaucerbao** [comment]
I had thought about creating this same GH issue in the past, but I understand the benefits of keeping a separate list and work was already done to achieve that.  However, I'd also prefer *ALEFindReferences* results to be in a QuickFix list:

1. The ALEPreviewWindow doesn't display the contents of the line where the reference is found.  This is helpful to differentiate between finding a function/class/variable in an *import* statement, versus finding a location where it's actually being used.
2. The ALEPreviewWindow disappears once you jump to one of the results.  Related to above, if the result I selected is not what I'm looking for, I can't get back to the results.
3.  As @dimbleby mentioned, it seems to be common to use the QuickFix window for a jumplist like this.  So, I believe that users are accustomed to the QF interface, and also already have QF bindings to help with navigation.
4.  Less custom code that replicates, to an extent, existing functionality.  Again, debatable, because I understand why you'd want a separate list.  I just lean towards common conventions.

**Comment by w0rp** [comment]
It might be good to add a command for re-opening the preview window too, similar to how Unite.vim let's you re-open search results.

**Comment by jamesob** [comment]
FWIW I've filed a patch that fixes this if anyone's desperate: https://github.com/w0rp/ale/pull/2644

**Comment by cf91** [comment]
I would LOVE if there were commands for populating certain output into locationlist or quickfix on demand. So ALEFindReferences would go to ALE's preview window, but you could also have ALEFindReferencesQF ALEFindReferencesLL (or some other means of accomplishing this if that's not clean).

I have plenty customization for how I use ll/qf in my workflow and it's important. As long as you are not automatically setting list content without consent, which you shouldn't be unless opted-in, I agree, just let us manage what we put in our lists.

**Comment by krishan** [comment]
Just a hint for those (like me) longing for this feature: As a workaround, it's possible to use this workflow:
* `:ALEFindReference` to open ALE's preview window
* `:cb` (short for `:cbuffer`) to read the content of ALE's preview window into the quickfix list
* you can now cycle using the standard quickfix commands (like `:cn`)
* or use `:copen` to open and inspect the quickfix list

**Comment by hsanson** [comment]
Related Issues:
 - #2866
 - #3128 
 - #3493 
 - #3457

From #3457 I get that vim 8.0 and latest neovim support quickfix-ID (see :h quickfix-ID) that would allow plugins to use quickfix windows without conflicting each other.  Could also allow ALE to have different quickfix windows for the different features it offers. For example use loclist for current buffer linter errors, a quickfix for project level (see #3599) linter errors, and another quickfix for listing found references.

**Comment by daliusd** [comment]
I have created PR to fix this with tests and etc. I have not done anything with `quickfix-ID` as I don't need that. If someone has ideas how this feature should look like it is good time to say it while I am on it.
