### ISSUE TITLE
Add support for fish_indent as a fixer

### ISSUE THREAD

**Issue by duganchen** [dense-analysis/ale#2148]
**Name:** fish_indent
**URL:** http://fishshell.com/docs/current/commands.html#fish_indent

The FISH shell ships its own formatter, **fish_indent**, and I think it would work well as an ALE fixer.

I've found one implementation so far of getting it integrated with ALE:

https://github.com/nthapaliya/dotfiles/blob/aef2e112f5207fb63ba1c492b08697fbb2be17fb/home/.config/nvim/init.vim

This project integrates fish_indent with "gq":
https://github.com/dag/vim-fish/

**Comment by neersighted** [comment]
The naive implementation in an init.vim won't work without `shell=/usr/bin/fish`, because `fish_indent` is a function. Still, this should be possible.

**Comment by duganchen** [comment]
fish_indent is an executable as of FISH 2.7.1.

**Comment by w0rp** [comment]
Done in #3576.
