### ISSUE TITLE
Have -fno-color-diagnostics default for clangcheck

### ISSUE THREAD

**Issue by ghost** [dense-analysis/ale#2188]
When I tried out Ale with clangcheck and clangtidy, I got these escape codes (color codes) in the warnings from clangcheck showing in the quickfix pane. Making it impossible to navigate to that file.

I found out that adding the line below fixed the problem:
let g:ale_cpp_clangcheck_options = '--extra-arg="-fno-color-diagnostics"'
Using clang-check from LLVM version 6.0.0

So my question is - shouldn't that option be default?

Cheers,

Daniel

**Comment by w0rp** [comment]
Yes, I think that should be the default, as long as the option is supported by old enough versions of `clangcheck`.
