### ISSUE TITLE
No linting errors shown in gutter (sign column) when running Vim inside Tmux.

### ISSUE THREAD

**Issue by wir3** [dense-analysis/ale#2197]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec  8 2018 11:23:48)
Included patches: 1-570

Operating System: Arch Linux, fully updated.

## What went wrong

ALE is working absolutely perfectly inside my Urxvt, however, when I run Vim inside a terminal, no error warnings are shown.

I have tried forcing gutters to be shown, which does show the gutters but no errors are shown at all.

Interesting to note, if I remove a ',' (for example), and I run :ALEFix, it will add the comma back. If I run :ALEFix *inside* of Tmux, :ALEFix will do nothing.

I've had a look at issues, and this is pretty much very similar: https://github.com/w0rp/ale/issues/511

My version of Tmux is: 2.8

### :ALEInfo

 Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
 Suggested Fixers: 
  'eslint' - Apply eslint --fix to a file.
  'importjs' - automatic imports for javascript
  'prettier' - Apply prettier to a file.
  'prettier_eslint', 'prettier-eslint' - Apply prettier-eslint to a file.
  'prettier_standard', 'prettier-standard' - Apply prettier-standard to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'standard' - Fix JavaScript files using standard --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'xo' - Fix JavaScript files using xo --fix.
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_ls_executable = 'flow'
let g:ale_javascript_flow_ls_use_global = 0
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_flow_use_home_config = 0
let g:ale_javascript_flow_use_respect_pragma = 1
let g:ale_javascript_jscs_executable = 'jscs'
let g:ale_javascript_jscs_use_global = 0
let g:ale_javascript_jshint_executable = 'jshint'
let g:ale_javascript_jshint_use_global = 0
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
let g:ale_javascript_tsserver_config_path = ''
let g:ale_javascript_tsserver_executable = 'tsserver'
let g:ale_javascript_tsserver_use_global = 0
let g:ale_javascript_xo_executable = 'xo'
let g:ale_javascript_xo_options = ''
let g:ale_javascript_xo_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'javascript': ['eslint']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) /home/caradhras/Development/react/explore-artists/node_modules/eslint/bin/eslint.js
(finished - exit code 127) ['/usr/bin/zsh', '-c', '''/home/caradhras/Development/react/explore-artists/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/home/caradhras/Development/react/explore-artists/src/components/TopArtists.js'' < ''/tmp/vjpcaVY/1/TopArtists.js''']

<<<OUTPUT STARTS>>>
nvm is not compatible with the "npm_config_prefix" environment variable: currently set to "/home/caradhras/.node_modules"
Run `unset npm_config_prefix` to unset it.
/usr/bin/env: ‘node’: No such file or directory
<<<OUTPUT ENDS>>>

(executable check - success) /home/caradhras/Development/react/explore-artists/node_modules/.bin/flow
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''/home/caradhras/Development/react/explore-artists/node_modules/.bin/flow'' --version; echo']
(started) ['/usr/bin/zsh', '-c', '''/home/caradhras/Development/react/explore-artists/node_modules/.bin/flow'' lsp --from ale-lsp']
(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(executable check - failure) xo
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''/home/caradhras/Development/react/explore-artists/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/home/caradhras/Development/react/explore-artists/src/components/TopArtists.js'' < ''/tmp/vjpcaVY/3/TopArtists.js''; echo']

<<<OUTPUT STARTS>>>

<<<OUTPUT ENDS>>>

**Comment by w0rp** [comment]
You may have to change your terminal settings to get Vim to work properly. There are a few terminal settings in Vim for the type of Terminal Vim is rendering to. I suspect this is more a Vim or tmux issue than an ALE issue. Vim handles the rendering logic and so on.

**Comment by w0rp** [comment]
What you might try to do is use the Sign command to set signs yourself with ALE disabled. If that doesn't work, change your settings until it does. If nothing works, you could open a bug report for Vim or tmux.

**Comment by wir3** [comment]
Thanks for the idea. So I've tested that, I can force a sign to be shown manually inside of Tmux. Next, I tried showing errors in a list using 'let g:ale_open_list = 1'. Inside of Tmux, no errors are shown at all whereas outside of Tmux I get a new buffer with errors shown (as I'd expect). It's like the errors are not getting from Vim to Tmux or something.

**Comment by ravenpdev** [comment]
Hi @wir3 
I also had the same problem /usr/bin/env: ‘node’.  no error are showing in vim inside tmux
this is m previous setup: I got a .zshrc file and .zshenv

i remove the export path from .zshenv file and put it inside .zshrc 
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin 

I hope it also works on you.

**Comment by w0rp** [comment]
That makes sense. Sounds like this is just a Tmux configuration issue with PATH or other environment variables being set differently.
