### ISSUE TITLE
Go-to definition doesn't work for me

### ISSUE THREAD

**Issue by Millani** [dense-analysis/ale#2231]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan 07 2019 10:34:10)
Included patches: 1-744

Operating System: Ubuntu 18.04

## What went wrong

I have just installed ALE. It works perfectly to show me where I committed styling mistakes in my code. That is, its main linting features seem to be all working. The only piece I can't make work is the "Go to definition" or "Go to references" features. I am trying it with both R and Python, and I do have `lintr`, `plint` and `tsserver` installed.

## Reproducing the bug

I open an R or a Python file, I define a function then call it. Then I move the cursor on top of the function call. Then I hit `:`, write `ALEGoToDefinition` and hit `<CR>`. My cursor moves down one line and nothing else seems to happen.

### :ALEInfo

 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pydocstyle', 'pyflakes', 'pylint', 'pyls', 'pyre', 'vulture']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Suggested Fixers: 
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:

let g:ale_python_flake8_auto_pipenv = 0
let g:ale_python_flake8_change_directory = 1
let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
let g:ale_python_mypy_auto_pipenv = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_ignore_invalid_syntax = 0
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_use_global = 0
let g:ale_python_pylint_auto_pipenv = 0
let g:ale_python_pylint_change_directory = 1
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy
(finished - exit code 16) ['/bin/bash', '-c', 'cd ''/home/millani/Documents'' && ''pylint''  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/home/millani/Documents/test.py''']

<<<OUTPUT STARTS>>>
************* Module test
test.py:1:0: C0111 (missing-docstring) Missing module docstring
test.py:1:0: C0103 (invalid-name) Function name "myFunc" doesn't conform to snake_case naming style
test.py:1:0: C0103 (invalid-name) Argument name "a" doesn't conform to snake_case naming style
test.py:1:0: C0103 (invalid-name) Argument name "b" doesn't conform to snake_case naming style
test.py:1:0: C0111 (missing-docstring) Missing function docstring

------------------------------------
Your code has been rated at -6.67/10

<<<OUTPUT ENDS>>>

(executable check - failure) flake8
(executable check - failure) mypy
(executable check - failure) flake8
(executable check - failure) mypy
(finished - exit code 16) ['/bin/bash', '-c', 'cd ''/home/millani/Documents'' && ''pylint''  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/home/millani/Documents/test.py''']

<<<OUTPUT STARTS>>>
************* Module test
test.py:6:0: C0305 (trailing-newlines) Trailing newlines
test.py:1:0: C0111 (missing-docstring) Missing module docstring
test.py:1:0: C0103 (invalid-name) Function name "myFunc" doesn't conform to snake_case naming style
test.py:1:0: C0103 (invalid-name) Argument name "a" doesn't conform to snake_case naming style
test.py:1:0: C0103 (invalid-name) Argument name "b" doesn't conform to snake_case naming style
test.py:1:0: C0111 (missing-docstring) Missing function docstring

---------------------------------------------------------------------
Your code has been rated at -10.00/10 (previous run: -6.67/10, -3.33)

<<<OUTPUT ENDS>>>

**Comment by w0rp** [comment]
Some off-by-1 issues where just fixed, so you might want to `git pull` and try again.

**Comment by Millani** [comment]
I just re-installed `ale` and unfortunately the exact same issue persists.

**Comment by Millani** [comment]
@w0rp I just re-installed `ale` and unfortunately the exact same issue persists.

**Comment by w0rp** [comment]
Okay. I have tested the command, and it works. There will something wrong with your configuration. You can try using `:call ch_logfile(expand('~/channel.log'), 'w')` to log all of the messages passing between the language server and ALE to find out what might be wrong.

**Comment by kharazi** [comment]
I have the same issue

**Comment by earonesty** [comment]
same issue, channel.log is empty.... other stuff in ALE works (bar with warnings/errors)

**Comment by olenderhub** [comment]
:ALEInfo in .js file

```
Current Filetype: javascript
Available Linters: ['eslint', 'fecs', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint']
 Suggested Fixers:
  'eslint' - Apply eslint --fix to a file.
  'fecs' - Apply fecs format to a file.
  'importjs' - automatic imports for javascript
  'prettier' - Apply prettier to a file.
  'prettier_eslint', 'prettier-eslint' - Apply prettier-eslint to a file.
  'prettier_standard', 'prettier-standard' - Apply prettier-standard to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'standard' - Fix JavaScript files using standard --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'xo' - Fix JavaScript/TypeScript files using xo --fix.
 Linter Variables:
let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
 Global Variables:
let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'scss': ['prettier'], 'javascript': ['prettier']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'scss': ['sasslint'], 'html': [{'handlebars': ['ember-template-lint']}, 'tidy'], 'javascript': ['eslint']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
```

doesn't work for me in .js file (:ALEGoToDefinition), also I have troubles with Completion from plain ALE (with installed deoplate it works, but I think it's from deoplate source and from my understanding ALE can do this also without deoplate). Find reference too doesn't work.

I know that is not my issue, but I think it could be a similar problem.

**Comment by w0rp** [comment]
I think this issue is out of date.

@olenderhub You issue is that `eslint` is the only thing you have enabled, and it doesn't provide language server features. `tsserver` does, if you install TypeScript.

**Comment by abitrolly** [comment]
@w0rp I do have the same problem with Python. Is there a bug with `mypy` or `pyright`? Or maybe  I need to enable other linters? 
```
Available Linters: ['bandit', 'flake8', 'jedils', 'mypy', 'prospector', 'pycodestyl
e', 'pydocstyle', 'pyflakes', 'pylama', 'pylint', 'pyls', 'pyre', 'pyright', 'vultu
re']
  Enabled Linters: ['flake8', 'mypy', 'pylint', 'pyright']
```

**Comment by w0rp** [comment]
I use Pyright with ALE, and it works fine for me. You might need to change your Pyright configuration file or your settings in ALE until it works. I use something like this for my project. (`pyrightconfig.json`)

```
{
  "venvPath": "./",
  "venv": "ve",
  "pythonVersion": "3.6",
  "include": [
    "module_one",
    "module_two"
  ],
  "exclude": [
    "ve"
  ],
  "reportUnusedVariable": false,
  "reportUnusedClass": false,
  "reportUnusedFunction": false,
  "typeCheckingMode": "off"
}
```

Note that I have type checking turned off in my project for now, which might not be what you want.

I'll lock this issue as this is an ancient one, and people should open new issues for bugs.
