### ISSUE TITLE
How to use Lombok in vim with "Ale" ?  ENV:oracle jdk8, maven

### ISSUE THREAD

**Issue by GavinGuan24** [dense-analysis/ale#2242]

**Comment by GavinGuan24** [comment]
someone know it ?

**Comment by w0rp** [comment]
Please add a description for your issue. It's not obvious what you are asking here. Then maybe someone who knows Java can help you. This is the first time I've ever heard of Lombok.

**Comment by GavinGuan24** [comment]
ok. Let me explain briefly "Lombok". This is URL (https://projectlombok.org/).
Official description: Project Lombok is a java library that automatically plugs into your editor and build tools, spicing up your java.
Never write another getter or equals method again, with one annotation your class has a fully featured builder, Automate your logging variables, and much more.
---------------
After I install oracle jdk8 on alpine linux, I found that ale is in effect on my vim. But, The function of the lombok annotation is marked as error by ale.
---------------
Actually, the Compile can pass, and "my_project.jar" can run.

**Comment by GavinGuan24** [comment]
And I try to that.
```
let g:ale_java_javac_options = "-cp lombok.jar"
```
Or
```
#shell
g_javac = javac -cp lombok 
# vimL
let g:ale_java_javac_executable = "g_javac"
```
But, All Failed.

**Comment by GavinGuan24** [comment]
Maybe "Lombok" is too new. Not many people are using this.

**Comment by Me1onRind** [comment]
```
let g:ale_java_javac_options = "-cp lombok.jar"
```
I think you can use absolute path, such as
```
let g:ale_java_javac_options = "-cp /home/xxx/.m2/xx/xxx/lombok.jar"
```

**Comment by andys8** [comment]
Changing the java options broke the integration with the `maven` classpath. Replacing the executable path instead seems to work for me:

```vim
let g:ale_java_javac_executable = "javac -cp ~/.m2/repository/org/projectlombok/lombok/1.18.6/lombok-1.18.6.jar"
```
