### ISSUE TITLE
C/C++ compiler flag -MMD creates -.d file

### ISSUE THREAD

**Issue by ranebrown** [dense-analysis/ale#2265]
Vim version: 8.1
OS: macOS Mojave 10.14.3

I am using the flag `-MMD` to generate dependency files to determine when a header has been changed. Since more compiler flags are now being parsed this flag causes a file with the name of `-.d` to be generated in the working directory.

I believe this is related to #2131 (possibly #2168 or #2194).

This flag should be ignored since it doesn't provide any useful linting information.

Thanks!

**Comment by w0rp** [comment]
>There will probably be some flags we shouldn't pass, like -o for example.

I did tell them. Feel free to create a pull request to filter flags like these out.
