### ISSUE TITLE
quit neovim is slow when ale is working.

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [dense-analysis/ale#2267]
I use neovim in large java projects, when i open a java file, it takes very long time for ale to finish its work. thanks to the async progressing,  i can browse and edit code without any delay, but when I exit vim, ale is still working and it causes significant time lag.
Now I disabled ale in java file, is there any way to fix this problem?

**Comment by RyanSquared** [comment]
Do you mind trimming down the enabled linters? Use `let g:ale_linters` to specify which linters are run; hopefully that can tell us which one in particular is causing issues. Additionally, what method are you using to quit Neovim? It might be possible that `:wq` - if that's what you use - might be blocked for some reason.

Related?: #1960

**Comment by w0rp** [comment]
Google how to profile Vim code, and attach a profiler log.

**Comment by w0rp** [comment]
I'll consider this issue stale now.

**Comment by jeffcasavant** [comment]
@RyanSquared I have this issue as well.  Using `:wq` exhibits the issue but `:x` does not - thanks for the tip.
