### ISSUE TITLE
Add support for xo + typescript

### ISSUE THREAD

**Issue by nikersify** [dense-analysis/ale#2389]
**Name:** xo/typescript
**URL:** https://github.com/xojs/xo

[If configured correctly](https://github.com/xojs/eslint-config-xo-typescript#use-with-xo) `xo` can be used to lint typescript files, in addition to javascript ones.

The implementation should be pretty much the same as in `ale_linters/javascript/xo.vim`, although I've tried blindly copying that file to `ale_linters/typescript/xo.vim` replacing `javascript` with `typescript` but that unfortunately turned out to be too silly to work:

![image](https://user-images.githubusercontent.com/7091471/54886784-0bb04480-4e8c-11e9-9195-e60aad49923b.png)
(output after running `:ALEInfo`)

Thanks in advance!

**Comment by lo1tuma** [comment]
I’ve ran into the same issue today. Enabling xo for typescript would be awesome.

**Comment by chaucerbao** [comment]
This was easy enough. I did the same thing you did, @nikersify; copied the file and replaced references to JavaScript with TypeScript. PR available at #2453.

Running **xo** as a fixer took a few seconds, but that's probably an issue with **xo** itself.

**Comment by hsanson** [comment]
ALE already supports XO linter/fixer for typescript (see #2453).
