### ISSUE TITLE
Support neovim floatwindow

### ISSUE THREAD

**Issue by glepnir** [dense-analysis/ale#2418]
Coc.nvim can show the lsp linter message in the float window。can ale support this feature？

**Comment by gbrlsnchs** [comment]
There are three things I think would be nice to show in a floating window:
- Hover information
- Documentation while navigating the items in popup menu
- Linting info

**Comment by pianocomposer321** [comment]
Any update on this? I would really like to see floating windows implemented.

**Comment by rbhanot4739** [comment]
I would also love to have this feature implemented as it makes vieweing linter messages much user friendly than having them displayed through `echo` or `virtualtext`.

**Comment by hsanson** [comment]
@glepnir with #3341 maybe this can be closed now?

**Comment by derlaft** [comment]
>with #3341 maybe this can be closed now?

Works for me:

![image](https://user-images.githubusercontent.com/852606/104747157-78c35700-5750-11eb-9d52-6d7067299c5d.png)

Big thanks to @kevinclark and everyone else involved.

Related: I wonder if there's a way to automatically turn on `:ALEHover` tips without an actual mouse.

**Comment by savchenko** [comment]
> Works for me:

Have you manually merged the #3341 into own Ale branch?.. Don't see it working with either nvim 0.4.4 or 0.5.0.

**Comment by derlaft** [comment]
> Have you manually merged the #3341 into own Ale branch?.. Don't see it working with either nvim 0.4.4 or 0.5.0.

No, it's this PR: https://github.com/dense-analysis/ale/pull/3470

At the time I wrote the comment, 0.5.0 was not released and I was using nvim-git AUR package. I think it should work with ale@master and latest neovim release.

**Comment by savchenko** [comment]
> I think it should work now with ale@master and the latest neovim release.

Unfortunately it does not. Assuming you refer to the v0.5.0 which is the latest _released_ version of nVim.

**Comment by kevinclark** [comment]
@savchenko Works for me on both 0.5.0 and 0.6.0+dev44 against c5c58f5bf82bf (committed yesterday). It was also working fine on 0.6.0+dev44 and master from back in April, last I updated before I pulled and then downgraded neovim to try to repro your issue.

I suspect it's a config issue. If you'd like to open a new issue with your config and @ me on it, I can take a look.
