### ISSUE TITLE
Add R Markdown (.Rmd) support with R lintr

### ISSUE THREAD

**Issue by cjber** [dense-analysis/ale#2450]
The implementation of the  current linter and fixer for .R scripts I believe would both work with .Rmd files as they currently are. Both of which use the `library('styler')` lint I believe (from [here](https://github.com/tvatter/ale/pull/1)). For example I am using this function:

```
function! Rlint()
        let filename = expand("%:r:t")
        let rcmd "require('styler');
            \styler::style_file(\"" . filename . ".Rmd\")"
        call g:SendCmdToR(rcmd)
endfunction
```
with `'djoshea/vim-autoread'` to auto update the file and `'jalvesaq/Nvim-R'` for the r console connection which works perfectly well with my .Rmd files containing both markdown and R code within chunks. 

I am very new to vim (<1 week) and this is my first post to github so apologies if I make any mistakes or if this seems an overly simple request.

**Comment by tvatter** [comment]
@cjber is totally correct and I can try a PR for that shortly.

For styler, it's just about adding to the list of suggested filetypes in the registry right?

**Comment by tvatter** [comment]
Well, better late than never. I had completely forgotten about that, my bad.

**Comment by statquant** [comment]
Hello, sorry to come back to this but are we supposed to have linting for rmd files ?
For me it works in .r files but not .rmd (with or without a R chunk)

**Comment by tvatter** [comment]
For me, it works. Stupid question, but you have the updated version from ALE (post-June 6, i.e., the date of my PR's merge) right?

**Comment by tvatter** [comment]
So, I just noticed something: in the PR, I used `rmarkdown` as the filetype. Right now, when testing in vim, I openened a `Rmd` file, and the lintr/styler didn't work because it was detected with and `rmd`. Doing `:set filetype=rmarkdown` activated ALE for the file.

**Comment by tvatter** [comment]
To prevent this, I just added `autocmd BufRead,BufNewFile *.Rmd set filetype=rmarkdown` to my `init.vim`.

**Comment by statquant** [comment]
Ah ok, problem is i think 99.99% of people using lintr in vim are using the the nvimr plugin that might expect ft=rmd ...

**Comment by statquant** [comment]
Copied your PR to create another one with rmd

**Comment by tvatter** [comment]
Goog idea, I also use nvim-r and didn't thing of that ^^

**Comment by tvatter** [comment]
Can you please let me know if/when the PR is accepted?

**Comment by w0rp** [comment]
I've merged that now. Thanks!
