### ISSUE TITLE
Support showing insert-completion results alongside LSP completion results

### ISSUE THREAD

**Issue by chenjie199234** [dense-analysis/ale#2465]
if can,how?
if can't,any other plugins suggest?
work on neovim(newest version)

**Comment by w0rp** [comment]
Could you describe this in more detail? I'm not sure that I understand. Are you asking if ALE could have an option to also show what normal insert completion shows for files in addition to what the language servers suggest?

**Comment by chenjie199234** [comment]
@w0rp 
now ale can only complete when i type "." 
the suggestions were coming from lsp,i'm writing ```go```,so they were coming from ```gopls```
can ale show suggestions,which lsp doesn't suggest?
```
package main
import "fmt"
type ThisIsATestForLongNameStruct struct{
        name string
}
func (this *ThisIsATestForLongNameStruct)p(){
        fmt.Println("This is a test for long name struct:",this.name)
}
func main(){
        //i want this to be completed,but it can't
       {
         t:=&ThisIsA
        }
        //when i type "." it will complete by lsp,and show function p()
        {
        t:=&ThisIsATestForLongNameStruct{name:"helloworld"}
        t.
        }
}
```
can ale complete the first situation?
if can,how?i did;n find any config options
if can't,is there any other plugins can enhance ale on this case.

**Comment by w0rp** [comment]
It sounds like you want a setting so ALE can offer regular insert completion results in the completion menu, in addition to the more accurate results that language servers return, is that correct? Note that completions like that may not represent valid symbol names.

**Comment by chenjie199234** [comment]
@w0rp 
yes how to do that

**Comment by w0rp** [comment]
Okay, you can't do that at the moment, but support could be added for that. I'll update the issue title.

**Comment by w0rp** [comment]
I want to do this so I don't have to do my trick of existing Insert Mode to get insert completion results in the list. I think the trick is to sort the completion menu so insert completion results come last, and smart completion results come first.
