### ISSUE TITLE
Add support for pandoc

### ISSUE THREAD

**Issue by pbnj** [dense-analysis/ale#2469]
**Name:** pandoc
**URL:** pandoc.org

I have been contemplating the possibility of using `pandoc` as a fixer for some filetypes.

For example:

Given this markdown file:
```
# GitHub-Flavored Markdown File

    ## Some Malformed header

- bullet a
- bullet b
  - bullet c

some really really really really really really really really really really really really long line
```

With ALE configured to use `pandoc --from gfm --to gfm --columns=80` as a markdown fixer, invoking `ALEFix` would generate:

```
# GitHub-Flavored Markdown File

## Some Malformed header

  - bullet a
  - bullet b
      - bullet c

some really really really really really really really
really really really really really long line
```

Would this be a good idea to implement?
If so, I would also like the pandoc flags to be configurable by the user since pandoc supports various input/output filetypes.

**Comment by petermbenjamin** [comment]
I also would not mind working on a PR for this, granted it is a good idea in the first place.

**Comment by w0rp** [comment]
Sounds like a good idea to me.

**Comment by hsanson** [comment]
Pandoc support as fixer already exists in ALE.
