### ISSUE TITLE
Add support for pyright

### ISSUE THREAD

**Issue by alok** [dense-analysis/ale#2472]
**Name:** foobar
**URL:** https://foo.bar.com

https://github.com/Microsoft/pyright  Like mypy.

**Comment by w0rp** [comment]
https://github.com/Microsoft/pyright/issues/99 I left a comment here asking how a command line utility for starting the language server for other editors like Vim can be built. I think it's worth building that, instead of running it from scratch from the command line.

**Comment by drozdowsky** [comment]
count me in as interested!

**Comment by lkgarrison** [comment]
I'd love to see this. I've tried mypy, pytype, and pyre, and I have to say, pyright has blown me away so far. It's type checker is much better and seems to catch many more edge cases that other checkers simply miss.

I'd be happy to help add support for pyright in Ale. However, I'm uncertain how to go about doing that. 

It sounds like we need two things:
  1. An ALE linter plugin for pyright. My best guess is this would look similar to the [pyre linter](https://github.com/dense-analysis/ale/blob/master/ale_linters/python/pyre.vim)?
  2. To be able to run [pyright](https://github.com/Microsoft/pyright) as a Language Server.

While I'm fuzzy on the details of how LSP-compatible fixers are configured, I'm more uncertain about how to go about #2. From microsoft/pyright#99, it sounds as though [pyright](https://github.com/Microsoft/pyright) itself can't currently be used to run the Language Server in a stand-alone way. But I'm unclear why not. Is it too tightly coupled with VSCode? Or would it need an additional CLI command to start up the language server that they don't want to add? I was surprised to see them pushing for a separate project that would expose the language server for other IDEs. It seems a bit silly and against the spirit of LSP to develop a tool like that that is only compatible with VSCode?

Any advice on how best to proceed would be great!

**Comment by w0rp** [comment]
I think someone needs to write a pyright CLI tool in JavaScript/TypeScript. At the moment clients can only connect to pyright if they are written in JavaScript/TypeScript and import the JavaScript/TypeScript code.

**Comment by fannheyward** [comment]
@alok @lkgarrison you can use pyright in vim/neovim with coc-pyright+coc.nvim, and they all works well with ALE. https://github.com/fannheyward/coc-pyright

**Comment by LanderMoerkerke** [comment]
To elaborate on this further, I see that there is a node cli app available: https://github.com/microsoft/pyright/#command-line

So it is possible possible to use it without importing it trough JS/TS code.

**Comment by dsifford** [comment]
It's now possible to add this to ALE as of https://github.com/microsoft/pyright/pull/810

If someone doesn't jump on this and open a PR before me, I might be able to get to it in the next week or two (time allowing).

**Comment by w0rp** [comment]
I'll probably try to add support for this myself.

Some rambling on what I want to do with it... I was thinking of using `pyls` with the `mypy` plugin, because I use Django at work, but then there's no VSCode marketplace extension for `pyls`, which my colleagues use a lot. `pyright` doesn't support a `mypy` plugin for working out the actual types of Django models, but I figure I can just write a `makemigrations` hook that automatically writes `.pyi` files to get around that.

**Comment by w0rp** [comment]
I've added `pyright` as a supported tool now, and it is enabled by default. I was able to set up the configuration so the virtualenv path and executable are automatically set by default, and can be overridden. See `:help ale-python-pyright` for the options and installation instructions for `pyright` itself.
