### ISSUE TITLE
Add support for Zig LSP (when built)

### ISSUE THREAD

**Issue by RyanSquared** [dense-analysis/ale#2484]
**Name:** Zig LSP
**Tracking Information:** https://github.com/ziglang/zig/issues/615

**Comment by w0rp** [comment]
ALE supports `zls` now, and that's the semi-official language server now. That should do the job.

**Comment by creepinson** [comment]
Unfortunately, I still don't see a way to fix code using zls with zig fmt 😕

**Comment by w0rp** [comment]
@creepinson Add an issue to add a fixer for that, or even a pull request.
