### ISSUE TITLE
ale_open_list open both quickfix and loclist

### ISSUE THREAD

**Issue by h0m3** [dense-analysis/ale#2487]
## Information

**VIM version**

NVIM v0.3.5
Build type: Release
Operating System: Arch Linux

## What went wrong

When using `ale_open_list = 1` both location list and quickfix are open. Location list is open in a new window and quickfix is open in a buffer. Even with `ale_set_quickfix = 0`

With `ale_open_list = 0` no quickfix or loclist is open.

## Reproducing the bug

1. Set `ale_open_list = 1` and `ale_set_quickfix = 0` in your vimrc
2. Open a file with errors
3. Navigate trought buffers with bnext and bprevius

### :ALEInfo

 Current Filetype: vim
Available Linters: ['ale_custom_linting_rules', 'vint']
  Enabled Linters: ['vint']
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_vim_vint_executable = 'vint'
let g:ale_vim_vint_show_style_issues = 1
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 0
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = v:null
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 0
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'llvm': ['llc'], 'asm': ['gcc'], 'html': ['tidy'], 'objective-c': ['clang'], 'c++': ['clang', 'gcc'], 'objective-c++': ['clang'], 'go': ['gofmt'], 'markdown': ['prettier'], 'vue': [], 'lua': ['luac'], 'bash': ['shell'], 'python': ['flake8', 'autopep8'], 'vim': ['vint'], 'c': ['clang', 'gcc'], 'php': ['php'], 'rust': ['cargo', 'rustfmt'], 'elixir': [], 'csh': [], 'hack': [], 'json': ['jq'], 'nasm': ['nasm']}
let g:ale_linters_explicit = 1
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = v:null
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 1048576
let g:ale_open_list = 1
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 0
let g:ale_warn_about_trailing_whitespace = 0
  Command History:

**Comment by w0rp** [comment]
The code looks like this.

```vim
        if g:ale_set_quickfix
            if !ale#list#IsQuickfixOpen()
                silent! execute l:open_type . 'copen ' . str2nr(ale#Var(a:buffer, 'list_window_size'))
            endif
        elseif g:ale_set_loclist
            silent! execute l:open_type . 'lopen ' . str2nr(ale#Var(a:buffer, 'list_window_size'))
        endif
```

I don't think it's possible for ALE to be doing this. Try disabling other plugins, or grep through your plugins for `lopen` and `copen` to see what is opening the window.
