### ISSUE TITLE
Pylint from stdin and on-the-fly python linting

### ISSUE THREAD

**Issue by cbosoft** [dense-analysis/ale#2522]
Hope this is the right place to post this! Didn't want to necro related issue #590.

Pylint [will add support](https://github.com/PyCQA/pylint/pull/2746) in v2.4 for reading from stdin, and users of the dev version have access to this now. Can ALE take advantage of this now? If so, how?

**Comment by w0rp** [comment]
That's good. :+1:  We can support that with a version check, but linters have to be declared as something that only runs when files are changed on disk, or as you type. I'll have to think about how to support linters that are sometimes one or the other, depending on the version.

**Comment by JanSurft** [comment]
Is it easy hard-code this feature into my current ale version?

**Comment by w0rp** [comment]
With the some of the code from @oliverwiegers, the supported I added for dynamically computing `lint_file` (#3285), and some additional fixes I just added, Pylint now checks code as you type in newer versions, and still only checks the file on disk in older versions. If you're running Pylint 2.4.0 or greater, it should just work.
