### ISSUE TITLE
Support mapping between different filesystems

### ISSUE THREAD

**Issue by w0rp** [dense-analysis/ale#2556]
Sometimes linters can be run with a different filesystem than the filesystem Vim is being run in, so `/foo/bar.txt` could be at `/other/path/bar.txt` in another filesystem. This happens most commonly with Docker. To support mapping between filesystems, a setting could be added which would convert `%s` and `%t` paths sent to linters from the host filesystem to the guest filesystem, and the paths from the guest filesystem can be mapped to the host filesystem when reading linter results and receiving events from language servers.

Because some linters and fixers need to read the directory the file is in, instead of the filename, we should add support for possibly a `%d` format for the directory of the file, or consider `%s:h` formatting and so on for applying `filename-modifiers` like with `fnamemodify()` to the format markers. This will make it easier to map filenames correctly. We should add functions for getting mapped filenames either way, that are documented, to `command.vim`, in case someone needs to get a path on the filesystem in a really particular way.

**Comment by sandrodz** [comment]
IF anyone is interested, I've a VM ready to test dockerised phpcs with ALE: https://github.com/wearede/DevCeption
```
vagrant up
./push.sh
```
inside VM
```
cd /srv/docker/services/phpcs/
sudo docker build . -t phpcs
```
https://github.com/wearede/DevCeption/blob/master/provisioning/roles/php-tools/files/phpcs is copied to /usr/local/bin/phpcs so it is available via cli in current users path. So running phpcs in terminal will work as if it is installed on the machine directly.

**Comment by sandrodz** [comment]
Any update on this issue? I've updated my tools, and got newer version of ALE where .phpcs is not detected at all.

**Comment by w0rp** [comment]
I have now added support for mapping paths between the local and remote file systems. See `:help ale-lint-other-machines`. This should allow anyone to run their tools via Docker, virtual machines, on remote servers, etc.

**Comment by w0rp** [comment]
I just pushed a commit which implements `filename-modifiers` for `%s` and `%t` in commands, limited only to `:h`, `:t`, `:r`, and `:e`, which won't cause any strange issues. See `:help ale-command-format-strings`.
