### ISSUE TITLE
Autoflake support

### ISSUE THREAD

**Issue by LanderMoerkerke** [dense-analysis/ale#2562]
Add support for [Autoflake](https://pypi.org/project/autoflake/) to make Python code more clean.

**Name:** Autoflake
**URL:** https://pypi.org/project/autoflake/

Autoflake has extra options to:

* Remove unused imports
* Expand "star" imports
* Remove duplicate keys
* Remove unused variables

These extra options would benefit every programmer involved in Python because we need more clean code.

**Comment by circld** [comment]
Just giving a heads-up that I've added this fixer in the following PR; https://github.com/dense-analysis/ale/pull/2985. 🍻
