### ISSUE TITLE
Problem: FindProjectRoot() in autoload/ale/python.vim 

### ISSUE THREAD

**Issue by cs86661** [dense-analysis/ale#2609]
```vim
    for l:path in ale#path#Upwards(expand('#' . a:buffer . ':p:h'))
        if !filereadable(l:path . '/__init__.py')
            return l:path
        endif
    endfor
```
I think `if !filereadable(l:path . '/__init__.py')` should be changed to `if filereadable(l:path . '/__init__.py')` ?
So it will return `l:path` when found `__init__.py`.

BR

**Comment by hsanson** [comment]
In a large python project you can find __init__.py files all over the place. This file is not a good indicator of a root project dir.

The comment in that function explicitly states this:

```
" If it is not possible to find the project root directory
" via init file, then it will be defined as the first directory found
" searching upwards through paths, including the current directory, until no
" __init__.py files is found.
```

Where init file refers to either MANIFEST.in, setup.cfg, pytest.ini, or tox.ini.
