### ISSUE TITLE
cmake-format doesn't find cmake-format.yaml/json/py

### ISSUE THREAD

**Issue by notskm** [dense-analysis/ale#2624]
## Information

**VIM version**
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 25 2019 22:02:57)
MS-Windows 64-bit console version

NVIM v0.4.0-1134-g615fc6826

Operating System: Windows 10 1903

## What went wrong

I have `cmake-format` set up as a fixer and ALE configured to fix on save. When run through ALE, `cmake-format` is using its default settings to format my `CMakeLists.txt` files. It should be automatically detecting and using `cmake-format.yaml/json/py` in the current working directory.

If I manually run `cmake-format CMakeLists.txt -i`, it finds and uses my `cmake-format.yaml` file.

## Reproducing the bug

1. Set up `cmake-format` as a fixer
2. Create a cmake-format.yaml file with non-default settings in the current working directory
3. Run ALEFix in a CMakeLists.txt file

### :ALEInfo

 Current Filetype: cmake
Available Linters: ['cmakelint']
  Enabled Linters: ['cmakelint']
 Suggested Fixers: 
  'cmakeformat' - Fix CMake files with cmake-format.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_cmake_cmakelint_executable = 'cmakelint'
let g:ale_cmake_cmakelint_options = ''
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'cmake': ['cmakeformat'], 'cpp': ['clang-format'], 'python': ['autopep8']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'cpp': ['clangcheck', 'clangtidy', 'cppcheck']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = ''
let g:ale_sign_info = ''
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = ''
let g:ale_sign_style_warning = ''
let g:ale_sign_warning = ''
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) cmakelint
(finished - exit code 0) 'cmd /s/c "cmake-format -i  C:\Users\MyName\AppData\Local\Temp\nvimEDT0r8\1\CMakeLists.txt"'
(executable check - failure) cmakelint
(executable check - failure) cmakelint

**Comment by w0rp** [comment]
The working directory probably needs to be set to the directory containing the file.

**Comment by sergeyklay** [comment]
I solved this issue by installing PyYAML:
```bash
pip install --upgrade cmake-format PyYAML
```

**Comment by fabi1cazenave** [comment]
Confirming the bug, even with PyYAML installed and the working directory set to the directory containing the configuration file. I’ve tried other configuration formats (`.cmake-format.py`, `.cmake-format.json`) but that didn’t work either.

`cmake-format CMakeLists.txt -i` works fine when run manually (= it finds my `.cmake-format.yaml` configuration), but when run by ALE it ignores my configuration file.

**Comment by avemilia** [comment]
Currently as a workaround you can use `let &l:equalprg = 'cmake-format -'` in cmake's ftplugin and use commands that involve `=`.

**Comment by hsanson** [comment]
Reported fix by #3725
