### ISSUE TITLE
Pylint ignores Message Control whe opening new buffer

### ISSUE THREAD

**Issue by ychnh** [dense-analysis/ale#2628]
I have in my ~/.pylintrc to ignore commenting on code style.
[MESSAGES CONTROL]
disable=C,F,I,R,W

It works fine with ale when I open a file in neovim.
But when I open another buffer, pylint starts showing errors for code style.

**Comment by w0rp** [comment]
Do you have any more information? I don't know if this is an ALE bug, a pylint bug, or a configuration issue.

**Comment by ychnh** [comment]
Finally had time to look back this issue.
You are right in one of your suggestions. It was something to do with configuration.
I originally had a buffer specific linter setting in my .vimrc which caused PEP8 to load on a new buffer.
`let b:ale_linters = ['pylint', 'nvcc', 'gcc']`

I changed it  to the following.

```
let g:ale_linters = {'python':['pylint'],
\'cuda':['nvcc'], 
\'c':['gcc']}
```

I have a question. Is there a way to create a configuration without using a dictionary?
