### ISSUE TITLE
Is there a way to pipe ale from vim quick fix to fzf quick fix?

### ISSUE THREAD

**Issue by ryanbas21** [dense-analysis/ale#2634]
There exists https://github.com/fszymanski/fzf-quickfix

I currently have Ale configured to open the quick fix list when there are errors, is there a way to make it open the errors in this fzf plugin quick fix?

I know with fzf you can pipe basically anything into it, but I'd like to if possible default Ale to open its errors in the fuzzy quick fix.

**Comment by w0rp** [comment]
I don't know what that is.

**Comment by w0rp** [comment]
There's nothing planned for this at this time. I'll close this for now.
