### ISSUE TITLE
[golangci-lint BUG] golangci-lint lint package option invalid

### ISSUE THREAD

**Issue by arthurkiller** [dense-analysis/ale#2635]
## Information

**version**

* vim 8.1 @ osx
* go: 1.12.7
* ale : latest tag
* golangci-lint : latest tag

## What went wrong

when I set `let g:ale_go_golangci_lint_package=1`, the golang ci lint stopped work.

### :ALEInfo

 Current Filetype: go
Available Linters: ['bingo', 'gobuild', 'gofmt', 'golangci-lint', 'golint', 'gometalinter', 'gopls', 'gosimple', 'gotype', 'govet', 'golangserver', 'staticcheck']
   Linter Aliases:
'gobuild' -> ['go build']
'govet' -> ['go vet']
  Enabled Linters: ['golangci-lint', 'golangserver']
 Suggested Fixers: 
  'gofmt' - Fix Go files with go fmt.
  'goimports' - Fix Go files imports with goimports.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 300
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 20
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '[%severity%] [%linter%] %code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 500
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'zsh': ['shell'], 'go': ['golangserver', 'golangci-lint'], 'c': ['gcc', 'clangd'], 'proto': ['protoc-gen-lint'], 'cpp': ['clangd', 'g++', 'clang++'], 'csh': ['shell'], 'python': ['pyls', 'autopep8', 'flake8']}
let g:ale_linters_explicit = 1
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '[%severity%] [%linter%] %code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = 'xx'
let g:ale_sign_info = '??'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = 'xx'
let g:ale_sign_style_warning = '??'
let g:ale_sign_warning = '??'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) golangci-lint
(finished - exit code 3) ['/bin/bash', '-c', 'cd ''/Users/arthur/golang/src/icode.baidu.com/baidu/bdrp/jarvis'' && ''golangci-lint'' run --fast']

<<<NO OUTPUT RETURNED>>>

(executable check - success) go-langserver
(started) ['/bin/bash', '-c', '''go-langserver'' -gocodecompletion']
(finished - exit code 3) ['/bin/bash', '-c', 'cd ''/Users/arthur/golang/src/xxxxxxxxxxxxxxxxxxxxxxxxxx/bdrp/jarvis'' && ''golangci-lint'' run --fast']

<<<NO OUTPUT RETURNED>>>
(executable check - success) go-langserver
(started) ['/bin/bash', '-c', '''go-langserver'' -gocodecompletion']

**Comment by arthurkiller** [comment]
![image](https://user-images.githubusercontent.com/11133870/60867306-16d18980-a25d-11e9-8c28-6c228ae6ad40.png)

seems the package option did not work properly

**Comment by arthurkiller** [comment]
after I disable the package option

```

 Current Filetype: go
Available Linters: ['bingo', 'gobuild', 'gofmt', 'golangci-lint', 'golint', 'gometalinter', 'gopls', 'gosimple', 'gotype', 'govet', 'golangserver', 'staticcheck']
   Linter Aliases:
'gobuild' -> ['go build']
'govet' -> ['go vet']
  Enabled Linters: ['golangci-lint', 'golangserver']
 Suggested Fixers: 
  'gofmt' - Fix Go files with go fmt.
  'goimports' - Fix Go files imports with goimports.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 300
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 20
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '[%severity%] [%linter%] %code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 500
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'zsh': ['shell'], 'go': ['golangserver', 'golangci-lint'], 'c': ['gcc', 'clangd'], 'proto': ['protoc-gen-lint'], 'cpp': ['clangd', 'g++', 'clang++'], 'csh': ['shell'], 'python': ['pyls', 'autopep8', 'flake8']}
let g:ale_linters_explicit = 1
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '[%severity%] [%linter%] %code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = 'xx'
let g:ale_sign_info = '??'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = 'xx'
let g:ale_sign_style_warning = '??'
let g:ale_sign_warning = '??'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) golangci-lint
(finished - exit code 1) ['/bin/bash', '-c', 'cd ''/Users/arthur/golang/src/xxxxxxxxxxxxxxxxxxxx/bdrp/jarvis'' && ''golangci-lint'' run ''task.go'' --fast']

<<<OUTPUT STARTS>>>
task.go:170:12: expected operand, found '>' (typecheck)
		sdf = 1>>>
		         ^
task.go:183:2: expected ';', found 'if' (typecheck)
	if err != nil {
	^
task.go:217:25: expected ';', found error (typecheck)
func (t *Task) Reboot() error {
                        ^
<<<OUTPUT ENDS>>>

(executable check - success) go-langserver
(started) ['/bin/bash', '-c', '''go-langserver'' -gocodecompletion']
```

**Comment by saschagrunert** [comment]
Hm, I’m not sure but to me it looks more like an issue related to golangci lint and cgo rather than ale...

**Comment by arthurkiller** [comment]
@saschagrunert  I'm not sure, but seems ale did not support this option properly.

**Comment by hsanson** [comment]
This seems to have been fixed in recent versions of ALE. Now package setting is on by default and is confirmed to work well for many.
