### ISSUE TITLE
Error/Warning detection

### ISSUE THREAD

**Issue by LongChampion** [dense-analysis/ale#2640]
I am trying to use `lightline` and `ale` for `Vim`. But i get a strange problem, please look at the screenshot below:
![image](https://user-images.githubusercontent.com/47727306/60982985-613d2e00-a363-11e9-97c1-b59dc80ec998.png)
There are 2 warning in this code (at line 7 and 16). But `ale` only count 1 warning at line 16, because it can't determine the "message" throw by GCC is "error" or "warning". Does anybody see this problem before and how to fix it?

**Comment by LongChampion** [comment]
My `vimrc' is quite simple:
![image](https://user-images.githubusercontent.com/47727306/60983723-aada4880-a364-11e9-99dc-c2ff4e3b0162.png)

**Comment by w0rp** [comment]
I have returned!

Could you provide some minimal steps for repeating this bug, perhaps with some example code or a project we can look at?
