### ISSUE TITLE
Document how to add your own LSP connections better

### ISSUE THREAD

**Issue by Huxpro** [dense-analysis/ale#2641]
It looks like ALE is intended to involve into a full-fledged LSP client. 
So why not support arbitrary executable that conforms with LSP protocol instead of ad-hoc linters supports? (Or do we already have this).

**Comment by w0rp** [comment]
Yeah, ALE already does that. If you want to connect to any type of LSP server, see `:help ale#linter#Define`. The minimum amount of information you'll need is as follows.

1. An `executable` and `command` for the server for stdio connections OR an `address` for TCP connections.
2. A `name` for describing the "linter." (ALE's name for any program ALE runs or connects to for finding problems.)
3. `lsp` needs to be set to `'stdio'` for stdio connections, or `'socket'` for TCP socket connections.
4. `project_root` needs to be set to describe where the roots of projects are.

You can call the function to define new linters in your vimrc file, in other plugin files, or define linters in runtimepath in `ale_linters/language/linter_name.vim`. The best way to find examples is to look at ALE's codebase for the pre-defined linters.

The way ALE works is that it comes with as many pre-defined linters as possible, and then if you want anything else ALE doesn't support out of the box, you can add as many extra linters as you want.

**Comment by w0rp** [comment]
The documentation is already pretty good, but after writing that I think it would be worth adding a section to the documentation which says pretty much that. I'll re-open this and tag it with the documentation label.

**Comment by EdgarOrtegaRamirez** [comment]
I'm in the same situation, I would like to add this javascript server to my config since it is not officially supported by Ale: https://www.npmjs.com/package/javascript-typescript-langserver

**Comment by OJFord** [comment]
For what it's worth, I was searching the issues hoping for exactly the sort of description you gave above - so definitely worth having in the readme. (There are sections that say 'using any enabled Language Server Protocol linters' that would be great if links to a section on how to enable a language server.)

**Comment by w0rp** [comment]
I've added some documentation for this now, with a brief description of how to define your own LSP linters. See `:help ale-lint-language-servers`.
