### ISSUE TITLE
Clang-format Fixer Should Use `--assume-filename`

### ISSUE THREAD

**Issue by paulreimer** [dense-analysis/ale#2645]
When using the `clang-format` fixer, the clang-format option to re-order `#include`s requires knowing the name of the file being edited. When providing file contents from stdin (as ALE does), the `--assume-filename` parameter should be used with the name (and/or full path) to the file.

This allows the following sort order when fixing `foo.cpp` (`--assume-filename "foo.cpp"`), so that `foo.h` will be sorted first:
```
#include "foo.h"
#include "a.h"
#include "b.h"
```

I'm not sure how to make sure this argument is supplied correctly by `ALE` (it is dynamic based on filename, so I don't think `g:ale_c_clangformat_options` can be used for this.)

**Comment by RyanSquared** [comment]
If you look throughout this repository for 'stdin-filename' you may find something useful. I'll check when I can to see if I can get a simple fix.

**Comment by w0rp** [comment]
Now merged. Thanks @paulreimer! :+1:
