### ISSUE TITLE
Suggestion: Add g:ale_fixers_ignore for better parity with g:ale_linters_ignore

### ISSUE THREAD

**Issue by dsifford** [dense-analysis/ale#2651]
As the title implies, my suggestion is adding in a `g:ale_fixers_ignore` option to ignore defined fixers from running.

My use case is specifically with `prettier`. I am contributing to a project that uses `eslint` to fix and not prettier, but I have prettier options defined globally because I use it so ubiquitously.

It would be nice if I could add `g:ale_fixers_ignore=["prettier"]` while working on that project to disable prettier and still use my `b:ale_fixers` workflow that I currently am using.

Thanks for considering.

**Comment by w0rp** [comment]
ALE runs either all linters it can for a filetype or as many as can be supported for a filetype by default, so ignoring only some makes sense for linters. It doesn't make sense for fixers, which are only ever explicitly enabled.

What you should do is select fixers with `b:ale_fixers` in your ftplugin file, and when editing a file in a particular project, you set the List so it doesn't include the fixers you don't want. You can also use `g:ale_pattern_options` to easily set the same variable based on matching paths with regular expressions.

**Comment by dsifford** [comment]
That is what I currently do, however if the fixers are defined as a buffer variable set in ftplugins, the moment you change files the variable gets overwritten. So it absolutely would be useful to have an ignore option particularly for prettier because I usually want it applied to all files unless I’m contributing to a project that doesn’t use it.

**Comment by w0rp** [comment]
I don't want to add too many options if there's a way you can already accomplish something. I only added `ale_linters_ignore` as it was the easiest way to disable diagnostics for LSP tools, while still using them for other purposes, and also making it easy to disable only a subset of linters, where many are enabled by default.

You can continue using `b:ale_fixers`.

**Comment by dsifford** [comment]
@w0rp But that's the thing. There is not currently a way to accomplish what I'm describing.

If i set `b:ale_fixers` to contain prettier in `ftplugins/javascript.vim`, there is no way to disable it or ignore it in a single project if that project doesn't use prettier.

If I reset `b:ale_fixers` in a file that I'm working on in that project, that works up until the moment that I switch to another file.

Does that make sense?

**Comment by w0rp** [comment]
The way to disable it is to either use `g:ale_pattern_options` to configure different settings for each project, use a plugin for setting different settings for buffers for different projects, use `exrc`, or implement logic for determining the value of settings in your `ftplugin` files.
