### ISSUE TITLE
Javascript linter error for ESlint 6.1.0 (latest version) 

### ISSUE THREAD

**Issue by DemonCloud** [dense-analysis/ale#2669]
## Information

**VIM version**

NeoVim 0.3.8

Operating System: Mac OS X 10.14.6

## What went wrong

Linter check error

## Reproducing the bug

when I was update to Eslint 6.1.0 lastest version

I think this error is because the Eslint 6 change command

it looks like Eslint search the config or plugins node-modules into project dir

In general, Eslint should look for the corresponding configuration or plugin in the global node-modules.

### :ALEInfo

<img width="1440" alt="Screen Shot 2019-07-31 at 4 45 49 PM" src="https://user-images.githubusercontent.com/7436361/62197787-112a1800-b3b3-11e9-89ca-425512537294.png">

(Sorry, I don't know how to copy the ALEInfo into clipboard)

**Comment by richyfish** [comment]
Use :ALEInfoToClipboard to copy into clipboard.

What is the output of the following command from your terminal? : 


```
cd /Users/yijun/Project/pay-console
eslint /Users/yijun/Project/pay-console/src/pc_console/views/payment.js
```

**Comment by DemonCloud** [comment]
@richyfish 
I was found some error.  is not about ALE, 
Node 12.8.0 + Eslint 6.1.0,  Eslint search the node_module relative the .eslintrc.js file position

it means: 
if the .eslintrc.js hold on my $HOME dir
```text
/Users/yijun/.eslintrc.js
```
Eslint command while search plugin or config base on "/Users/yijun/node_modules".

But the global node_module is located "/usr/local/lib/node_modules". 

So, the Eslint can not find dependent node packages
