### ISSUE TITLE
Indent Sizes based on Linter rules

### ISSUE THREAD

**Issue by qauff** [dense-analysis/ale#2673]
I'm starting a new project and typically I would create an `.editorconfig` file, but I've noticed IDEs like Visual Studio Code would actually read the linter's config (in my case, `.eslintrc`) and set the indent size and type for the IDE based on the lint rules.

Is it possible to do something like this with Ale + Vim?

This stackoverflow thread describes what I'm suggesting in more detail:
https://stackoverflow.com/questions/46719726/set-vim-indentation-setting-based-on-local-styleguide-file

-----

So my vim instance defaults to using 4 spaces per tab for most of my development purposes. But lets say I cd into a project like the following

```
.
├── .eslintrc
└── src
    ├── bar.js
    └── foo.js
```
and the .eslintrc file specifies a indentation setting of 2 spaces.

```
/* .eslintrc */

{
    "indent": ["error", 2]
}
```
How can I configure vim to automatically change to the indentation setting defined in the local .eslintrc file?

**Comment by w0rp** [comment]
This is out of scope for what ALE handles. ALE handles checking files with linters, fixing files, and supports some language server functionality. editorconfig is probably the right way to go for what you want to do. This plugin is probably good: https://github.com/editorconfig/editorconfig-vim
