### ISSUE TITLE
Feature: Add option 'g:ale_highlight_linenrs' (default to 0) to control 'numhl'-based highlighting

### ISSUE THREAD

**Issue by bluz71** [dense-analysis/ale#2680]
Hello ALE maintainers,

Pull request [#2637](https://github.com/dense-analysis/ale/pull/2637) added line number highlighting to Neovim via the new `numhl` feature.

As a Vim syntax theme maintainer, this enhancement is a regression, as noted in [this comment](https://github.com/dense-analysis/ale/pull/2637#issuecomment-517976840).

`numhl`-based highlighting was also added to the GitGutter in [this pull request](https://github.com/airblade/vim-gitgutter/pull/632).

In GitGutter `numhl`-based highlighting is controllable via a flag `g:gitgutter_highlight_linenrs` (defaulting to off).
I request the same happen here, a new flag `g:ale_highlight_linenrs` (defaulting to off).

There is already a pull request in the queue [#2678](https://github.com/dense-analysis/ale/pull/2678), but it keeps the default behaviour to on. I would also recommend using the term `g:ale_highlight_linenrs` (plural) instead of `g:ale_highlight_linenr` (singular).

I **strongly** believe it should be disabled by default since it causes problems with many Vim themes.

What problems? 

An inability to distinguish between the current line and lines with errors since they will all be marked with `LineNr` styling. If one then styles via the new highlight groups then `LineNr` styling will disappear on lines with errors (again making it hard to distinguish the current line).

Another issue is that Vim and Neovim will not look the same, and currently there is no ability to make them look the same without a flag such as `g:ale_highlight_linenrs`. Consistency (by default) between the two editors is a worthwhile aim.

Many thanks.

**Comment by delphinus** [comment]
Agree. I used almost the same syntax to define highlights for the `*SignLineNr` families as the `*Sign` ones. But it lacked the viewpoint you mentioned, so now I also think `*SignLineNr` should be disabled in default.

**Comment by w0rp** [comment]
All of this sounds fine to me. I left a comment on the PR.

**Comment by bluz71** [comment]
Superb. Many thanks to all involved.
