### ISSUE TITLE
Support single loclist per tab instead of per window

### ISSUE THREAD

**Issue by timlag1305** [dense-analysis/ale#2682]
I often use vim with multiple windows and I have `g:ale_open_list` set to 1. This opens a `loclist` for each window. I would like it to open one `loclist` per tab instead of per window.

**Comment by w0rp** [comment]
ALE can support opening only one loclist window for the same buffer split across two tabs, but won't support showing one loclist for two different buffers. Each buffer has its own loclist and loclist window.

**Comment by marcinn** [comment]
Hi @w0rp. As a workaround, is possible to automatically close loclist window when switching active buffer, and reopen if needed for a new one?

**Comment by w0rp** [comment]
Hello, I'm not sure I understand.

**Comment by marcinn** [comment]
Hi. 

You said that each buffer has its own loclist and loclist window. And yes - if you split the window, each pane will have own loclist window. 

![Screenshot from 2019-11-07 12-51-11](https://user-images.githubusercontent.com/139032/68386986-8e58ec00-015d-11ea-87b2-4e7b09a468f7.png)


But if you close loclist windows, you can open loclist for the current (active) pane by `:botright lopen`, like this:

![Screenshot from 2019-11-07 12-52-00](https://user-images.githubusercontent.com/139032/68387067-bb0d0380-015d-11ea-936d-6ff447d83379.png)
  
![Screenshot from 2019-11-07 12-52-12](https://user-images.githubusercontent.com/139032/68387073-be07f400-015d-11ea-9ddf-f0cccac0ffd0.png)

The newly opened loclist window will stay at the bottom of the window, it would display issues related to the active pane (top), and it will be just one on the screen (the goal).

It would be nice to have stable placement of the window containing list of issues.
