### ISSUE TITLE
Explicit ALEGoToDefinition <argument> 

### ISSUE THREAD

**Issue by bogdan** [dense-analysis/ale#2684]
I think it is good to have an ability to specify an argument of `ALEGoToDefinition`  if one knows the place they want to go instead of taking a word under the cursor.

``` 
:ALEGoToDefinition MyClass
```

Builtin tagging functionality supports that by calling `:tag <argument>`.

**Comment by w0rp** [comment]
This is not possible, as Language Server Protocol requires a position in the document to find the definition of something. See here: https://microsoft.github.io/language-server-protocol/specification#textdocumentpositionparams
