### ISSUE TITLE
Missing VSP features

### ISSUE THREAD

**Issue by XVilka** [dense-analysis/ale#2692]
Based on the ccls [comparison table](https://github.com/MaskRay/ccls/wiki/Editor-Configuration)

- [ ] documentHighlight - https://microsoft.github.io/language-server-protocol/specification#textDocument_documentHighlight 
- [ ] signatureHelp - https://microsoft.github.io/language-server-protocol/specification#textDocument_signatureHelp
- [ ] codeLens - https://microsoft.github.io/language-server-protocol/specification#textDocument_codeLens
- [ ] onTypeFormatting - https://microsoft.github.io/language-server-protocol/specification#textDocument_onTypeFormatting

**Comment by w0rp** [comment]
I'll close this, as this doesn't describe a bug or feature request. You can open issues for each language server protocol feature. I found one that already exists: https://github.com/dense-analysis/ale/issues/1530

**Comment by XVilka** [comment]
Done:
- https://github.com/dense-analysis/ale/issues/2716
- https://github.com/dense-analysis/ale/issues/2717
- https://github.com/dense-analysis/ale/issues/2718

**Comment by w0rp** [comment]
Thanks!

**Comment by EvanCarroll** [comment]
[It would be great to know what LSP features ALE supports and doesn't support.](https://www.reddit.com/r/rust/comments/mjmwbs/ale_vs_youcompleteme_vs_cocrust_vs/) Without a TODO list or matrix/comparison, it's hard to decide on an LSP client. It seems now though with these issues opened (thanks a ton), I can see exactly why ALE has fallen out of favor to newer things like YouCompleteMe and CoC (neither of which I have any experience with).
