### ISSUE TITLE
Rust Clippy could show suggestions

### ISSUE THREAD

**Issue by benmp** [dense-analysis/ale#2698]
Currently, Clippy warnings do not come across into ALE with the "help" or "note" lines

> ALE
![image](https://user-images.githubusercontent.com/9081154/62973060-9a3d4800-bdd2-11e9-9f9f-80732000ebe4.png)

> command line
![image](https://user-images.githubusercontent.com/9081154/62973086-a88b6400-bdd2-11e9-9759-06a734d5d594.png)

It would be really sweet if this was configurable, or if it was parsed in a way where the suggested fix ```try this: Rc::<i32>::clone(&x)``` was presented in the location list.

It looks pretty hairy to pull out this information, at least given the message content from :ALEInfo

```
"message":"for further information visit https://rust-lang.gith
    ub.io/rust-clippy/master/index.html#clone_on_ref_ptr","rendered":null,"spans":[]},{"children":[],"code":null,"level":"he
    lp","message":"try this","rendered":null,"spans":[{"byte_end":68,"byte_start":59,"column_end":14,"column_start":5,"expan
    sion":null,"file_name":"src/main.rs","is_primary":true,"label":null,"line_end":6,"line_start":6,"suggested_replacement":
    "Rc::<i32>::clone(&x)"
```

```
"rendered": "warning: using '.clone ()' on a ref-counted pointer\n --> src/main.rs: 6: 5\n  |\n6 |     x.clone();\n  |     ^^^^^^^^^ help: try this: `Rc: :<i32 >: :clone(&x)`\n  |\n  = note: requested on the command line with `-W clippy: :clone-on-ref-ptr`\n  = help: for further in formation visit https: //rust-lang.github.io/rust-clippy/master/index.html#clone_on_ref_ptr\n\n"
```

**Comment by RyanSquared** [comment]
Apologies for not being able to test this at the moment. Does `:ALEDetail` show this information?

**Comment by benmp** [comment]
Thank you for the fast response.  `:ALEDetail` does in fact appropriately show the information I was looking for albeit with no colors.  I promptly remapped it to <leader>d.  Thanks!

![image](https://user-images.githubusercontent.com/9081154/62975127-f609d000-bdd6-11e9-87e6-d203cdb5552a.png)

**Comment by RyanSquared** [comment]
We don't get colors from RLS or other sources, so that's the only thing we have. Glad to have helped.
