### ISSUE TITLE
Texlab linter not run

### ISSUE THREAD

**Issue by AntoinePrv** [dense-analysis/ale#2699]
## Information

**VIM version** 
NVIM v0.3.7
Build type: Release

**Operating System**
macOS Mojave 10.14.6

## What went wrong

Thank you for ALE, it's a great project that I use daily!

The Texlab linter does not seem to run. Specifically, looking at `:ALEInfo`, all Latex linters are enabled, but TexLab is the only one not present in the command history.

I think my ALE setup is working alright since I use it without running into any issues with Python.

## Reproducing the bug

1. Install Texlab binary (in `~/.local/bin` in my case). Texlab is properly found in `PATH` and can be executed in the terminal.
2. Open a `.tex` file in vim
3. Start writing unproper Latex, no completion or linting appear, even after `:ALELint`
4. Run `:ALEInfo`, `texlab` appears in both available and enabled linters. However, in the Command history, all linter are run (tentatively as they are not installed), except for `texlab`

### :ALEInfo
```
 
 Current Filetype: tex
Available Linters: ['alex', 'chktex', 'lacheck', 'proselint', 'redpen', 'texlab', 'textlint', 'vale', 'writegood']
   Linter Aliases:
'writegood' -> ['write-good']
  Enabled Linters: ['alex', 'chktex', 'lacheck', 'proselint', 'redpen', 'texlab', 'textlint', 'vale', 'writegood']
 Suggested Fixers: 
  'latexindent' - Indent code within environments, commands, after headings and within special code blocks.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'textlint' - Fix text files with textlint --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_tex_chktex_executable = 'chktex'
let g:ale_tex_chktex_options = '-I'
let g:ale_tex_lacheck_executable = 'lacheck'
let g:ale_tex_texlab_executable = 'texlab'
let g:ale_tex_texlab_options = ''
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'*': ['remove_trailing_lines', 'trim_whitespace'], 'python': ['black']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'python': ['pyls', 'pydocstyle']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = 'ﱥ'
let g:ale_sign_info = ''
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = 'ﱥ'
let g:ale_sign_style_warning = ''
let g:ale_sign_warning = ''
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) proselint
(executable check - failure) redpen
(executable check - failure) textlint
(executable check - failure) vale
(executable check - failure) write-good
(executable check - failure) chktex
(executable check - failure) lacheck
(executable check - failure) proselint
(executable check - failure) redpen
(executable check - failure) textlint
(executable check - failure) vale
(executable check - failure) write-good
(executable check - failure) alex
(executable check - failure) chktex
(executable check - failure) lacheck
(executable check - failure) proselint
(executable check - failure) redpen
(executable check - failure) textlint
(executable check - failure) vale
(executable check - failure) write-good
```

**Comment by richyfish** [comment]
Try this: 

```
let g:ale_linters = {
    \   'python': ['pyls', 'pydocstyle']],
    \   'tex': ['texlab']
    \ }

```
Explanation:

The 'tex' filetype is not included in the g:ale_linters defaults.   
See  `:help g:ale_linters` for more info

**Comment by AntoinePrv** [comment]
Thank you for the suggestion. I just tried this with the same outcome...
My understanding of the `ALEInfo` above is that if `textlab` is appearing in`Enabled Linters`, it was already activated. Am I correct?

**Comment by hsanson** [comment]
Texlab linter (language server) is broken currently. The ale_linters#tex#texlab#GetProjectRoot(buffer) method for this language server is hardcoded to always return blank. This effectively disables the linter.

As temporary fix it is possible to set a custom project root using `g:ale_lsp_root` configuration.

A correct fix is to modify the ale_linters#text#texlab#GetProjectRoot(buffer) method to find the project root automatically. Unfortunately is not clear how to find a latex project root now (see #2501).

**Comment by w0rp** [comment]
There's no default method for detecting the root of a textab project, so you have to specify what the root of the project is for the linter to run. If someone knows a way to reliably detect the project root, they can create a pull request for it.

The project root isn't hardcoded because it's configurable with `ale_lsp_root`.

**Comment by yrammos** [comment]
@hsanson just to confirm, the temporary fix would be something along the lines of the following?

`let g:ale_lsp_root = {'texlab': '<Project_path_here>'}`

Thanks.

**Comment by hsanson** [comment]
Yes, that should do. If it doesn't please create an issue so is easier for me to track.
