### ISSUE TITLE
mypy notes aren't shown

### ISSUE THREAD

**Issue by anowlcalledjosh** [dense-analysis/ale#2704]
ALE shows `error`s from mypy, but not `note`s. This firstly makes it hard to debug some issues, since mypy often emits a note immediately after an error with more explanation of the types involved or a link to an explanation of the error (and these notes aren't even visible in `:ALEDetail`), and secondly means that adding `reveal_type` to something doesn't show the type of the expression in the editor – you have to go and run mypy by hand to see the result.

It would be nice if mypy's notes could be shown in the editor as well as its errors.

**Comment by w0rp** [comment]
If anyone has some suggestions for how to handle notes, please let us know.

**Comment by Hnasar** [comment]
@w0rp can't we just map `note` outputs to 

`  |ALEInfo.|        - Items with `'type': 'I'`

Sample:

```
x = 1
reveal_type(x)

def foo():
    pass
```

```
$ mypy foo.py
foo.py:2: note: Revealed type is 'builtins.int'
foo.py:4: error: Function is missing a return type annotation
foo.py:4: note: Use "-> None" if function does not return a value
```

**Comment by phodge** [comment]
For anyone else waiting for the patch to land, you can try rolling back mypy to version 0.700 where the `reveal_type()` output had an "error" severity.

**Comment by phodge** [comment]
Another workaround is to create a sed script to rewrite the mypy output and point Ale at that script instead of mypy.

I.e., Create a `~/bin/mypy-escalated-reveal-type` with the following contents:

    #!/usr/bin/env bash
    mypy "$@" | sed -e 's/^\([^:]\+:\([0-9]\+:\)\{1,2\}\) note: Revealed type is /\1 error: Revealed type is /'

And then add the following to your `vimrc.vim`:

    let g:ale_python_mypy_executable = 'mypy-escalated-reveal-type'
    let g:ale_python_mypy_use_global = 1

**Comment by w0rp** [comment]
I've pushed a commit which implements this now, and I've turned on the notes by default, as only the notes in the file you're looking at with line numbers will be displayed. If you don't want to see the notes, you can set `g:ale_python_mypy_show_notes` to `0`.
