### ISSUE TITLE
could add more completion support

### ISSUE THREAD

**Issue by NewUserHa** [dense-analysis/ale#2722]
ALE has `lint, reformat, goto, completion, etc` function. It seems an IDE plugin to me(may wrong).

I searched and found no good linter for vim8 like ALE do. there also is only a formatting tool that is vim-autoformat.

ALE is great. but the completion only supports deoplete.nvim. could make ALE support more completion source like `youcompleteme, mucomplete, etc.` or document how to add custom completion like `jedi-vim`?

thanks!

**Comment by polyzen** [comment]
Just found out `asyncomplete.vim` is now supported as well: https://github.com/dense-analysis/ale/pull/2627

**Comment by w0rp** [comment]
`mucomplete` should work, but i haven't tried it myself. I think if you want to add something to make support for a specific completion plugin better, open an issue for that.

The IDE-like features for ALE are always optional and limited in scope to doing what is somewhat easy to do, in case someone just wants to check their code with tsserver or LSP servers, and maybe use just a few small features like basic completion support, or renaming symbols.

**Comment by NewUserHa** [comment]
ok.
but none summaries the detailed completers ale supported. hope there's someone who is familiar with it will do that.
