### ISSUE TITLE
Better terraform linting

### ISSUE THREAD

**Issue by Funk66** [dense-analysis/ale#2726]
The command `terraform fmt` is a fixer, not a linter. It does output some errors when it is unable to parse a file, but it doesn't provide any useful feedback otherwise. Besides that, the formatting of the error report seems to have changed in recent versions of terraform.

On the other hand, `terraform validate -json`  provides detailed information on syntax errors in JSON format. I started adapting ALE to use this other command and noticed that the linter checks the whole directory instead of reading from stdin, so I guess we can't run it on an unsaved buffer.
Would it make sense to save a copy of the buffer everytime the linter is invoked?
I willing to give it a shot if anybody offers to help.

**Comment by OJFord** [comment]
Note there is a language server that looks pretty good:
https://github.com/juliosueiras/terraform-lsp

**Comment by w0rp** [comment]
Adding a default configuration for `terraform-lsp` is probably a good option.

**Comment by hsanson** [comment]
ALE already supports terraform-lsp, tflint, and soon terraform-ls. I believe this issue is no longer needed given the currently available tools.
