### ISSUE TITLE
Autocmd event not working

### ISSUE THREAD

**Issue by ayroblu** [dense-analysis/ale#2728]
I'm not sure what the issue is here, would love to know how to debug this.
I just started learning rust and in setting up, I wanted my errors to show up (`:lwindow`), so I searched around and I think the autocmd is:

```vim
au FileType rust au User ALELint lwindow
```

However, it just does not run for me.
Also strangely, if I run `:ALELint` my errors go away too (but on save they're there?)

This is puzzling to me, my plugins are pretty much up to date with vim 8.1 

Wondering if someone has a clue of what I can run to debug this

**Comment by w0rp** [comment]
You don't have to create an `autocmd` command to lint files. With the default settings, ALE will check files when you open them or make changes. See `:help g:ale_open_list` for opening the loclist window automatically.
