### ISSUE TITLE
is it possible to showing %code% for pylint like flake8

### ISSUE THREAD

**Issue by NewUserHa** [dense-analysis/ale#2747]
![image](https://user-images.githubusercontent.com/32261870/64109505-48288a80-cdb2-11e9-918c-355c06c83717.png)
![image](https://user-images.githubusercontent.com/32261870/64109529-55457980-cdb2-11e9-8c5a-1acc5e3e9d7c.png)

the error code `wrong-import-order` from pylint is too long for `let g:ale_python_pylint_options='--disable=...'`

I didn't find any info from doc, and I saw pylint seems can do that.
Is it possible for ale?

thanks

**Comment by w0rp** [comment]
See `:help g:ale_python_pylint_use_msg_id`. You can turn that setting on to use the IDs instead of the more descriptive names.
