### ISSUE TITLE
Add tests for usage of Neovim highlight API

### ISSUE THREAD

**Issue by frangio** [dense-analysis/ale#2748]
Code to use the Neovim highlight API was introduced in #2638 without tests, because I couldn’t get them to work. See the PR comments for more information.

**Comment by frangio** [comment]
Commit https://github.com/dense-analysis/ale/commit/67ee2b9586743db4a7224c4f42bbd494373b6a85 patched the tests so they don’t fail on neovim but as far as I can see this is accomplished by skipping some necessary  assertions.

**Comment by w0rp** [comment]
The test coverage is good enough as it is. Some things cannot be tested.
