### ISSUE TITLE
terraform linter tflint throws an error and stopped working

### ISSUE THREAD

**Issue by AlaaSMansour** [dense-analysis/ale#2762]
## Information

**VIM version**
NVIM v0.3.8
Build type: Release

Operating System: macOS 10.14.5 

## What went wrong

When opening a terraform file with nvim I get the following error and it keeps appearing whenever something is typed.

```
Error detected while processing function <SNR>40_NeoVimCallback[29]..<lambda>3[1]..<SN
R>38_ExitCallback[28]..<SNR>37_HandleExit[39]..ale_linters#terraform#tflint#Handle:
line    3:
E714: List required
```
![image](https://user-images.githubusercontent.com/54977713/64669429-d3b0b400-d461-11e9-82f8-07f277e9ac7b.png)

## Reproducing the bug

1. install tflint
2. use the following vim config

```
call plug#begin()
 
Plug 'hashivim/vim-terraform'
Plug 'dense-analysis/ale'
  let g:ale_fixers = {
  \   '*': ['remove_trailing_lines', 'trim_whitespace'],
  \}
  let g:ale_close_preview_on_insert = 1
  let g:ale_fix_on_save = 1
  let g:ale_lint_on_text_changed = "Always"
 
call plug#end()
```
3. open any terraform file. a file that ends with .tf and try to edit it
    can also be reproduced by just opening an empty .tf file ```nvim test.tf``` try to edit it
    can also be reproduced by running this command ```:TerraformFmt```

### :ALEInfo

Current Filetype: terraform
Available Linters: ['terraform', 'tflint']
  Enabled Linters: ['terraform', 'tflint']
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'terraform' - Fix tf and hcl files with terraform fmt.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_terraform_terraform_executable = 'terraform'
let g:ale_terraform_tflint_executable = 'tflint'
let g:ale_terraform_tflint_options = ''
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'*': ['remove_trailing_lines', 'trim_whitespace']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'Always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) terraform
(finished - exit code 0) ['/usr/local/bin/zsh', '-c', '''terraform'' fmt -no-color --check=true - < ''/var/folders/gs/m8r6lb55577cv24v6lr30n9r0000gn/T/nvimL3hX77/1/tflint.tf''']

<<<NO OUTPUT RETURNED>>>

(executable check - success) tflint
(finished - exit code 3) ['/usr/local/bin/zsh', '-c', '''tflint'' -f json ''/var/folders/gs/m8r6lb55577cv24v6lr30n9r0000gn/T/nvimL3hX77/3/tflint.tf''']

<<<OUTPUT STARTS>>>
{"issues":[{"rule":{"name":"aws_instance_invalid_type","severity":"error","link":""},"message":"instance_type is not a valid value","range":{"filename":"/var/folders/gs/m8r6lb55577cv24v6lr30n9r0000gn/T/nvimL3hX77/3/tflint.tf","start":{"line":3,"column":19},"end":{"line":3,"column":31}},"callers":[]}],"errors":[]}
<<<OUTPUT ENDS>>>

**Comment by Miradorn** [comment]
tflint changed its output formatting in https://github.com/wata727/tflint/releases/tag/v0.11.0
so the integration has to be updated.

**Comment by AlaaSMansour** [comment]
I see, as I'm not able to fix it on my own. I hope someone who has enough knowledge can update the integration.
Thanks for the info.
