### ISSUE TITLE
Support `javascriptreact` filetype

### ISSUE THREAD

**Issue by nu0xeda** [dense-analysis/ale#2765]
**Name:** eslint (for javascriptreact filetype)
**URL:** https://eslint.org/

This issue may be bug report.
After the Vim version 8.1.1930, .jsx file is recognized as 'javascriptreact' filetype.
vim/vim#4830

I use Vim 8.1.1999 version, so I need to add below lines to my .vimrc to use ALE:

```vim
" filetype javascriptreact -> javascript.jsx
au BufRead,BufNewFile *.jsx set filetype=javascript.jsx
```

Sorry for my cheep English skills.
ALE is great plugin. Thank you.

**Comment by w0rp** [comment]
I'll add default aliases for that and `typescriptreact` to the relevant filetypes in ALE.

**Comment by w0rp** [comment]
I tagged the wrong commit ID in the commit, but this is done now.

**Comment by nu0xeda** [comment]
@w0rp 
Thank you for your great work!!
