### ISSUE TITLE
Mypy internal errors are not shown

### ISSUE THREAD

**Issue by hackaugusto** [dense-analysis/ale#2774]
I'm writing a piece of test code, and I realized that type checking was not working properly, after running mypy on the CLI I got this error:

```
mypy_test.py:210: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 0.720
mypy_test.py:210: : note: please use --show-traceback to print a traceback when reporting a bug
```

It would be interesting to have this shown early own.

**Comment by elebow** [comment]
@hackaugusto, it looks like ALE should be able to handle that mypy output and show an error on line 210.

Is this still reproducible, and can you provide an input file and mypy configuration to reproduce the behavior?

**Comment by hackaugusto** [comment]
Hey @elebow now the error is shown, tested against 4afbf2f25dc0ce86b118261b0cfb904c80ae6ba0. The MWE is available here: https://github.com/python/mypy/issues/7535 .

Thanks :)
