### ISSUE TITLE
SHould I be able to call ALEFic on visual mode

### ISSUE THREAD

**Issue by statquant** [dense-analysis/ale#2781]
Hello,
I do not know if this is a bug but I cannot use `:ALEFix` in visual mode.
I get a `E481: No range allowed` issue when selecting a line and doing `ALEFix`
I get this on a `Rmd` file
I use `neovim` on `centos7.4`
```
NVIM v0.5.0-23-gafd576ee9
Build type: Debug     
```

**Comment by w0rp** [comment]
It's not a bug. `:ALEFix` doesn't have support for ranges, and probably won't unless someone very clever implements something that will work. Many tools don't support fixing ranges of lines, and in many cases it doesn't make sense.

**Comment by Konstantin-Glukhov** [comment]
I think this should be re-opened as a feature request. It makes a lot of sense to format a selection.
