### ISSUE TITLE
Is it possible to auto-detect which linter to use?

### ISSUE THREAD

**Issue by christianbundy** [dense-analysis/ale#2783]
Some projects use `eslint`, some use `standard`, and some use `prettier`, so I've been spending lots of time editing my global Vim config when I switch between JavaScript repositories using different linters.

I'd love for Ale to be able to automatically detect which linter should be used, parsing `package.json` or similar to see which one the project uses. Is this possible? Or is there a suggested way of doing something similar?

I've been prototyping a tool called [common-lint](https://github.com/fraction/common-lint) that does the auto-detection from `package.json` and calls either `eslint` or `standard`, but have had trouble integrating with Ale because the tools have different output. I'd love any thoughts on how to do this better or circumvent the problem.

See also: https://github.com/standard/standard/issues/1420

**Comment by hsanson** [comment]
@christianbundy by default ALE will look for local executables, for example those within the node_modules folder. See  `:h  ale-integrations-local-executables`.

**Comment by w0rp** [comment]
Detecting which tools to run is out of scope for ALE. You should configure each project instead. You can use `g:ale_pattern_options`, or any plugin for project settings. You should prefer to install linters into `node_modules`.

Also, people should probably ditch `xo`, `standard`, `semistandard`, and all of the other things that are just ESLint anyway and just use ESLint with different configurations.
