### ISSUE TITLE
c/clangd.vim not defining the language as c

### ISSUE THREAD

**Issue by RageKnify** [dense-analysis/ale#2785]
## Information

**VIM version**

NVIM v0.4.2
Build type: Release

Operating System: Arch Linux

## What went wrong

clangd for `.c` files isn't defining the language as `C` so it gives `C++` warnings/errors.
https://github.com/dense-analysis/ale/blob/master/ale_linters/c/clangd.vim#L8
clang for `.c` files does define it, it's just adding the option `-x c`
https://github.com/dense-analysis/ale/blob/master/ale_linters/c/clang.vim#L12

I changed line 8 in clangd.vim to:
`return '%e -x c' . ale#Pad(ale#Var(a:buffer, 'c_clangd_options'))` and I stopped getting the `C++` warnings/errors.

**Comment by w0rp** [comment]
This make sense. If that option is required for it to work, create a pull request for this.
