### ISSUE TITLE
ESLint 6 couldn't find the plugin

### ISSUE THREAD

**Issue by kevinoid** [dense-analysis/ale#2787]
## Information

**VIM version**

    VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)
    Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401

Operating System: Debian GNU/Linux (testing)

## What went wrong

Using ESLint 6, which implements [RFC 2018-simplified-package-loading](https://github.com/eslint/rfcs/blob/master/designs/2018-simplified-package-loading/README.md), if Vim edits a JavaScript file from a directory outside the project root (i.e. directory containing `node_modules`) and an applicable `.eslintrc` references plugins or formatters which are not installed globally, an error such as the following is produced:

    Oops! Something went wrong! :(
    
    ESLint: 6.4.0.
    
    ESLint couldn't find the plugin "eslint-plugin-node".
    
    (The package "eslint-plugin-node" was not found when loaded as a Node module from the directory "/tmp/b".)
    
    It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
    
        npm install eslint-plugin-node@latest --save-dev
    
    The plugin "eslint-plugin-node" was referenced from the config file in "../a/.eslintrc.json".
    
    If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.

## Reproducing the bug

1. Create a project using `eslint-plugin-node`
```sh
cd "$(mktemp -d)"
npm init -y
npm install --save-dev eslint eslint-plugin-node
echo '{"extends":"plugin:node/recommended"}' > .eslintrc.json
```
2. Run `vim index.js` - `:ALEInfo` shouldn't show any ESLint errors.
3. Run `cd .. && vim "$OLDPWD/index.js` - `:ALEInfo` should show ESLint errors similar to the above.

<details>
<summary><strong>:ALEInfo</strong></summary>

     Current Filetype: javascript
    Available Linters: ['eslint', 'fecs', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
      Enabled Linters: ['eslint']
     Suggested Fixers: 
      'eslint' - Apply eslint --fix to a file.
      'fecs' - Apply fecs format to a file.
      'importjs' - automatic imports for javascript
      'prettier' - Apply prettier to a file.
      'prettier_eslint', 'prettier-eslint' - Apply prettier-eslint to a file.
      'prettier_standard', 'prettier-standard' - Apply prettier-standard to a file.
      'remove_trailing_lines' - Remove all blank lines at the end of a file.
      'standard' - Fix JavaScript files using standard --fix
      'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
      'xo' - Fix JavaScript/TypeScript files using xo --fix.
     Linter Variables:
    
    let g:ale_javascript_eslint_executable = 'eslint'
    let g:ale_javascript_eslint_options = '--report-unused-disable-directives'
    let g:ale_javascript_eslint_suppress_eslintignore = 0
    let g:ale_javascript_eslint_suppress_missing_config = 0
    let g:ale_javascript_eslint_use_global = 0
     Global Variables:
    
    let g:ale_cache_executable_check_failures = v:null
    let g:ale_change_sign_column_color = 0
    let g:ale_command_wrapper = ''
    let g:ale_completion_delay = v:null
    let g:ale_completion_enabled = 0
    let g:ale_completion_max_suggestions = v:null
    let g:ale_echo_cursor = 1
    let g:ale_echo_msg_error_str = 'Error'
    let g:ale_echo_msg_format = '%code%: %s [%linter%]'
    let g:ale_echo_msg_info_str = 'Info'
    let g:ale_echo_msg_warning_str = 'Warning'
    let g:ale_enabled = 1
    let g:ale_fix_on_save = 0
    let g:ale_fixers = {'go': ['gofmt'], 'sh': ['shfmt'], 'javascript': ['eslint'], 'python': ['isort', 'black']}
    let g:ale_history_enabled = 1
    let g:ale_history_log_output = 1
    let g:ale_keep_list_window_open = 0
    let g:ale_lint_delay = 200
    let g:ale_lint_on_enter = 1
    let g:ale_lint_on_filetype_changed = 1
    let g:ale_lint_on_insert_leave = 1
    let g:ale_lint_on_save = 1
    let g:ale_lint_on_text_changed = 'never'
    let g:ale_linter_aliases = {}
    let g:ale_linters = {'sh': ['shellcheck']}
    let b:ale_linters = ['eslint']
    let g:ale_linters_explicit = 0
    let g:ale_list_vertical = 0
    let g:ale_list_window_size = 5
    let g:ale_loclist_msg_format = '%code%: %s [%linter%]'
    let g:ale_lsp_root = {}
    let g:ale_max_buffer_history_size = 20
    let g:ale_max_signs = -1
    let g:ale_maximum_file_size = v:null
    let g:ale_open_list = 0
    let g:ale_pattern_options = {'\.min\.css$': {'ale_linters': [], 'ale_fixers': []}, '\.min\.js$': {'ale_linters': [], 'ale_fixers': []}}
    let g:ale_pattern_options_enabled = v:null
    let g:ale_set_balloons = 0
    let g:ale_set_highlights = 1
    let g:ale_set_loclist = 1
    let g:ale_set_quickfix = 0
    let g:ale_set_signs = 1
    let g:ale_sign_column_always = 0
    let g:ale_sign_error = '>>'
    let g:ale_sign_info = '--'
    let g:ale_sign_offset = 1000000
    let g:ale_sign_style_error = '>>'
    let g:ale_sign_style_warning = '--'
    let g:ale_sign_warning = '--'
    let g:ale_sign_highlight_linenrs = 0
    let g:ale_statusline_format = v:null
    let g:ale_type_map = {}
    let g:ale_use_global_executables = v:null
    let g:ale_virtualtext_cursor = 0
    let g:ale_warn_about_trailing_blank_lines = 1
    let g:ale_warn_about_trailing_whitespace = 1
      Command History:
    
    (executable check - success) /tmp/tmp.gu5POK8wHO/node_modules/eslint/bin/eslint.js
    (finished - exit code 2) ['/bin/bash', '-c', '''/tmp/tmp.gu5POK8wHO/node_modules/eslint/bin/eslint.js'' --report-unused-disable-directives -f json --stdin --stdin-filename ''/tmp/tmp.gu5POK8wHO/index.js'' < ''/tmp/vCGY0Xz/2/index.js''']
    
    <<<OUTPUT STARTS>>>
    
    Oops! Something went wrong! :(
    
    ESLint: 6.4.0.
    
    ESLint couldn't find the plugin "eslint-plugin-node".
    
    (The package "eslint-plugin-node" was not found when loaded as a Node module from the directory "/tmp".)
    
    It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
    
        npm install eslint-plugin-node@latest --save-dev
    
    The plugin "eslint-plugin-node" was referenced from the config file in "tmp.gu5POK8wHO/.eslintrc.json".
    
    If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
    
    <<<OUTPUT ENDS>>>
</details>

## Potential Solutions

I would be willing to submit a PR to resolve this issue.  Some potential solutions:

1.  Run ESLint from the same directory as the file being linted (either unconditionally or configurable).
2.  Add [`--resolve-plugins-relative-to`](https://github.com/eslint/eslint/pull/11696) file being linted (requires ESLint > 6 version detection - done either unconditionally or configurable).

Would either of these, or another approach, be acceptable?

Thanks for considering,
Kevin

**Comment by w0rp** [comment]
I think setting the working directory to the buffer's directory is the way to go. That should be easy to fix and test for.

**Comment by w0rp** [comment]
It's worth bearing this in mind.

>With the new design, ESLint will load all plugins and formatters relative to the project root. By default, the project root is simply the CWD of the running process. Integrations can configure a specific project root using the already-existing cwd option in CLIEngine. ESLint will load all other third-party packages (e.g. shareable configs and parsers) relative to the config file where they're referenced.

The way I read this, this means that plugins that run ESLint are now responsible for figuring out where the project root is, whereas before it was relative to `lib/config/plugins.js`. I recommend setting the root to the directory containing `node_modules`, instead of the directory containing the file, which will probably work most of the time.

**Comment by chrismllr** [comment]
Yep, seeing the same thing. We run a monorepo with multiple application dirs. Simply need to start `vim` from the root of each individual directory (one containing node_modules), instead of the root of the monorepo.

**Comment by apcomplete** [comment]
Is this as simple to fix as this?

```
function! ale#handlers#eslint#GetCommand(buffer) abort
    let l:executable = ale#handlers#eslint#GetExecutable(a:buffer)

    let l:options = ale#Var(a:buffer, 'javascript_eslint_options')

    return ale#path#BufferCdString(a:buffer)
    \   . ale#node#Executable(a:buffer, l:executable)
    \   . (!empty(l:options) ? ' ' . l:options : '')
    \   . ' -f json --stdin --stdin-filename %s'
endfunction
```

**Comment by kevinoid** [comment]
> Is this as simple to fix as this?

I think so.  Plus tests, of course.  In particular, I'm not sure what `ale#path#BufferCdString(a:buffer)` produces when the current buffer is not a file.  You'd want to test that case.

You may also want to consider `ale#path#BufferCdString(ale#path#FindNearestDirectory(a:buffer, 'node_modules'))` (with fallback to `ale#path#BufferCdString(a:buffer)` when `ale#path#FindNearestDirectory(a:buffer, 'node_modules')` is empty) as noted in https://github.com/dense-analysis/ale/issues/2787#issuecomment-536469489.  I don't think it is required for ESLint, as currently implemented, but the RFC does specify `$PWD` is interpreted as the project root.

I have been meaning to work up a PR for this, but it may take me a while.  Feel free to submit one.  I'd be happy to help review as I have time.

**Comment by w0rp** [comment]
Let me know when there's a PR, and I'll eventually have a look. I plan to go through all of the issues and pull requests I haven't looked at in a while soon.

**Comment by kevinoid** [comment]
I just created #2937 with a potential fix.  When you have some time to review, let me know what you think (and whether it fixes the issue for everyone else).

**Comment by w0rp** [comment]
I've merged that PR now. That looks good to me.
