### ISSUE TITLE
Add support for terraform-lsp

### ISSUE THREAD

**Issue by sebiwi** [dense-analysis/ale#2794]
**Name:** terraform-lsp
**URL:** https://github.com/juliosueiras/terraform-lsp

This is an LSP for Terraform. It seems pretty powerful, it would be a great addition to
the tools you support already.

**Comment by varac** [comment]
https://github.com/dense-analysis/ale/blob/master/supported-tools.md shows terraform-lsp in the list of supported linters, is there anything more to do here or can this get closed ?

**Comment by hsanson** [comment]
This language server is already supported.
