### ISSUE TITLE
Use ALE Fixers in `formatprg`

### ISSUE THREAD

**Issue by aymanbagabas** [dense-analysis/ale#2796]
Is there a way to use ALE Fixers in `formatprg` and `equalprg` with Vim keybinding `gq`?

**Comment by w0rp** [comment]
This is not possible, as both execute synchronously.

**Comment by aymanbagabas** [comment]
What about using `ALEFix` with a visual range?

**Comment by w0rp** [comment]
Supporting a range is complicated, as not all tools support fixing ranges. See #850
