### ISSUE TITLE
Allow postprocessing LSP linter output

### ISSUE THREAD

**Issue by merijn** [dense-analysis/ale#2798]
Currently the docs say it's not possible to use the `callback` argument when defining/creating an LSP based linter. This means that, afaict, there's no way to format/process the output from LSP before it ends up in, e.g. the location list or what gets displayed by the `echo_cursor_msg`.

This is a problem for me as the linter I'm dealing with prefixes every message with the full path of the filename and the sevetiy. As a result the location list and echos use up all space on displaying the path/severity and there's no room to see the actual message. There seems to be no way I can have ALE modify the LSP output before displaying it to work around this problem.

**Comment by w0rp** [comment]
I think it makes sense to add an option for this.

**Comment by w0rp** [comment]
https://github.com/dense-analysis/ale/issues/1263 duplicates this, yes.
