### ISSUE TITLE
Is there a way to fold everything except errors 

### ISSUE THREAD

**Issue by oguzbilgic** [dense-analysis/ale#2805]
Is there a way to fold everything except errors :ALEFold ? Similart to Gitgutter's :GitGutterFold command.

https://github.com/airblade/vim-gitgutter/commit/ac787afa02e07331c53ab24253d71c7a873c9823

**Comment by w0rp** [comment]
No, I don't think that's a good idea. It's better to jump to errors and look at the surrounding lines.
