### ISSUE TITLE
Using `ALEOrganizeImports` and `g:ale_completion_tsserver_autoimport` writes the buffer unexpectedly

### ISSUE THREAD

**Issue by chaucerbao** [dense-analysis/ale#2811]
Using `ALEOrganizeImports` or `g:ale_completion_tsserver_autoimport` causes the buffer to automatically be written.  Since they only modify the current buffer, it would be preferable if it did not automatically write the file in the process, in case the user decides to just `:q` and doesn't realize that the file has actually changed.

@jeremija

**Comment by jeremija** [comment]
I guess `ale#code_action#HandleCodeAction()` could be updated to modify the current buffer  instead of writing to disk when there are only changes in the current buffer.

@w0rp What do you think? Is there an easier way to set buffer contents than using `setline` and `append`?

**Comment by w0rp** [comment]
I think every buffer should be written for consistency. Otherwise files you don't have open will be written to disk, but other files you have open won't be written.

**Comment by chaucerbao** [comment]
I agree with that reasoning for commands like `ALERename` which can affect multiple files, but `ALEOrganizeImports` and `g:ale_completion_tsserver_autoimport` only modify the current buffer, similar to how `ALEFix` only modifies the current buffer without writing it.

**Comment by w0rp** [comment]
Ah, that is a good point. I that case, I think we should add a flag to the functions for applying changes so they don't write to the buffers, and use that flag just for organising imports.

**Comment by jeremija** [comment]
Looks like a lot of the code from `ale#fix#ApplyQueuedFixes` could be reused for this behavior.
