### ISSUE TITLE
How to run eslint with CWD set to project root?

### ISSUE THREAD

**Issue by ronen** [dense-analysis/ale#2817]
Hello, I've looked at #286 and poked around other issues and looked at the `ale` source, and I'm stumped (although I'll admit that my vimscript hacking skills are limited).

Because my `eslint` configuration includes some relative paths, I need to run `eslint` with CWD set to the project root, i.e. the nearest directory that has `package.json`.

Is it possible to configure this somehow, both for linting and for fixing?

My best guess so far is to create a custom linter `~/.vim/ale_linters/javascript/eslint-root.vim` by copying `eslint.vim` from the ale source and changing the `command:` with some appropriate function (if I can figure out how to write that function!).   But I don't know how to create a corresponding custom fixer.   Or maybe there's a better/simpler way to go about this?

Any help would be appreciated.  A cut-and-paste example for vimscript dummies would be extra appreciated 😄.  Thanks!

**Comment by w0rp** [comment]
You can replace the linter with your own definition if you copy and paste it. At some point someone will fix the ESLint linter to work with ESLint 6 changes so it will run from the project root automatically.

**Comment by kbulygin** [comment]
> But I don't know how to create a corresponding custom fixer. Or maybe there's a better/simpler way to go about this?

I also spent some time on this. Here's an example: to run `pyupgrade` before `black`, add this to your `.vimrc`:
```vim
let g:ale_fixers = {
\ 'python': [
\   {buffer -> {'command': 'pyupgrade --py38-plus %t',
\               'read_temporary_file': 1}},
\   'black',
\ ],
\ }
let g:ale_fix_on_save = 1
```

(I used https://github.com/dense-analysis/ale/blob/d93512fe606fbcc411287e4a491b5b4e12d90fb3/test/fix/test_ale_fix.vader#L65 and other code in this file in addition to `:h ale-fix`.)

**Comment by w0rp** [comment]
ESLint should run from the project root automatically now, due to recent changes to support what changed in recent versions of ESLint.
