### ISSUE TITLE
Cursor becomes invisible when moving around the sign line.

### ISSUE THREAD

**Issue by mbinary** [dense-analysis/ale#2827]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41)
include patch: 1-1453
(with GTK3 GUI)

Operating System:  Ubuntu 18.04

## What went wrong

In vim normal mode, the **cursor** becomes **invisible** when moving on the sign gutter line( and the previous, the next line). This problem happens after I installed gvim.

## Reproducing the bug

1. I installed gvim.
2. Then this happened.

**Comment by w0rp** [comment]
See here #1334.

This is a bug in Vim, fixed over a year ago, and it the Ubuntu package for that version of Ubuntu will probably never be fixed. You can install Vim from a PPA instead to fix it.
