### ISSUE TITLE
Support rust-analyzer

### ISSUE THREAD

**Issue by nycex** [dense-analysis/ale#2832]
Add support for rust-analyzer

**Name:** rust-analyzer
**URL:** https://github.com/rust-analyzer/rust-analyzer

rust-analyzer is an experimental rust language server which is part of a rls 2.0 effort.

**Comment by cwndrws** [comment]
For anyone else who wants to use `rust-analyzer` with ale before that PR is merged, this is how I have my `ftplugin/rust.vim` to do it:
```
let b:ale_linters = ['rls']
let g:ale_rust_rls_executable = 'ra_lsp_server'
let b:ale_fixers = ['rustfmt']
```
Because they both use the LSP interface, it works as a drop in replacement.

**Comment by kamek-pf** [comment]
@cwndrws did you manage to also get clippy working with this setup ?

**Comment by cwndrws** [comment]
@kamek-pf no, as far as I can tell, you can only use clippy if you use the `cargo` linter.

**Comment by elshize** [comment]
@cwndrws I got it working, but with executable `rust-analyzer` (maybe it changed in the meantime?)

**Comment by cwndrws** [comment]
@elshize Yeah it looks like they changed the name of the binary in [this commit](https://github.com/rust-analyzer/rust-analyzer/commit/c0fa5e2246457df10e92c2e11c971f2f40921793#diff-4410868824e9f5b142e83796b27f6257). I have updated the snippet in my comment.

**Comment by xliiv** [comment]
> Because they both use the LSP interface, it works as a drop in replacement.

Doesn't work for me. Does it work for you now?

**Comment by elshize** [comment]
@xliiv yeah, I've been using it for a week or so now. Here's my rust-related ALE config in `.vimrc`:
```
let g:ale_rust_rls_config = {
	\ 'rust': {
		\ 'all_targets': 1,
		\ 'build_on_save': 1,
		\ 'clippy_preference': 'on'
	\ }
	\ }
let g:ale_rust_rls_toolchain = ''
let g:ale_rust_rls_executable = 'rust-analyzer'
let g:ale_linters = {
    \ 'rust': ['rls']
    \ }
let g:ale_fixers = {
    \ 'rust': ['rustfmt']
    \ }
```

If you're not seeing any effects, I suggest running `:ALEInfo` and seeing what the logs say.

**Comment by xliiv** [comment]
@elshize thanks it helps, not it's running.

**Comment by RyanSquared** [comment]
@xliiv good news! rust-analyzer now has builds for nightly, so assuming your default toolchain was nightly you can now use that.

**Comment by elshize** [comment]
Does anyone know if it is possible to enable clippy for rust-analyzer? That option `'clippy_preference': 'on'` that worked on rls doesn't seem to work anymore, at least I'm not getting any clippy warnings. Any ideas?

**Comment by cuviper** [comment]
There's now an RFC for Rust to officially transition from RLS to rust-analyzer: https://github.com/rust-lang/rfcs/pull/2912

**Comment by sbromberger** [comment]
I can't seem to get rust-analyzer to lint properly on leaving insert mode. It takes about a second for an error to show up in the gutter, and then when I erase the offending line, the error doesn't disappear. It's not quite a replacement for rls because rls doesn't seem to have this problem.

Any ideas?
