### ISSUE TITLE
Expose gopls initialization options (e.g. completeUnimported)

### ISSUE THREAD

**Issue by ratorx** [dense-analysis/ale#2839]
According to [gopls docs](https://github.com/golang/tools/blob/master/gopls/doc/settings.md), there are additional settings that can be passed to the server by the client. From the source code, it seems that these need to be passed as initialization options.

Please could ale expose this? Specifically I'm interested in `completeUnimported`.

**Comment by w0rp** [comment]
Someone just needs to update the linter file to accept a Dictionary for those options. The first example I found in the codebase is the `ccls` linter.

**Comment by hsanson** [comment]
This is now supported thanks to #3571.
