### ISSUE TITLE
ALEOrganizeImports with import groups?

### ISSUE THREAD

**Issue by croaky** [dense-analysis/ale#2842]
Given two TypeScript `import` groups separated by a blank line:

```ts
import * as React from 'react'
import { Provider } from 'react-redux'

import { logos } from 'assets/logos'
import { persistor, store } from 'lib/store'
```

When I run `:ALEOrganizeImports`, I'd like the imports to be organized within their groups.
Our team's convention happens to be an import group for third-party modules
and an import group for internal modules but there are other reasonable grouping conventions.

For example, [Go's tooling behaves this way](https://github.com/golang/go/issues/26846#issuecomment-412629549):

> We intentionally leave this to local custom - gofmt and goimports will never move imports across blank lines in the import block. So if I want path with the others, I can do that, and gofmt/goimports respect that. And if you want all your renamed imports together, you can do that, and gofmt/goimports respect that too.

But at the moment, the result will be:

```ts
import { logos } from 'assets/logos'
import { persistor, store } from 'lib/store'
import * as React from 'react'
import { Provider } from 'react-redux'

```

With the blank line moved to the bottom.

Would it be possible for `ALEOrganizeImports` to not move imports across blank lines?
Or be configured to behave this way?

Thank you! v2.6.0 is looking great!

**Comment by w0rp** [comment]
ALE doesn't decide where imports are arranged, that's up to the language servers and `tsserver`. At the moment ALE only organises imports with `tsserver`.

**Comment by w0rp** [comment]
All of the tools for organising imports in TypeScript aren't very good.  The best that I've found so far is this ESLint plugin with this option. https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md

**Comment by croaky** [comment]
Good info, thanks!
