### ISSUE TITLE
Show info about issues in fold line

### ISSUE THREAD

**Issue by somospocos** [dense-analysis/ale#2843]
This is how my vim looks with folds open:

![foldopen](https://user-images.githubusercontent.com/40846997/67062947-81476f00-f154-11e9-9ad4-1b22903bbee2.png)

This is how it looks with folds closed:

![foldclosed](https://user-images.githubusercontent.com/40846997/67062946-80aed880-f154-11e9-9b75-b66e75284f0e.png)

I would really like to know if ALE has spotted any warnings/errors in folded pieces of code, if that's technically possible, by modifying fold lines with info from first existing issue inside the fold for example.

**Comment by w0rp** [comment]
Unfortunately, there's no way to do this.
