### ISSUE TITLE
Running languagetool on non-text filetypes

### ISSUE THREAD

**Issue by Aryailia** [dense-analysis/ale#2848]
## What I'm trying to do
I am trying to get *languagetool* to work with other filetypes that are not text but *languagetool* seems to not trigger at all.

## So you know whether or not I'm using Ale properly
Currently I have *languagetool* and *proselint* installed for prose linting. I have verified that both work on a markdown file. I trigger *languagetool* with `:ALELint`. I'm trying to get *languagetool* to check grammar/spelling for a different filetype. By doing
```let g:ale_linters={'tex': ['languagetool', 'proselint'] }```

I'm able to get *proselint* to run regularly (without the above line in my vimrc neither run) but *languagetool* doesn't do anything. I also made sure to check that feeding my .tex file to *languagetool* does indeed indicate places that need changing.

## Question
I noticed from :ALEInfo that for latex files, *languagetool* is not an available linter so it would seem that this is intended, however I would like to use ale to run grammar checks on more filetypes (latex just being an example). Is there anyway for me to add *languagetool* to more filetypes? Or is it possible for me to a specific linter manually?

**Comment by w0rp** [comment]
You need to alias the `tex` files so they also run text linters with `let b:ale_linter_aliases = ['tex', 'text']` in your `tex.vim` ftplugin file, or you can add `'tex': ['tex', 'text']`. to your `g:ale_linter_aliases` Dictionary.
