### ISSUE TITLE
Configure linter and auto-completion differently

### ISSUE THREAD

**Issue by sn0opy** [dense-analysis/ale#2855]
Right now, there's the auto-completion uses the `g:ale_linters` dict to configure linters and completion at once. In my case, I work with Python. I'd like to use auto-completion which requires me to set the linter to `pyls`, but all my projects have a `.flake8` file to exclude some rules, so I want to use `flake8` for linting and `pyls` for auto-completion.

While using pyls my .flake8 file is completely ignored.

**Comment by azdkj532** [comment]
Have a look on this, [python-language-server#configuration](https://github.com/palantir/python-language-server#configuration), maybe it helps.

**Comment by sn0opy** [comment]
I've found that option after creating my issue, but I'm not  sure about the correct syntax for g:ale_python_pyls_config.

This is what I've tried without success:
```
let g:ale_python_pyls_config = {
\ 'pyls': { 'configurationSources': '["flake8"]' }
\}
```

or 

```
let g:ale_python_pyls_config = {
\  'pyls': { 'configurationSources': ['flake8'] }
\}
```

Neither of the two did work. At least my .flake8 in the project was still being ignored.

**Comment by azdkj532** [comment]
I don't know how to config that in vim too :P, so I wrote configs into `~/.config/pycodestyle`.
Hope this helps.

**Comment by Yutsuten** [comment]
This configuration worked for me.

```vim
let g:ale_python_pyls_config = {
\  'pyls': { 'configurationSources': ['flake8'] }
\}
```

**Comment by w0rp** [comment]
The configuration here should work, and you can also use `ale_linters_ignore` to disable diagnostics for any linter, which is mostly useful for using LSP features without the diagnostics.
