### ISSUE TITLE
Allow to populate (quickfix|loclist) only on demand

### ISSUE THREAD

**Issue by przepompownia** [dense-analysis/ale#2866]
In most cases echoed messages are sufficient for me. I don't need to have the quickfix or location window (depending of settings) frequently populated by ALE. However, I would not like to disable populating the quickfix completely by setting `g:ale_set_quickfix` to `0`. 

I would like to have a command to manual populate quickfix list once per call.

**Comment by hsanson** [comment]
This PR seems to add commands to populate the quick/loc lists on demand: #3761

**Comment by idbrii** [comment]
@przepompownia If you're still interested in this feature, I'd love if you could test #3761 to help get it merged.

**Comment by przepompownia** [comment]
Within those 21 months I strongly reduced my ALE usage in favor of diagnostic-languageserver. Finding any linter not configured there and configured by default by ALE wasn't so quick ;) After finding such one I can confirm that your change works for me :) It may be helpful someday so please merge it if possible :+1: Thanks!

**Comment by hsanson** [comment]
#3761 was merged long ago.
