### ISSUE TITLE
Support Cookstyle as a fixer for Chef files

### ISSUE THREAD

**Issue by sunjon** [dense-analysis/ale#2867]
Cookstyle is already available as a linter for Ale.

I currently use it to fix files with:
```vim
:!cookstyle --auto-correct %:p | sed "1,/^====================$/d"
```
Having it as a native fixer would be convenient.

**Comment by w0rp** [comment]
Someone added `cookstyle` a while ago.

**Comment by kmf** [comment]
@w0rp not as a fixer

**Comment by kmf** [comment]
@sunjon hey I opened a [PR](https://github.com/dense-analysis/ale/pull/3705) for this please test
