### ISSUE TITLE
Add support for yaml language server

### ISSUE THREAD

**Issue by hsanson** [dense-analysis/ale#2874]
**Name:** yaml-language-server
**URL:** https://github.com/redhat-developer/yaml-language-server

**Comment by jamilraichouni** [comment]
Hi!

Does that actually work?

I tried with NVIM v0.6.1 and v0.7.0 and installed `yaml-language-server` on macos first via `brew` and second via `npm`.

In all cases:

When I open an invalid (introduced an error) `.yml`file I see that `:ALEInfo` lists `yaml-language-server` as enabled linter. But I see no linting. When I activate `yamllint` as second linter in parallel I directly see an error message for the same file.

Output of `:ALEInfoToFile`:

[ale.txt](https://github.com/dense-analysis/ale/files/8543405/ale.txt)

I tried a lot (with and without manipulating `vim.g.ale_yaml_ls_config`.

When I set `vim.g.ale_yaml_ls_config` I tried

```lua
vim.g.ale_yaml_ls_config = {
    yaml = {
        yamlVersion = "1.2",
        completion = false,
    }
}
```

and also something more complex where I am not 100% sure if that is valid:

```lua
vim.g.ale_yaml_ls_config = {
    yaml = {
        yamlVersion = "1.2",
        validate = true,
        format = true,
        hover = true,
        completion = false,
        schemaStore = {
            enable = true
        },
        schemas = {
            ["/Users/jamilraichouni/repos/mddocgen/builddesc_schema.json"] = "builddesc*.yml"
        }
    },
}
```

Any help will be much appreciated.

Thanks,
Jamil
