### ISSUE TITLE
hadolint: Honor config when using docker image

### ISSUE THREAD

**Issue by varac** [dense-analysis/ale#2875]
When using the hadolint docker image, the [hadolint global config file](https://github.com/hadolint/hadolint#configure) won't be evalutated.
I propose to add sth like `ale_dockerfile_hadolint_docker_opts` which lets you [configure hadolint ](https://github.com/hadolint/hadolint#how-to-use) using command-line options.

**Comment by matthewarmand** [comment]
Took a stab at adding this over at #4353, if anyone interested wants to take a peek
