### ISSUE TITLE
Run fixers on change?

### ISSUE THREAD

**Issue by cprn** [dense-analysis/ale#2883]
Would it be possible to run fixers on change in the same way `vim` e.g. breaks the line as I type before it gets too long (longer than `set tw`)?

**Comment by w0rp** [comment]
This has been thought about before. As far as I can tell, it's not possible to implement this and also support the wide array of tools that ALE supports, as some tools need to write to disk to work. However, it may be possible if we make it clear that those tools simply cannot work while you type, in the same way that some linters cannot work while you type.

So far, I haven't imagined a clean way to handle fixing while you type yet.

**Comment by w0rp** [comment]
I'll close this one for now. I don't think it can work well, at least not with the way Vim and Neovim currently work.
