### ISSUE TITLE
How to I specifiy a command to call linters

### ISSUE THREAD

**Issue by lialslasher** [dense-analysis/ale#2892]
I installed my linters with

```python3 -m pip install --user pylint```

so I need to call `python3 -m pylint` in my Neovim and not `pylint` so an `ALEInfo` give me the following error :

```(executable check - failure) pylint```

How do I specify custom command to call it, like I would add customs arguments (`let g:ale_python_mypy_options = '--ignore-missing-imports'`) ?

**Comment by lialslasher** [comment]
Ok, so those executables were in `~/.local/bin` and my path wasn't updated. So nevermind, tks.

**Comment by hsanson** [comment]
@lialslasher can you please close the issue if it is solved for you?
