### ISSUE TITLE
Ale's `ale_completion_tsserver_autoimport` inserts `default` when accepting autoimport suggestion for default import for typescript.

### ISSUE THREAD

**Issue by dephiros** [dense-analysis/ale#2899]
## Information

**VIM version**
NVIM v0.4.2
Build type: Release

Operating System: Mac 10.14.6 

## What went wrong
Ale's `ale_completion_tsserver_autoimport` inserts `default` when accepting autoimport suggestion for default import for typescript.

## Reproducing the bug

1. Create file `abcd.ts` with a default export
2. In file b.ts, type `abc`, ale will pop up `default v Import default 'abcd' from module "abcd.ts`
3. accept the suggestion, you will see the import statement added `import abcd from "abcd" but the inserted text is `default`. Note: the import takes two times to be inserted in the first example below as well

This happens for both ts and tsx files.
![Nov-15-2019 13-40-10](https://user-images.githubusercontent.com/2289753/68977679-a78d1880-07ad-11ea-91bd-f67be1077f44.gif)
![Nov-15-2019 13-30-08](https://user-images.githubusercontent.com/2289753/68977680-a78d1880-07ad-11ea-8662-cb0ceb1c425b.gif)

### :ALEInfo

```
 Current Filetype: typescript
Available Linters: ['eslint', 'standard', 'tslint', 'tsserver', 'typecheck', 'xo']
  Enabled Linters: ['eslint', 'standard', 'tslint', 'tsserver', 'typecheck', 'xo']
 Suggested Fixers: 
  'eslint' - Apply eslint --fix to a file.
  'prettier' - Apply prettier to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'tslint' - Fix typescript files with tslint --fix.
  'xo' - Fix JavaScript/TypeScript files using xo --fix.
 Linter Variables:

let g:ale_typescript_standard_executable = 'standard'
let g:ale_typescript_standard_options = ''
let g:ale_typescript_standard_use_global = 0
let g:ale_typescript_tslint_config_path = ''
let g:ale_typescript_tslint_executable = 'tslint'
let g:ale_typescript_tslint_ignore_empty_files = 0
let g:ale_typescript_tslint_rules_dir = ''
let g:ale_typescript_tslint_use_global = 0
let g:ale_typescript_tsserver_config_path = ''
let g:ale_typescript_tsserver_executable = 'tsserver'

```

**Comment by w0rp** [comment]
This might be something specific to JSX.

**Comment by eduinlight** [comment]
Can you please tell me how I accept an autoimport? I type untill the popup is show and with C-n C-p C-o select the import that I need, but I don't know how to select it. I try a lot of keys and combinations but nothing happend.

**Comment by w0rp** [comment]
You want to select the menu item so it's highlighted, then press either space or enter to keep typing.

**Comment by w0rp** [comment]
I should have fixed this now. The format for default import completion data is weird, but you can read `localName` from `displayParts` to get the real name.
