### ISSUE TITLE
Virtual text message gets cut off.

### ISSUE THREAD

**Issue by BonaBeavis** [dense-analysis/ale#2902]
A long line with error produces following situation:

![image](https://user-images.githubusercontent.com/3330855/69161247-27d3b680-0aeb-11ea-88a4-7d2df7ca6eac.png)

The error message is cut off. I would suggest either do a line break on the message or display it on the next line.

**Comment by RyanSquared** [comment]
I'm not sure what the best solution is for this but as an FYI I believe you can use `:ALEDetail` to get more information about the error.

**Comment by BonaBeavis** [comment]
Is the error message always a popup? Then the error message could be displayed on the next line.

**Comment by RyanSquared** [comment]
The error message can also be shown at the bottom of the screen, if you have the "cmdheight" option set to 1 or more, as can be shown here: https://user-images.githubusercontent.com/3518142/59195938-3a81b100-8b85-11e9-8e8d-6a601b1db908.gif

**Comment by w0rp** [comment]
I don't think there's a good way to fix this. virtualtext will just be cut off sometimes. Use other methods of viewing the text, like `:ALEDetail` or `:ALEHover.`
