### ISSUE TITLE
Eclipse LSP With ALE

### ISSUE THREAD

**Issue by husainaloos** [dense-analysis/ale#2904]
Currently I want to use the Eclipse LSP with ale. I used LanguageClient-neovim before, and I had this script that runs the server:

```bash
#!/usr/bin/env sh

JAVA_STYLE_CONFIG=$HOME/.vim/support/java-lsp-support/eclipse-java-google-style.xml
SERVER=$HOME/.vim/support/java-lsp-support/eclipse-jdt
LOMBOK_JAR=$HOME/.vim/support/java-lsp-support/lombok.jar

case "$OSTYPE" in
  darwin*)  CONFIG=config_mac ;; 
  linux*)   CONFIG=config_linux ;;
  *)        echo "unknown: $OSTYPE" ;;
esac

java \
	-javaagent:$LOMBOK_JAR \
	-Xbootclasspath/p:$LOMBOK_JAR \
	-Declipse.application=org.eclipse.jdt.ls.core.id1 \
	-Dosgi.bundles.defaultStartLevel=4 \
	-Declipse.product=org.eclipse.jdt.ls.core.product \
	-Dlog.level=WARN \
	-noverify \
	-Xmx1G \
	-jar $SERVER/plugins/org.eclipse.equinox.launcher_1.*.jar \
	-configuration $SERVER/config_mac \
	-Djava.formatter.fileName $JAVA_STYLE_CONFIG \
	"$@"
```

However, I do not know how to convert that in ale. According to the documentation, I need to set the 

```
	let g:ale_java_eclipselsp_path = '$HOME/.vim/support/java-lsp-support/eclipse-jdt'
	let g:ale_java_eclipse_config_path = '$HOME/.vim/support/java-lsp-support/eclipse-jdt/config_mac'
```

But I do not know how to translate my previous configuration to ALE. As you can see, I use a specific java style, and lombok support. Note that I downloaded the LSP from here: https://download.eclipse.org/jdtls/milestones/?d rather than building it myself.

Any idea how to resolve this?

**Comment by hsanson** [comment]
@husainaloos I have submitted a PR #/2916 that would allow you to add extra command line options to the eclipselsp command:

```
let g:ale_java_eclipse_extra_options = [
  \  '-javaageng:/home/user/jar/lombok.jar',
  \ '-Xbootclasspath/p:/home/user/jar/lombok.jar'
  \]
```

The above configuration will add those command line arguments to the command. You can check the command used to invoke eclipse LSP using `ALEInfo`.

**Comment by husainaloos** [comment]
Thank you very much @hsanson. You change works for me. For those who are interested, here are my config:

```
let g:ale_completion_enabled = 1
let g:ale_java_eclipselsp_path = '$HOME/Downloads/eclipse-jdt'
let g:ale_java_eclipse_config_path = '$HOME/Downloads/eclipse-jdt/config_mac'
let g:ale_java_eclipse_extra_options = [
  \  '-javaageng:/path/to/lombok.jar',
  \ '-Xbootclasspath/p:/path/to/lombok.jar'
  \]
let g:ale_linters = {
  	\   'java': ['eclipselsp']
	\}
```

**Comment by husainaloos** [comment]
#2916

**Comment by w0rp** [comment]
#3077 Might possible resolve this for you, @husainaloos. I don't know that much about Eclipse and Java, but it sounds similar.

**Comment by husainaloos** [comment]
Thanks @w0rp. Unfortunately I have moved one to another solution, and will not be able to test or fiddle with the config to check if it resolves my issue. Feel free to close this issue.
