### ISSUE TITLE
Completion seems to trigger ALEDocumentation

### ISSUE THREAD

**Issue by RobinClowers** [dense-analysis/ale#2905]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 19 2019 12:07:03)
macOS version

Operating System: macOS 10.14.6

## What went wrong

I recently updated all my plugins, including ALE, and now when I trigger completion with `C-n`, the ALEDocumentation command seems to run, it opens a scratch buffer with the docs for the top completion option. I've search for other folks having this problem and tried searching my plugins for that mapping, but nothing seems to come up.

## Reproducing the bug
 
Using deoplete.nvim and ale.vim

1. Open a typescript file
2. Trigger completion with `C-n`
3. Observe the documentation opening in a scratch preview buffer

### :ALEInfo

<details><summary>Show ALEInfo</summary>
<p>
 Current Filetype: typescript
Available Linters: ['eslint', 'standard', 'tslint', 'tsserver', 'typecheck', 'xo']
  Enabled Linters: ['eslint', 'standard', 'tslint', 'tsserver', 'typecheck', 'xo']
 Suggested Fixers: 
  'eslint' - Apply eslint --fix to a file.
  'prettier' - Apply prettier to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'tslint' - Fix typescript files with tslint --fix.
  'xo' - Fix JavaScript/TypeScript files using xo --fix.
 Linter Variables:

let g:ale_typescript_standard_executable = 'standard'
let g:ale_typescript_standard_options = ''
let g:ale_typescript_standard_use_global = 0
let g:ale_typescript_tslint_config_path = ''
let g:ale_typescript_tslint_executable = 'tslint'
let g:ale_typescript_tslint_ignore_empty_files = 0
let g:ale_typescript_tslint_rules_dir = ''
let g:ale_typescript_tslint_use_global = 0
let g:ale_typescript_tsserver_config_path = ''
let g:ale_typescript_tsserver_executable = 'tsserver'
let g:ale_typescript_tsserver_use_global = 0
let g:ale_typescript_xo_executable = 'xo'
let g:ale_typescript_xo_options = ''
let g:ale_typescript_xo_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'elixir': ['mix_format'], 'go': ['goimports', 'gofmt'], 'typescript': ['tslint', 'prettier'], 'scss': ['prettier'], 'terraform': ['terraform'], 'markdown.mdx': ['prettier'], 'javascript': ['eslint', 'prettier'], 'markdown': ['prettier']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'elixir': ['credo'], 'html': [], 'javascript': ['eslint', 'flow']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) eslint
(executable check - failure) standard
(executable check - failure) tslint
(executable check - failure) typecheck
(executable check - failure) xo
(executable check - failure) eslint
(executable check - failure) standard
(executable check - failure) tslint
(executable check - failure) typecheck
(executable check - failure) xo
(executable check - failure) eslint
(executable check - failure) standard
(executable check - failure) tslint
(executable check - failure) typecheck
(executable check - failure) xo
(executable check - failure) eslint
(executable check - failure) standard
(executable check - failure) tslint
(executable check - failure) typecheck
(executable check - failure) xo
 </p>
</details>

**Comment by RyanSquared** [comment]
It may be possible that if you're using a language server, the language server sends the documentation alongside that function, leading ALE to believe that you requested that documentation.

Can you use `ch_logfile()` to a file that you can send here for debugging? I believe the LSP output will be listed in there.

**Comment by RobinClowers** [comment]
Here you go, it's a lot of output, hopefully it's helpful!

[channel.log](https://github.com/dense-analysis/ale/files/3877022/channel.log)

**Comment by w0rp** [comment]
Documentation for items in the completion menu appear in the preview window by default. You can disable preview messages for completion by remove `preview` from `completeopt`. See `:h completeopt`.
