### ISSUE TITLE
Can we hide the quickfix/loc list all the time and open it on demand?

### ISSUE THREAD

**Issue by ckuchimanchi** [dense-analysis/ale#2912]
Hello,

I'd like to know if there's an option to always hide the quick fix list or location list, even if there are errors? I'm right now running an LSP/linter that's a bit flaky at times (and would automatically start working after few moments) and it's a bit frustrating to manually close the quick fix list every time it fails. Usually the sign gutter is enough for me to find any issues, so please let me know if there's a way to do this. Even if it's not a supporting setting right now, can I hack anything to make it behave so? 

Thanks in advance.

**Comment by w0rp** [comment]
Use the default setting of `let g:ale_open_list = 0`, or `let b:ale_open_list = 0` in your buffer, and use `:lopen` or `:copen` to open the windows.

**Comment by ckuchimanchi** [comment]
Thanks  w0rp. It's popping up the window even after setting that variable. (and is reflecting in ALEInfo that it's 0)

In this case, flow is just reporting that there are no errors and that it's running in watchman lazy mode. 
Please let me know if you need more details

Screenshot below:

![image](https://user-images.githubusercontent.com/7849452/69742302-752bd580-1134-11ea-8dcf-f7c23c8eb621.png)

ALEInfo Output:

[ALE_Info_Output.txt](https://github.com/dense-analysis/ale/files/3897911/ALE_Info_Output.txt)

**Comment by ckuchimanchi** [comment]
@w0rp Mentioning you so that you can look at this :) I can't open as this is closed by you.

**Comment by RyanSquared** [comment]
Can you reproduce this with just ALE? I think this may be another program that's configured to automatically open it.

Also, what's the configuration of your `.vimrc` ?

**Comment by ckuchimanchi** [comment]
Hi @RyanSquared Thank you so much for the note. I've tried removing the plugins one by one and was able to find the culprit! (vim-flow was the plugin). Thanks again for the response. Appreciate it. Closing this!
