### ISSUE TITLE
php-cs-fixer is not available as fixer

### ISSUE THREAD

**Issue by ecmrauh** [dense-analysis/ale#2921]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18 kompiliert am Jun 15 2019 16:41:15)
Inklusive der Patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401

Operating System: 
Debian Buster, KDE, Kernel Linux debian 5.2.0-0.bpo.2-amd64

## What went wrong

I tried to integrate php-cs-fixer, but calling :ALEFix results in the message:

`No fixers have been defined. Try :ALEFixSuggest`

php-cs-fixer works on the command line and within Vim with [this plugin](https://github.com/stephpy/vim-php-cs-fixer), but not with ALE. Other linters and fixers work as expected.

## Reproducing the bug

1. I installed [php-cs-fixer](https://cs.symfony.com/#globally-manual)
2. In updated ALE to v2.6.0
3. I set up the fixer in vimrc
`
let g:ale_fixers = {
...
\  'php': ['php-cs-fixer'],
...
}
`
4. Calling :ALEXFix results in `No fixers have been defined. Try :ALEFixSuggest`

### :ALEInfo

 Current Filetype: php
Available Linters: ['langserver', 'phan', 'php', 'phpcs', 'phpmd', 'phpstan', 'psalm']
  Enabled Linters: ['php']
 Suggested Fixers: 
  'php_cs_fixer' - Fix PHP files with php-cs-fixer.
  'phpcbf' - Fix PHP files with phpcbf.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_php_cs_fixer_executable = 'php-cs-fixer'
let g:ale_php_cs_fixer_use_global = 1
let g:ale_php_php_executable = 'php'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'yaml': ['prettier'], 'typescript': ['prettier'], 'go': ['gofmt'], 'markdown': ['prettier'], 'xml': ['xmllint'], 'json': ['prettier'], 'sh': ['shfmt'], 'php': ['php-cs-fixer'], 'html': ['prettier'], 'ruby': ['rubocop'], 'javascript': ['prettier'], 'css': ['prettier']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 0
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 0
let g:ale_lint_on_text_changed = 'never'
let g:ale_linter_aliases = {}
let g:ale_linters = {'yaml': ['yamllint'], 'typescript': ['tsserver'], 'go': ['golint'], 'markdown': ['markdownlint'], 'xml': ['xmllint'], 'json': ['jshint'], 'sh': ['shellcheck'], 'php': ['php'], 'ruby': ['rubocop'], 'javascript': ['jshint']}
let g:ale_linters_explicit = 1
let g:ale_list_vertical = v:null
let g:ale_list_window_size = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = v:null
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_sign_highlight_linenrs = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

**Comment by kakposoe** [comment]
If anyone is coming back to this issue. The definition of cs fixer requires underscores (`_`) rather than hyphens (`-`):

    let g:ale_fixers = { ... \ 'php': ['php_cs_fixer'], ... }
