### ISSUE TITLE
ALE doesn't load compile_commands.json file

### ISSUE THREAD

**Issue by fuzhen011** [dense-analysis/ale#2927]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 30 2019 23:05:13)
macOS version

Operating System: macOS Catalina, 10.15.1

## What went wrong

I was cross-compiling an embedded project using arm-none-eabi-gcc as the compiler and the compile_commands.json was generated by Bear. However, ALE seems not load it correctly. I'm not sure if this is a configuration problem but it loads the compile_commands.json file correctly in another project which uses native gcc.

## Reproducing the bug

1. I typed "bear make all" to compile an embedded project and generated the compile_commands.json
2. When I open any files in the project, ALE doesn't load the compiling flags in compile_commands.json.

### :ALEInfo

 Current Filetype: c
Available Linters: ['ccls', 'clang', 'clangd', 'clangtidy', 'cppcheck', 'cquery', 'flawfinder', 'gcc']
  Enabled Linters: ['gcc']
 Suggested Fixers: 
  'clang-format' - Fix C/C++ and cuda files with clang-format.
  'clangtidy' - Fix C/C++ and ObjectiveC files with clang-tidy.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'uncrustify' - Fix C, C++, C#, ObjectiveC, ObjectiveC++, D, Java, Pawn, and VALA files with uncrustify.
 Linter Variables:

let g:ale_c_build_dir = ''
let g:ale_c_build_dir_names = ['build', 'GNU ARM v7.2.1 - Default']
let g:ale_c_gcc_executable = 'arm-none-eabi-gcc'
let g:ale_c_gcc_options = '-std=c99 -Wall'
let g:ale_c_parse_compile_commands = 1
let g:ale_c_parse_makefile = 0
let g:ale_c_uncrustify_executable = 'uncrustify'
let g:ale_c_uncrustify_options = '-c ~/.uncrustify.cfg -l C --replace'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'vim': ['trim_whitespace'], 'cmake': ['cmakeformat', 'trim_whitespace'], 'c': ['uncrustify', 'trim_whitespace'], 'xml': ['xmllint', 'trim_whitespace'], 'json': ['prettier', 'trim_whitespace'], 'sh': ['shfmt', 'trim_whitespace'], '*': ['remove_trailing_lines'], 'cpp': ['uncrustify', 'trim_whitespace'], 'markdown': ['prettier'], 'python': ['autopep8', 'isort', 'trim_whitespace']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 1
let g:ale_linter_aliases = {}
let g:ale_linters = {'c': ['gcc'], 'cpp': ['gcc'], 'c++': ['gcc'], 'python': ['pylint']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 0
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = 'E'
let g:ale_sign_info = 'W'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = 'E'
let g:ale_sign_style_warning = 'W'
let g:ale_sign_warning = 'W'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = ['✗ %d', '⚡ %d', '✔ OK']
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) arm-none-eabi-gcc
(finished - exit code 1) ['/bin/zsh', '-c', '''arm-none-eabi-gcc'' -S -x c -o /dev/null -iquote ''/Users/zhfu/SimplicityStudio/v4_workspace/bg13_se'' -std=c99 -Wall - < ''/var/folders/88/y8cbjgx93r79j5jw65c3t81c0000gn/T/v32zFNb/1/app.c''']

<<<OUTPUT STARTS>>>
<stdin>:23:10: fatal error: bg_types.h: No such file or directory
compilation terminated.
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/bin/zsh', '-c', '''arm-none-eabi-gcc'' -S -x c -o /dev/null -iquote ''/Users/zhfu/SimplicityStudio/v4_workspace/bg13_se'' -std=c99 -Wall - < ''/var/folders/88/y8cbjgx93r79j5jw65c3t81c0000gn/T/v32zFNb/2/app.c''']

<<<OUTPUT STARTS>>>
<stdin>:23:10: fatal error: bg_types.h: No such file or directory
compilation terminated.
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/bin/zsh', '-c', '''arm-none-eabi-gcc'' -S -x c -o /dev/null -iquote ''/Users/zhfu/SimplicityStudio/v4_workspace/bg13_se'' -std=c99 -Wall - < ''/var/folders/88/y8cbjgx93r79j5jw65c3t81c0000gn/T/v32zFNb/3/app.c''']

<<<OUTPUT STARTS>>>
<stdin>:23:10: fatal error: bg_types.h: No such file or directory
compilation terminated.
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/bin/zsh', '-c', '''arm-none-eabi-gcc'' -S -x c -o /dev/null -iquote ''/Users/zhfu/SimplicityStudio/v4_workspace/bg13_se'' -std=c99 -Wall - < ''/var/folders/88/y8cbjgx93r79j5jw65c3t81c0000gn/T/v32zFNb/4/app.c''']

<<<OUTPUT STARTS>>>
<stdin>:23:10: fatal error: bg_types.h: No such file or directory
compilation terminated.
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/bin/zsh', '-c', '''uncrustify'' --no-backup -c ~/.uncrustify.cfg -l C --replace < ''/var/folders/88/y8cbjgx93r79j5jw65c3t81c0000gn/T/v32zFNb/5/app.c''']
(finished - exit code 1) ['/bin/zsh', '-c', '''arm-none-eabi-gcc'' -S -x c -o /dev/null -iquote ''/Users/zhfu/SimplicityStudio/v4_workspace/bg13_se'' -std=c99 -Wall - < ''/var/folders/88/y8cbjgx93r79j5jw65c3t81c0000gn/T/v32zFNb/6/app.c''']

<<<OUTPUT STARTS>>>
<stdin>:23:10: fatal error: bg_types.h: No such file or directory
compilation terminated.
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/bin/zsh', '-c', '''arm-none-eabi-gcc'' -S -x c -o /dev/null -iquote ''/Users/zhfu/SimplicityStudio/v4_workspace/bg13_se'' -std=c99 -Wall - < ''/var/folders/88/y8cbjgx93r79j5jw65c3t81c0000gn/T/v32zFNb/7/app.c''']

<<<OUTPUT STARTS>>>
<stdin>:23:10: fatal error: bg_types.h: No such file or directory
compilation terminated.
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/bin/zsh', '-c', '''uncrustify'' --no-backup -c ~/.uncrustify.cfg -l C --replace < ''/var/folders/88/y8cbjgx93r79j5jw65c3t81c0000gn/T/v32zFNb/8/app.c''']
(finished - exit code 1) ['/bin/zsh', '-c', '''arm-none-eabi-gcc'' -S -x c -o /dev/null -iquote ''/Users/zhfu/SimplicityStudio/v4_workspace/bg13_se'' -std=c99 -Wall - < ''/var/folders/88/y8cbjgx93r79j5jw65c3t81c0000gn/T/v32zFNb/9/app.c''']

<<<OUTPUT STARTS>>>
<stdin>:23:10: fatal error: bg_types.h: No such file or directory
compilation terminated.
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/bin/zsh', '-c', '''arm-none-eabi-gcc'' -S -x c -o /dev/null -iquote ''/Users/zhfu/SimplicityStudio/v4_workspace/bg13_se'' -std=c99 -Wall - < ''/var/folders/88/y8cbjgx93r79j5jw65c3t81c0000gn/T/v32zFNb/10/app.c''']

<<<OUTPUT STARTS>>>
<stdin>:23:10: fatal error: bg_types.h: No such file or directory
compilation terminated.
<<<OUTPUT ENDS>>>

**Comment by ranebrown** [comment]
The output format generated by bear isn't supported. See #1933.

**Comment by Ram-Z** [comment]
> Enabled Linters: ['gcc']

You don't have the clangtidy linter enabled. The only linter that is enabled is 'gcc' but it seems to use 'arm-none-eabi-gcc' instead.
