### ISSUE TITLE
ALEDetail preserve color

### ISSUE THREAD

**Issue by ultrox** [dense-analysis/ale#2928]
I wonder is there any way to pipe `ALEDEtails` text through the pygmentize, or just preserve original color?

**Comment by RyanSquared** [comment]
I think what you're asking is to highlight the function definition as though it were a code segment, but I'm not sure if that's possible, given it would require writing a syntax file for every possible ALEDetail, and assume that the current Vim syntax setup (which is always system dependent) can handle the function definition by itself, assuming that function definition is even valid code.

**Comment by ultrox** [comment]
@RyanSquared thanks for trying to help. In the meantime, I made a minimalistic plugin that does this.

https://github.com/ultrox/elm-ale-pretty
