### ISSUE TITLE
Support for Code Actions

### ISSUE THREAD

**Issue by husainaloos** [dense-analysis/ale#2930]
Currently, ALE does not seem to support Code Action functionality LSP support. This is to support this functionality.

Consider eclipse.jdt.ls LSP server; this server supports multiple code actions, such as formatting a file per custom eclipse format file (which is passed to the server as an argument). ALE does not support that out of the box.

Does this functionality already exist and I just missed it?

**Comment by RyanSquared** [comment]
I don't think it already exists. I'm not sure if code actions use arbitrary commands but if they do it might be hard to implement a standard interface that can be used with keybinds. I see generic stuff such as "refactor range" or "refactor line" but nothing more specific than that such as fix indentation or reformat.

I'm not sure how this would be best implemented.

**Comment by w0rp** [comment]
I've experimented with it before, and an issue is already open here: #1466
