### ISSUE TITLE
ale_linters has linters set, but none are enabled when editing a buffer

### ISSUE THREAD

**Issue by kovasap** [dense-analysis/ale#2939]
## Information

**VIM version**

NVIM v0.3.8
Build type: Release

Operating System: Linux

## What went wrong

I set my desired linters in g:ale_linters, but they are not enabled when I am editing my buffer.  This happened after I reinstalled all my plugins using vim-plug instead of vundle and reinstalled.  I've tried reinstalling ale and still see this problem.  Can I trigger a re-parse of the ale_linters dictionary somehow to try to re-enable my linters?

### :ALEInfo

 Current Filetype: python
Available Linters: ['bandit', 'flake8', 'mypy', 'prospector', 'pycodestyle', 'pydocstyle', 'pyflakes', 'pylama', 'pylint', 'pyls', 'pyre', 'vulture', 'glint']
  Enabled Linters: []
 Suggested Fixers: 
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'reorder-python-imports' - Sort Python imports with reorder-python-imports.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:

let g:ale_python_auto_pipenv = 0
let g:ale_python_gpylint_executable = 'bash'
let g:ale_python_gpylint_options = ' -c ''tf=$(mktemp /tmp/tmp.gpylint.XXXXXX) ; trap "rm -rf $tf" 0 ; cat > $tf ; gpylint3 "$@" $tf'' dummycmd --no-docstring-rgx=.'
let g:ale_python_gpylint_use_global = 1
 Global Variables:

let g:ale_cache_executable_check_failures = 1
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'bzl': ['glint'], 'c': [], 'go': ['govet'], 'markdown': ['gmdlint'], 'proto': ['glint'], 'java': ['glint'], 'javascript': ['glint'], 'cpp': [], 'python': ['gpylint']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = 1
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

**Comment by hsanson** [comment]
According to the log you show there are no linters enabled:

```
Enabled Linters: []
```

You must set the `g:ale_linters` variable in you configuration to enable them.

**Comment by w0rp** [comment]
`'python': ['gpylint']` There's a typo in your configuration, so all you'll need to do is fix that and ensure that `pylint` is installed, or `glint`, depending on which linter it is you want to run.

**Comment by kovasap** [comment]
Actually, gpylint is a modified version of pylint that I use (not a typo):

```
$ ls .vim/bundle/ale/ale_linters/python/
bandit.vim  flake8.vim  gpylint.vim  mypy.vim  prospector.vim  pycodestyle.vim  pydocstyle.vim  pyflakes.vim  pylama.vim  pylint.vim  pyls.vim  pyre.vim  vulture.vim
```

```
gpylint.vim
---------------
call ale#Set('python_gpylint_executable', 'gpylint3')
call ale#Set('python_gpylint_options', '')
call ale#Set('python_gpylint_use_global', get(g:, 'ale_use_global_executables', 0))
call ale#Set('python_gpylint_change_directory', 1)

function! ale_linters#python#gpylint#GetExecutable(buffer) abort
    return ale#python#FindExecutable(a:buffer, 'python_gpylint', ['gpylint3'])
endfunction

function! ale_linters#python#gpylint#GetCommand(buffer) abort
    let l:cd_string = ale#Var(a:buffer, 'python_gpylint_change_directory')
    \   ? ale#path#BufferCdString(a:buffer)
    \   : ''

    let l:executable = ale_linters#python#gpylint#GetExecutable(a:buffer)

    let l:exec_args = l:executable =~? 'pipenv$'
    \   ? ' run gpylint'
    \   : ''

    return l:cd_string
    \   . ale#Escape(l:executable) . l:exec_args
    \   . ' ' . ale#Var(a:buffer, 'python_gpylint_options')
    \   . ' --output-format=text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports=n'
    " \   . ' %s'
endfunction

call ale#linter#Define('python', {
\   'name': 'gpylint',
\   'executable_callback': 'ale_linters#python#gpylint#GetExecutable',
\   'command_callback': 'ale_linters#python#gpylint#GetCommand',
\   'callback': 'ale_linters#python#pylint#Handle',
\})
" \   'lint_file': 1,
```

**Comment by kovasap** [comment]
Are there some logs I can examine for ale to see if this linter attempted to load and failed?

**Comment by RyanSquared** [comment]
`:ALEInfo` will usually say information about what commands are run and whether ALE has found valid executables.

**Comment by RyanSquared** [comment]
I'm not sure what's up with your configuration because your plugin seems to have it defined as `gpylint3` and yet I see that your configuration has it set to `bash` along with some other options.

**Comment by kovasap** [comment]
The `bash` executable is a hack to get this linter to work with buffers before they are saved (essentially to write the buffer to a temporary file so that I can actually get async linting as I type).  I didn't come up with this solution, so I don't know all the details, but it has been working fine for me for almost a year so far.  I don't think it's related to the problem I'm seeing here (that the linter isn't enabled).

Are there any error logs anywhere I could see that trace ALE's process of attempting to enable linters?  That might reveal the root cause.

**Comment by kovasap** [comment]
Still looking for a way to find out where in ALE's linter enabling pipeline this is getting lost.  Anyone know how I could get more visibility into this pipeline via logs or code paths?

**Comment by kovasap** [comment]
Turns out that the problem was my linter configurations were in the "bundle" ale directory when I had things installed with vundle, and I didn't move them over to the "plugged" ale directory, which is created/managed by vim-plug.  Sorry for the spam!
