### ISSUE TITLE
ale_cpp_{gcc,clang}_options should be ignored when ale_c_parse_compile_commands = 1

### ISSUE THREAD

**Issue by Ram-Z** [dense-analysis/ale#2950]
When the compile flags are being read from a compilation database, ALE should'n override them by appending `ale_cpp_options` to the end.

Obviously one could simply `let g:ale_cpp_options = ''`, but that prevents setting sane defaults when a compilation database cannot be found. 

There should still be the ability to add additional options even if a compilation database is found.

I propose to split the variables into two `ale_cpp_options` and `ale_cpp_extra_options` and have something like this in `ale_linters/cpp/{gcc,clang}.vim`.

```diff
diff --git a/ale_linters/cpp/gcc.vim b/ale_linters/cpp/gcc.vim
index 108d6d7..6da499c 100644
--- a/ale_linters/cpp/gcc.vim
+++ b/ale_linters/cpp/gcc.vim
@@ -16,7 +16,7 @@ function! ale_linters#cpp#gcc#GetCommand(buffer, output) abort
     \   . ' -o ' . g:ale#util#nul_file
     \   . ' -iquote ' . ale#Escape(fnamemodify(bufname(a:buffer), ':p:h'))
     \   . ale#Pad(l:cflags)
-    \   . ale#Pad(ale#Var(a:buffer, 'cpp_gcc_options')) . ' -'
+    \   . ale#Pad(ale#Var(a:buffer, 'cpp_gcc_extra_options')) . ' -'
 endfunction
 
 call ale#linter#Define('cpp', {
diff --git a/autoload/ale/c.vim b/autoload/ale/c.vim
index 9b42870..c3d9b47 100644
--- a/autoload/ale/c.vim
+++ b/autoload/ale/c.vim
@@ -347,7 +347,8 @@ function! ale#c#GetCFlags(buffer, output) abort
     endif
 
     if l:cflags is v:null
-        let l:cflags = ale#c#IncludeOptions(ale#c#FindLocalHeaderPaths(a:buffer))
+        let l:cflags = ale#Var(a:buffer, 'cpp_gcc_options')
+        \            . ale#Pad(ale#c#IncludeOptions(ale#c#FindLocalHeaderPaths(a:buffer)))
     endif
 
     return l:cflags isnot v:null ? l:cflags : ''
```

**Comment by Ram-Z** [comment]
@w0rp Hopefully this is a quick one to ease you back in. Patch attached.

Thank you for all your work on this project.

**Comment by w0rp** [comment]
Almost all C/C++ issues with flags should now be discussed in #3276, so a comprehensive solution can be found for most people, for automatically detecting flags.
