### ISSUE TITLE
Add support for shfmt

### ISSUE THREAD

**Issue by mastertinner** [dense-analysis/ale#2952]
**Name:** shfmt
**URL:** https://github.com/mvdan/sh

This tool seems to be quite popular and provides an easy way of formatting shell scripts. It would be great to support it as a fixer.

**Comment by sQVe** [comment]
There is already support for that fixer. I've been running it for more than a year. See https://github.com/dense-analysis/ale/blob/master/doc/ale-sh.txt for further information.

I suggest closing this issue.

**Comment by mastertinner** [comment]
You're absolutely right, @sQVe. Thanks for pointing that out and sorry for not doing the proper research!
