### ISSUE TITLE
Always add the linter name to the error messages

### ISSUE THREAD

**Issue by hackaugusto** [dense-analysis/ale#2954]
I have a project in c/c++ that uses a cross compiler, this means most of the linters won't work out-of-the-box without setting the proper include paths and a few extra bits. Understanding which linter is not properly configure is a bit hard ATM. E.g. I had a nasty time with the 'clangd' since its error messages had the tag `[clang]` in the beginning, it mislead me to check the configuration from the wrong linter for a little while.

 Having the linter name consistently set, say at the beginning of the error message would help.

**Comment by TerryChau** [comment]
Already possible:

> let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'

**Comment by hackaugusto** [comment]
thanks
