### ISSUE TITLE
Allow virtual text to always appear for all issues

### ISSUE THREAD

**Issue by iocentos** [dense-analysis/ale#2962]
Just a small suggestion. 
I really like the virtual text option when I am on the line that has the issue. Currently you can choose between the following by setting the option `g:ale_virtualtext_cursor`

0 - completely disable the feature
1 - show virtual text one line at a time only when cursor is on the faulty line

There could be an extra option to allow to show virtual text for all issues in a file. In this case virtual text is always on for all issues. We would not need to hover or go to the line to actually see the error.

**Comment by bapjiws** [comment]
Is there any update on this one? Would be really neat to have it for the entire file all at once, like,say, [vim-lsp](https://github.com/prabirshrestha/vim-lsp#virtual-text) has it 🙂

**Comment by malukenho** [comment]
That would be pretty nice!

**Comment by malukenho** [comment]
I just made it work in a hacky way https://gist.github.com/malukenho/6392a69c55f3f1daff4ab4bfb7d56654
