### ISSUE TITLE
Rubocop linter and fixer are not working for me

### ISSUE THREAD

**Issue by jncampbell** [dense-analysis/ale#2975]
**VIM version**
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 19 2019 19:08:44)
Included patches: 1-503, 505-680, 682-1283, 1365

**Ruby version**
ruby-2.5.7

**Rubocop version**
.79.0

**System information **
macOS Mojave
Version 10.14.6

## What went wrong

ALE seems to stop working on ruby files because of rubocop. I have a brand new project and tried to set up Rubocop as my linter. I can see it active in the `Enabled Linters` section of my ALEInfo. However, not only does rubocop linting not work, it also seems to prevent any of my fixers from working. For instance, I have my fixers set to trim whitespace and trailing lines. If I remove any mention of rubocop from my ale configuration in my `.vimrc`, it works. And adding rubocop back as a linter/fixer seems to break it. I've scoured the other issues that mention ALE and Rubocop but none of those fixes work for me (I've set my rubocop executable to `bundle`, removed any flags that could conflict, and disabled other plugins).

One interesting thing I've noticed is that if I run `:debug` on the files, I get a 
```
E486: Pattern not found: EchoExecutable('rubocop')
```

I can run rubocop as a standalone and it reports correctly. And running: `:! which rubocop` outputs:
```
/Users/wheresmyspaceship/.rvm/gems/ruby-2.5.7/bin/rubocop
```
So it seems like my executable is there so I'm not sure where to go from here.

Can anyone see anything in my configuration that I'm missing or give me any more steps to debug this issue. Any help would be greatly appreciated!

** Steps to reproduce **
1. Create a new rails project using Ruby v2.5.7 and rails 5.2.4
2. Add the following configuration to your vimrc:
```
let g:ale_sign_error = '❌'
let g:ale_sign_warning = '⚠️ '
let g:ale_fix_on_save = 1
 
let g:ale_linters_explicit = 1

let g:ale_linters = {
\   'ruby': ['rubocop'],
\}

let g:ale_history_log_output = 1

let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'ruby': ['rubocop'],
\   'javascript': ['prettier', 'eslint'],
\   'typescript': ['eslint'],
\   'css': ['prettier']
\}

let g:ale_ruby_rubocop_executable = 'bundle'
let g:ale_ruby_rubocop_options = '-D'
```

### :ALEInfo
```
 Current Filetype: ruby
Available Linters: ['brakeman', 'debride', 'rails_best_practices', 'reek', 'rubocop', 'ruby', 'solargraph', 'sorbet', 'standardrb']
   Linter Aliases:
'sorbet' -> ['srb']
  Enabled Linters: ['rubocop']
 Suggested Fixers:
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'rubocop' - Fix ruby files with rubocop --auto-correct.
  'rufo' - Fix ruby files with rufo
  'sorbet' - Fix ruby files with srb tc --autocorrect.
  'standardrb' - Fix ruby files with standardrb --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_ruby_rails_best_practices_options = ''
let g:ale_ruby_rubocop_executable = 'bundle'
let g:ale_ruby_rubocop_options = '-D'
 Global Variables:
let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'typescript': ['eslint'], '*': ['remove_trailing_lines', 'trim_whitespace'], 'javascript': ['prettier', 'eslint'], 'ruby': ['rubocop'], 'css': ['prettier']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'ruby': ['rubocop']}
let g:ale_linters_explicit = 1
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '❌'
let g:ale_sign_info = '⚠️ '
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '❌'
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) bundle
(finished - exit code 1) ['sh', '-c', '''bundle'' exec rubocop --format json --force-exclusion -D --stdin ''/Users/wheresmyspaceship/Desktop/Code/ChallengesAPI/app/controllers/application_controller.rb'' < ''/var/folders/rl/6qkhh4616cs1wyd67xvqv48w0000gn/T/vz0qCPn/3/application_cont
roller.rb''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/bin/bash', '-c', '''bundle'' exec rubocop --config ''/Users/wheresmyspaceship/Desktop/Code/ChallengesAPI/.rubocop.yml'' -D --auto-correct --force-exclusion ''/var/folders/rl/6qkhh4616cs1wyd67xvqv48w0000gn/T/vz0qCPn/5/application_controller.rb''']
(finished - exit code 1) ['/bin/bash', '-c', '''bundle'' exec rubocop --format json --force-exclusion -D --stdin ''/Users/wheresmyspaceship/Desktop/Code/ChallengesAPI/app/controllers/application_controller.rb'' < ''/var/folders/rl/6qkhh4616cs1wyd67xvqv48w0000gn/T/vz0qCPn/6/applicati
on_controller.rb''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/bin/bash', '-c', '''bundle'' exec rubocop --config ''/Users/wheresmyspaceship/Desktop/Code/ChallengesAPI/.rubocop.yml'' -D --auto-correct --force-exclusion ''/var/folders/rl/6qkhh4616cs1wyd67xvqv48w0000gn/T/vz0qCPn/7/application_controller.rb''']
(finished - exit code 1) ['/bin/bash', '-c', '''bundle'' exec rubocop --format json --force-exclusion -D --stdin ''/Users/wheresmyspaceship/Desktop/Code/ChallengesAPI/app/controllers/application_controller.rb'' < ''/var/folders/rl/6qkhh4616cs1wyd67xvqv48w0000gn/T/vz0qCPn/8/applicati
on_controller.rb''']

<<<NO OUTPUT RETURNED>>>
```

**Comment by elebow** [comment]
I am able to reproduce the behavior under Ruby 2.6.5 with the `.vimrc` lines from the issue description and this Ruby file:

```ruby
class What
end

```

1. When the rubocop fixer cannot run, none of the other fixers seem to be run. This may be a bug, or it may be an intentional decision to be conservative with fixers—I'm not very familiar with that part of ALE.

   `:echo ale#fix#Fix(bufnr(''), '')` returns 1, so the function is running to the end without error. It just doesn't change the buffer.

1. @jncampbell, your particular case appears to mix a system gem RuboCop and a bundler-managed RuboCop.

   If you wish to use bundler-managed RuboCop, add `rubocop` to your Gemfile and keep `let g:ale_ruby_rubocop_executable = 'bundle'` in your `.vimrc`.

   If you wish to use the system RuboCop, run `gem install rubocop` (bearing in mind the Ruby version that may be managed by rbenv/rvm/etc) and leave `g:ale_ruby_rubocop_executable` unset.

   This may resolve the issue for you regardless of the possible fixer bug.

**Comment by jncampbell** [comment]
@elebow Unfortunately, neither of those works for me. The vimrc config above has the ruby executable set to bundler.

Alternatively, I've tried installing rubocop globally on my system and removing the setting for the rubocop executable from my vimrc and that yielded the same results

Glad to know its not just me. I've been banging my head on this for 2 days now

**Comment by hsanson** [comment]
@jncampbell I think there is a misunderstanding on how the fixers configuration work. From the ALEInfo you posted I see you have these fixers configured:

```
let g:ale_fixers = {
   \ 'typescript': ['eslint'], 
   \ '*': ['remove_trailing_lines', 'trim_whitespace'],
   \ 'javascript': ['prettier', 'eslint'],
   \ 'ruby': ['rubocop'],
   \ 'css': ['prettier']
   \ }
```

With this configuration if you execute :ALEFix it will only run rubocop when the buffer is a ruby file. If you also want the generic fixers to run for ruby buffers you need to add them to the ruby key:

```
   \ 'ruby': ['rubocop','remove_trailing_lines', 'trim_whitespace' ],
```

Since rubocop does both remove_trailing_lines and trim_whitespaces it really does not make sense to have all three configured.

I have no issues with ruby 2.5.1 and rubocop 0.67.2.

**Comment by w0rp** [comment]
Yeah, that's right. `*` is a fallback for when no other filetype is matched. If you want to use them in every place, you can add them in every place. You can do that easily by applying a Vim function in your vimrc file `'filetype': f(['a', 'b', 'c'])`, etc. It's not done by ALE, as there's not much need to, and everything little thing like that makes ALE a little slower.

**Comment by jncampbell** [comment]
Ahh. I see. I mistakenly thought * told ALE to run these fixes regardless of the filetype, '*' in regex usually meaning all.

ok. so the whitespace and trailing lines are working but I'm still not seeing Rubocop errors. 

My Gemfile looks like:
```
# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.7'

gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'email_address'
gem 'jwt'
gem 'mysql2', '>= 0.4.4', '< 0.6.0'
gem 'puma', '~> 3.11'
gem 'rails', '~> 5.2.4'
gem 'simple_command'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails', '~> 3.5'
  gem 'rubocop', '~> 0.79.0', require: false
  gem 'rubocop-rails', require: false
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'database_cleaner'
  gem 'factory_bot_rails', '~> 4.0'
  gem 'faker'
  gem 'shoulda-matchers', '~> 3.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

```

The `require: false` is suggested by rubucop if you're planning to use it with bundler.

And when I run `bundle exec rubocop` I see the errors but nothing in VIM.

**Comment by w0rp** [comment]
You are right in thinking it means "all," it just means "all if everything else fails."

I will leave the actual rubocop issues here to people who understand Ruby better. I might try to get some pull requests merged over the next few weeks. I haven't been able to work on ALE for a while now.

**Comment by hsanson** [comment]
@jncampbell It is common for these linters to change their output, thus breaking ALE parsers. Can you please post here the json ouput you get when running rubocop directly from the terminal? Best if you use the exact same command reported by ALEInfo:

```
bundle exec rubocop --format json --force-exclusion -D --stdin ''/Users/wheresmyspaceship/Desktop/Code/ChallengesAPI/app/controllers/application_controller.rb'' < ''/var/folders/rl/6qkhh4616cs1wyd67xvqv48w0000gn/T/vz0qCPn/8/application_controller.rb
```

Here is an example running ruby 2.5.1 and rubocop 0.71.0:

```json
rubocop --format json --force-exclusion Projects/ruby/test.rb
{"metadata":{"rubocop_version":"0.71.0","ruby_engine":"ruby","ruby_version":"2.5.1","ruby_patchlevel":"57","ruby_platform":"x86_64-linux-gnu"},"files":[{"path":"test.rb","offenses":[{"severity":"convention","message":"Trailing whitespace detected.","cop_name":"Layout/TrailingWhitespace","corrected":false,"location":{"start_line":9,"start_column":4,"last_line":9,"last_column":4,"length":1,"line":9,"column":4}},{"severity":"convention","message":"1 trailing blank lines detected.","cop_name":"Layout/TrailingBlankLines","corrected":false,"location":{"start_line":13,"start_column":1,"last_line":14,"last_column":0,"length":1,"line":13,"column":1}}]}],"summary":{"offense_count":2,"target_file_count":1,"inspected_file_count":1}}
```

**Comment by jncampbell** [comment]
Running that command exactly as you pasted gave me the following error: 
```
-bash: /var/folders/rl/6qkhh4616cs1wyd67xvqv48w0000gn/T/vz0qCPn/8/application_controller.rb: No such file or directory
```
When I run it with the `/var/folders/rl/6qkhh4616cs1wyd67xvqv48w0000gn/T/vz0qCPn/8/application_controller.rb`
part, it hangs indefinitely.

The only thing that works is removing he `--stdin` flag. 

When I remove that I receive:
```
{"metadata":{"rubocop_version":"0.79.0","ruby_engine":"ruby","ruby_version":"2.5.7","ruby_patchlevel":"206","ruby_platform":"x86_64-darwin18"},"files":[{"path":"app/controllers/application_controller.rb","offenses":[{"severity":"convention","message":"Style/Documentation: Missing top-level class documentation comment.","cop_name":"Style/Documentation","corrected":false,"correctable":false,"location":{"start_line":1,"start_column":1,"last_line":1,"last_column":5,"length":5,"line":1,"column":1}},{"severity":"convention","message":"Style/FrozenStringLiteralComment: Missing magic comment `# frozen_string_literal: true`.","cop_name":"Style/FrozenStringLiteralComment","corrected":false,"correctable":true,"location":{"start_line":1,"start_column":1,"last_line":1,"last_column":1,"length":1,"line":1,"column":1}},{"severity":"convention","message":"Layout/LineLength: Line is too long. [51/25]","cop_name":"Layout/LineLength","corrected":false,"correctable":true,"location":{"start_line":1,"start_column":26,"last_line":1,"last_column":51,"length":26,"line":1,"column":26}},{"severity":"convention","message":"Layout/LineLength: Line is too long. [37/25]","cop_name":"Layout/LineLength","corrected":false,"correctable":true,"location":{"start_line":2,"start_column":26,"last_line":2,"last_column":37,"length":12,"line":2,"column":26}},{"severity":"convention","message":"Layout/LineLength: Line is too long. [27/25]","cop_name":"Layout/LineLength","corrected":false,"correctable":true,"location":{"start_line":3,"start_column":26,"last_line":3,"last_column":27,"length":2,"line":3,"column":26}},{"severity":"convention","message":"Layout/TrailingWhitespace: Trailing whitespace detected.","cop_name":"Layout/TrailingWhitespace","corrected":false,"correctable":true,"location":{"start_line":4,"start_column":1,"last_line":4,"last_column":4,"length":4,"line":4,"column":1}},{"severity":"convention","message":"Layout/LineLength: Line is too long. [26/25]","cop_name":"Layout/LineLength","corrected":false,"correctable":true,"location":{"start_line":7,"start_column":26,"last_line":7,"last_column":26,"length":1,"line":7,"column":26}},{"severity":"convention","message":"Layout/LineLength: Line is too long. [68/25]","cop_name":"Layout/LineLength","corrected":false,"correctable":true,"location":{"start_line":8,"start_column":26,"last_line":8,"last_column":68,"length":43,"line":8,"column":26}},{"severity":"convention","message":"Layout/LineLength: Line is too long. [78/25]","cop_name":"Layout/LineLength","corrected":false,"correctable":true,"location":{"start_line":9,"start_column":26,"last_line":9,"last_column":78,"length":53,"line":9,"column":26}},{"severity":"convention","message":"Rails/HttpStatus: Prefer `:unauthorized` over `401` to define HTTP status code.","cop_name":"Rails/HttpStatus","corrected":false,"correctable":true,"location":{"start_line":9,"start_column":55,"last_line":9,"last_column":57,"length":3,"line":9,"column":55}},{"severity":"convention","message":"Style/IfUnlessModifier: Modifier form of `unless` makes the line too long.","cop_name":"Style/IfUnlessModifier","corrected":false,"correctable":true,"location":{"start_line":9,"start_column":59,"last_line":9,"last_column":64,"length":6,"line":9,"column":59}}]}],"summary":{"offense_count":11,"target_file_count":1,"inspected_file_count":1}}
```

**Comment by hsanson** [comment]
Json output is identical and rubocop output parser and tests are all correct. I am sorry to say I cannot see any issues on ALE side.

**Comment by RyanSquared** [comment]
So if I understand correctly, it is now hanging when using `--stdin` ? What command are you using when you use `--stdin`, including all arguments?

**Comment by hsanson** [comment]
Sorry if my example above was confusing.  The --stdin option requires a file to be read from STDIN and this file is magically generated by ALE. Therefore it only exists when ALE executes rubocop:

    --stdin  < /var/folders/rl/6qkhh4616cs1wyd67xvqv48w0000gn/T/vz0qCPn/8/application_controller.rb

This is why you get a file not found error when you run the command outside ALE.

From the ALEInfo you posted we can see that ALE is executing rubocop:

```
 Command History:

(executable check - success) bundle
(finished - exit code 1) ['sh', '-c', '''bundle'' exec rubocop --format json --force-exclusion -D --stdin ''/Users/wheresmyspaceship/Desktop/Code/ChallengesAPI/app/controllers/application_controller.rb'' < ''/var/folders/rl/6qkhh4616cs1wyd67xvqv48w0000gn/T/vz0qCPn/3/application_cont
roller.rb''']
```
But then it shows there was no output at all from that command:

```
<<<NO OUTPUT RETURNED>>>
```

This means rubocop did not output anything, therefore ALE gets no errors.

You can try running the command in the terminal, removing the stdin part, to see what output you get:

```
bash -c bundle exec rubocop --format json --force-exclusion -D /Users/wheresmyspaceship/Desktop/Code/ChallengesAPI/app/controllers/application_controller.rb
```

IMPORTANT:  ALE runs the commands within the same directory vim is. This may be the problem with bundle that requires you to run within the root folder of the rails project. Within vim run `:pwd` to see the current path and then run the above command within that directory.

**Comment by jncampbell** [comment]
@hsanson @RyanSquared So I was actually able to get this working by setting the rubocop executable in my .vimrc with an absolute path. I had stumbled across [https://github.com/dense-analysis/ale/issues/1016#issuecomment-338377209](this)  before but never went the route of setting an absolute path because running `which bundle` from the command lline and `!which bundle` from vim gave me the same output. 

Not sure if that was a change or points to something else going on with my environment but the absolute path works so I'll go ahead and close this out.

Thank you all so much for all your help! Awesome tool and community.
