### ISSUE TITLE
Add autoimport support for LSP linters

### ISSUE THREAD

**Issue by jeremija** [dense-analysis/ale#2976]
Hello!

I made some changes to completion.vim that enable autoimports for completions from LSP servers using the `additionalTextEdits` variable. I've used it for a while in a Go project and seems to work well (similar to #2779). 

I'd like to submit a pull request for it, but I would need my PR #2823 merged (or rejected) first. This has been open for a while and I believe I've implemented all the requested changes. I'd greatly appreciate it if somebody can review this.

Cheers,
🍺

**Comment by w0rp** [comment]
I'm slowing catching up on issues, and I might have a look at the pull request soon. My plan is to add stalebot only for pull requests, close some old pull request that haven't been looked at in ages, and merge all of the pull requests that are basically good to go.
