### ISSUE TITLE
Disable line highlights for only specific error codes/messages

### ISSUE THREAD

**Issue by w0rp** [dense-analysis/ale#2982]
Often during testing or debugging code you want to make changes to code that will trigger errors that span multiple lines, slow down editing, and make your code look ugly. If you are displaying errors in a file in some other way, such as with the gutter/sign icons, you don't need to see the ugly line highlights to know that you have to fix something.

I think it would a good idea to add a setting for disabling line highlights for very specific error codes, and also with support for matching errors to ignore for highlighting based on the message with regex. This is only an issue for highlights, so we wouldn't need to consider filtering for other ways of displaying errors, in the short term.

**Comment by vkaracic** [comment]
@w0rp I'm getting this error when saving files now:
```
Error detected while processing function <SNR>125_NeoVimCallback[29]..<lambda>19[1]..<SNR>119_ExitCallback[28]..<SNR>118_HandleExit[45]..ale#engine#HandleLoclist[40]..ale#engine#SetResults[19]..ale#highlight#SetHighlights[8]..ale#Var:
line    4:
E716: Key not present in Dictionary: ale_exclude_highlights
Press ENTER or type command to continue
```
which is related to this work I presume.
Reading the changes I believe `ale_exclude_highlights` is optional?

**Comment by RyanSquared** [comment]
It should be optional and additionally it should be *set* if it isn't already (based on the line here: https://github.com/dense-analysis/ale/commit/bbe5153fcb36dec9860ced33ae8ff0b5d76ac02a#diff-f6b9e256c10b3ac5141bd19d5007c1f3R113).

What's the output of `:ALEInfo` now, and `:echo g:ale_exclude_highlights` ?

**Comment by vkaracic** [comment]
Sorry! Just had to restart Vim for changes to take effect I guess.
`:echo g:ale_exclude_highlights` now correctly returns `[]`.
