### ISSUE TITLE
About ale-go-bingo not continue to maintain; please delete the options

### ISSUE THREAD

**Issue by Gemo-X** [dense-analysis/ale#2992]
[saibing/bingo](https://github.com/saibing/bingo) is not continue. The Options For `ale-go-bingo`, I don't think it's necessary.
**Recommended deletion**
[ #13 collaborating on golsp](https://github.com/saibing/bingo/issues/13)

**Comment by w0rp** [comment]
I'll keep it around for a very long time. It might be worth not enabling it by default at some point.
