### ISSUE TITLE
ale_javascript_eslint_suppress_eslintignore analogy for tslint

### ISSUE THREAD

**Issue by bogdan** [dense-analysis/ale#2993]
I am looking to disable tslint for files in `node_modules`. This is set in my tslint.json config.

The same behavior seems to be achivable for `eslint` by using `ale_javascript_eslint_suppress_eslintignore` variable.

Is it possible to add the similar config variable for `tslint`?

**Comment by w0rp** [comment]
There's no point improving `tslint` at this point, as it has been deprecated. At some point, I'll remove the linter from ALE.

Have a look at this project, which replaces TSLint: https://github.com/typescript-eslint/typescript-eslint
