### ISSUE TITLE
local .rubocop.yml isn't used when using ALE

### ISSUE THREAD

**Issue by fakeharxy** [dense-analysis/ale#2995]
## Information

NVIM v0.4.3
Build type: Release

Operating System:  Mac OS Mojave
## What went wrong

When using rubocop as the ruby linter, it is not seem to use the local .rubocop.yml and defaults to the global rubocop settings. For clarity, VSCode and Solargraph pick up these settings.

Something went wrong in specifically this place, and I also searched through both open and closed issues for the same problem before reporting a bug here.

Are you having trouble configuring ALE? Try asking for help on [Stack Exchange](https://vi.stackexchange.com/) or perhaps on [Reddit](https://www.reddit.com/r/vim/) instead. The GitHub issue tracker should be used for reporting bugs or asking for new features.

## Reproducing the bug

have a .rubocop.yml with some specifications in a project.
Use Ale and see if the specifications are picked up.

### :ALEInfo

I don't have anything particularly interesting in my .vimrc but here it is anyway:

```
let g:ale_fixers = {
\   'ruby': ['rubocop'],
\}

let g:ale_sign_error = '!>'
let g:ale_sign_warning = '>>'
let g:ale_sign_column_always = 1
let g:ale_lint_delay = 1000
highlight clear ALEErrorSign
highlight clear ALEWarningSign
hi ALEErrorSign   guibg=#501010 ctermbg=52 guifg=#FD3F44 ctermfg=203
hi ALEWarningSign guibg=#503010 ctermbg=58 guifg=#FF9800 ctermfg=208
```

**Comment by bekicot** [comment]
I ran into similiar behavior, I though ALE wasn't pick up `.rubocop.yml`

But the problem was, ALE tried to run linter to every available ruby linters (`standardrb`, `rufo`, etc)

In my case, I installed `standardrb` which ignores `.rubocop.yml`

To fix it, I added this to my `init.vim`
```
let g:ale_fixers = {'ruby': ['rubocop']}
```
It probably will disable linters on another file type I was lazy, most of my work are in ruby anyway. see `readme` and configure it based on your needs.

**Comment by fakeharxy** [comment]
Hi! Thank you! This wasn't exactly my problem, as the fixer was working fine, it was the linter that was wrong. But, you led me to the solution, which was almost exactly as you say... so, I added:

```
let g:ale_linters = {
\   'ruby': ['rubocop'],
\}
```

to my vimrc and boom! It seems to work as I want.

**Comment by bekicot** [comment]
Awesome. I think this issue should be closed.
