### ISSUE TITLE
black fixer could use psf black.vim

### ISSUE THREAD

**Issue by marciomazza** [dense-analysis/ale#2998]
It looks like the black fixer on 
https://github.com/dense-analysis/ale/blob/master/autoload/ale/fixers/black.vim

could be faster if it delegated to the official `black.vim` plugin on
https://github.com/psf/black/blob/master/plugin/black.vim

If I understood correctly, `black.vim` avoids reading the file from disk by using the buffer contents in memory.

**Comment by w0rp** [comment]
I don't want to rely on other plugins in that way, but the fixer could be enhanced to use options for reading from stdin and so on, if `black` supports options like that now.

**Comment by marciomazza** [comment]
I see.

The `black.vim` plugin user the method `black.format_file_contents` to format the buffer contents directly. For reference, that happens here:

https://github.com/psf/black/blob/ce14fa8b497bae2b50ec48b3bd7022573a59cdb1/plugin/black.vim#L119

**Comment by georgexsh** [comment]
@w0rp black supports reading from stdin: `black -`. if the black fixer could leverage this, I guess it could format `netrw` buffer.

**Comment by w0rp** [comment]
The black fixer seems to use `-` now, so I'm closing this.

**Comment by georgexsh** [comment]
@w0rp I have just updated ale to 0989da4a, but found `netrw` and range still don't work.
