### ISSUE TITLE
Disable ale_fix_on_save when in a specific directory?

### ISSUE THREAD

**Issue by kevholder** [dense-analysis/ale#3002]
Is it possible to disable `let g:ale_fix_on_save = 1` in a specific directory?

**Comment by w0rp** [comment]
What you should do is use the buffer option `b:ale_fix_on_save` and write some Vim script to set the option based on whatever paths you want. You can also use `g:ale_pattern_options` to do the same with some regex for paths. Have a look at the help text for each.
