### ISSUE TITLE
ale_linters_ignore variable missing in :ALEInfo

### ISSUE THREAD

**Issue by majewsky** [dense-analysis/ale#3003]
As of current master, `g:ale_linters_ignore` is not shown in the list of global variables in `:ALEInfo`.

**Comment by zeorin** [comment]
ATM I'm working around this with:
```
autocmd FileType javascript let b:ale_linters_ignore = ['tsserver']
```

**Comment by w0rp** [comment]
Ignored linters now appear clearly in `:ALEInfo`, along with more ALE variables.
