### ISSUE TITLE
Using ALE in very large source trees

### ISSUE THREAD

**Issue by danijar** [dense-analysis/ale#3020]
I'm working on a repository with hundreds of thousands of files. Vim becomes very slow when enabling ALE even when only editing a single Python file at a time. I first tried to restrict ALE to files within a smaller subdirectory of interest inside the large repository:

```
let g:ale_linters = {'python': ['flake8']}
let g:ale_pattern_options = {
\ '/big/repository/.*': {'ale_enabled': 0},
\ '/big/repository/.*/relevant/subdirectory/.*': {'ale_enabled': 1},
\}
```

This indeed disables ALE outside of the subdirectory. However, it does not speed up linting of files inside the subdirectory. This made me think that running flake8 on the files of interest might still analyze files from parent directories to find symbols. To check this, I tried to exclude the whole repository from flake8:

```
let g:ale_python_flake8_options = "--exclude=/big/repository/*"
```

This indeed disabled all linting within the repository. However, having ALE enabled still slows down Vim by the same amount as before, even though all files are excluded from flake8 and no warnings show up. I'm hoping you might have insights into why this is still slow and how to completely restrict ALE to a subdirectory of a large repository.

**Comment by danijar** [comment]
Not solved but reporting progress. Opening buffers has changed from ~5s to a bit under 500ms by disabling the search for virtual envs in the file tree:

```
let g:ale_use_global_executables = 1
```

**Comment by bukzor** [comment]
Similarly, you want `let g:ale_virtualenv_dir_names=[]` to prevent extra `stats` for a virtualenv directory.
I found this with `strace -e file -o vim.strace vim`.

**Comment by bukzor** [comment]
A more accurate title would be "Using ALE in very slow filesystems". It's not tree size but rather `stat` latency that is the key factor here.

**Comment by w0rp** [comment]
There's nothing we can really change by default to make working with some projects faster. You just have to change the options to limit how many files ALE searches across. Note that you can use `b:ale_virtualenv_dir_names` in your ftplugin file for particular file paths you can write your own `if` statements for.
