### ISSUE TITLE
Add support for deno fmt on typescript files

### ISSUE THREAD

**Issue by fczuardi** [dense-analysis/ale#3023]
**Name:** deno fmt
**URL:** https://deno.land/std/manual.md#built-in-deno-utilities--commands

[Deno](https://deno.land/) is an alternative to node.js and it has a code formatter tool.

As a workaround, I have tried to use the following lines on my .vimrc but I could not make it work, I must be doing something wrong :(

```
let g:ale_fixers['typescript'] = ['prettier']
let g:ale_typescript_prettier_executable = 'deno fmt'
let g:ale_typescript_prettier_use_global = 1
```

**Comment by flipactual** [comment]
Here's what I'm doing after finding help over [here](https://github.com/dense-analysis/ale/issues/3167#issuecomment-721280756)

```
function! FormatDeno(buffer) abort
  return {
        \   'command': 'deno fmt -'
        \}
endfunction

execute ale#fix#registry#Add('denofmt', 'FormatDeno', ['typescript'], 'deno fmt for TypeScript')

let g:ale_fixers = {
      \   'typescript': ['denofmt'],
      \}
```

**Comment by nlordell** [comment]
For those wanting to use the new `deno lsp` subcommand for linting, it also works out of the box with ALE:

```vim
function! DenoProjectRoot(buffer) abort
    return expand('#' . a:buffer . ':p:h')
endfunction

execute ale#linter#Define('typescript', {
\   'name': 'deno',
\   'lsp': 'stdio',
\   'initialization_options': {
\       'enable': v:true,
\       'lint': v:true,
\       'unstable': v:true,
\   },
\   'executable': 'deno',
\   'command': '%e lsp -q',
\   'project_root': function('DenoProjectRoot'),
\})

let b:ale_linters = ['deno']
```

**Comment by nlordell** [comment]
I think this issue can be closed now. Latest ALE includes `deno` linter (using `deno lsp`) and fixer (using `deno fmt`) out of the box. You can enable the fixer for example with:
```vim
let g:ale_fixers = {
    \   'typescript': ['deno'],
    \}
```

**Comment by khangal** [comment]
for anyone who struggling to setup both tsserver and deno

in ~/.config/nvim/lua/filetypes/typescript.lua

local has_deno = vim.fn.filereadable("deno.json") == 1

```
if has_deno then
    vim.b.ale_fixers = {
        typescript = {'deno'},
    }
    vim.b.ale_linters = {
        typescript = {'deno'},
    }
else
    vim.b.ale_fixers = {
        typescript = {'eslint', 'prettier'},
    }
    vim.b.ale_linters = {
        typescript = {'eslint'},
    }
end
```
