### ISSUE TITLE
ale_python_pyls_options

### ISSUE THREAD

**Issue by n8henrie** [dense-analysis/ale#3033]
`pyls` is conspicuously missing from the list of python linters that supports additional command line arguments:

```console
$ curl -s https://raw.githubusercontent.com/dense-analysis/ale/master/doc/ale-python.txt | awk '$1 ~ /^g:.*_options/ { print $1 }'
g:ale_python_autopep8_options
g:ale_python_bandit_options
g:ale_python_black_options
g:ale_python_flake8_options
g:ale_python_isort_options
g:ale_python_mypy_options
g:ale_python_prospector_options
g:ale_python_pycodestyle_options
g:ale_python_pydocstyle_options
g:ale_python_pylama_options
g:ale_python_pylint_options
g:ale_python_reorder_python_imports_options
g:ale_python_vulture_options
```

It's been [discussed][1] in the context of changing the pyls configuration, but my use case (and I suspect the more common use case) would be for invoking pyls as a module, [like this example in the documentation for flake8][2] .

For some reason my python install loses its `pyls` executable frequently, even though the module remains and is still works fine with `python -m pyls`. I've tried `let g:ale_python_pyls_executable = "/usr/local/bin/python3 -m pyls"` but this doesn't work. Being able to follow the example of several other python linters and use:

```
let g:ale_python_pyls_executable = 'python3'
let g:ale_python_pyls_options = '-m pyls'
```

seems like it would do the trick. I'd be happy to work on a PR if this seems acceptable.

[1]: https://github.com/dense-analysis/ale/issues/1443
[2]: https://github.com/dense-analysis/ale/blob/master/doc/ale-python.txt#L202

**Comment by w0rp** [comment]
Yeah, add a pull request for it. Just make it clear what the difference between `_config` and `_options` is, in the documentation.
