### ISSUE TITLE
error finding /bin/bash

### ISSUE THREAD

**Issue by eyalk5** [dense-analysis/ale#3038]
## Information

**VIM version**
NVIM v0.5.0-295-g234232ff4
Build type: Release

Operating System: High Sierra
I work with nvim-qt

## What went wrong

At some point when working with tex files, I get the following error. I keep getting this error  whenever  I save the file. 
I don't have exact reproducible procedure. 
I work with vimtex + coc-texlab. 

```
Error detected while processing function ale#events#SaveEvent[13]..ale#Queue[33]..<SNR>129_Lint[26]..ale#engine#RunLinters[14]..<SNR>249_RunLinter[6]..<SNR>249_RunIfExecutable[36]..<SNR>249_RunJob[28]..ale#command#Run[56]..ale#job#Start:
line   21:
E903: Process failed to start: resource temporarily unavailable: "/bin/bash"
```

### :ALEInfo

 Current Filetype: 
Available Linters: []
  Enabled Linters: []
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'tex': ['chktex', 'latexindent', 'texlab', 'textlint'], 'text': ['textlint'], 'python': ['black']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

**Comment by RyanSquared** [comment]
This can mean that either your `/bin/bash` does not have the appropriate permissions or you're running into some sort of user limits issue. If it happens seemingly at random, I think it could be due to your ulimits, which you can see by using `ulimit -a`.

**Comment by eyalk5** [comment]
Well, apparently my entire OS is malfunction.  too many handles.
