### ISSUE TITLE
Add support for gitlab-lint

### ISSUE THREAD

**Issue by scottrbaxter** [dense-analysis/ale#3039]
**Name:** gitlab-lint
**URL:** https://github.com/elijah-roberts/gitlab-lint

Linter for `.gitlab-ci.yml` files, using the gitlab api.

The cli version (installed via `python3 -m pip install -U gitlab_lint`) has been very useful, and I believe would make a great addition to ale.

**Comment by thegcat** [comment]
Duplicates #843
