### ISSUE TITLE
-std in ale_{c,cpp}_{clang,gcc}_options overrides -std from compile_commands.json

### ISSUE THREAD

**Issue by ts826848** [dense-analysis/ale#3055]
## Information

**VIM version**

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  4 2020 22:41:50)
Included patches: 1-350

Operating System: macOS 10.15.3

## What went wrong

ALE appends its flags after the flags parsed from compile_commands.json (and guessing the same for Makefiles?). If ALE's flags contain `-std`, it will override the parsed `-std` flags, potentially resulting in errors that are not consistent between vim and the actual build.

If the `-std` flag must remain in `ale_{c,cpp}_{clang,gcc}_options`, this can be worked around either by swapping the `ale#Pad` calls in the `return` statement in `ale_linters#{c,cpp}#{clang,gcc}#GetCommand`, by filtering out `-std` from ALE's flags if it is present in `l:cflags`, or some other option.

I'm open to making a PR for this. I considered making one instead of an issue, but I was not sure what the best approach would be, as swapping the `ale#Pad` calls could result in similar issues in the reverse direction (i.e., perhaps a user *wants* ALE's flags to override other flags), and I wasn't sure if there might be a better solution than filtering out `-std`.

## Reproducing the bug

CMakeLists.txt:

```cmake
project(test)
add_executable(main main.cpp)
target_compile_features(main PRIVATE cxx_std_17)
```

main.cpp:

```cpp
#include <type_traits>
int main() {
	return std::is_same_v<int, float>;
}
```

1. Put CMakeLists.txt and main.cpp in same directory
2. `mkdir build && cd build`
3. `cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON`
4. `make` -> no compile errors
5. `vim ../main.cpp` -> error on line 3:

```
no template named 'is_same_v' in namespace 'std'; did you mean 'is_same'?
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits:872:61: note: 'is_same' declared here
```

`std::is_same_v` was introduced in C++17.

### :ALEInfo

 Current Filetype: cpp
Available Linters: ['ccls', 'clang', 'clangcheck', 'clangd', 'clangtidy', 'clazy', 'cppcheck', 'cpplint', 'cquery', 'flawfinder', 'gcc']
   Linter Aliases:
'gcc' -> ['g++']
  Enabled Linters: ['ccls', 'clang', 'clangcheck', 'clangd', 'clangtidy', 'clazy', 'cppcheck', 'cpplint', 'cquery', 'flawfinder', 'gcc']
 Suggested Fixers: 
  'clang-format' - Fix C/C++ and cuda files with clang-format.
  'clangtidy' - Fix C/C++ and ObjectiveC files with clang-tidy.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'uncrustify' - Fix C, C++, C#, ObjectiveC, ObjectiveC++, D, Java, Pawn, and VALA files with uncrustify.
 Linter Variables:

let g:ale_cpp_ccls_executable = 'ccls'
let g:ale_cpp_ccls_init_options = {}
let g:ale_cpp_clang_executable = 'clang++'
let g:ale_cpp_clang_options = '-std=c++14 -Wall'
let g:ale_cpp_clangcheck_executable = 'clang-check'
let g:ale_cpp_clangcheck_options = ''
let g:ale_cpp_clangd_executable = 'clangd'
let b:ale_cpp_clangd_executable = '/usr/local/opt/llvm/bin/clangd'
let g:ale_cpp_clangd_options = ''
let g:ale_cpp_clangtidy_checks = []
let g:ale_cpp_clangtidy_executable = 'clang-tidy'
let g:ale_cpp_clangtidy_extra_options = ''
let g:ale_cpp_clangtidy_options = ''
let g:ale_cpp_clazy_checks = ['level1']
let g:ale_cpp_clazy_executable = 'clazy-standalone'
let b:ale_cpp_clazy_executable = '/usr/local/opt/clazy/bin/clazy-standalone'
let g:ale_cpp_clazy_options = ''
let g:ale_cpp_cppcheck_executable = 'cppcheck'
let g:ale_cpp_cppcheck_options = '--enable=style'
let g:ale_cpp_cpplint_executable = 'cpplint'
let g:ale_cpp_cpplint_options = ''
let g:ale_cpp_cquery_cache_directory = '/Users/awang/.cache/cquery'
let g:ale_cpp_cquery_executable = 'cquery'
let g:ale_cpp_flawfinder_executable = 'flawfinder'
let g:ale_cpp_flawfinder_minlevel = 1
let g:ale_cpp_flawfinder_options = ''
let g:ale_cpp_gcc_executable = 'gcc'
let g:ale_cpp_gcc_options = '-std=c++14 -Wall'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'*': ['remove_trailing_lines', 'trim_whitespace']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) ccls
(executable check - success) clang++
(finished - exit code 1) ['/bin/zsh', '-c', '''clang++'' -S -x c++ -fsyntax-only -iquote ''/private/tmp'' -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -std=gnu++1z -std=c++14 -Wall - < ''/var/folders/38/7n17x4m55w523lmdfxz5yxtr0000gn/T/vNQ2l2K/1/main.cpp''']

<<<OUTPUT STARTS>>>
<stdin>:3:14: error: no template named 'is_same_v' in namespace 'std'; did you mean 'is_same'?
        return std::is_same_v<int, float>;
               ~~~~~^~~~~~~~~
                    is_same
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits:872:61: note: 'is_same' declared here
template <class _Tp, class _Up> struct _LIBCPP_TEMPLATE_VIS is_same           : public false_type {};
                                                            ^
<stdin>:3:35: error: expected '(' for function-style cast or type construction
        return std::is_same_v<int, float>;
               ~~~~~~~~~~~~~~~~~~~~~~~~~~^
2 errors generated.
<<<OUTPUT ENDS>>>

(executable check - failure) clang-check
(executable check - success) /usr/local/opt/llvm/bin/clangd
(executable check - failure) clang-tidy
(executable check - success) /usr/local/opt/clazy/bin/clazy-standalone
(finished - exit code 0) ['/bin/zsh', '-c', '''/usr/local/opt/clazy/bin/clazy-standalone'' -checks=''level1'' -p ''/private/tmp/build'' ''/private/tmp/main.cpp''']

<<<NO OUTPUT RETURNED>>>

(executable check - failure) cppcheck
(executable check - failure) cpplint
(executable check - failure) cquery
(executable check - failure) flawfinder
(executable check - success) gcc
(finished - exit code 1) ['/bin/zsh', '-c', '''gcc'' -S -x c++ -o /dev/null -iquote ''/private/tmp'' -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -std=gnu++1z -std=c++14 -Wall - < ''/var/folders/38/7n17x4m55w523lmdfxz5yxtr0000gn/T/vNQ2l2K/2/main.cpp''']

<<<OUTPUT STARTS>>>
<stdin>:3:14: error: no template named 'is_same_v' in namespace 'std'; did you mean 'is_same'?
        return std::is_same_v<int, float>;
               ~~~~~^~~~~~~~~
                    is_same
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits:872:61: note: 'is_same' declared here
template <class _Tp, class _Up> struct _LIBCPP_TEMPLATE_VIS is_same           : public false_type {};
                                                            ^
<stdin>:3:35: error: expected '(' for function-style cast or type construction
        return std::is_same_v<int, float>;
               ~~~~~~~~~~~~~~~~~~~~~~~~~~^
2 errors generated.
<<<OUTPUT ENDS>>>

(started) ['/bin/zsh', '-c', '''/usr/local/opt/llvm/bin/clangd'' -compile-commands-dir=''/private/tmp/build''']

**Comment by w0rp** [comment]
Almost all C/C++ issues with flags should now be discussed in #3276, so a comprehensive solution can be found for most people, for automatically detecting flags.
