### ISSUE TITLE
Javalsp doesn't have "<path-to-java-language-server>/java-language-server/dist/mac/bin/launcher" in their latest version

### ISSUE THREAD

**Issue by rightpeter** [dense-analysis/ale#3059]
## Information

**VIM version**

NVIM v0.4.3
Build type: Release

Operating System: 

## What went wrong

macOS 10.14.6

Something went wrong in specifically this place, and I also searched through both open and closed issues for the same problem before reporting a bug here.

Are you having trouble configuring ALE? Try asking for help on [Stack Exchange](https://vi.stackexchange.com/) or perhaps on [Reddit](https://www.reddit.com/r/vim/) instead. The GitHub issue tracker should be used for reporting bugs or asking for new features.

## Reproducing the bug

1. I did this: I tried to use Javalsp with Ale, but it complained about "executable check - success" for "java-language-server/dist/mac/bin/launcher". When I checked the dist folder build with latest Javalsp build script. I found there is no "launcher" any more. What I did was rolling back to the previous Javalsp commit and compiled from there.
2. Then this happened: Then it worked. But I think this can be fixed easily with a few lines change? I'm willing to learn how to fix this bug. Any suggestion on where I shall start?

Thanks!

### :ALEInfo

ALEInfo seems not relevant here.

**Comment by hsanson** [comment]
@rightpeter unfortunately javalsp devs keep changing this a lot and keeping the documentation on sync is challenging.

The latest version has language launcher scripts, for linux would be:

```
let g:ale_java_javalsp_executable = '/path/to/java-language-server/dist/lang_server_linux.sh'
```

There are lang_server_mac.sh and lang_server_windows.sh scripts for those platforms too.

**Comment by rightpeter** [comment]
> @rightpeter unfortunately javalsp devs keep changing this a lot and keeping the documentation on sync is challenging.
> 
> The latest version has language launcher scripts, for linux would be:
> 
> ```
> let g:ale_java_javalsp_executable = '/path/to/java-language-server/dist/lang_server_linux.sh'
> ```
> 
> There are lang_server_mac.sh and lang_server_windows.sh scripts for those platforms too.

Interesting, thanks for the clarification!
