### ISSUE TITLE
Floating window causes some abnormal phenomena.

### ISSUE THREAD

**Issue by onlycalm** [dense-analysis/ale#3072]
Floating windows that pop up when syntax errors are detected can cause some exceptions. But these phenomena will not cause the function to stop. If they can be improved, the user experience will be better.
* Before the floating window appears, an abnormal highlight will pop up in the center of the screen.
![8~BPBWIZD(BCH5VBLR6T2}O](https://user-images.githubusercontent.com/48640489/77390341-acec1680-6dd0-11ea-817d-62d2dce3df3b.png)
Then
![2020-03-24_9-13-19](https://user-images.githubusercontent.com/48640489/77390359-b83f4200-6dd0-11ea-98a9-04eb5b8dba23.png)
I have verified that other plug-in pop-up floating windows do not have this phenomenon.

* Floating window causes neartree to page up.
This anomaly may also be a problem with neartree. I've tried other plugins that don't have this problem with floating windows.
When more files are displayed in the neartree, the floating window will cause the neartree to page up. It seems to want the current file to be called the first line in the neartree. Sometimes it's not stable. It's always bouncing on the left. 
![2020-03-24_14-13-19](https://user-images.githubusercontent.com/48640489/77394719-01948f00-6ddb-11ea-9f30-f81398aa1ba2.png)
then
![2020-03-24_14-12-49](https://user-images.githubusercontent.com/48640489/77394725-048f7f80-6ddb-11ea-8fac-1840056835a1.png)

Thank you for the convenience this plug-in brings to my programming. It's excellent

**Comment by Calm-cpy** [comment]
The second question should have nothing to do with ale. After I tried to disable the plugins ryanoasis/vim-devicons, the failure disappeared.
