### ISSUE TITLE
Shut down idle LSPs

### ISSUE THREAD

**Issue by danielbeardsley** [dense-analysis/ale#3073]
I work on a fairly large php project and psalm (and its integration with ale) is fantastic.

Ale launches one "Psalm language server" per vim process and those (in my project) take upwards of 2 - 4GB of RAM each. This means I can only have several vim instances alive on my machine at any given time.

A reasonable solution could be to kill LSPs after some period of idleness. Then, restart them the first time they are requested.

That... or find some way to share the Psalm LSP so we don't need one per vim instance, but that seems much harder.

**Comment by danielbeardsley** [comment]
It turns out, ALE will already re-launch LSPs (at least psalm) if it disappears, so setting a timeout and killing procs we haven't made a request to in some amount of time seems not too difficult.

**Comment by w0rp** [comment]
I think the best way to handle this, as a timeout could confuse users and kill servers that need to stay alive, is to use the existing command `:ALEStopAllLSPs`.
