### ISSUE TITLE
Prepend linter name to error message

### ISSUE THREAD

**Issue by dubst3pp4** [dense-analysis/ale#3088]
Hello,
I've searched in the docs but could not find how to show which linter reports the error in the quickfix/location window?

In my projects I usually run different linters, but I want to see which error is coming from which linter, so it would be nice to have the name of the linter somehow prepended to the error, eg.:

    nuxt.config.js|1 col 45 error| <jshint> Missing semicolon.

Is this somehow possible?

**Comment by hsanson** [comment]
It is possible to configure the message shown in the quickfix/location window using the `g:ale_echo_msg_format`:

```
let g:ale_echo_msg_format = '%severity% [%linter%] (%code%) - %s'
```

**Comment by dubst3pp4** [comment]
Wow thank you so much, exactly what I wanted :-)
