### ISSUE TITLE
C/C++: should add support for @file arguments

### ISSUE THREAD

**Issue by sudobash1** [dense-analysis/ale#3092]
## Background
GCC and Clang allow you to place command line flags together in a file, and include all of those flags as if they were on the command line by using a `@file` flag.

For example, suppose I had the file `./debug_args` with the content:
```
-DDEBUG
-O0
-g
```
and I ran gcc like this:
```
gcc @debug_args -o main main.c
```
It would be equivalent to running:
```
gcc -DDEBUG -O0 -g -o main main.c
```
## Request

Currently, ALE will filter out `@file` flags. I would like them to be properly handled by ALE.

I came across this recently when compiling a project which used `@file` flags. I used [bear](https://github.com/rizsotto/Bear) to generate a `compile_commands.json` file, but had issues because ALE was filtering out the `@file` flag `gcc` needed.

**Comment by w0rp** [comment]
Almost all C/C++ issues with flags should now be discussed in #3276, so a comprehensive solution can be found for most people, for automatically detecting flags.
