### ISSUE TITLE
Include support of std::filesystem

### ISSUE THREAD

**Issue by Apitronix** [dense-analysis/ale#3097]
Hi there !

It seems that the namespace **std::filesystem** (from C++ 17) is not recognize by ALE (at least by default).
I think it's a good idea to fix it.
Tell me if I'm wrong and / or if you need more information.

Thanks for all,
Ben.

**Comment by wwitzke** [comment]
I am experiencing this problem as well. Is there maybe a work around? Maybe I need to configure ALE for C++17 or something like that?

**Comment by wwitzke** [comment]
I was able to fix this problem by setting the appropriate options for the gcc lint parser. In my .vimrc file I added:
`let g:ale_cpp_gcc_options = '-std=c++17 -Wall'`
Now there seems to be no issue with std::filesystem. I'd say this is not an issue.

**Comment by w0rp** [comment]
Agreed, this is not an issue. I think it's still a little too early to use C++17 by default, at least not until perhaps Debian stable uses GCC 9 or greater. You just have to change the C++ standard if you want to use a newer one by default.
