### ISSUE TITLE
Language servers and |ale_lint_on_text_changed|

### ISSUE THREAD

**Issue by mversic** [dense-analysis/ale#3105]
## Information

**VIM version**
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5

Operating System:
Manjaro 19.0.2 Kyria

## What went wrong

When `ale_lint_on_text_changed=never` ALE shouldn't lint while I am inserting which it doesn't unless I have ALE configured with some language server. I've tried using `rls` and `pyls`, it happened for both. 
As far as I can determine, with language servers used, ALE bahaves as if `ale_lint_on_text_changed=insert` was set even when it's set to `never`.

## Reproducing the bug

1. enable LS for some language
2. set `ale_lint_on_text_changed=never`
3. open a document and start typing randomly
4. observe how linting is being done even though it shouldn't be

### :ALEInfo
```
Current Filetype: rust
Available Linters: ['cargo', 'rls', 'rustc']
Enabled Linters: ['rls']
Suggested Fixers:
'remove_trailing_lines' - Remove all blank lines at the end of a file.
'rustfmt' - Fix Rust files with Rustfmt.
'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
Linter Variables:

let g:ale_rust_rls_config = {}
let g:ale_rust_rls_executable = 'rls'
let g:ale_rust_rls_toolchain = ''
Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 1
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_linter_aliases = {}
let g:ale_linters = {'rust': ['rls'], 'python': ['pyls']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = v:null
let g:ale_list_window_size = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_sign_highlight_linenrs = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
Command History:

(executable check - success) rls
(started) ['/usr/bin/zsh', '-c', '''rls''''']'''']
```

**Comment by mnilyshome** [comment]
K

**Comment by jasontcole** [comment]
I am trying to setup ale for the first time today and am having issues getting lint_on_text_changed='never' to work.

**Comment by jasontcole** [comment]
I ended up adding this and behaves like I was hoping.  Not sure what the difference is between these variables...

`let g:ale_lint_on_insert_leave = 0
`

**Comment by mversic** [comment]
@jasontcole as far as I can see you are not using a language server, therefore your comment is unrelated to this issue

**Comment by mversic** [comment]
@jasontcole if you are not using a language server, and it seems you don't, then your problem is unrelated to this issue

**Comment by copy** [comment]
I also have this issue with ALE and rls. The issue goes away when automatic completion popups are disabled (e.g., `let g:ale_completion_enabled = 0` and deoplete is disabled). I suspect rls responds with a list of errors when ALE asks it for completion, and ALE fills the error list with this info even though `ale_lint_on_text_changed=never` is set.

**Comment by w0rp** [comment]
It is not possible to fix this without changing Language Server Protocol itself. See this issue I filed a while ago: https://github.com/microsoft/language-server-protocol/issues/737

**Comment by copy** [comment]
@w0rp I don't see this being fixed upstream any time soon. In the mean time, could ALE buffer diagnostic responses when in insert mode?

**Comment by w0rp** [comment]
No, the LSP standard should be changed.
