### ISSUE TITLE
Unknown function ale#linter#Define

### ISSUE THREAD

**Issue by dylanirlbeck** [dense-analysis/ale#3112]
I was trying to configure ALE and my ocaml linter like this:

```
call ale#linter#Define('ocaml', {
\   'name': 'ocaml-lsp',
\   'lsp': 'stdio',
\   'executable': function('s:executable_callback'),
\   'command': function('s:get_command'),
\   'language': function('s:get_language'),
\   'project_root': function('s:get_project_root')
\})
```

but I get the following error on startup:

```
line  353:                                                                                              
E117: Unknown function: ale#linter#Define                                                                
```

## Information

Neovim

MacOSX

## What went wrong

I was adding some linters to my ALE configuration 

## Reproducing the bug

I opened Neovim from the terminal.

**Comment by creativenull** [comment]
Hey @dylanirlbeck 

Did you try calling the define function after you load all your plugins? I also had this issue, after calling the define function after loading all my plugins did the trick.

**Comment by dylanirlbeck** [comment]
Hey @creativenull. I totally forgot I opened this issue! I can't remember exactly what I did to fix it, though I wouldn't be surprised if what you suggested was indeed the fix.

I'll close this out for now.
