### ISSUE TITLE
ale#Env quoting bug on Windows

### ISSUE THREAD

**Issue by char101** [dense-analysis/ale#3115]
## Information

**VIM version**

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 16 2020 10:34:48)
MS-Windows 64-bit GUI version

Operating System: Windows 10

## What went wrong

On Windows, `ale#Env` sets environment variable which contains space this way

```batch
set ENV=" value "
```

When set this way, the quotes become part of the environment variable value. The right way is

```batch
set "ENV= value "
```

This problem can be observed on the `xmllint` fixer because on Windows it indents with `"  "` (quotes included) because the supposed two space indent `  ` is quoted as `"  "` when set into `XMLLINT_INDENT` environment variable.

## Reproducing the bug

On Windows

1. set `xmllint` as fixer for `xml`
2. open an `xml` file and save it

**Comment by w0rp** [comment]
I've fixed this now. Values without spaces or special characters will be set with `set foo=bar`. Spaces will be escaped via `ale#Escape` like `set "foo=some words"`. When there's no spaces, other characters may be escaped with carets (`^`).
