### ISSUE TITLE
Disable Ale on startup

### ISSUE THREAD

**Issue by tkolleh** [dense-analysis/ale#3127]
Are there a set of options that disable ale (`:ALEDisable`) on startup (default) and use `:ALEEnable` to enable it as needed? If not it would be helpful to have a global option for disabling Ale on vim/neovim startup.

**Comment by kornicameister** [comment]
@tkolleh what about [this](https://github.com/kornicameister/dotfiles/blob/master/vim/plugins.vim#L349). This is for linting.  You can disable a part of `ale`.

Or, according to the docs, there are both global and buffer options `ale_enabled`. So I assume you can try doing `b:ale_enabled = 0` for particular file type or `g:ale_enabled = 0` for whole setup.

**Comment by tkolleh** [comment]
Thanks for providing the info and sharing the documentation.
