### ISSUE TITLE
Retain ALEPreviewWindow when a reference is opened

### ISSUE THREAD

**Issue by jericdeleon** [dense-analysis/ale#3128]
First, thanks for the great plugin! Been using it to great effect.

During reference investigation in a codebase, I usually enter into this workflow:
1. Using `ALEFindReferences`, I view the reference list in `ALEPreviewWindow`.
2. I open the 1st reference in a new tab with `t`. 
3. When I go back to the previous tab (with `gt`), I find that `ALEPreviewWindow` is gone. So I highlight the symbol once more, use `ALEFindReferences`, eyeball the last location that I checked, move to the next reference, and so on.

It'd be so useful if there was a way to make `ALEPreviewWindow` stick instead of it closing after a new reference tab is opened. Is there a simple way to do so?

**Comment by tplk** [comment]
It was actually this way before https://github.com/dense-analysis/ale/commit/82f734a7c286d8705c9a6e2879b4173fe18a6356#diff-7886de1b9eb477acb2e0edff7c99e8ddR103

You can manually remove this line for now.

**Comment by john-kurkowski** [comment]
A workaround is to read `ALEFindReferences` into the quickfix list. Once that list is opened, it sticks around. See [this comment in #1759](https://github.com/dense-analysis/ale/issues/1759#issuecomment-601263880).

**Comment by jericdeleon** [comment]
That workaround is even better than what I wanted, thanks @john-kurkowski!

**Comment by shirohana** [comment]
I met the same problem, here's my workaround:

#### .vimrc
```vim
autocmd MyAutoCmd FileType ale-preview-selection
      \ nnoremap <buffer> <CR> :<C-u>call helper#ale#OpenSelection()<CR>

```

#### plugin/helper/ale.vim
```vim
function! s:Open() abort
    let l:item_list = get(b:, 'ale_preview_item_list', [])
    let l:index = getpos('.')[1] - 1
    let l:item = get(l:item_list, l:index, {})

    if empty(l:item)
        return
    endif

    wincmd p

    call ale#util#Open(
    \   l:item.filename,
    \   l:item.line,
    \   l:item.column,
    \   {'open_in': 'current-buffer'},
    \)
endfunction

function! helper#ale#OpenSelection() abort
    call s:Open()
endfunction
```

By the way, is there any easy way to change the preview window to the bottom?

**Comment by karolinepauls** [comment]
So there is no solution that doesn't include hacking ALE?
