### ISSUE TITLE
Different virtualenv for different linters

### ISSUE THREAD

**Issue by JPFrancoia** [dense-analysis/ale#3142]
Hi,

I've been using ale with neovim for quite some time now. I use various linters and I code in Python. I have a "problem" regarding the virtualenv of each linter. Here is what I would like to achieve:

- mypy should always use the virtualenv of the current Python project
- flake8 should always use the `nvim` virtualenv. nvim is the virtualenv for neovim, as recommended in the doc here: https://github.com/neovim/neovim/wiki/Installing-Neovim, and it uses pynvim.

I have this in my neovim config file to tell it where to find the python executable:

```
let g:python3_host_prog = '/Users/jpfrancoia/.local/share/virtualenvs/nvim/bin/python'
```

I need this separation of virtualenvs because mypy needs access to all the libraries installed for a given Python project. So it needs to work in the virtualenv of the Python project I'm working on.

Flake8 however doesn't need access to these libraries, and I want it configured in a certain way: I always install a lot of flake8 plugins. I can't install all these plugins for each Python project I work on, this would introduce too many dependencies for each project.

Is there a way to achieve that?

I tried to put this in my neovim python config file:

```
let g:ale_virtualenv_dir_names = ['/Users/jpfrancoia/.local/share/virtualenvs/nvim']
```

And it forces ale to use the nvim virtualenv for *all* linters. This includes mypy, which therefore doens't have access to the libraries of the Python project I work on. Flake8 works as expected in this case.

If I do this:

```
let g:ale_virtualenv_dir_names = []
```

Ale uses the venv of the Python project. Mypy works as expected, but not flake8!

Any idea?

**Comment by w0rp** [comment]
The default for `g:ale_virtualenv_dir_names` is `['.env', '.venv', 'env', 've-py3', 've', 'virtualenv', 'venv']`, which are some common directory names. I prefer to put the virtualenv directory inside a git repository I'm working on, and then ALE finds that at the root of the project and uses that.

For loading virtualenv directories that are in other locations, I believe some people prefer this plugin: https://github.com/jmcantrell/vim-virtualenv You can also either configure your `vtplugin` file to see the virtualenv directory for different projects, or use `g:ale_pattern_options` to set them up based on regex for paths to files.

**Comment by JPFrancoia** [comment]
Thanks for your answer. However I believe it's not exactly what I'm looking for.

> The default for g:ale_virtualenv_dir_names is ['.env', '.venv', 'env', 've-py3', 've', 'virtualenv', 'venv'], which are some common directory names. I prefer to put the virtualenv directory inside a git repository I'm working on, and then ALE finds that at the root of the project and uses that.

This actually doesn't matter too much, because if you run `pipenv shell` or `poetry shell`  and *then* start editing the file, the virtualenv is properly detected. I can use mypy and flake8 installed in the virtualenv of the Python project.

I want to use mypy from the Python project's venv, but flake8 from the nvim virtualenv.

If I do this:

```
let g:ale_virtualenv_dir_names = []
```

I believe Ale will use the `$VIRTUALENV` variable for its venv, which is properly set if you run `pipenv shell` or `poetry shell`.

If I do this:

```
let g:ale_virtualenv_dir_names = ['/Users/jpfrancoia/.local/share/virtualenvs/nvim']
```

I am able to load another virtualenv. But I'm in either of these two situations:

- mypy from Python project venv, flake8 from python project venv
- mypy from nvim virtualenv, flake8 from nvim virtualenv

But what I would like is:

- mypy from Python project venv, flake8 from nvim virtualenv

Do you think it's possible?

**Comment by w0rp** [comment]
You can set the `_executable` option for `flake8` to `whatever-directory/bin/flake8`, but really you should install a specific `flake8` version in the project and require that everyone else working on the project use the same version, or you'll have a lot of conflicts.
