### ISSUE TITLE
Fixer Speed

### ISSUE THREAD

**Issue by nkabbara** [dense-analysis/ale#3149]
Hello!

Is the speed of the fixer in the gif below the expected speed of fixing? If not, how can I go about troubleshooting the slowness?

Thank you!

p.s didn't use template because it's much clearer to describe this specific possible issue with gif.

![fixer](https://user-images.githubusercontent.com/31865/80742613-4948bd80-8ae1-11ea-8ef7-36848e680b5b.gif)

**Comment by w0rp** [comment]
There's no way to improve on this in ALE. It's the program you're running that's slow. If you're using ESLint for fixing your code, I recommend trying [eslint_d](https://www.npmjs.com/package/eslint_d), which keeps some information in memory and runs faster.
