### ISSUE TITLE
Is there a way remove all unused import in python file

### ISSUE THREAD

**Issue by zdmgmail** [dense-analysis/ale#3156]
Is there a way remove all unused import in python file?

I saw someone say ale can do these, but I haven't found it after a long search ..

**Comment by RyanSquared** [comment]
ALE has a set of fixers for Python that you can use to automatically reorder imports, though I do not know if they will remove unused ones. If you look at the documentation for `:h ale-fix`, you can read more about the fixers system. The ones that you might find useful are probably `isort` or `reorder_python_imports`.

**Comment by zdmgmail** [comment]
> ALE has a set of fixers for Python that you can use to automatically reorder imports, though I do not know if they will remove unused ones. If you look at the documentation for `:h ale-fix`, you can read more about the fixers system. The ones that you might find useful are probably `isort` or `reorder_python_imports`.

I just found that recorder_python_imports works, but there seems to be no way to remove unused import

**Comment by RyanSquared** [comment]
Perhaps we do not have one that just removes unused imports. Maybe `yapf`'s fixer would do it, but it also reformats the file entirely.

**Comment by zdmgmail** [comment]
> e `yapf`

I don't find it in `yapf` , but find another way

```
:ALEFix reorder-python-imports<CR>
:w<cr>
:!autoflake --in-place --remove-all-unused-imports %<cr>
```

But the strange thing is that if the file is saved quickly, the third command is invalid
So I can’t put these three commands into a shortcut key and I have to execute it manually

Why is this   ... Is this because of ale ?

**Comment by zdmgmail** [comment]
> Perhaps we do not have one that just removes unused imports. Maybe `yapf`'s fixer would do it, but it also reformats the file entirely.

I don't find it in yapf , but find another way

:ALEFix reorder-python-imports<CR>
:w<cr>
:!autoflake --in-place --remove-all-unused-imports %<cr>
But the strange thing is that if the file is saved quickly, the third command is invalid
So I can’t put these three commands into a shortcut key and I have to execute it manually

Why is this ... Is this because of ale ?

**Comment by RyanSquared** [comment]
If ALE is set to run configured fixers on save, or the ALE fixing process takes longer than it takes to run those two commands, then ALE can still be running in the background while you're running your other commands.
