### ISSUE TITLE
There is no .deb package.

### ISSUE THREAD

**Issue by pavel-the-best** [dense-analysis/ale#3160]
1) This is easier to install plugin from deb package.
2) I've wanted to submit vim-ale to debian repo, but I didn't find the package.

What requirements does ale have? I wanted to create the package, but I didn't find the requirements.

**Comment by nospam2998** [comment]
According to [packages.debian.org](https://packages.debian.org/vim-ale), vim-ale is available in bullseye, bookworm and sid. Details in [salsa](https://salsa.debian.org/vim-team/vim-ale). Similarly, searching [packages.ubuntu.com](https://packages.ubuntu.com/vim-ale) suggests availability in universe for hirsute, impish and jammy.

Ergo, there are .deb packages. Could this ticket thus be closed?

**Comment by pavel-the-best** [comment]
Sure, that feels like a LONG time ago
