### ISSUE TITLE
Provide `node_modules` path for js related linters?

### ISSUE THREAD

**Issue by lowski** [dense-analysis/ale#3162]
Hi!
I've been working on monorepo project with structure as follows:

```
project
  - app
  - ember
    - node_modules
    - index.js
```

If I open a neovim from project root, is there a way to let Ale know that all JavaScript related linters and fixers (eslint / prettier) are in `node_modules` directory inside `ember` folder?

I've tried to search existing issues and docs to find option for that but I wasn't able to find anything that matches my use case.

Thank you in advance!

**Comment by hsanson** [comment]
Check `:h ale-integrations-local-executables`. By default ALE will look for the linter executables within those local folders unless the global executable flag is set.
