### ISSUE TITLE
Flake8 errors are kept hidden until all pylint warnings are fixed (errors and warnings exist in the same line)

### ISSUE THREAD

**Issue by gbihtas** [dense-analysis/ale#3168]
## Information

**VIM version**
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  2 2020 19:10:24)
Included patches: 1-501

Operating System: MX-19.1_x64 patito feo (Debian 10)

## What went wrong

I am using Ale for a Python project which lives in a conda venv with flake8 and pylint installed.
When pylint warnings and flake8 errors exist in the same line then the flake8 error is hidden until all pylint warnings are resolved. The only way to find out about the existence of the flake8 error is either to resolve all warnings (which might not be realistic in some use cases) or run `:lopen` (or flake8 from terminal) which makes redundant the visual representation of the errors/warnings in the gutter since you can no longer trust it. 

## Reproducing the bug

 I created the following code snippet to reproduce the problematic behaviour.

![ale1s](https://user-images.githubusercontent.com/17926845/81785730-899f3700-94f6-11ea-8b7f-b3ff217f5d27.jpg)

Line 6 has 2 pylint warnings ("Too many arguments" and "Unused argument") as well as a flake8 error: `error| [flake8] E303: too many blank lines (3)` 

The flake8 error is hidden and the user doesn't know its existence in order to fix it unless the warnings are fixed or you execute `:lopen` (or flake8 from terminal) 

After removing the "Unused arguments" warning, the flake8 error is still hidden:

![ale2s](https://user-images.githubusercontent.com/17926845/81786737-f830c480-94f7-11ea-9fb8-4c790d6b85fd.jpg)

I have to change the code and remove some arguments in order to fix the "Too many arguments" warning. Then the flake8 error becomes visible. Obviously you can't reduce the number of arguments in a real life scenario. So in that case the flake8 error will be always hidden unless you run `:lopen` or `flake8` in the terminal. This creates a loss of trust since valuable information are kept hidden and the visual representation of the errors becomes obsolete since you always have to manually check for hidden errors as the final source of truth.

![ale3s](https://user-images.githubusercontent.com/17926845/81787095-768d6680-94f8-11ea-8b23-025c74d96920.jpg)

### :ALEInfo

 Current Filetype: python
Available Linters: ['bandit', 'flake8', 'mypy', 'prospector', 'pycodestyle', 'pydocstyle', 'pyflakes', 'pylama', 'pylint', 'pyls', 'pyre', 'vulture']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Suggested Fixers: 
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'reorder-python-imports' - Sort Python imports with reorder-python-imports.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:

let g:ale_python_auto_pipenv = 0
let g:ale_python_flake8_auto_pipenv = 0
let g:ale_python_flake8_change_directory = 1
let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
let g:ale_python_mypy_auto_pipenv = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_ignore_invalid_syntax = 0
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_show_notes = 1
let g:ale_python_mypy_use_global = 0
let g:ale_python_pylint_auto_pipenv = 0
let g:ale_python_pylint_change_directory = 1
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
let g:ale_python_pylint_use_msg_id = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '[%linter%] %code: %%s [%severity%]'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '[%linter%] %code: %%s [%severity%]'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) flake8
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''flake8'' --version']

<<<OUTPUT STARTS>>>
3.7.9 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.7.7 on Linux
<<<OUTPUT ENDS>>>

(executable check - failure) mypy
(executable check - success) pylint
(finished - exit code 16) ['/usr/bin/zsh', '-c', 'cd ''/home/AnnaMaria'' && ''pylint''  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/home/AnnaMaria/errors.py''']

<<<OUTPUT STARTS>>>
************* Module errors
errors.py:1:0: C0114 (missing-module-docstring) Missing module docstring
errors.py:1:0: C0102 (blacklisted-name) Black listed name "foo"
errors.py:1:0: C0116 (missing-function-docstring) Missing function or method docstring

------------------------------------------------------------------
Your code has been rated at 4.00/10 (previous run: 4.00/10, +0.00)

<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/usr/bin/zsh', '-c', 'cd ''/home/AnnaMaria'' && ''flake8'' --format=default --stdin-display-name ''/home/AnnaMaria/errors.py'' - < ''/tmp/v5ubMyp/1/errors.py''']

<<<OUTPUT STARTS>>>
/home/AnnaMaria/errors.py:6:1: E303 too many blank lines (3)
<<<OUTPUT ENDS>>>

**Comment by w0rp** [comment]
This is the correct behaviour, and it's not possible to do any better. ALE prefers to show errors over warnings. I personally never use `pylint`, and only use `flake8`, as barely anything `pylint` says actually matters, and it's too slow.
