### ISSUE TITLE
Default Fixer(s)?

### ISSUE THREAD

**Issue by lanespade** [dense-analysis/ale#3174]
I love the concept of ALE! ALL linters are enabled by default (that don't conflict with each other), but ALE doesn't seem to have a similar concept for fixers?

ALEFixSuggest provides 'fixJson', 'jq', and 'prettier' as suggestions for my `package.json`, ['eslint', 'fecs', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo'] for a JS file (not sure why prettier isn't in the list), and I'm sure other filetypes have multiple choices for fixers.

I know that users can specify fixers per file type via...

`let g:ale_fixers.json = ['prettier']`

...but is there any reason why there cannot be defaults per filetype that choose one or more fixer(s) in an opinionated fashion that can be enabled by an option and overridden by users as done today?

It would be REALLY cool if ALE could detect that prettier, for example, is installed in the project directory (or globally) and choose that as the default fixer for JSON, for example, or if the user has fixJson installed instead, use that (with tie-breaking logic as well, or if both can be run together...).

I like convention over configuration; if there's a way to do this today, I would love to learn how to do it!

**Comment by w0rp** [comment]
No default fixers are used so ALE doesn't modify any of your files by default. The policy is to never modify something unless you tell it to.

If you want to share configuration files across projects, there are some Vim plugins that let you load shared configuration files. I'd look for any plugin that loads local configuration files with `:sandbox`. I found one that does here: https://github.com/embear/vim-localvimrc
