### ISSUE TITLE
Show errors from entire project in statusline/lint entire project on buffer saved

### ISSUE THREAD

**Issue by pianocomposer321** [dense-analysis/ale#3175]
Is there a way to make ale lint entire project, even files that have not been opened in the current [neo]vim session yet? For example, I open src/main.cpp and I have an error in src/Class.cpp. Can I make the error show in statusline (via lightline-ale) and in the quickfix window (with g:ale_set_quickfix = 1)?

**Comment by hsanson** [comment]
ALE reports whatever it reads from the underlying linters output and even if the linter returns errors for multiple files in a project, ALE will only show those that correspond to the currently open buffer.

**Comment by pianocomposer321** [comment]
Is there a way I can change a setting to make it show for all the files? (similar to vscode's behavior).

**Comment by Mimerme** [comment]
Also interested. Wondering if you've found a solution

**Comment by pianocomposer321** [comment]
@Mimerme nope, just been relying a little less on linting. It still would be nice, but I can live without it.

**Comment by hsanson** [comment]
Duplicates: #3524 #844 #653.  ALE already supports this as long as the underlying linter supports it.
