### ISSUE TITLE
new git release tag

### ISSUE THREAD

**Issue by anthraxx** [dense-analysis/ale#3176]
Hey, thanks for the great work. The last release has been quite a while and there are 120 commits for which some of them would really be awesome to see being included in a new release.
Any schedule to tag a new one?

**Comment by RyanSquared** [comment]
I checked the draft changelog and it doesn't look like there's any breaking changes if you just want to use what's available on master.

**Comment by w0rp** [comment]
I'll create another one when I look at ALE again. It has been a while.

**Comment by anthraxx** [comment]
thanks for the feedback, but I'm mostly also interested in upgrading our distro package of vim-ale and we don't pin to master branches :cat:

**Comment by w0rp** [comment]
Thank you and others for building those packages.

I haven't done much work on ALE recently. I thought that life under lockdown would make me want to work on things more, but I think it's actually had the opposite effect. It's like living life in a giant cube of Jell-O for a while. I will eventually merge some more pull requests and create a release version. I might just create another version before merging a lot of things, in case they introduce more issues.

**Comment by ejiek** [comment]
Is it possible to tag/release current master?

ps. Hang on tight, Jell-O won't stay with us forever!

**Comment by w0rp** [comment]
I've released version v2.7.0 now.
