### ISSUE TITLE
Use `<C-X><C-O><C-P>` instead of `<C-X><C-O>`

### ISSUE THREAD

**Issue by matsuhav** [dense-analysis/ale#3205]
Currently, ALE needs `completeopt+=noselect,noinsert` in users' .vimrc.

If completeopt is default value, first completion is selected. Type `<C-P><C-N>` to insert first one.
If completeopt is dafault value and `omnifunc=ale#completion#OmniFunc`, first completion is selected and inserted.

I want to select and insert first completion with `<C-P>`, `<C-X><C-L>` and `<C-X><C-O>` when I manually typed.
And I don't want to select first completion provided by ALE.
```
inoremap <silent> <Plug>(ale_show_completion_menu) <C-x><C-o><C-p>
```
solves this problem and looks like it has no degradation whatever `completeopt` is.

I've tested with this minimal .vimrc. with installed only latest ALE in .vim
```
filetype plugin indent on
syntax enable
set completeopt=menu,preview
" set completeopt=menu,menuone,preview,noselect,noinsert
let g:ale_linters = {'python': ['pyls']}
let g:ale_completion_enabled = 1
" set omnifunc=ale#completion#OmniFunc
```
and typed `vim test.py`
```
x = "foo"
x.
```

**Comment by w0rp** [comment]
This is genius. :) I have done this now.

**Comment by matsuhav** [comment]
Thank you for implementing and this great plugin!
