### ISSUE TITLE
Solargraph doesn't show suggestions for installed gems

### ISSUE THREAD

**Issue by sarna** [dense-analysis/ale#3218]
## Information

**VIM version**
NVIM v0.4.3
Build type: Release

**Operating System** 
Ubuntu 20.04
## What went wrong
Completion via Solargraph works only for standard library. For installed gems, I don't get any completion suggestions.

It's not an issue with Solargraph - completion works in VSCode for the very same file, without changing anything.
It's not an issue with Deoplete either, as it completes everything else just fine.

I had this working with this setup before, but I don't know what I should change to make it work. I searched through both open and closed issues for the same problem before reporting a bug here, didn't find anything useful.

You could say it's about configuring ALE, but to me it not working out-of-the-box like in other editors seems like a bug.

## Reproducing the bug

1. Install `vim-plug`, put this in `~/.config/nvim/init.vim`, run `:PlugInstall`.
```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'dense-analysis/ale'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'ervandew/supertab'
call plug#end()

set encoding=utf-8

syntax enable

let g:ale_linters = {
\ 'ruby': ['debride', 'reek', 'ruby', 'solargraph', 'sorbet', 'standardrb']
\}

let g:ale_fixers = {
\ '*': ['remove_trailing_lines', 'trim_whitespace'],
\ 'ruby': ['standardrb']
\}

let g:ale_fix_on_save = 1

let g:deoplete#enable_at_startup = 1
call deoplete#custom#option('sources', {
\ '_': [],
\ 'ruby': ['buffer', 'file', 'ale']
\})

let g:SuperTabDefaultCompletionType = "<c-n>"
```
2. Make a `test` directory with a `Gemfile` in it:
```
source "https://rubygems.org"
 
gem "solargraph"
gem "standardrb"

gem "http"
```
3. Run `bundle install` and `yard gems`.
4. Create a `test.rb` file
```
require "http"
```
5. Type `Hash.` - a nice completion thingy appears, you can browse the methods.
6. Type `HTTP` - you'll get a pop-up saying it's a module. So far so good. Add a dot - nothing happens, right? Hit tab - the only completions available are "require", "http" and "HTTP". I'd like the completion to work properly.

### :ALEInfo

 ```
 Current Filetype: ruby
Available Linters: ['brakeman', 'debride', 'rails_best_practices', 'reek', 'rubocop', 'ruby', 'solargraph', 'sorbet', 'standardrb']
   Linter Aliases:
'sorbet' -> ['srb']
  Enabled Linters: ['solargraph']
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'rubocop' - Fix ruby files with rubocop --auto-correct.
  'rufo' - Fix ruby files with rufo
  'sorbet' - Fix ruby files with srb tc --autocorrect.
  'standardrb' - Fix ruby files with standardrb --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_ruby_rails_best_practices_executable = 'rails_best_practices'
let g:ale_ruby_rails_best_practices_options = ''
let g:ale_ruby_solargraph_executable = 'solargraph'
let g:ale_ruby_solargraph_options = {}
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'*': ['remove_trailing_lines', 'trim_whitespace'], 'ruby': ['standardrb']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'ruby': ['solargraph']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = v:null
let g:ale_list_window_size = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_sign_highlight_linenrs = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) solargraph
(started) ['/bin/bash', '-c', '''solargraph'' stdio']
```

**Comment by hsanson** [comment]
Seems to work fine. Make sure to follow solargraph documentation, create a config file, and generate yarn documentation of gems:

 - Solargraph troubleshooting:  https://solargraph.org/guides/troubleshooting    <-- Read carefully
 - Solargraph Yard documentation: https://solargraph.org/guides/yard               <-- Important!
 - Solargraph configuration:  https://solargraph.org/guides/configuration            <-- May help with special project structures
 - Solargraph workspace scan:  https://solargraph.org/guides/scanning-workspaces  

If things work after reading the above please close this issue.

**Comment by sarna** [comment]
I read what you linked, applied the recommendations - nothing changed. I'm closing the issue though, since I don't want to spend any more time on this - and I don't want to waste yours :) It's probably a configuration quirk anyway. I'm going to use a different tool for now, thanks for the assistance.
