### ISSUE TITLE
Why is ALEGoToDefinitionInVSplit deprecated? How should I implement this behaviour in the future?

### ISSUE THREAD

**Issue by horttanainen** [dense-analysis/ale#3221]
I get the following error message:
```
:ALEGoToDefinitionInVSplit is deprecated. Use `let g:ale_ignore_2_7_warnings = 1` to disable
 this message.
```
Improvement idea:
Instruct user how to implement this behaviour in the future instead of supressing warnings.

**Comment by w0rp** [comment]
You can use `:ALEGoToDefinition -vsplit` instead. See the release notes here: https://github.com/dense-analysis/ale/releases/tag/v2.7.0
