### ISSUE TITLE
Add support for astyle

### ISSUE THREAD

**Issue by cjappl** [dense-analysis/ale#3228]
**Name:** astyle 
**URL:** http://astyle.sourceforge.net/

Astyle is a code format fixer for c and c++. It is run in the command line using:

`astyle` 

It also respects project based config files using 

`astyle --project`

I attempted to implement this myself but unfortunately my vimscript skills are very lacking. Here is what could maybe be the bones of an `autoload/ale/fixers/astyle.vim`

```
" Author:
" Description:

call ale#Set('c_astyle_executable', 'astyle')
call ale#Set('c_astyle_options', '')

function! ale#fixers#astyle#Fix(buffer)
    let l:executable = ale#Var(a:buffer, 'c_astyle_executable')
    let l:options = ale#Var(a:buffer, 'c_astyle_options')

    return {
    \   'command': ale#Escape(l:executable)
    \       . ' --project '
    \       . (empty(l:options) ? '' : ' ' . l:options)
    \}
endfunction
```

**Comment by skorokithakis** [comment]
This is being worked on in #3231.

**Comment by hsanson** [comment]
This is already done for C/C++ thanks to @jhlink efforts.
