### ISSUE TITLE
Line breaks and colors in echo messages

### ISSUE THREAD

**Issue by fedorpashin** [dense-analysis/ale#3242]
Some linters (e.g. _cabal_ghc_ for Haskell) use line breaks and colors inside their messages, so they look like this:
<img width="663" alt="" src="https://user-images.githubusercontent.com/19939537/88168700-74940200-cc23-11ea-8739-d0345a19e91e.png">
But in the location list it looks much worse:
<img width="764" alt="" src="https://user-images.githubusercontent.com/19939537/88169079-1a477100-cc24-11ea-8d17-17fd9d794d29.png">
Is there any possibility to do something about it?

**Comment by w0rp** [comment]
Unfortunately, due to limitations in Vim, this cannot be fixed. You can view messages over several lines with the `:ALEDetail` command in a preview window, when you cursor rests on the line with the problem.
