### ISSUE TITLE
designate clang-format version

### ISSUE THREAD

**Issue by laoshaw** [dense-analysis/ale#3244]
I have multiple clang-format installed on ubuntu and the default is not the newest, is there a way I can designate clang-format-9 and such just like the way  I designate newer g++, gcc , clang++ from a different path with different name(e.g. g++-9) under ALE?

**Comment by maujim** [comment]
You can set `g:ale_c_clangformat_executable` in your vimrc or set `b:ale_c_clangformat_executable` if you need buffer specific versions. This variable is used for both C and C++ files.

**Comment by laoshaw** [comment]
Thanks.
