### ISSUE TITLE
Autocopletion does not get shown when enabled

### ISSUE THREAD

**Issue by prezmyl** [dense-analysis/ale#3248]
## Information

**VIM version**

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun  5 2020 00:00:00)
Included patches: 1-905

Operating System: FEDORA31 Linux desktop-qdpsqn6 5.6.19-200.fc31.x86_64 #1 SMP Wed Jun 17 16:54:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

## What went wrong
 the autocompletion popup does not get shown as typing, could not figure out why. I read throught similar bugs tried some stuff that I was able to understand, but none of it seems to be working
-ALE Plugin updated
-let g:ale_completion_enabled = 1
-linters avilable and enabled (tried diffrent ones: clangd, clange-tide, gcc)
-
 
## Reproducing the bug
1.I set "let g:ale_completion_enabled = 1" in .vimrc
2. nothing happens when typing

### :ALEInfo
Current Filetype: c
Available Linters: ['ccls', 'clang', 'clangd', 'clangtidy', 'cppcheck', 'cquery', 'flawfinder', 'gcc']
  Enabled Linters: ['clangtidy', 'gcc']
 Suggested Fixers: 
  'clang-format' - Fix C/C++ and cuda files with clang-format.
  'clangtidy' - Fix C/C++ and ObjectiveC files with clang-tidy.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'uncrustify' - Fix C, C++, C#, ObjectiveC, ObjectiveC++, D, Java, Pawn, and VALA files with uncrustify.
 Linter Variables:

let g:ale_c_build_dir = ''
let g:ale_c_build_dir_names = ['build', 'bin']
let g:ale_c_clangtidy_checks = []
let g:ale_c_clangtidy_executable = 'clang-tidy'
let g:ale_c_clangtidy_extra_options = ''
let g:ale_c_clangtidy_options = '-std=c99 -Wall -Wextra -pedantic'
let g:ale_c_gcc_executable = 'gcc'
let g:ale_c_gcc_options = '-std=c99 -Wall -Wextra -pedantic'
let g:ale_c_parse_compile_commands = 0
let g:ale_c_parse_makefile = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'c': ['gcc', 'clangtidy', 'clang-format']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) clang-tidy
(executable check - success) gcc
(started) ['/bin/bash', '-c', '''gcc'' -S -x c -o /dev/null -iquote ''/home/xpolas/coding/cviceni3'' -std=c99 -Wall -Wextra -pedantic - < ''/tmp/vZqKmQR/1/main.c''']
(executable check - failure) clang-tidy
(finished - exit code 0) ['/bin/bash', '-c', '''gcc'' -S -x c -o /dev/null -iquote ''/home/xpolas/coding/cviceni3'' -std=c99 -Wall -Wextra -pedantic - < ''/tmp/vZqKmQR/2/main.c''']

<<<OUTPUT STARTS>>>
<stdin>: In function ‘main’:
<stdin>:14:11: warning: format ‘%d’ expects argument of type ‘int *’, but argument 2 has type ‘int’ [-Wformat=]
<stdin>:10:9: warning: unused variable ‘array’ [-Wunused-variable]
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/bash', '-c', '''gcc'' -S -x c -o /dev/null -iquote ''/home/xpolas/coding/cviceni3'' -std=c99 -Wall -Wextra -pedantic - < ''/tmp/vZqKmQR/3/main.c''']

<<<OUTPUT STARTS>>>
<stdin>: In function ‘main’:
<stdin>:14:11: warning: format ‘%d’ expects argument of type ‘int *’, but argument 2 has type ‘int’ [-Wformat=]
<stdin>:10:9: warning: unused variable ‘array’ [-Wunused-variable]
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/bin/bash', '-c', '''gcc'' -S -x c -o /dev/null -iquote ''/home/xpolas/coding/cviceni3'' -std=c99 -Wall -Wextra -pedantic - < ''/tmp/vZqKmQR/4/main.c''']

<<<OUTPUT STARTS>>>
<stdin>: In function ‘main’:
<stdin>:14:11: warning: format ‘%d’ expects argument of type ‘int *’, but argument 2 has type ‘int’ [-Wformat=]
<stdin>:19:5: error: unknown type name ‘prin’
<stdin>:21:5: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘}’ token
<stdin>:23:1: error: expected declaration or statement at end of input
<stdin>:10:9: warning: unused variable ‘array’ [-Wunused-variable]
<<<OUTPUT ENDS>>>

my **vimrc**
" Sample config for pb071 students, available at fi.muni.cz/pb071
" ===============================================================
" Requires VIM-8.0 to enable linting, on aisa run:
"   $ module add vim-8.0
" However, the linting will fail silently, if version is older.
"
" Comes with plugin manager Plug: we added 2 colorschemes
" and linting plugin ALE, which uses clang-tidy and gcc
" to highlight some syntax errors.
"
" Install Plug first in bash:
"   $ curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" Then run vim and install the plugins using command in normal mode:
"   :PlugInstall
"
" Most of the settings come from vimconfig.com. 
" We added few handy key mappings:
"
" Ctrl+Up/Down	    Move line or a block of selected lines  
" Ctrl+j/k	
" <leader>pp	    Toggle paste mode on and off
" <leader><cr>	    Disable search highlight
"
" <cr> is carriage return, "Enter"
" <leader> is backspace, "\", complete the combination in 1 second

set nocompatible
set encoding=utf-8

"""""
""""" Plugin manager Plug from https://github.com/junegunn/vim-plug
"""""
call plug#begin('~/.vim/plugged')
" Plug 'vim-airline/vim-airline' " status bar mod
    Plug 'tomasiser/vim-code-dark'  " colorscheme codedark
    Plug 'romainl/Apprentice'	    " colorscheme apprentice
    Plug 'w0rp/ale'
    Plug 'romainl/vim-cool'
call plug#end()

" Setup linting for c99
let g:ale_completion_enabled = 1
let g:ale_linters = {'c': ['gcc', 'clangtidy', 'clang-format']}
let g:ale_c_gcc_executable = 'gcc'
let g:ale_c_gcc_options = '-std=c99 -Wall -Wextra -pedantic'
let g:ale_c_clang_executable = 'gcc'
let g:ale_c_clang_options = '-std=c99 -Wall -Wextra -pedantic'
let g:ale_c_clangtidy_executable = 'clang-tidy'
let g:ale_c_clangtidy_options = '-std=c99 -Wall -Wextra -pedantic'

"""""
""""" Colors
"""""
syntax on

" Color schemes belong to ~/.vim/colors
" Find yours at https://vimcolors.com
colorscheme codedark

" If using plugin vim-airline
" let g:airline_theme = 'codedark'

if &term =~ '256color'
	" disable Background Color Erase (BCE) so that color schemes
	" render properly when inside 256-color tmux and GNU screen.
	" see also http://snk.tuxfamily.org/log/vim-256color-bce.html
	set t_ut=
endif 

" If you happen to still have a problem on some terminal, uncomment:
" set t_Co=256
" set t_ut=

" Color 81. character in line to visualize long lines
highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn', '\%81v', 100)
"""""
""""" General
"""""
set number		" Show line numbers
set linebreak		" Break lines at word (requires Wrap lines)
set showbreak=+++ 	" Wrap-broken line prefix
set textwidth=100	" Line wrap (number of cols)
set showmatch		" Highlight matching brace
set showcmd	    	" Show last command on right
set cursorline 		" Highlight current line
 
set hlsearch		" Highlight all search results
set smartcase		" Enable smart-case search
set ignorecase		" Always case-insensitive
set incsearch		" Searches for strings incrementally
 
set autoindent		" Auto-indent new lines
set cindent		" Use 'C' style program indenting
set shiftwidth=4	" Number of auto-indent spaces
set smartindent		" Enable smart-indent
set smarttab		" Enable smart-tabs
set softtabstop=4 noexpandtab	" Number of spaces per Tab
set wrap 		" Wrap lines
 
"""""
""""" Advanced
"""""
set ruler			" Show row and column ruler information
set undolevels=1000		" Number of undo levels
set backspace=indent,eol,start	" Backspace behaviour

"""""
""""" Key mapping
"""""
" Move lines using Ctrl+Up/Down in normal, insert and visual modes
nnoremap <C-Up> :m-2<CR>
nnoremap <C-Down> :m+<CR>
inoremap <C-Up> <Esc>:m-2<CR>
inoremap <C-Down> <Esc>:m+<CR>
vnoremap <C-Up> :m '<-2<CR>gv=gv
vnoremap <C-Down> :m '>+1<CR>gv=gv
" or Ctrl+j/k
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
inoremap <C-j> <ESC>:m .+1<CR>==gi
inoremap <C-k> <ESC>:m .-2<CR>==gi
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv

" Toggle paste mode on and off
" \ + pp
map <leader>pp :setlocal paste!<cr>

" Disable search highlight when <leader><cr> is pressed
map <silent> <leader><cr> :noh<cr>

**Comment by w0rp** [comment]
> (executable check - failure) clang-tidy

It's because there's that will provide completion that's installed on your system, or at least where ALE can find it. Try installing `clang-tidy`, or setting the executable path so ALE can find it with `ale_c_clangtidy_executable`.

I personally recommend `clangd` as my C language server of choice. It generally doesn't require any configuration, and tends to just work, so long as you get the right version installed. I have a few lines in my `vimrc` file that try to look for different versions and use them where available.

```vim
if executable('clangd-6.0')
    let g:ale_c_clangd_executable = 'clangd-6.0'
    let g:ale_cpp_clangd_executable = 'clangd-6.0'
endif

if executable('clangd-8')
    let g:ale_c_clangd_executable = 'clangd-8'
    let g:ale_cpp_clangd_executable = 'clangd-8'
endif
```
