### ISSUE TITLE
Make ALE find automatically the config file for specific linters/fixers?

### ISSUE THREAD

**Issue by a666** [dense-analysis/ale#3250]
This issue is mostly related to some linter/fixers that do not autoresolve their config files (php_cs_fixer in this case).

My first idea was to use a shell function for it. For reference this is it:

```bash
find-config () {
        if [ -f "$1" ]
        then
                printf '%s\n' "${PWD%/}/$1"
        elif [ "$PWD" = / ]
        then
                false
        else
                (
                        cd .. && find-config "$1"
                )
        fi
}
```

Unfortunately since ALE encloses in single quotes, the following gets interpreted as a variable (like $HOME):
```
let g:ale_php_cs_fixer_options = '--config=$(find-config .php_cs.dist)'
```
which results in: 
```
(finished - exit code 16) ['/usr/bin/zsh', '-c', '''/home/thething/project/vendor/bin/php-cs-fixer'' --config=$(find-config .php_cs.dist) fix ''/tmp/nvimzrYFLk/7/thing.php''']
```
(exit code 16 is config error in php-cs-fixer)

This issue is specially vexing since I got `g:ale_fix_on_save` enabled permanently and when doing rapid fire file editing in multiple projects sometimes the files get formatted/fixed incorrectly.

Has anybody found a workaround for this that wouldn't involve changing/adding code in ALE?
Is this feature even desirable?

**Comment by hsanson** [comment]
@a666 what you are proposing is not supported by ALE and I don't think it will ever be. The only possible solution would be to modify the [php_cs_fixer](https://github.com/dense-analysis/ale/blob/master/autoload/ale/fixers/php_cs_fixer.vim) itself to auto-detect the configuration file. This PR https://github.com/dense-analysis/ale/pull/3231#issuecomment-664712084 is an example and discussion on how to do this in case you or anyone that uses this fixer is willing to take the task of modifying the fixer and adding tests.

**Comment by a666** [comment]
I'll check it, thanks.

**Comment by w0rp** [comment]
There's another issue open for `phpcs` now.

One thing you can do to set whatever options you write is to write logic into your `ftplugin` files to change your settings. For example, I did this recently when I was testing Docker support.

```vim
if expand('%:p') =~# 'test-pylint'
    let b:ale_linters = ['pylint']
    let b:ale_python_pylint_use_global = 1
    let b:ale_python_pylint_executable = '/home/w0rp/git/test-pylint/pylint.sh'
    let b:ale_filename_mappings = {'pylint': [['/home/w0rp/git/test-pylint', '/data']]}
endif
```

You can write whatever code you want in Vim script, in your ftplugin files.
