### ISSUE TITLE
Astyle Cannot Find Project Options file when placed with Source Files

### ISSUE THREAD

**Issue by jhlink** [dense-analysis/ale#3256]
## Information

**VIM version**

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 10 2020 16:42:10)                                                    
macOS version                                                                                                         

Operating System: Catalina v10.15.5

## What went wrong
ALE failed to find the project options file located in the same directory as the source c/cpp file.

## Reproducing the bug

Given the following directory structure, 
- rootDir
  - .astylerc
  - src

Launching vim and executing ALEFix in the **root directory** causes the following error. 

### :ALEInfo

```
$ bash -c "astyle --project=.astylerc --stdin= < ''./processorblocks/delayblock/test/test_DelayBlockBasics.cpp"                                                                                                                                                         
Cannot open project option file .astylerc
Artistic Style has terminated
```

When launching vim from the **src directory**, astyle loads the .astylerc file located in `src`'s parent directory.

Credit to @cjappl in PR #3231 for reporting the error. 

## Actions
Will follow up with PR fix.

**Comment by hsanson** [comment]
Fixed in #3257
