### ISSUE TITLE
Dynamically ignore warnings/error in a buffer

### ISSUE THREAD

**Issue by AlijahArcher** [dense-analysis/ale#3260]
Is there a way/can there be a feature that allows the user to ignore one specific error or warning in a buffer?  So, for example, pylint is making an incorrect assumption about one line in a script, and this is quite distracting.  Can there be a `:set ignore-linters` so that when the linters mess up, I can ignore the linting/ALE-highlighting for that one line?  I don't want to disable the entire "type" of error/warning message globally.

**Comment by w0rp** [comment]
You can add comments in your code like this, for example.

```
# pylint: disable=C0321
```

ALE will never let you disable particular errors or warnings. That should be something done in code or a shared configuration file.
