### ISSUE TITLE
Add an :ALEImport command

### ISSUE THREAD

**Issue by w0rp** [dense-analysis/ale#3268]
Because ALE supports generating import lines from completion results, it wouldn't be too difficult to leverage that code to add a command which looks for the first completion result that has some other text changes associated with it adds the import lines.

A new `:ALEImport` command can try to find an import for the symbol at the cursor and insert the first one it finds. As part of this, I would also like to add an `ALECompleteDone` event that fires whenever ALE finishes performing some kind of completion, including for this command. We should set a `g:ale_import_added` variable to `1` or `0` before the event fires so you can check if imports were added or not. I'll personally be using the event for running `:ALEFix` after importing code, plus my own custom code.

**Comment by w0rp** [comment]
I have implemented `:ALEImport` now, and it's in the documentation. #3333 is tracking a post completion hook.

**Comment by massimiliano-della-rovere** [comment]
Pyright is installed and works if executed manually; python 3.11.1.

python code: 
`print(collections.defaultdict())
decimal.Decimal()`

ALEImport does not import decimal or collections.
-------------
`$ pyright

No configuration file found.
No pyproject.toml file found.
stubPath /home/mader/Documenti/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 1 source file
pyright 1.1.291
/home/mader/Documenti/test.py
  /home/mader/Documenti/test.py:1:7 - error: "collections" is not defined (reportUndefinedVariable)
  /home/mader/Documenti/test.py:2:1 - error: "decimal" is not defined (reportUndefinedVariable)
2 errors, 0 warnings, 0 informations 
Completed in 0.864sec`
-------------
 Current Filetype: python
Available Linters: ['bandit', 'cspell', 'flake8', 'flakehell', 'jedils', 'mypy', 'prospector', 'pycln', 'pycodest
yle', 'pydocstyle', 'pyflakes', 'pylama', 'pylint', 'pylsp', 'pyre', 'pyright', 'refurb', 'ruff', 'unimport', 'vu
lture']
  Enabled Linters: ['bandit', 'jedils', 'pycln', 'pylama', 'pylsp', 'pyright']
  Ignored Linters: []
 Suggested Fixers:
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autoflake' - Fix flake issues with autoflake.
  'autoimport' - Fix import issues with autoimport.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'pycln' - remove unused python import statements
  'pyflyby' - Tidy Python imports with pyflyby.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'reorder-python-imports' - Sort Python imports with reorder-python-imports.
  'ruff' - A python linter/fixer for Python written in Rust
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:
let g:ale_python_auto_pipenv = 0
let g:ale_python_auto_poetry = 0
let g:ale_python_bandit_auto_pipenv = 0
let g:ale_python_bandit_auto_poetry = 0
let g:ale_python_bandit_executable = 'bandit'
let g:ale_python_bandit_options = ''
let g:ale_python_bandit_use_config = 1
let g:ale_python_bandit_use_global = 0
let g:ale_python_jedils_auto_pipenv = 0
let g:ale_python_jedils_executable = 'jedi-language-server'
let g:ale_python_jedils_use_global = 0
let g:ale_python_pycln_auto_pipenv = 0
let g:ale_python_pycln_auto_poetry = 0
let g:ale_python_pycln_change_directory = 1
let g:ale_python_pycln_config_file = ''
let g:ale_python_pycln_executable = 'pycln'
let g:ale_python_pycln_options = ''
let g:ale_python_pycln_use_global = 0
let g:ale_python_pylama_auto_pipenv = 0
let g:ale_python_pylama_auto_poetry = 0
let g:ale_python_pylama_change_directory = 1
let g:ale_python_pylama_executable = 'pylama'
let g:ale_python_pylama_options = ''
let g:ale_python_pylama_use_global = 0
let g:ale_python_pylsp_auto_pipenv = 0
let g:ale_python_pylsp_auto_poetry = 0
let g:ale_python_pylsp_config = {}
let g:ale_python_pylsp_executable = 'pylsp'
let g:ale_python_pylsp_options = ''
let g:ale_python_pylsp_use_global = 0
let g:ale_python_pyright_config = {}
let g:ale_python_pyright_executable = 'pyright-langserver'
 Global Variables:
let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'vim': ['remove_trailing_lines', 'trim_whitespace'], 'sh': ['remove_trailing_lines', 'shfmt',
 'trim_whitespace'], 'javascript': ['prettier', 'remove_trailing_lines', 'trim_whitespace', 'xo'], 'python': ['ad
d_blank_lines_for_python_control_statements', 'black', 'isort', 'reorder-python-imports', 'remove_trailing_lines'
, 'ruff', 'trim_whitespace', 'yapf']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'sh': ['bashate', 'shell', 'shellcheck'], 'dockerfile': ['dockerfile_linter'], 'javascript':
 ['importjs', 'prettier', 'xo'], 'python': ['bandit', 'jedils', 'pycln', 'pylama', 'pylsp', 'pyright']}
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_root = {}
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = ''
let g:ale_sign_info = ''
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = ''
let g:ale_sign_style_warning = ''
let g:ale_sign_warning = ''
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_neovim_diagnostics_api = 0
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 'all'
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - success) bandit
(finished - exit code 0) ['/bin/bash', '-c', '''bandit'' --format custom --msg-template "{line}:{test_id}:{severi
ty}:{msg}"  - < ''/tmp/vyrgM3T/3/test.py''']
<<<NO OUTPUT RETURNED>>>
(executable check - success) jedi-language-server
(executable check - success) pycln
(finished - exit code 0) ['/bin/bash', '-c', 'cd ''/home/mader/Documenti'' && ''pycln'' --version']
<<<OUTPUT STARTS>>>
pycln, version 2.1.3
<<<OUTPUT ENDS>>>
(executable check - success) pylama
(finished - exit code 0) ['/bin/bash', '-c', 'cd ''/home/mader/Documenti'' && ''pylama'' --version']
<<<OUTPUT STARTS>>>
pylama 8.4.1
<<<OUTPUT ENDS>>>
(executable check - success) pylsp
(executable check - success) pyright-langserver
(finished - exit code 0) ['/bin/bash', '-c', 'cd ''/home/mader/Documenti'' && ''pycln'' --check - < ''/tmp/vyrgM3
T/6/test.py''']
<<<OUTPUT STARTS>>>
print(collections.defaultdict())
decimal.Decimal()
Looks good! ✨ 🍰 ✨
1 file would be left unchanged.
<<<OUTPUT ENDS>>>
(started) ['/bin/bash', '-c', 'cd ''/home/mader/Documenti'' && ''pyright-langserver'' --stdio']
(started) ['/bin/bash', '-c', '''jedi-language-server''']
(started) ['/bin/bash', '-c', 'cd ''/home/mader/Documenti'' && ''pylsp''']
(finished - exit code 1) ['/bin/bash', '-c', 'cd ''/home/mader/Documenti'' && ''pylama'' --format json ''/home/ma
der/Documenti/test.py''']
<<<OUTPUT STARTS>>>
[{"source": "pyflakes", "col": 7, "lnum": 1, "etype": "E", "message": "undefined name 'collections'", "filename":
 "test.py", "number": "E0602"}, {"source": "pyflakes", "col": 1, "lnum": 2, "etype": "E", "message": "undefined n
ame 'decimal'", "filename": "test.py", "number": "E0602"}]
<<<OUTPUT ENDS>>>
