### ISSUE TITLE
Add support for Rome

### ISSUE THREAD

**Issue by wlabranche** [dense-analysis/ale#3280]
**Name:** Rome frontend
**URL:** https://romefrontend.dev/

Rome is a linter, compiler, bundler, and more for JavaScript, TypeScript, JSON, HTML, Markdown, and CSS. At the current beta release only the linter is availble.

**Comment by Ashvith10** [comment]
Commenting to bump the issue - would love to see Rome working on Vim via ALE.

**Comment by 4k1k0** [comment]
Hope this gets implemented! ❤️

**Comment by redbmk** [comment]
@wlabranche Since rome was replaced with biome, would you be ok closing this in favor of #4674?
