### ISSUE TITLE
(:helptags) E154: Duplicate tag

### ISSUE THREAD

**Issue by ProjectAlice** [dense-analysis/ale#3286]
E154: Duplicate tag "**b:ale_ruby_rubocop_options**" in file **~\.vim\bundle\ale\doc\/ale-ruby.txt**
E154: Duplicate tag "**g:ale_ruby_rubocop_options**" in file **~\.vim\bundle\ale\doc\/ale-ruby.txt**

**Comment by w0rp** [comment]
I've pushed a fix for that now. Thanks for letting me know.
