### ISSUE TITLE
Using ale only as a fixer

### ISSUE THREAD

**Issue by pyrr** [dense-analysis/ale#3290]
Hello, I want to use ale only for it's fixing functionality and disable anything else it offers.
Do these settings suffice ?
```
let g:ale_disable_lsp = 0
let g:ale_fix_on_save = 1
let g:ale_linters_explicit = 1

```

**Comment by w0rp** [comment]
You want to use `g:ale_enabled = 0` too. `g:ale_enabled` controls ALE linting only.

**Comment by pyrr** [comment]
Thank you.
