### ISSUE TITLE
Incredibly obtrusive error message when the LSP server produces bad output

### ISSUE THREAD

**Issue by rrichardson** [dense-analysis/ale#3294]
## Information

**VIM version**

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug 10 2020 17:11:32)
Included patches: 1-1412

Operating System: 
Arch Linux

## What went wrong

I'm running `rust-analyzer` as an LSP and rustfmt as the fixer. When I operate on relatively complete code, and rust-analyzer is happy, there are no problems.. however.. when modules are missing (haven't been created yet) it outputs data that ALE appears to not expect. then a huge, red error message takes over my screen.. sometimes it stays.. other times it just flashes for a second or two. 

Here is the error: 

```
Error detected while processing function <SNR>133_VimOutputCallback[6]..<lambda>121[1]..ale#lsp#HandleMessage[15
]..ale#lsp#ReadMessageData:
line   36:
E491: json decode error at 'Content-Length: 1604^M^@^M^@{"jsonrpc":"2.0","id":14,"result":{"capabilities":{"call
HierarchyProvider":true,"codeActionProvider":true,"codeLensProvider":{"resolveProvider":true},"completionProvide
r":{"triggerCharacters":[":","."]},"definitionProvider":true,"documentFormattingProvider":true,"documentHighligh
tProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"=","moreTriggerCharacter":[".",">"]
},"documentSymbolProvider":true,"experimental":{"joinLines":true,"onEnter":true,"parentModule":true,"runnables":
{"kinds":["cargo"]},"ssr":true},"foldingRangeProvider":true,"hoverProvider":true,"implementationProvider":true,"
referencesProvider":true,"renameProvider":{"prepareProvider":true},"selectionRangeProvider":true,"semanticTokens
Provider":{"documentProvider":{"edits":true},"legend":{"tokenModifiers":["documentation","declaration","definiti
on","static","abstract","deprecated","readonly","constant","controlFlow","injected","mutable","unsafe","attribut
e"],"tokenTypes":["c
Error detected while processing function <SNR>133_VimOutputCallback[6]..<lambda>121[1]..ale#lsp#HandleMessage:
line   15:
E714: List required
```

## Reproducing the bug

1. Opened up an existing Rust project. 
2. Started modifying it, referencing files that don't exist. 
3. Presumably, rust-analyzer produced an error message instead of its usual JSON list. 

### :ALEInfo

```
 Current Filetype: rust
Available Linters: ['analyzer', 'cargo', 'rls', 'rustc']
  Enabled Linters: ['analyzer']
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'rustfmt' - Fix Rust files with Rustfmt.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_rust_analyzer_config = {}
let g:ale_rust_analyzer_executable = 'rust-analyzer'
let g:ale_rust_rustfmt_executable = 'rustfmt'
let g:ale_rust_rustfmt_options = ''
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'typescript': ['prettier', 'eslint'], 'typescriptreact': ['prettier', 'eslint'], 'yaml': ['prettier'], 'rust': ['rustfmt'], 'javascript': ['prettier'], 'css': ['prettier']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {'typescriptreact': 'typescript'}
let g:ale_linters = {'typescript': ['eslint', 'tsserver'], 'yaml': ['yamllint'], 'rust': ['analyzer'], 'javascript': ['eslint']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1

Command History:

(started) ['/usr/bin/zsh', '-c', '''rust-analyzer''']
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''rustfmt'' < ''/tmp/vblVchk/10/mod.rs''']
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''rustfmt'' < ''/tmp/vblVchk/14/mod.rs''']
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''rustfmt'' < ''/tmp/vblVchk/18/mod.rs''']
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''rustfmt'' < ''/tmp/vblVchk/22/mod.rs''']
```

**Comment by w0rp** [comment]
That will be difficult to fix. It's hard to tell, but it looks like the language server is sending data where the `Content-Length` doesn't match the size of the JSON text.

**Comment by rrichardson** [comment]
I am sure there is an issue on their side. I'll try to track it down.  Is there at least a way to squelch these errors in ALE? like maybe a 
```
let g:ale_set_i_really_really_dont_care_about_errors = 1
```

**Comment by w0rp** [comment]
There's no way to get rid of those errors other than to not use that language server altogether, or to stop using particular features that are triggering the errors. The error is that the JSON-RPC message data is either being read incorrectly by ALE, or the wrong data is being sent by the server. ALE works with tons of other servers, so I doubt ALE is the issue, unless there's some weird Unicode BS going on I don't know about. That shouldn't ever happen, but it is.

**Comment by w0rp** [comment]
Let me know which exact version of `rust-analyzer` you are using, any any other information you can provide, like project configuration, OS version, Rust version, etc. I might see if I can repeat the bug on my machine and come up with a way to handle garbage in JSON-RPC messages, or if there's some potential weird Unicode issue I don't know about, etc.

**Comment by w0rp** [comment]
Actually, there's something else you can do for me, which will make fixing this issue a lot easier.

Put `:call ch_logfile(expand('~/channel.log'), 'w')` in your vimrc file before ALE is loaded, run ALE with this language server on your project until you start seeing these errors, and then attach that log file. I will be able to see all of the messages sent by the server and work out where we can deal with the message data not being exactly right.

I wouldn't be surprised if the server is sending out incomplete message data, then later sending out more text that closes large JSON objects, etc.

**Comment by rrichardson** [comment]
I've added the config line.. here is my setup: 

```
active toolchain
----------------
stable-x86_64-unknown-linux-gnu (default)
rustc 1.45.2 (d3fb005a3 2020-07-31)
```

Rust analyzer was installed by rustup, and its "version" is 
```
➜ rust-analyzer --version
rust-analyzer 8a57afe
```

I'm trying to reproduce the error and everything is happy so far.. I fixed my code last night, so rust-analyzer isn't angry any more.. I'm about to do something more drastic.

**Comment by rrichardson** [comment]
Here's the log.. I think it may contain the problem messages. There are no incomplete messages from analyzer,  and I was unable to reproduce the exact problem.  After making the change to use channel.log,  instead of showing the red error message,  ale just permanently stopped updating until I closed and re-opened vim.   I was doing the same thing as I was doing previously to produce the error.. namely referencing modules and types that didn't exist yet. 

[channel.log](https://github.com/dense-analysis/ale/files/5085430/channel.log)

**Comment by w0rp** [comment]
I can't see anything wrong in that output. If you see the same errors again, try to use `ch_logfile()` again and capture the output when you have those errors. It's difficult to say what caused the error.

**Comment by rrichardson** [comment]
I managed to reproduce it.  I am pretty sure the offending messages start around 98. 

[channel.log](https://github.com/dense-analysis/ale/files/5087244/channel.log)

**Comment by w0rp** [comment]
Thank you. It will be difficult to determine what is wrong, but the answer will lie somewhere in that output. :+1:

**Comment by w0rp** [comment]
>  98.028363 RECV on 27(err): 'expected initialized notification, got Ok(Notification(Notification { method: "textDocument/didChange"

I think this is the issue. Somehow ALE isn't sending `initialized` to this server, probably because it's set up in such a way that it initializes more than once. I think the error with the message is happening because the channel is closing too early, somehow that's changing the string being read in Vim. That's my hunch.

**Comment by w0rp** [comment]
I have figured out what's going on from your log. Here's the gist.

1. The servers crashes because it doesn't handle negative numbers in input gracefully.
2. ALE doesn't handle a server crashing properly, so it doesn't send an `initialized` message when it starts it up again.

Here's what's happening in order.

1. Everything starts up like it should.
2. The server responses with `"hoverProvider":true`, meaning it is capable of handling hover messages.
3. ALE sends a hover message with `"position":{"character":-1,"line":1}`, which is a bug in of itself, but it should be a minor one.
4. This makes Rust freak out: ` 6.491682 RECV on 0(err): 'thread 'main' panicked at 'Invalid request ... Method: textDocument/hover ... error: invalid value: integer `-1`, expected u64'`
5. The server crashes.
6. ALE doesn't expect the server to crash, and doesn't start it up again properly.
7. Further things go wrong.

I'll push a fix that will fix the `-1` positions and handle servers crashing better.

**Comment by w0rp** [comment]
I've pushed a fix now, which I believe should fix your issues.

**Comment by rrichardson** [comment]
That looks like it did the trick.  Thanks for the fast turnaround!

**Comment by w0rp** [comment]
I opened an issue in the rust-analyzer repository, so they can handle invalid input in some way without the server crashing.
