### ISSUE TITLE
Add Python linter support for FlakeHell (flake8 wrapper)

### ISSUE THREAD

**Issue by bowmanjd** [dense-analysis/ale#3295]
**Name:** FlakeHell
**URL:** https://github.com/life4/flakehell

[FlakeHell] is a nice wrapper around Flake8. Even though it has a drop-in replacement script `flake8helled`, and I have it set in `g:ale_python_flake8_executable`, ALEInfo continues to show that `flake8` is being called, not `flake8helled`.

So, I would love to help with adding support for [FlakeHell] itself. It wraps flake8, but provides more output options and configuration options (It [supports `pyproject.toml`, for instance](https://dev.to/bowmanjd/using-flake8-and-pyproject-toml-with-flakehell-1cn1)). It even has a JSON output option, if that is helpful.

If this is worthwhile, I would love to help with a PR, but could use a few pointers: should it be modeled after flake8.vim, or is there another plugin that would be a better example, given that JSON output is an option.

Or, I welcome advice on what I might be doing wrong with `g:ale_python_flake8_executable`.

Thanks for any opportunities or advice!

[FlakeHell]: https://flakehell.readthedocs.io/

**Comment by w0rp** [comment]
For the `_executable` options, you need to use absolute paths to executables. For Python linters, you need to set the `_use_global` settings to `1` to use your `_executable` setting instead of some path found in virtualenv.

Adding a new linter definition for this other linter is a good idea. A good place to start would be copying the `flake8` linter, and then removing certain parts that aren't needed for the other linter.

**Comment by bowmanjd** [comment]
Thank you! `let g:ale_python_flake8_use_global = 1` certainly did the trick.

I will work on a PR for a flakehell.vim in my spare time. Thanks for the opportunity.

It would seem a shame to not use the JSON output of flakehell. Are there plugins I should look at for examples of reading JSON output? Or would you prefer I stay close to flake8.vim?

**Comment by w0rp** [comment]
Look for uses of `ale#util#FuzzyJSONDecode` in the codebase. That function tries to read JSON from output and silently fails if it can't parse JSON.

**Comment by lyz-code** [comment]
@bowmanjd thank you for your temporal solution, I can't manage to make flakehell respect the exclusion of rules written in `pyproject.toml` does that work for you?

```toml
...

[tool.flakehell.exceptions."tests/"]
flake8-docstrings = ["-D103"]
```

```vimrc
let g:ale_python_flake8_executable = "flake8helled"
let g:ale_python_flake8_use_global = 1
```

The `D103` error keeps on showing, even though `flakehell lint` and `flake8helled` don't show it

**Comment by a666** [comment]
@bowmanjd , @lyz-code, the flakehell linter has been merged.
Sorry for the spam.
