### ISSUE TITLE
[help needed] How to always use a specified virtualenv

### ISSUE THREAD

**Issue by subnut** [dense-analysis/ale#3296]
I install all my linters in my neovim virtualenv. How can I configure ALE to **always** use it?

**Comment by w0rp** [comment]
If you set up your virtualenv directory inside of your repositories, ALE can find it by searching for a few names you can configure with `g:ale_virtualenv_dir_names`. There are a few good defaults. See `:help g:ale_virtualenv_dir_names`. ALE also uses the `$VIRTUAL_ENV` environment variable, which you can easily set with this plugin: https://github.com/jmcantrell/vim-virtualenv

If you never want to run a globally installed version of a Python linter, you can set the `_executable` option for that linter to an empty string.
