### ISSUE TITLE
Features Removed for ALE v3.0.0

### ISSUE THREAD

**Issue by w0rp** [dense-analysis/ale#3298]
This issue lists the features removed in the most recent commit, for the ALE v3.0.0 release. I'm putting the information here now so people can find it easily and update their Vim scripts.

---

## Removed Features

Many previously deprecated features have been removed. Here is a list of the features removed, and what you should use instead.

| Removed | Replacement |
| ------- | ----------- |
| `:ALEGoToDefinitionInTab` | `:ALEGoToDefinition -tab` |
| `:ALEGoToDefinitionInSplit` | `:ALEGoToDefinition -split` |
| `:ALEGoToDefinitionInVSplit` | `:ALEGoToDefinition -vsplit` |
| `:ALEGoToTypeDefinitionInTab` | `:ALEGoToTypeDefinition -tab` |
| `:ALEGoToTypeDefinitionInSplit` | `:ALEGoToTypeDefinition -split` |
| `:ALEGoToTypeDefinitionInVSplit` | `:ALEGoToTypeDefinition -vsplit` |
| `ale#engine#ManageFile` | `ale#command#ManageFile` |
| `ale#engine#ManageDirectory` | `ale#command#ManageDirectory` |
| `ale#engine#CreateFile` | `ale#command#CreateFile` |
| `ale#engine#CreateDirectory` | `ale#command#CreateDirectory` |
| (linter) `command_chain` | `ale#command#Run` |
| (linter) `'command_callback': 'Foo'` | `'command': function('Foo')` |
| (linter) `'executable_callback': 'Foo'` | `'executable': function('Foo')` |
| (linter) `'address_callback': 'Foo'` | `'address': function('Foo')` |
| (linter) `'language_callback': 'Foo'` | `'language': function('Foo')` |
| (linter) `'initialization_options_callback': 'Foo'` | `'initialization_options': function('Foo')` |
| (linter) `'lsp_config_callback': 'Foo'` | `'lsp_config': function('Foo')` |
| (fixer) `chain_with` | `ale#command#Run` |

The following `<Plug>` mappings were previously scheduled for deprecation, but instead will be supported forever, and are now documented again.

* `<Plug>(ale_go_to_definition_in_tab)`
* `<Plug>(ale_go_to_definition_in_split)`
* `<Plug>(ale_go_to_definition_in_vsplit)`
* `<Plug>(ale_go_to_type_definition_in_tab)`
* `<Plug>(ale_go_to_type_definition_in_split)`
* `<Plug>(ale_go_to_type_definition_in_vsplit)`

**Comment by chipsenkbeil** [comment]
@w0rp, was `project_root_callback` also changed in the migration to `project_root`? Or was that earlier? Just did my migration of a custom linter and had to update that one alongside command and executable.
