### ISSUE TITLE
how to use  intelephense for php

### ISSUE THREAD

**Issue by likelxl** [dense-analysis/ale#3306]
## Information

**VIM version**

NVIM v0.5.0-634-g161cdba1e
Build type: Release

Operating System: deepin linux

## What went wrong

the php lsp intelephense can't work.

## Reproducing the bug

my config is below
```
call ale#linter#Define('php', {
\   'name': 'intelephense',
\   'lsp': 'stdio',
\   'executable': 'intelephense',
\   'command': '%e run',
\   'project_root': '/home/erge/code/php/base',
\})
let g:ale_completion_enabled=1
let g:ale_linters = {
\ 'php': ['intelephense']
\}
```

### :ALEInfo

 Current Filetype: php
Available Linters: ['intelephense', 'langserver', 'phan', 'php', 'phpcs', 'phpmd', 'phpstan', 'psalm']
  Enabled Linters: ['intelephense']
 Suggested Fixers: 
  'php_cs_fixer' - Fix PHP files with php-cs-fixer.
  'phpcbf' - Fix PHP files with phpcbf.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'php': ['intelephense']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = v:null
let g:ale_list_window_size = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_sign_highlight_linenrs = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) intelephense

**Comment by w0rp** [comment]
Try completion again now, as I just fixed #3312, which may be related.

**Comment by likelxl** [comment]
It still doesn't work

**Comment by creativenull** [comment]
Hey @likelxl I got it to work after I changed the `command` key to `%e --stdio` try that and see if you are able to get this to work. I am also trying to use intelephense with ale 🙂

I have my intelephense globally installed if that helps as well.

```
call ale#linter#Define('php', {
\   'name': 'intelephense',
\   'lsp': 'stdio',
\   'executable': 'intelephense',
\   'command': '%e --stdio',
\   'project_root': '...',
\ })
```

**Comment by likelxl** [comment]
yes,it can work @creativenull thank you very much.
In addition, I would like to ask, why can’t I complete the functions of the posix series and what settings are needed?

**Comment by creativenull** [comment]
I'm not quite sure what you mean by the posix series. Do you mean if there is autocompletion for general/global php functions? Then yes, it should have those functions available through intelephense.

**Comment by likelxl** [comment]
> I'm not quite sure what you mean by the posix series. Do you mean if there is autocompletion for general/global php functions? Then yes, it should have those functions available through intelephense.

eg:posix_getpid
but i can't complete these, what settings do I need,

**Comment by creativenull** [comment]
Ok I see what you mean now. I did try it and it seemed to work with my config. Auto-completion should work out-of-box you don't really need to set `omnifunc`.

Note, the way I have it setup, intelephense will only work if it finds a `composer.json` file in the project root. So I am using this with a blank Laravel project. Below is my minimal ale config that it worked with, let me know if works.

[Here is an asciinema video](https://asciinema.org/a/JzV9XiYnCKuoPw5FKoCXsjLcu)

```vim
call ale#linter#Define('php', {
\   'name': 'intelephense',
\   'lsp': 'stdio',
\   'executable': 'intelephense',
\   'command': '%e --stdio',
\   'project_root': function('ale_linters#php#langserver#GetProjectRoot')
\ })

" ALE general config
let g:ale_completion_enabled = 1
let g:ale_completion_delay = 100
let g:ale_completion_autoimport = 1

" ALE linters config
let g:ale_linters_explicit = 1
let g:ale_linters = {
\   'php': ['intelephense'],
\ }

set omnifunc=ale#completion#OmniFunc
```

**Comment by likelxl** [comment]
> Ok I see what you mean now. I did try it and it seemed to work with my config. Auto-completion should work out-of-box you don't really need to set `omnifunc`.
> 
> Note, the way I have it setup, intelephense will only work if it finds a `composer.json` file in the project root. So I am using this with a blank Laravel project. Below is my minimal ale config that it worked with, let me know if works.
> 
> [Here is an asciinema video](https://asciinema.org/a/JzV9XiYnCKuoPw5FKoCXsjLcu)
> 
> ```viml
> call ale#linter#Define('php', {
> \   'name': 'intelephense',
> \   'lsp': 'stdio',
> \   'executable': 'intelephense',
> \   'command': '%e --stdio',
> \   'project_root': function('ale_linters#php#langserver#GetProjectRoot')
> \ })
> 
> " ALE general config
> let g:ale_completion_enabled = 1
> let g:ale_completion_delay = 100
> let g:ale_completion_autoimport = 1
> 
> " ALE linters config
> let g:ale_linters_explicit = 1
> let g:ale_linters = {
> \   'php': ['intelephense'],
> \ }
> 
> set omnifunc=ale#completion#OmniFunc
> ```

i copy your config,It still doesn't work. 
![image](https://user-images.githubusercontent.com/12811070/92998713-14984880-f54e-11ea-8f21-de9d9ce8a660.png)
![image](https://user-images.githubusercontent.com/12811070/92998718-237efb00-f54e-11ea-89cb-65e1585cec15.png)

**Comment by creativenull** [comment]
That's weird, what's the output of your `:ALEInfo` ? Are you able to see the `--stdio` in `:ALEInfo` ?

I did the exact same directory structure and I am still getting it to work 😕

**Comment by likelxl** [comment]
Current Filetype: php
Available Linters: ['intelephense', 'langserver', 'phan', 'php', 'phpcs', 'phpmd', 'phpstan', 'psalm']
  Enabled Linters: ['intelephense']
  Ignored Linters: []
 Suggested Fixers: 
  'php_cs_fixer' - Fix PHP files with php-cs-fixer.
  'phpcbf' - Fix PHP files with phpcbf.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = v:null
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'php': ['intelephense']}
let g:ale_linters_explicit = 1
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) intelephense
(started) ['/bin/bash', '-c', '''intelephense'' --stdio']

**Comment by likelxl** [comment]
PHP 7.4.9 (cli) (built: Aug 21 2020 21:42:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

My php version,if i use [vim-lsc](https://github.com/natebosch/vim-lsc),[phpcd](https://github.com/lvht/phpcd.vim)，it can complete posix function

**Comment by creativenull** [comment]
Looking from `:ALEInfo` the only difference I see is the `let g:ale_completion_max_suggestions = v:null` for me this is set to 50 by default. Try adding this to your vimrc and see if that helps. I'm not too sure what else could be the issue.

**Comment by likelxl** [comment]
i tried set 50 and null both,but no useful,so sad.

**Comment by creativenull** [comment]
Welp I tired all the resources I had lol. Sorry to hear that 😢

**Comment by creativenull** [comment]
If I get time today or tomorrow I'll try and make a PR for adding intelephense support to ale and test it that way and see if it would help anyone else using intelephense with ale

**Comment by likelxl** [comment]
ok,thx

**Comment by likelxl** [comment]
@creativenull  I found the reason, it is that omnifunc does not work, because the 
```
filetype indent plugin on
```
 is set, in the php file
```
:set omnifunc?
``` 
You can see the currently used omnifunc
