### ISSUE TITLE
ALE Linter Flake8 does not respect user configurations

### ISSUE THREAD

**Issue by averydark** [dense-analysis/ale#3308]
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)
Included patches: 1-2269

Operating System: Pop!_OS 20.04 LTS x86_64

## What went wrong

ALE Linter Python Flake8 ignores user configuration. Setting `~/.config/flake8` is ignored. Changing `python_flake8_use_global` from 0 to 1 does nothing to affect this behavior.

Issue #1538 is not related to this problem even though it is a related end result.

## Reproducing the bug

I created the flake8 configuration file.

```bash
touch ~/.config/flake8
vim ~/.config/flake8
```

I copy/pasted directly from [flake8 official docs](https://flake8.pycqa.org/en/latest/user/configuration.html#project-configuration)

```
[flake8]
ignore = E251,E501,
exclude =
    # No need to traverse our git directory
    .git,
    # There's no value in checking cache directories
    __pycache__,
    # The conf file is mostly autogenerated, ignore it
    docs/source/conf.py,
    # The old directory contains Flake8 2.0
    old,
    # This contains our built documentation
    build,
    # This contains builds of flake8 that we don't want to check
    dist
# max-complexity = 10
```

Wrote the results and quit. Then I modified [line 6](https://github.com/dense-analysis/ale/blob/master/ale_linters/python/flake8.vim#L6)  `~/.vim/plugged/ale/ale_linters/python/flake8.vim` and changed 0 to 1 to use global flake8.

Using [a file to test out GTK grid](https://python-gtk-3-tutorial.readthedocs.io/en/latest/layout.html#id1) displayed the `E501` flake8 error.

### :ALEInfo

```
 Current Filetype: python
Available Linters: ['bandit', 'flake8', 'mypy', 'prospector', 'pycodestyle', 'pydocstyle', 'pyflakes', 'pylama', 'pylint', 'pyls', 'pyre', 'pyright', 'vulture']
  Enabled Linters: ['flake8']
 Suggested Fixers: 
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'reorder-python-imports' - Sort Python imports with reorder-python-imports.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:

let g:ale_python_auto_pipenv = 0
let g:ale_python_flake8_auto_pipenv = 0
let g:ale_python_flake8_change_directory = 1
let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 1
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'python': ['flake8']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) flake8
(finished - exit code 0) ['/bin/bash', '-c', '''flake8'' --version']

<<<OUTPUT STARTS>>>
3.7.9 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.8.2 on Linux
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/bin/bash', '-c', 'cd ''/media/avery/pragma/documents/code/python/gtkdev'' && ''flake8'' --format=default --stdin-display-name ''/media/avery/pragma/documents/code/python/gtkdev/6.2.1.grid.py'' - < ''/tmp/vqjtFdn/2/6.2.1.grid.py''']

<<<OUTPUT STARTS>>>
/media/avery/pragma/documents/code/python/gtkdev/6.2.1.grid.py:20:80: E501 line too long (88 > 79 characters)
/media/avery/pragma/documents/code/python/gtkdev/6.2.1.grid.py:23:80: E501 line too long (90 > 79 characters)
/media/avery/pragma/documents/code/python/gtkdev/6.2.1.grid.py:27:80: E501 line too long (90 > 79 characters)
<<<OUTPUT ENDS>>>
```

### FIX

Changing 

```vim
call ale#Set('python_flake8_options', '')
```

to 

```vim
call ale#Set('python_flake8_options', '--config=$HOME/.config/flake8')
```

fixes this issue.

Flake8 checks specific [directories by default](https://flake8.pycqa.org/en/latest/user/configuration.html#configuration-locations). Leaving the option blank shouldn't make a difference. The current working directory, the config directory, and the global directory should all be respected and this setting should not be required. Flake8 should be trusted enough to do what it does automatically by default.

After spending some time tinkering with this issue and investigating it my self, I was able to narrow it down to ALE interfering with its default operation and I'm not sure why it does this.

**Comment by w0rp** [comment]
If it's not loading a default configuration file when none is specified, that sounds like a bug in `flake8`. The only options we set are `--format` and `--stdin-display-name`, and it doesn't make sense for either of them to stop default configuration files from being loaded.

**Comment by averydark** [comment]
@w0rp 

Both the manual and the docs state that `flake8` does this automatically. This is the first time it has been an issue for me after having used `flake8` in both the CLI and a variety of editors. Setting the `--config` flag manually was never a requirement. After testing out `flake8` with the config set, `flake8` used the `~/.config/flake8` config file automatically in the CLI.

**Comment by w0rp** [comment]
Report a bug for `flake8`, or set `--config` to work around it. ALE doesn't seem to be doing anything that ought to cause problems.

**Comment by AmagicalFishy** [comment]
This is old, but: https://flake8.pycqa.org/en/latest/release-notes/4.0.0.html#backwards-incompatible-changes

As of 4.0.0, `flake8` no longer supports user-level configuration

**Comment by solomonxie** [comment]
Thanks @AmagicalFishy
This solves the issue: 
```sh
pip install flake8==3.9.2
```
