### ISSUE TITLE
rust-analyzer code completions are broken by default (g:ale_completion_autoimport = 0)

### ISSUE THREAD

**Issue by derlaft** [dense-analysis/ale#3312]
## Information

**VIM version**
* vim 8.2.1522

Also reproduced on:
* neovim 0.4.4
* neovim 0.5.0-637-g43202964f

Operating System: Archlinux

## What went wrong

Commit 6d502233d849600ecb2a08227299ffea2b2ea0c7 breaks auto completions with `rust-analyzer` for me.

Setting `let g:ale_completion_autoimport = 1` or reverting to 8bfb5c64073cf12018e5b7e115867b2ef4dfa7e0 fixes the problem instantly.

## Reproducing the bug

1. Setup rust and rust-analyzer
2. Use a clean config file:

```
call plug#begin('~/.vim/plugged')

Plug 'dense-analysis/ale'

call plug#end()
let b:ale_linters = {'rust': ['analyzer']}
let g:ale_completion_enabled = 1
set omnifunc=ale#completion#OmniFunc
```
2. Try code completions inside `src/main.rs` of an empty rust project (`cargo new something`)
3. Completions do not work
4. Add `let g:ale_completion_autoimport = 1` or revert 6d502233d849600ecb2a08227299ffea2b2ea0c7
5. See that completions are fixed

### :ALEInfo

```
 Current Filetype: rust
Available Linters: ['analyzer', 'cargo', 'rls', 'rustc']
  Enabled Linters: ['analyzer']
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'rustfmt' - Fix Rust files with Rustfmt.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_rust_analyzer_config = {}
let g:ale_rust_analyzer_executable = 'rust-analyzer'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let b:ale_linters = {'rust': ['analyzer']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) rust-analyzer
(started) ['/bin/zsh', '-c', '''rust-analyzer''']
```

**Comment by derlaft** [comment]
If that is something expected, I guess documentation could be improved, because I could not really understand why everything broke and what "automatic imports from external modules" in context of `rust-analyzer` means.

`rls` doesn't seem to be affected by this

**Comment by derlaft** [comment]
I am looking at what that code does:

```
        if has_key(l:item, 'additionalTextEdits') && !g:ale_completion_autoimport
            continue
        endif
```

and this is how `rust-analyzer` message looks like:

```
    {
      "additionalTextEdits": [],
      "deprecated": false,
      "detail": "pub fn iter(&self) -> Iter",
      "filterText": "iter",
      "insertTextFormat": 1,
      "kind": 2,
      "label": "iter",
      "textEdit": {
        "newText": "iter",
        "range": {
          "end": {
            "character": 9,
            "line": 27
          },
          "start": {
            "character": 9,
            "line": 27
          }
        }
      }
    },
```

`additionalTextEdits` seems to always be present, but only as an empty array (at least from what I could see)

**Comment by w0rp** [comment]
That's a weird quirk. Turning the setting of shouldn't stop you from seeing those completion items. I'll fix that by checking of the additional text edits in in range of the line you're editing, instead of way off somewhere else, as an import would be.

**Comment by w0rp** [comment]
I've pushed a fix for that now. Now ALE only skips completion results that have `additionalTextEdits` that start on some line other than the current one. In your case, this means that results with an empty Array will be included. I also made ALE throw away any `additionalTextEdits` that are identical to what inserting the completion text will do, just in case.

**Comment by w0rp** [comment]
Actually, that's silly. I just changed it now to check if `additionalTextEdits` is non-empty, which is what caused your problem, the key being present, but empty.

**Comment by derlaft** [comment]
Thank you, I think it works now
