### ISSUE TITLE
Add <Plug>(ale_find_references_relative) to use for mapping

### ISSUE THREAD

**Issue by Andoku** [dense-analysis/ale#3314]
We can run command with argument:
`:ALEFindReferences -relative`
But there is no <Plug>(ale_find_references_relative) to use as for key mappings.

**Comment by w0rp** [comment]
There are currently 8 possible variations for the command, as you can combine `-relative` with `-tab`, `-vsplit`, and `-split`. There will probably be more options in future. I don't want to define any more `<Plug>` mappings, as we'll end up with a combinatorial explosion of mappings, which will gradually increase plugin load times by a lot. I recommend creating your own instead.

```vim
nnoremap <silent> <Plug>(ale_find_references_relative) :ALEFindReferences -relative<Return>
```

I was going to remove the additional mappings for `:ALEGoToDefinition` and `:ALEGoToTypeDefinition` as a breaking change for ALE 3.0, but I decided to just keep them forever, and never add any more additional plug mappings for future options for commands.

**Comment by w0rp** [comment]
I updated the documentation now to explain how to write new `<Plug>` mappings for `ALEFindReferences`.
