### ISSUE TITLE
unlet g:ale_fixers error at saving time

### ISSUE THREAD

**Issue by laoshaw** [dense-analysis/ale#3315]
on ubuntu 20.04 with vim 8.2, I need edit a few old c files without ale_fixers applied(to make sure the diff files are sane), so I tried to disable ale_fixers temporary:

1. let g:ale_fixers={}  works fine.
2. unlet g:ale_fixers , then save the file(I have fix-on-save), this does not work, instead vim says:

```
Error detected while processing function ale#events#SaveEvent[8]..ale#fix#Fix[6]..<SNR>206_GetCallbacks[9]..ale#Var:
line    4:
E716: Key not present in Dictionary: ale_fixers
E116: Invalid arguments for function get(l:vars, l:full_name, g:[l:full_name])
Error detected while processing function ale#events#SaveEvent:
line    8:
E171: Missing :endif
```

**Comment by w0rp** [comment]
You shouldn't delete the ALE global variables, as you'll get lots of errors. Try using `let g:ale_fixers = {}` instead, or `let g:ale_fix_on_save = 0`.

You might want to consider using `g:ale_pattern_options` to set `b:ale_fix_on_save` for your buffers automatically, based on a regular expression match for the files you don't want to modify. See `:help g:ale_pattern_options`.
