### ISSUE TITLE
"Cannot make changes, 'modifiable' is off" race condition with ale when foldexpr is set

### ISSUE THREAD

**Issue by DanCardin** [dense-analysis/ale#3319]
## Information

**VIM version**

```
NVIM v0.5.0-dev
Build type: Release
```

Operating System: macos 10.14.6

## What went wrong

Errors with `Cannot make changes, 'modifiable' is off` during the period of time when ale is trying to fix a file while changing the screen focus. And seems to require `set foldmethod=expr` to be set

Given that the error references a callback from ale, it feels a bit more natural that it'd be an ale bug rather than a floaterm but, but eel free to let me know if this makes more sense as an floaterm bug report.

This may not be the most minimal rc file but I'm not sure how to minimally produce things like delayed buffer modifications in the same way ale does + focused floating windows like floaterm does.

## Reproducing the bug

vimrc:
```vim
set nocompatible
set runtimepath^=~/.config/nvim/pack/packager/start/ale  " or path to ale
set runtimepath^=~/.config/nvim/pack/packager/start/vim-floaterm  " or path to vim-floaterm

set foldmethod=expr
" arbitrary foldexpr
func! FoldIndent() abort
    return -1
endfunc
setlocal foldexpr=FoldIndent()

let g:ale_fixers = {
\   'python': ['isort'],
\}
let g:ale_fix_on_save = 1

noremap  <silent> <Leader>fj :FloatermToggle<CR>

filetype plugin indent on
syntax on
```
1. Open a python file, which will be modified by an ale fixer. Here i use python/isort and like... `import pytest; import unittest`
2. save that file
3. Quickly (before the fixer is completed) invoke floaterm
4. See:
```
Error detected while processing function <SNR>111_NeoVimCallback[29]..<lambda>40[1]..<SNR>106_ExitCallback[28]..<SNR>129_HandleExit[32]..<SNR>129_RunFixer[6]..ale#fix#ApplyFixe
s[26]..ale#fix#ApplyQueuedFixes[10]..ale#util#SetBufferContents:
line   17:
E21: Cannot make changes, 'modifiable' is off
Press ENTER or type command to continue
```

**Expected behavior**
The same behehavior, as when `set foldmethod=expr` is left out, i.e. the fix is applied in the background, while you are focused into the floating window.

### :ALEInfo
```

 Current Filetype: python
Available Linters: ['bandit', 'flake8', 'mypy', 'prospector', 'pycodestyle', 'pydocstyle', 'pyflakes', 'pylama', 'pylint', 'pyls', 'pyre', 'pyright', 'vulture']
  Enabled Linters: ['flake8', 'mypy', 'pylint', 'pyright']
 Suggested Fixers: 
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'reorder-python-imports' - Sort Python imports with reorder-python-imports.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:

<redacted settings because they're all default except for what's set in the vimrc>
```

**Comment by w0rp** [comment]
This is difficult to deal with. ALE can't safely modify a file if it's been modified in-between starting processes to fix a file and when the results are ready to apply to a file, as it can wipe out other changes you've made.

It is possible to modify the `vim-floaterm` plugin so it either doesn't modify a file, or marks a file as not being modified after it toggles folds?

**Comment by DanCardin** [comment]
So I dont think `vim-floaterm` is modifying the file, (i think) it's just popping up a focused floating window in front of the current buffer. I wouldn't think it's doing anything with folds either.

I can also reproduce this by doing an lsp hover twice (with nvim-lsp where it pops up a floating window the first time, and focuses it the 2nd time), or with https://github.com/rhysd/git-messenger.vim (which similarly focuses the floating window after invoking it twice

**Comment by w0rp** [comment]
I have fixed this now by temporarily setting `modifiable` for a buffer ALE is trying to edit for `:ALEFix` and other commands if they become `nomodifiable` for some reason. It might mess up folds or something, but it will change the buffer.

**Comment by DanCardin** [comment]
I updated the plugin (making sure that my current Ale includes your commit) and can still reproduce both with my normal config as well as the minimalish rc i posted above.

The one difference between the two is the minimal config produces the error once whereas i get pages of the same error repeated with my normal config for some reason.

**Comment by w0rp** [comment]
What exactly is changing the value of `modifiable`? Why does a buffer stop being modifiable when you use folds?

**Comment by DanCardin** [comment]
Im not using folds at all. I just noticed that it seems to only occur with that setting. A far as i know, the above vimrc does this reliably across environments on any file, so long as alefix would have made a change

Do you not think it’s related to the fact that it occurs when the input focus moves to a floating window. Knowing nothing about how the plugin works, it seems like it’s trying to write the contents of the fixed file to the newly focused floating window, or the focusing of the floating window sets the current buffer to non modifiable for some reason. Although, i idk why that would be related to the foldexpr setting...

**Comment by w0rp** [comment]
I have pushed a patch now which might fix your issue. Give it a try. Now ALE will catch E21, give up on trying to apply fixes, and try again later when the buffer is entered. It might fail to fix a buffer in your circumstances until you switch back and forth from one buffer to another, or it might just work.

**Comment by DanCardin** [comment]
This does seem to at least avoid the errors 👍! The buffer shows as modified (although the buffer is not visibly changed), and then switching back **does** cause it to visibly change and save the modification.

My only nit would be ideally it would work exactly like e.g. switching buffers does by simply performing the fix in the background on the now-non-focused buffer. Given the odd reliance of this on `foldmethod=foldexpr`, could this be a nvim bug which I should report there?

**Comment by w0rp** [comment]
I can't repeat the issue in just the same way that you can, but you could help me discover a way to make this a little better, _possibly_. Have a look at `:help autocmd-events-abc`. You might be able to identify a reasonable event that is fired after you finish using your floating windows which ALE could hook into. ALE uses `BufEnter` to attempt to fix a file, especially for older Vim versions which do not support editing buffers other than the currently focused one. It might be that another event like `WinEnter` or `BufWinEnter` will fire before `BufEnter` does, so we can apply fixes more quickly.

Have a look at `autoload/ale/fix.vim` at the end of the file. You can experiment with setting events other than `BufEnter`. It might not be possible to do any better, but it's worth a try.

**Comment by DanCardin** [comment]
I just want to be clear, this works "correctly" in normal cases.
* with normal buffers: i.e. save buffer, quickly switch, and it will save the alefix/save the first buffer while the 2nd one is focused
* with floating windows when foldexpr is unset: i.e. save buffer, quickly focus floating window, and it will save the alefix/save the first buffer while the floating window is focused

It only exhibits the problematic behavior when foldexpr is set, regardless of whether anything has been done with folds.

Granted I know very little about what's going on with foldexpr set/unset but it feels like anything behavior you can achieve with it unset should also be possible with it set, no? Which makes it feel like the delayed save behavior you were able to produce with https://github.com/dense-analysis/ale/commit/dd9ad9b5be84bea7105a91bb7e15c308cfe2c57f is maybe just working around some other issue.

> I can't repeat the issue in just the same way that you can
Is there something I could do to help in that regard? I can repro with python fixers on any machine i've got.
