### ISSUE TITLE
ALERename applies changes in the wrong order

### ISSUE THREAD

**Issue by Andoku** [dense-analysis/ale#3322]
## Information

**VIM version**

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 18 2020 18:29:15)
Included patches: 1-1453   

Operating System: Ubuntu 18.04

clangd: 10.0.0

## What went wrong

`:ALERename` command is not working properly with `clangd`. 
It messes up code. 
And if i undo changes by pressing `u` and quit without saving `:q!` changes are still saved in the file somehow.

## Reproducing the bug

1. Move to a symbole
2. Run :ALERename, type the new symbol name and hit
3. Everything gets messed up

### :ALEInfo

```
 Current Filetype: cpp
Available Linters: ['cc', 'ccls', 'clangcheck', 'clangd', 'clangtidy', 'clazy', 'cppcheck', 'cpplint', 'cquery', 'flawfinder']
   Linter Aliases:
'cc' -> ['gcc', 'clang', 'g++', 'clang++']
  Enabled Linters: ['clangd']
 Suggested Fixers: 
  'astyle' - Fix C/C++ with astyle.
  'clang-format' - Fix C/C++ and cuda files with clang-format.
  'clangtidy' - Fix C/C++ and ObjectiveC files with clang-tidy.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'uncrustify' - Fix C, C++, C#, ObjectiveC, ObjectiveC++, D, Java, Pawn, and VALA files with uncrustify.
 Linter Variables:

let g:ale_cpp_clangd_executable = '/home/anton/clangd_10.0.0/bin/clangd'
let g:ale_cpp_clangd_options = ''
let g:ale_cpp_gcc_options = '-std=c++11 -Wall'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 0
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'c': ['clangd'], 'cpp': ['clangd']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 1
let g:ale_set_highlights = 0
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(started) ['/bin/bash', '-c', '''/home/anton/clangd_10.0.0/bin/clangd'' -compile-commands-dir=''/media/anton/a6b7069c-182f-4828-9105-32e95652ae41/home/anton/NetBeansProjects/ima_2019/trunk/wise_collector/build''']
```

**Comment by Andoku** [comment]
Also if symbol is in different files it gives me:
`No changes received from server`

**Comment by w0rp** [comment]
What does "gets messed up" mean? Can you provide any examples of what happens?

One thing you can do that will be very helpful is add `call ch_logfile(expand('~/channel.log'), 'w')` to your `vimrc` file before ALE is loaded, rename your code, and submit the log here. Vim lets you log absolutely everything that gets sent back and forth between the client and the language server, so we can know exactly what messages were sent to `clangd` and what messages `clangd` sent back to ALE.

**Comment by Andoku** [comment]
@w0rp 
Before :ALERename of `args` to `x
`![Screenshot from 2020-08-28 12-39-22](https://user-images.githubusercontent.com/669031/91546810-b8b5a900-e92b-11ea-9f6e-1a9ce6b619d2.png)

After  :ALERename of `args` to `x`
![Screenshot from 2020-08-28 12-39-49](https://user-images.githubusercontent.com/669031/91546853-ca974c00-e92b-11ea-887c-4d08335e2fea.png)

**LOG:**
[channel.log](https://github.com/dense-analysis/ale/files/5141329/channel.log)

**Comment by w0rp** [comment]
Thank you. I can use that output to fix it.

**Comment by w0rp** [comment]
I believe I have fixed this now. I had the same problem with `tsserver` at work. The issue was that the changes from `tsserver` or the Language server can be sent in an order other than the order ALE needs. Now the changes are sorted before ALE applies them, so they should just work.

**Comment by w0rp** [comment]
```vim
Given typescript(An example TypeScript file):
  type Foo = {}

  export interface ISomething {
    fooLongName: Foo | null
  }

  export class SomethingElse implements ISomething {
    // Bindings
    fooLongName!: ISomething['fooLongName']
  }

Execute():
  let g:changes = [
  \ {'end': {'offset': 14, 'line': 4}, 'newText': 'foo', 'start': {'offset': 3, 'line': 4}},
  \ {'end': {'offset': 40, 'line': 9}, 'newText': 'foo', 'start': {'offset': 29, 'line': 9}},
  \ {'end': {'offset': 14, 'line': 9}, 'newText': 'foo', 'start': {'offset': 3, 'line': 9}},
  \]

  call ale#code_action#ApplyChanges(expand('%:p'), g:changes, 0)

Expect(The changes should be applied correctly):
  type Foo = {}

  export interface ISomething {
    foo: Foo | null
  }

  export class SomethingElse implements ISomething {
    // Bindings
    foo!: ISomething['foo']
  }
```

I'm pretty happy with the test case. If there are ever any issues, they should be easy to add a test case for and fix.

**Comment by Andoku** [comment]
@w0rp 
Seems like it still doesn't work with clangd - same problems. I will try clean install.

**Comment by w0rp** [comment]
Sure, reinstall ALE completely and let me know if it's any different.

**Comment by Andoku** [comment]
[channel.log](https://github.com/dense-analysis/ale/files/5173994/channel.log)

Seems like result is still the same.

**Comment by w0rp** [comment]
Thanks for checking. I'll see if I can fix that too. I had a similar issue, and I fixed that, so it looked like I had fixed it.

**Comment by AlxHnr** [comment]
I can confirm this issue with clangd 10, nvim 0.4.4 and the latest ALE from today. Here is what happens if I try to to rename `setValue` to `setValue123`:

Before:

```cpp
void Bar::setValue(int value) {
  this->value = value;
}
```

After:

```cpp
void Bar::setValue123(int value) { s->value = value; 
```

The new code is missing `}` and `this` gets replaced with `s`.


Here a minimal example to reproduce this issue:

### 1. Install ALE and set this variable:

```vim
let g:ale_cpp_clangd_options = '-cross-file-rename --header-insertion=never'
```

### 2. Copy this to `/tmp/compile_commands.json`:

```json
[{
  "directory": "/tmp/foo.cpp",
  "command": "/usr/bin/c++      -std=gnu++17 -o foo.o -c /tmp/foo.cpp",
  "file": "/tmp/foo.cpp"
}]
```

### 3. Copy this to `/tmp/foo.cpp`:

```cpp
class Bar {
public:
  void setValue(int value);

private:
  int value{};
};

void Bar::setValue(int value) {
  this->value = value;
}
```

### 4. Edit `/tmp/foo.cpp`

Go to `setValue`, type `:ALERename` and rename to `setValue123`.

**Comment by w0rp** [comment]
@AlxHnr As mentioned in the PR, please use `:call ch_logfile(expand('~/channel.log'), 'w')` to produce a log file, repeat the issue on your machine, and attach that here. I can use that to repeat the bug in tests and fix the issue.

**Comment by w0rp** [comment]
I believe this has been fixed now. Let me know if you still have any issues.
