### ISSUE TITLE
Errors when opening or writing to some file types (Rust, Python, ..?)

### ISSUE THREAD

**Issue by PaulDance** [dense-analysis/ale#3323]
## Information

**VIM version**

```
NVIM v0.3.4
Build type: Release
```

Operating System: 

Linux: Debian 10.5 (Buster), kernel 4.19.0-10-amd64

## What went wrong

When opening or writing to some of the supported file types such as Rust or Python files - maybe others as well, but not C or Java files for example, there are errors thrown about the absence of the `ale_filename_mappings` variable, see below for details.

From my investigating, it is linked to #2556 addressed by ba3dd0d and #2449. I found that contrary to the documentation of `g:ale_filename_mappings` stating that "Default: `{}`", the global variable is actually not defined by default, although there is

https://github.com/dense-analysis/ale/blob/ecd7abecc08ead5d8f055b26498e1c4a2a2c3065/autoload/ale/fix.vim#L5

but I can't comment further on this.

Also, defining the variable as `{}` in the `.vimrc` suppresses the errors: it is properly defined and accessible by the `ale#GetFilenameMappings` function.

Finally, manually checking out ba3dd0d's parent 2b78568 in the local repo (without having the variable defined in `.vimrc`), the errors do not show up either, so I think the bug was introduced by the said commit.

## Reproducing the bug

1. Open a Rust or Python file using `nvim the-file.[rs | py]`.
2. Then the errors appear:

![image](https://user-images.githubusercontent.com/35344098/91509736-6a78b980-e8db-11ea-8d0c-29f165631721.png)

3. Write the buffer to the disk using `:w`.
4. Other similar errors show up:

![image](https://user-images.githubusercontent.com/35344098/91509908-d2c79b00-e8db-11ea-9018-5d9eddafa2eb.png)

and

![image](https://user-images.githubusercontent.com/35344098/91509932-e6730180-e8db-11ea-9b9a-feebd0158b67.png)

### :ALEInfo

When opening an error-prone file:

```
 Current Filetype: rust
Available Linters: ['analyzer', 'cargo', 'rls', 'rustc']
  Enabled Linters: ['cargo']
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'rustfmt' - Fix Rust files with Rustfmt.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_rust_cargo_avoid_whole_workspace = 1
let g:ale_rust_cargo_check_all_targets = 0
let g:ale_rust_cargo_check_examples = 0
let g:ale_rust_cargo_check_tests = 0
let g:ale_rust_cargo_clippy_options = ''
let g:ale_rust_cargo_default_feature_behavior = 'default'
let g:ale_rust_cargo_include_features = ''
let g:ale_rust_cargo_target_dir = ''
let g:ale_rust_cargo_use_check = 1
let g:ale_rust_cargo_use_clippy = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = v:null
let g:ale_list_window_size = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_sign_highlight_linenrs = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) cargo
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''cargo'' --version']

<<<OUTPUT STARTS>>>
cargo 1.46.0 (149022b1d 2020-07-17)
<<<OUTPUT ENDS>>>
```

I haven't overridden any ALE configuration variables in my `.vimrc`.

**Comment by w0rp** [comment]
I've fixed that now by setting the default also in `engine.vim`.

**Comment by PaulDance** [comment]
Thanks, works perfectly!
