### ISSUE TITLE
Neovim. Own ale linter fails: Undefined variable: name

### ISSUE THREAD

**Issue by Glavnokoman** [dense-analysis/ale#3356]
Reopening https://github.com/dense-analysis/ale/issues/2480. The issue is limited to Neovim users. But there ALE seem to be contributing to it as well https://github.com/dense-analysis/ale/issues/2480#issuecomment-691989268

**Comment by w0rp** [comment]
Please share the code for your linter, and I'll have a look. You probably need to change your code.

**Comment by Glavnokoman** [comment]
I can't really share that, but I'll try to come up with some minimal reproducible example. In the meantime replacing `let l:name_list = [l:linter.name] + l:linter.aliases` by `let l:name_list = [l:linter.name]` in `autoload/ale/linter.vim:366` fixes the issue for me. So I thought maybe that's some variable being undefined and handled differently by neovim. Cause all people affected by #2480 were also on neovim.

**Comment by w0rp** [comment]
It'll be because `aliases` somehow becomes a number, which shouldn't happen, but might be happening. That code should be there.

Let me know when you can share something with me, and I'll have a look.

**Comment by copy** [comment]
Bisecting between v2.7.0 and v3.0.0 reveals this as the bad commit: 5eda1df0a96e691ebf24e5d8a3585c2feb2a48a3

**Comment by w0rp** [comment]
@copy Could you share your code, please? It's almost certainly deprecated functionality I removed, and you need to update your linter definition.

**Comment by copy** [comment]
This is using the built-in merlin linter: https://github.com/dense-analysis/ale/blob/master/ale_linters/ocaml/merlin.vim

**Comment by copy** [comment]
I was wrong, this was actually causes by a linter I had written a long time ago that I never used nor committed. Apologies about the noise.

**Comment by Glavnokoman** [comment]
Yes, this was the glitch in my linter. Sorry. And thanks!

**Comment by kovasap** [comment]
I'm having this issue too, @copy and @Glavnokoman do either of you happen to remember what the linter glitches that were causing this looked like?   some code snippets would be very helpful if you have them for me to debug my own setup!

**Comment by fvisin** [comment]
I hit this error as well. After updating Ale, I am getting this error message:

> Error detected while processing function ale#events#LintOnEnter[5]..ale#Queue[33]..<SNR>243_Lint[3]..ale#linter#Get:
> line   15:
> E745: Using a List as a Number
> E15: Invalid expression: [l:linter.name] + l:linter.aliases
> Error detected while processing function <SNR>2_python_mypylint_update[17]..ale#Queue[33]..> SNR>243_Lint[3]..ale#linter#Get:
> line   15:
> E745: Using a List as a Number
> E15: Invalid expression: [l:linter.name] + l:linter.aliases
> E745: Using a List as a Number
> E15: Invalid expression: [l:linter.name] + l:linter.aliases

From my rudimental debugging:
```
                try
                  let l:name_list = [l:linter.name] + l:linter.aliases
                catch /.*/
                  echo "Caught error: " . v:exception
                  echo "name" l:linter.name
                  echo "aliases" l:linter.aliases
                endtry
```
 
l:linter.aliases seems to be empty:

> Caught error: Vim(let):E745: Using a List as a Number
> 0vulture
> aliases

What is more surprising, the error doesn't seem to originate from my linter's code. In fact, removing all my ale-related configs and my linter's code only solves part of the issue:

> Error detected while processing function ale#events#LintOnEnter[5]..ale#Queue[33]..<SNR>243_Lint[3]..ale#linter#Get:
> line   15:
> E745: Using a List as a Number
> E15: Invalid expression: [l:linter.name] + l:linter.aliases

I also ran git bisect and found the same commit as the culprit.

Unfortunately I also cannot share the code of the linter, but as I said it doesn't seem to be the cause of the issue. @w0rp is any of this helpful to pinpoint the issue? Let me know if I can run more tests. Thank you

**Comment by w0rp** [comment]
I can't fix your issue without looking at your linters, but you can find it by looking through all of the linters you have loaded and finding the one that has set `aliases` to a Number. Search through all of your linters defined in `ale_linters` anywhere in `runtimepath` and anywhere else you've defined them. Make sure `aliases` isn't set to a Number. `aliases` defaults to `[]`, and all of the aliases for linters are defined as List values in the ALE codebase, so it shouldn't be a bug in ALE's code.

**Comment by fvisin** [comment]
A-ha, I found it! It was somewhere else entirely - your suggestion helped me figure it out. Thank you @w0rp !!
