### ISSUE TITLE
Failed tests against Vim 8.2

### ISSUE THREAD

**Issue by mymedia2** [dense-analysis/ale#3411]
## Information

**VIM version**

    VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 24 2020 11:11:04)
    Included patches: 1-1895
    Compiled by vim-testbed

Operating System: Alpine Linux (in Docker)

## What went wrong

    (1/3) [EXECUTE] (X) [] should be equal to [{'lnum': 2, 'bufnr': 3, 'vcol': 0, 'pattern': '', 'valid': 1, 'nr': -1, 'type': 'E', 'col': 3, 'text': 'foo bar'}]
    (5/7) [EXECUTE] (X) Vim(let):E491: json decode error at 'x'
      > command line..function <SNR>23_vader[5]..vader#run[45]..<SNR>25_run[41]..<SNR>25_execute[2]..vader#window#execute[11]..script /tmp/vAFhjPN/772[1]..function ale#util#FuzzyJSONDecode, line 8
    (6/7) [EXECUTE] (X) Vim(let):E491: json decode error at 'x'
      > command line..function <SNR>23_vader[5]..vader#run[45]..<SNR>25_run[41]..<SNR>25_execute[2]..vader#window#execute[11]..script /tmp/vAFhjPN/773[1]..function ale#util#FuzzyJSONDecode, line 8
    (1/1) [EXECUTE] (X) [{'lnum': 1, 'bufnr': 3, 'col': 10, 'linter_name': 'testlinter', 'vcol': 0, 'nr': -1, 'type': 'W', 'text': 'Infix operators must be spaced. [Warning/space-infix-ops]', 'sign_id': 1000002}, {'lnum': 2, 'bufnr': 3, 'col': 10, 'linter_name': 'testlinter', 'vcol': 0, 'nr': -1, 'type': 'E', 'text': 'Missing semicolon. [Error/semi]', 'sign_id': 1000003}] should be equal to [{'lnum': 1, 'bufnr': 3, 'vcol': 0, 'linter_name': 'testlinter', 'nr': -1, 'sign_id': 1000001, 'type': 'W', 'col': 10, 'text': 'Infix operators must be spaced. [Warning/space-infix-ops]'}, {'lnum': 2, 'bufnr': 3, 'vcol': 0, 'linter_name': 'testlinter', 'nr': -1, 'sign_id': 1000002, 'type': 'E', 'col': 10, 'text': 'Missing semicolon. [Error/semi]'}]
    ( 1/19) [EXECUTE] (X) 1 should be equal to 0
    ( 2/19) [EXECUTE] (X) Assertion failure
    ( 3/19) [EXECUTE] (X) Assertion failure
    ( 9/19) [EXECUTE] (X) Assertion failure
    (10/19) [EXECUTE] (X) The quickfix window was opened when the list was empty
    (12/19) [EXECUTE] (X) 0 should be equal to 7
    (13/19) [EXECUTE] (X) 0 should be equal to 8
    (18/19) [EXECUTE] (X) Assertion failure
    (19/19) [EXECUTE] (X) Assertion failure
    (2/4) [EXECUTE] (X) Vim(let):E491: json decode error at 'issues":[]},{"path":"my_file_without_issues.cr",issues":[]}],"metadata":{ameba_version":"0.8.1",crystal_version":"0.26.1"},"summary":{target_sources_count":2,issues_count":0}}'
      > command line..function <SNR>23_vader[5]..vader#run[45]..<SNR>25_run[41]..<SNR>25_execute[2]..vader#window#execute[11]..script /tmp/vAFhjPN/5621[1]..function ale_linters#crystal#ameba#HandleAmebaOutput[5]..ale#util#FuzzyJSONDecode, line 8
    (3/4) [EXECUTE] (X) Vim(let):E491: json decode error at 'ameba_version":"0.8.1",crystal_version":"0.26.1"},"summary":{target_sources_count":0,issues_count":0}}'
      > command line..function <SNR>23_vader[5]..vader#run[45]..<SNR>25_run[41]..<SNR>25_execute[2]..vader#window#execute[11]..script /tmp/vAFhjPN/5624[1]..function ale_linters#crystal#ameba#HandleAmebaOutput[5]..ale#util#FuzzyJSONDecode, line 8
    (3/3) [EXECUTE] (X) Vim(let):E491: json decode error at 'No such command in 2.4.1 of ruby'
      > command line..function <SNR>23_vader[5]..vader#run[45]..<SNR>25_run[41]..<SNR>25_execute[2]..vader#window#execute[11]..script /tmp/vAFhjPN/5666[1]..function ale_linters#ruby#brakeman#Handle[2]..ale#util#FuzzyJSONDecode, line 8
    (6/9) [EXECUTE] (X) Vim(let):E491: json decode error at 'Potential difficulties:    Redeclaration of symbol '$_'    at /home/travis/perl6-error-fail/insanity-test.pl6:1    ------>  sub foo($_) {.say}; my $_<HERE> = 1; .&foo;    Space is not significant here; please use quotes or :s (:sigspace) modifier (or, to suppress this warning, omit the space, or otherwise change the spacing)    at /home/travis/perl6-error-fail/insanity-test.pl6:4    ------> /win<HERE> 3/Syntax OK'
      > command line..function <SNR>23_vader[5]..vader#run[45]..<SNR>25_run[41]..<SNR>25_execute[2]..vader#window#execute[11]..script /tmp/vAFhjPN/6218[3]..function ale_linters#perl6#perl6#Handle, line 12
    (3/3) [EXECUTE] (X) Vim(let):E491: json decode error at 'No such command in 2.4.1 of ruby'
      > command line..function <SNR>23_vader[5]..vader#run[45]..<SNR>25_run[41]..<SNR>25_execute[2]..vader#window#execute[11]..script /tmp/vAFhjPN/6408[1]..function ale_linters#ruby#rails_best_practices#Handle[3]..ale#util#FuzzyJSONDecode, line 8
    (5/5) [EXECUTE] (X) Vim(let):E491: json decode error at 'No such command in 2.4.1 of ruby'
      > command line..function <SNR>23_vader[5]..vader#run[45]..<SNR>25_run[41]..<SNR>25_execute[2]..vader#window#execute[11]..script /tmp/vAFhjPN/6432[1]..function ale_linters#ruby#reek#Handle[3]..ale#util#FuzzyJSONDecode, line 8

Full log at TravisCI: https://travis-ci.com/github/mymedia2/vim-ale/jobs/406757164

## Reproducing the bug

Add switches to run automatic tests in Vim 8.2: https://github.com/mymedia2/vim-ale/commit/1cc382aa68cafbc0bbfcfdb68d0c6c0209446d39

---

Can you please take a look? 19 tests failed against Vim 8.2.1895, some of them even crash vim-vader. The same issue appears with a little outdated vim-ale Debian package: https://ci.debian.net/data/autopkgtest/testing/amd64/v/vim-ale/7584361/log.gz

**Comment by hsanson** [comment]
This should be solved by #3561
