### ISSUE TITLE
Change the deoplete's source mark from [L] to [ale] or similar.

### ISSUE THREAD

**Issue by iddinev** [dense-analysis/ale#3415]
Although ale's doc state that the deoplete source is called 'ale' the mark that people see in the popup completion menu is '[L]'. 
Some might have difficulties matching that mark back to ale when configuring/tinkering with ale/deoplete - especially if they also use other completion sources.

Apart from that - deoplete has no (nor plans to have) functionality to list sources/source configs.
https://github.com/dense-analysis/ale/blob/557a1ed5da70cb443a8650766f4e8ea95e8c0da3/rplugin/python3/deoplete/sources/ale.py#L23

**Comment by w0rp** [comment]
Deoplete is deprecated now, so it's not worth doing further work on it.
