### ISSUE TITLE
Option to select first completion provided by ALE (without inserting)

### ISSUE THREAD

**Issue by MeTheFlea** [dense-analysis/ale#3433]
Is there a way to auto select the first option in the completion menu whenever `:ALEComplete` is used? I have `set completeopt=menu,menuone,preview,noinsert` in my `.vimrc` but every time the menu opens I have no entry selected.

I saw commit 25b572b fixed an issue with automatically inserting the completion text by forcing the selection away from the first match but after I reverted this commit locally I got exactly the behaviour I wanted (without knowing the full consequences of such a change). 

Is there a supported way of getting this same behaviour?

**Comment by w0rp** [comment]
I think this is worth doing when you request completion result manually. I added that fix to prevent a selection from being made as you type with automatic completion. We can send a different key sequence to open the completion menu when you manually request completion results, from the one we send when they are shown automatically.

**Comment by rouge8** [comment]
@MeTheFlea i think #3573 might fix this for you?

**Comment by w0rp** [comment]
@rouge8 @MeTheFlea I've pushed a commit now which only sets `noselect` in the options if you've configured Vim that way.

**Comment by rouge8** [comment]
Thanks! 🎉
