### ISSUE TITLE
can't find opencv headers

### ISSUE THREAD

**Issue by baker0611** [dense-analysis/ale#3439]
1. update ale
2. can't find opencv libs and headers
my conf:
let g:ale_cpp_gcc_options            = '-Wall -Werror -O2 -std=c++11 `pkg-config --cflags opencv --libs`'

ALEInfo:
 Current Filetype: cpp
Available Linters: ['gcc', 'ccls', 'clangcheck', 'clangd', 'clangtidy', 'clazy', 'cppcheck', 'cpplint', 'cquery', 'flawfinder']
   Linter Aliases:
'gcc' -> ['gcc', 'g++']
  Enabled Linters: ['gcc']
  Ignored Linters: []
 Suggested Fixers:
  'astyle' - Fix C/C++ with astyle.
  'clang-format' - Fix C/C++ and cuda files with clang-format.
  'clangtidy' - Fix C/C++ and ObjectiveC files with clang-tidy.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'uncrustify' - Fix C, C++, C#, ObjectiveC, ObjectiveC++, D, Java, Pawn, and VALA files with uncrustify.
 Linter Variables:

let g:ale_cpp_cc_executable = '<auto>'
let g:ale_cpp_cc_options = '-std=c++14 -Wall'
let g:ale_cpp_clang_options = '-Wall -Werror -O2 -std=c++11 `pkg-config --cflags opencv --libs`'
let g:ale_cpp_gcc_options = '-Wall -Werror -O2 -std=c++11 `pkg-config --cflags opencv --libs`'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'c': ['gcc'], 'javascript': ['eslint'], 'bash': ['shell'], 'cpp': ['gcc'], 'java': ['eclipselsp'], 'python': ['pylint']}
let g:ale_linters_explicit = 1
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '[%linter%] %s [%severity%]'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 0
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '✗'
let g:ale_sign_info = '⚡'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '✗'
let g:ale_sign_style_warning = '⚡'
let g:ale_sign_warning = '⚡'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = ['✗ %d', '⚡ %d', '✔ OK']
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  
 Command History:

(executable check - success) clang++
(finished - exit code 1) ['/bin/bash', '-c', '''clang++'' -S -x c++ -o /dev/null -iquote ''/home'' -std=c++14 -Wall - < ''/tmp/v1rJzF0/2/1.cpp''']

<<<OUTPUT STARTS>>>
<stdin>:1:10: fatal error: 'opencv2/core/core.hpp' file not found
#include <opencv2/core/core.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
<<<OUTPUT ENDS>>>

**Comment by w0rp** [comment]
I merged the `gcc` and `clang` linters into one `cc` linter for getting errors from a C/C++ compiler. Update your settings to fix this. See here: #3299
