### ISSUE TITLE
Some language servers not used if open file is not inside git repository

### ISSUE THREAD

**Issue by gregdan3** [dense-analysis/ale#3446]
## Information
**VIM version**
`vim --version | head -2`
`VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 15 2020 16:37:08)`
`Included patches: 1-1989`

**Operating System**
`uname --all`
`Linux Theros 5.9.8-arch1-1 #1 SMP PREEMPT Tue, 10 Nov 2020 22:44:11 +0000 x86_64 GNU/Linux`

## What went wrong
`clangd` and `bash-language-server` (as `language_server`) do not get started by `ale` unless the open file is inside a git repository (or, for the former, a `compile_commands.json` is in the same or a parent directory). If a relevant file is opened outside of a git repository, these completion servers are never started. Conversely, if the relevant file is opened inside a git repository, these completion servers will work.

## Reproducing the bug
1. Install the following minimal vimrc set up for use with `junegunn/vim-plug`:
[vimrc.txt](https://github.com/dense-analysis/ale/files/5575304/vimrc.txt)
2. Create a new directory and place a simple .c or .sh file into it
3. Open your file and begin typing. Observe that no completion occurs, and that the language server is not mentioned in `:ALEInfo`
4. `git init` in the same directory
5. Open the same file again and begin typing. Completion is now working, and `:ALEInfo` shows that the server was found to exist and initialized.

### :ALEInfo
[bash_wo_git.txt](https://github.com/dense-analysis/ale/files/5575308/bash_wo_git.txt)
[bash_w_git.txt](https://github.com/dense-analysis/ale/files/5575307/bash_w_git.txt)

### Other details
As noted, `bash-language-server` only appears in the former of the ALEInfo files. This issue also applies to `clangd` and `ccls`, but strangely, does not apply to `pyls`, which is also provided in my config. `clangd` can be made to work if a `compile_commands.json` is in the current directory or a parent directory, regardless of a git repository being present.

**Comment by w0rp** [comment]
This is by design. The language servers need to be launched with a root project directory, and ALE starts one executable per project. If they all start automatically with one server per file, you'll run out of memory pretty quickly.

See `:help g:ale_lsp_root` for setting project root directories manually, when they can't be detected automatically. I recommend using the `b:ale_lsp_root` option in an ftplugin file, possibly with `g:ale_pattern_options`.
