### ISSUE TITLE
Completely disable auto lint and something else

### ISSUE THREAD

**Issue by timsofteng** [dense-analysis/ale#3450]
Hello. 
1. How can i completely disable ale linting until I'll invoke `:ALELint`? Even after :ALEFix. I don't wanna see any linters errors.

2. Is it possible to disable all linter's messages and symbols when buffer was changed? So I invoke :ALELint and it show me all errors and messages. BUT when I start to change something in buffer linters should completely off. How can I do it?

Thanks

**Comment by RyannDaGreat** [comment]
I second this...I don't always want this plugin running; I only want it when I need it!

**Comment by hsanson** [comment]
Reading `:h ale-lint` I see this:

```
 ALE will check your code in the following
circumstances, which can be configured with the associated options.

* When you modify a buffer.                           - g:ale_lint_on_text_changed
* On leaving insert mode.                              - g:ale_lint_on_insert_leave
* When you open a new or modified buffer.  - g:ale_lint_on_enter
* When you save a buffer.                            - g:ale_lint_on_save
* When the filetype changes for a buffer.     - g:ale_lint_on_filetype_changed
* If ALE is used to check code manually.     - :ALELint
```

Try setting all those variables to 0 and see if ALE stops linting until ALELint is invoked manually.  If this is not the case then something must be wrong according to documentation.

**Comment by w0rp** [comment]
This question was answered. You can also use the `:ALEToggle` and `:ALEToggleBuffer` commands to turn off ALE linting temporarily.
