### ISSUE TITLE
Add support for PyLance

### ISSUE THREAD

**Issue by hsanson** [dense-analysis/ale#3456]
**Name:** PyLance
**URL:** https://github.com/microsoft/pylance-release

The python-language-server (pyls) keeps CPU usage on the sky even for a single python file. See the amount of [high CPU issues](https://github.com/microsoft/python-language-server/issues?q=high+CPU) reported in Github.

Pylance is a newer, better, and more efficient python language server that hopefully does not make our machines sound like jet-engines.

  - https://github.com/microsoft/python-language-server/issues/2100#issuecomment-654955055
  - https://devblogs.microsoft.com/python/announcing-pylance-fast-feature-rich-language-support-for-python-in-visual-studio-code/
  - https://github.com/microsoft/pylance-release

Note:  Pylance is not opensource and so far I have been unable to find ways to install it without visual code extensions.

**Comment by blayz3r** [comment]
Why not Pyright

**Comment by hsanson** [comment]
After more investigation seems pylance uses pyright behind the scenes and ALE already supports this. PyLance is a visual studio only plugin that implements the language server protocol.

I think using pyright directly is best for ALE so closing this issue.
