### ISSUE TITLE
show only errors?

### ISSUE THREAD

**Issue by ExpandingMan** [dense-analysis/ale#3465]
Is there currently a way to only display a minimal warning level?  I'd like to hide all warnings and show only errors.  Reading through `:help ale-options` I cannot find a way to do this.

**Comment by davidatbu** [comment]
I think `g:ale_lsp_show_message_severity` is what you're looking for.

**Comment by w0rp** [comment]
I don't like turning off problems in ALE. It should be done in configuration of the tool ALE uses.

**Comment by WhiteBlackGoose** [comment]
Hi. I found this accidentally, but it would really be nice to have it. It's all inconsistent and different in tools - whereas it could be one interface. Of course, as you decide

**Comment by w0rp** [comment]
My position for years is that developers shouldn't bury warnings or errors in their editors. Everyone in a team should see the same information and address warnings and errors. It also saves me effort maintaining code for filters when the tools do it better.

**Comment by WhiteBlackGoose** [comment]
Absolutely. It's just that I was making single function tiny program which does nothing but proves/disproves my theory, so I didn't like being spammed with warnings (disabling which is less trivial)
