### ISSUE TITLE
Fortran language server is not starting up

### ISSUE THREAD

**Issue by zoj613** [dense-analysis/ale#3483]
## Information

**VIM version**

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 15 2020 16:37:08)
Included patches: 1-1989

Operating System: Manjaro Linux 20.2

## What went wrong
Whenever I open a fortran source file, the language server does not start, only gcc linter seems to work. I tried installing fortran language server as a system-wide package and also as a pip installation on a virtual environment. It still doesn't start. There is no message at all about it when I use `ALEInfo`. Even if I turn off the `gcc` lilnter, it still wont work.

## Reproducing the bug
opening a fortran source file with the .f90 extension?

### :ALEInfo
```
 Current Filetype: fortran
Available Linters: ['gcc', 'language_server']
  Enabled Linters: ['gcc', 'language_server']
  Ignored Linters: []
 Suggested Fixers:
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_fortran_gcc_executable = 'gcc'
let g:ale_fortran_gcc_options = '-Wall'
let g:ale_fortran_gcc_use_free_form = 1
let g:ale_fortran_language_server_executable = 'fortls --lowercase_intrinsics --max_line_length=80'
let g:ale_fortran_language_server_use_global = 1
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 25
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'r': ['styler'], 'c': ['clang-format', 'clangtidy'], 'sh': ['shfmt'], '*': ['remove_trailing_lines
', 'trim_whitespace'], 'python': ['add_blank_lines_for_python_control_statements', 'black', 'reorder-python-imports']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'vim': ['ale_custom_linting_rules', 'vimls'], 'r': ['languageserver', 'lintr'], 'c': ['cc', 'clan
gd', 'clangtidy'], 'sh': ['language_server'], 'fortran': ['language_server', 'gcc'], 'python': ['pyls', 'flake8', 'myp
y']}
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) gcc
(finished - exit code 0) ['/bin/bash', '-c', '''gcc'' -S -x f95 -fsyntax-only -ffree-form -Wall - < ''/tmp/v9r154o/0/e
x_time.f90''']

<<<NO OUTPUT RETURNED>>>
```

**Comment by zoj613** [comment]
It seems that fortls only works if I specify a .fortls JSON file in the root of the project. Is this normal behavior? I think it is a bug because without a .fortls file the language server should just work and use global settings.

**Comment by zoj613** [comment]
What are your thoughts @unpairedbracket ?

**Comment by unpairedbracket** [comment]
It's been a long time since I've worked on this, but I'll try to figure out what's going on

**Comment by zoj613** [comment]
> It's been a long time since I've worked on this, but I'll try to figure out what's going on

That would be much appreciated. Let me know if there is anyway I can help.

**Comment by unpairedbracket** [comment]
Sorry this has taken an unreasonably long time to look into. It looks like the need for the `.fortls` file to signify the project root is intentional and was based on the similar behaviour of some other language server plugins (in particular the Rust `rls` which I used for reference looks for `cargo.toml`, several languages look for either some language-specific config file or a `.git` folder). It can be made to run just using pwd as the project root, but I'm not sure if this hasn't been done in most other language servers because it might have undesirable side-effects. Maybe @w0rp would know more about it?

**Comment by zoj613** [comment]
> Sorry this has taken an unreasonably long time to look into. It looks like the need for the `.fortls` file to signify the project root is intentional and was based on the similar behaviour of some other language server plugins (in particular the Rust `rls` which I used for reference looks for `cargo.toml`, several languages look for either some language-specific config file or a `.git` folder). It can be made to run just using pwd as the project root, but I'm not sure if this hasn't been done in most other language servers because it might have undesirable side-effects. Maybe @w0rp would know more about it?

Thanks for the feedback. Python and C language servers that I used do not necessarily need a config file. This is important when writing a script to run once-off, where setting up a config would be overkill.
