### ISSUE TITLE
Highlighting error with Python

### ISSUE THREAD

**Issue by kitmonisit** [dense-analysis/ale#3487]
## Information

**VIM version**

    VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec  3 2020 01:11:23)
    macOS version

Operating System: MacOS 10.15.7

## What went wrong

Highlighting of errors is painful to the eyes. I thought this was intentional. However, when I switch color schemes and then back to the previous color scheme, the bad highlighting goes away, and all I have left is the marker in the `signcolumn`.

## Reproducing the bug

1. Open a Python file with linting errors.
2. Then this happened.
![image](https://user-images.githubusercontent.com/1175380/102016314-3f877800-3d9b-11eb-9991-cfafebf28c92.png)

3. Try switching color schemes then back to the previous color scheme

       :color darkblue

        
    ![image](https://user-images.githubusercontent.com/1175380/102016374-92f9c600-3d9b-11eb-87a3-e0fcdab2a4fd.png)

       :color base16-default-dark

    All is well at this point.  
    ![image](https://user-images.githubusercontent.com/1175380/102016395-b02e9480-3d9b-11eb-9bdf-c72745a82474.png)

4. Even if I start with a different color scheme (even the default that comes with vim), the bad highlighting still happens. I could fix it away by doing the color scheme switcheroo.

### :ALEInfo

```
 Current Filetype: python
Available Linters: ['bandit', 'flake8', 'jedils', 'mypy', 'prospector', 'pycodestyle', 'pydocstyle', 'pyflakes', 'pylama', 'pylint', 'pyls', 'pyre', 'pyright', 'vulture']
  Enabled Linters: ['pyls']
  Ignored Linters: []
 Suggested Fixers: 
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autoimport' - Fix import issues with autoimport.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'reorder-python-imports' - Sort Python imports with reorder-python-imports.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:

let g:ale_python_auto_pipenv = 0
let g:ale_python_pyls_auto_pipenv = 0
let g:ale_python_pyls_config = {}
let g:ale_python_pyls_executable = 'pyls'
let g:ale_python_pyls_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'python': ['black']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'python': ['pyls']}
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) pyls
(started) ['/usr/local/bin/zsh', '-c', '''pyls''']

```

**Comment by kitmonisit** [comment]
Related #3468

**Comment by hsanson** [comment]
ALE uses the whatever the colorscheme sets for SpellBad and SpellCap hightligth groups. You can run this command to check your hightlight configuration:

```
 :so $VIMRUNTIME/syntax/hitest.vim
```

Look for SpellCap and SpellBad to see how the colorscheme should show them. In my case they look like this:

![image](https://user-images.githubusercontent.com/900716/103046231-d5f14000-45ca-11eb-9bc2-8f807b27133d.png)


The ALEError and ALEWarning hightlights are linked to these two. To fix the problem you can change the hightlight configuration of SpellCap, SpellBad that affects the color scheme for everything or change the highlight configuration of ALEError and ALEWarning that will change it only for ALE.

Use the :hi command to do the changes.

**Comment by davidatbu** [comment]
@kitmonisit , does @hsanson 's suggestion make sense? If not, could you ask further questions, and if so, could you close the issue? This repo has a LOT of issues and not enough man power, it would be good to clean up as many as possible to w0rp (the dev) has less things to worry about.

**Comment by kitmonisit** [comment]
Hi @davidatbu, my apologies, I was not on my computer for a few days. Thanks for the tip @hsanson.

Indeed, SpellCap and SpellBad look ugly for me:
![image](https://user-images.githubusercontent.com/1175380/103332681-f2e3b280-4aa5-11eb-9876-5716e06b92f8.png)

Just for completeness' sake, here are ALEError and ALEWarning:
![image](https://user-images.githubusercontent.com/1175380/103332727-1eff3380-4aa6-11eb-8bd0-6851f6f9e493.png)

Digging further, `:verbose highlight` gives me the following:
![image](https://user-images.githubusercontent.com/1175380/103332951-fdeb1280-4aa6-11eb-98fc-84d9a87e29cd.png)
![image](https://user-images.githubusercontent.com/1175380/103332964-08a5a780-4aa7-11eb-952a-5787bafff351.png)

It looks like base16-vim has some aesthetics fixes going for it.

For me a quick good-looking fix goes like this:

    :highlight SpellCap ctermbg=NONE

It appears to me that base16-vim is the culprit. What's your colorscheme? I could try that out.
