### ISSUE TITLE
Help ALE doesn't appear to be doing anything

### ISSUE THREAD

**Issue by LukeAI** [dense-analysis/ale#3488]
I open a python file, add some mistakes and nonsense - no error highlighting happens and no autocomplete is offered.

:ALEInfo suggests that several linters are enabled:

```
 Current Filetype: python
Available Linters: ['bandit', 'flake8', 'jedils', 'mypy', 'prospector', 'pycodestyle', 'pydocstyle', 'pyflakes', 'pylama', 'pylint', 'pyls', 'pyre', 'pyright', 'vulture']
  Enabled Linters: ['flake8', 'mypy', 'pylint', 'pyright']
  Ignored Linters: []
 Suggested Fixers:
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autoimport' - Fix import issues with autoimport.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'reorder-python-imports' - Sort Python imports with reorder-python-imports.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:
```
why is nothing happening?

**Comment by ikwyl6** [comment]
Try running one of the linters on the command line against your file and see what it outputs.

**Comment by hsanson** [comment]
Provide the full output of ALEInfo, it should show if the tools are being found and what is the output when executed. Something like this:

```
  Command History:
(executable check - failure) pyright-langserver
(executable check - failure) pyright-langserver
(finished - exit code 0) ['/bin/bash', '-c', '''pylint'' --version']
<<<OUTPUT STARTS>>>
pylint 2.6.0
astroid 2.4.2
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0]
<<<OUTPUT ENDS>>>
(executable check - success) flake8
(finished - exit code 0) ['/bin/bash', '-c', '''flake8'' --version']
<<<OUTPUT STARTS>>>
3.8.3 (mccabe: 0.6.1, pycodestyle: 2.6.0, pyflakes: 2.2.0) CPython 3.8.5 on
Linux
<<<OUTPUT ENDS>>>
(executable check - success) pylint
(finished - exit code 30) ['/bin/bash', '-c', 'cd ''/home/Research/Source/icu_rnn'' && ''pylint'' --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n --from-st
din ''/home/Research/Source/icu_rnn/lib.py'' < ''/tmp/nvimtduZU7/2/lib.py''']
<<<OUTPUT STARTS>>>
************* Module lib
lib.py:1:0: C0114 (missing-module-docstring) Missing module docstring
lib.py:1:0: E0401 (import-error) Unable to import 'numpy'
lib.py:2:0: E0401 (import-error) Unable to import 'theano'
lib.py:3:0: E0401 (import-error) Unable to import 'theano.tensor'
lib.py:4:0: E0401 (import-error) Unable to import 'theano.ifelse'
lib.py:14:13: E0602 (undefined-variable) Undefined variable 'xrange'
```

**Comment by LukeAI** [comment]
hey both, thanks for reply! I simply hadn't installed the underlying tools. I didn't realise that ALE worked like that. thanks anyway

**Comment by githorse** [comment]
I came here with the same issue -- now I get it! An "available" and "enabled" linter is not necessarily actually installed on my system. I think we're violating the Principle of Least Surprise here; if something's both "available" and "enabled" it's pretty natural to assume it exists.

What if we add an additional line to the ALEInfo output called "Installed Linters", and/or renamed "Available Linters" to "Possible Linters", "Known Linters", or something less confusing?

```
Current Filetype: python
Known Linters: ['bandit', 'flake8', 'jedils', 'mypy', ...]
Installed Linters: ['flake8']
Enabled Linters: ['bandit']
Ignored Linters: []
```

In the above, it's still kind of confusing that `bandit` is enabled but not installed, but it's much clearer than the current output. 

For further clarity, we could possibly:
* add more categories to further clarify what's going on (e.g. `Enabled but Unavailable Linters: [...]`)
* append an indicator showing that an enabled linter is not installed (e.g, `['bandit'✘, 'mypy']`)
* throw a warning or even an error if an enabled linter is not installed

**Comment by githorse** [comment]
I'm now reading this statement from the [pyright repo](https://github.com/Microsoft/pyright):

> Alternatively, ALE will automatically check your code with Pyright, without requiring any additional configuration.

This does not seem to be the case for me -- I have to install `pyright` first before anything happens. Perhaps the folks at pyright are also thrown off by pyright being "available" and "enabled" by default? Or perhaps I'm egregiously misunderstanding something here.
