### ISSUE TITLE
How to disable all warnings

### ISSUE THREAD

**Issue by benzanol** [dense-analysis/ale#3503]
99% of the warnings that show up are completely unnecessary for me, and they also interfere with plugins like vimspector that also use the sign column. Is there any way to disable all warnings and only show errors, similar to how `let g:syntastic_quiet_messages = { "level": "warnings" }` works in syntastic?

**Comment by davidatbu** [comment]
If you're using an LSP linter, `g:ale_lsp_show_message_severity` is exactly what you're looking for.

**Comment by AdamTillou** [comment]
Looking at the documentation, it looks like the default minimum severity is errors, yet warnings still show up. I even tried setting it to disabled to see if that would work but both errors and warnings still show up. Is it possible I am not using an LSP linter, and how do I check that? I am using python with all of the default ALE settings.

**Comment by davidatbu** [comment]
Hmm. I just tried out the flag, and it's not working for me either. (Using `pyright` to lint python). So I think this issue should be turned into a bug report.

FYI, I said "LSP linter" to differentiate ale linters that conform to the Language Server Protocol (LSP), versus ones that do not. For python, AFAIK, pyright and pyls are the only current LSP linters supported by ALE. 

This doesn't tell you if the current linter(s) are LSP linters, but you can see which linters are currently being run by typing in `:ALEInfo`, which shows a detailed log.

**Comment by w0rp** [comment]
I don't like turning off problems in ALE. It should be done in configuration of the tool ALE uses.
