### ISSUE TITLE
ALE fix causes jump

### ISSUE THREAD

**Issue by basharh** [dense-analysis/ale#3504]
## Information

**VIM version**

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec  3 2020 01:24:40)
macOS version

macOS Big Sur version 11.0.1 

## What went wrong

- running with `g:ale_fix_on_save=1` and saving a file with errors causes VIM/ALE to jump in the file after those errors are fixed

## Reproducing the bug

1. Run with `g:ale_fix_on_save=1`
2. introduce an error that a linter(eg prettier) can fix(eg, missing trailing semicolon).
3. navigate to the line that contains the error and press `zt` to make sure it's at the first line
4. save and notice that line jumps to the middle. Behavior is inconsistent.

### :ALEInfo

 Current Filetype: typescriptreact
Available Linters: ['eslint', 'standard', 'tslint', 'tsserver', 'typecheck', 'xo']
  Enabled Linters: ['eslint', 'tsserver']
  Ignored Linters: []
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'typescript': ['eslint', 'prettier'], 'json': ['prettier'], 'typescriptreact': ['eslint', 'prettier'], 'java': ['google_java_format'], 'javascript': ['eslint']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = -1
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'typescript': ['tsserver', 'eslint'], 'typescriptreact': ['tsserver', 'eslint'], 'javascript': ['eslint']}
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) /Users/bashar/work/projects/smpi/node_modules/eslint/bin/eslint.js
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/bashar/work/projects/smpi'' && ''/Users/bashar/work/projects/smpi/node_modules/eslint/bin/eslint.js'' -f json --stdin --stdin-filename ''/Users/bashar/work/projects/smpi/src/pages/index.tsx'' < ''/var/folders/6y/n_x952j55h92tpxs3t19m8880000gn/T/vextAaJ/3/index.tsx''']

<<<OUTPUT STARTS>>>
[{"filePath":"/Users/bashar/work/projects/smpi/src/pages/index.tsx","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]}]
<<<OUTPUT ENDS>>>

(executable check - success) /Users/bashar/work/projects/smpi/node_modules/.bin/tsserver
(started) ['/bin/zsh', '-c', '''/Users/bashar/work/projects/smpi/node_modules/.bin/tsserver''']
(finished - exit code 1) ['/bin/zsh', '-c', 'cd ''/Users/bashar/work/projects/smpi'' && ''/Users/bashar/work/projects/smpi/node_modules/eslint/bin/eslint.js'' -f json --stdin --stdin-filename ''/Users/bashar/work/projects/smpi/src/pages/index.tsx'' < ''/var/folders/6y/n_x952j55h92tpxs3t19m8880000gn/T/vextAaJ/4/index.tsx''']

<<<OUTPUT STARTS>>>
[{"filePath":"/Users/bashar/work/projects/smpi/src/pages/index.tsx","messages":[{"ruleId":"prettier/prettier","severity":2,"message":"Insert `;`","line":42,"column":25,"nodeType":null,"endLine":42,"endColumn":25,"fix":{"range":[1158,1158],"text":";"}}],"errorCount":1,"warningCount":0,"fixableErrorCount":1,"fixableWarningCount":0,"source":"import React from \"react\";\nimport Layout from \"../components/layout/\";\nimport Banner from \"../components/index/banner/\";\nimport SectionPreview from \"../components/index/section-preview/\";\nimport SEO from \"../components/seo\";\n\nconst description = {\n  performance: `Learn more about the performing arms of SMPI: Takht al-Nagham and Raqs\nal-Samah.  Get updates on upcoming events`,\n  preservation: `Learn more about the performing arms of SMPI: Takht al-Nagham and Raqs\nal-Samah.  Get updates on upcoming events`,\n  education: `Learn more: the SMPI is a hub for Arabic music education, references, and workshops`,\n};\n\nconst Sections: React.FC = () => (\n  <div>\n    <SectionPreview\n      title=\"Performance\"\n      description={description[\"performance\"]}\n    />\n    <SectionPreview\n      title=\"Preservation\"\n      description={description[\"preservation\"]}\n      reversed={true}\n    />\n    <SectionPreview\n      title=\"Education\"\n      description={description[\"education\"]}\n      reversed={false}\n    />\n  </div>\n);\n\nconst IndexPage: React.FC = () => (\n  <Layout>\n    <SEO title=\"Home\" />\n    <Banner />\n    <Sections />\n  </Layout>\n);\n\nexport default IndexPage\n","usedDeprecatedRules":[]}]
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/zsh', '-c', '''/Users/bashar/work/projects/smpi/node_modules/eslint/bin/eslint.js'' --version']

<<<OUTPUT STARTS>>>
v7.15.0
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/bashar/work/projects/smpi'' && ''/Users/bashar/work/projects/smpi/node_modules/eslint/bin/eslint.js'' --stdin-filename ''/Users/bashar/work/projects/smpi/src/pages/index.tsx'' --stdin --fix-dry-run --format=json < ''/var/folders/6y/n_x952j55h92tpxs3t19m8880000gn/T/vextAaJ/5/index.tsx''']
(finished - exit code 0) ['/bin/zsh', '-c', '''/Users/bashar/work/projects/smpi/node_modules/.bin/prettier'' --version']

<<<OUTPUT STARTS>>>
2.2.1
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/bashar/work/projects/smpi'' && ''/Users/bashar/work/projects/smpi/node_modules/.bin/prettier'' --stdin-filepath ''/Users/bashar/work/projects/smpi/src/pages/index.tsx'' --stdin < ''/var/folders/6y/n_x952j55h92tpxs3t19m8880000gn/T/vextAaJ/6/index.tsx''']
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/bashar/work/projects/smpi'' && ''/Users/bashar/work/projects/smpi/node_modules/eslint/bin/eslint.js'' -f json --stdin --stdin-filename ''/Users/bashar/work/projects/smpi/src/pages/index.tsx'' < ''/var/folders/6y/n_x952j55h92tpxs3t19m8880000gn/T/vextAaJ/7/index.tsx''']

<<<OUTPUT STARTS>>>
[{"filePath":"/Users/bashar/work/projects/smpi/src/pages/index.tsx","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]}]
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/bashar/work/projects/smpi'' && ''/Users/bashar/work/projects/smpi/node_modules/eslint/bin/eslint.js'' -f json --stdin --stdin-filename ''/Users/bashar/work/projects/smpi/src/pages/index.tsx'' < ''/var/folders/6y/n_x952j55h92tpxs3t19m8880000gn/T/vextAaJ/8/index.tsx''']

<<<OUTPUT STARTS>>>
[{"filePath":"/Users/bashar/work/projects/smpi/src/pages/index.tsx","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]}]
<<<OUTPUT ENDS>>>

**Comment by possibilities** [comment]
I believe I'm experiencing the same thing. On save I see a visual jump. Sometimes after this I am left with the line where the curor is pushed down to the bottom of off the bottom of the screen. Lastly when I undo my cursor moves to the top of the screen.

**Comment by grosscr** [comment]
I'm experiencing the same things as possibilities is, with the undo jumping the cursor to the top of the screen and everything.

**Comment by karloskar** [comment]
I'm having the same issue and did some digging. For me b8aaff2cf77883702374aee28f088b8a64c3b492 is the commit that breaks the positioning. It also affect folds. As in: after ALEFix, the fold surrounding the cursor position is folded.

Running NVIM v0.5.0-dev.

**Comment by sbmueller** [comment]
Same here. I experience a jump but more obviously fold collapsing every time I save + fix.

**Comment by hsanson** [comment]
@basharh @possibilities @grosscr @karloskar @sbmueller PR #3535 reverts the commits that caused the undesired jumps. Please check if the jumps and undo issues are fixed now.

**Comment by karloskar** [comment]
They are fixed for me. Thanks!

**Comment by grosscr** [comment]
Same. Thanks!

**Comment by basharh** [comment]
Same here. Thank you!

**Comment by possibilities** [comment]
Thank you!
