### ISSUE TITLE
Setting `g:ale_linters` overrides the default linters instead of merging them.

### ISSUE THREAD

**Issue by itaranto** [dense-analysis/ale#3510]
## Information

**VIM version**

NVIM v0.4.4
Build type: Release

**Operating System**

Arch Linux

## What went wrong

Setting `g:ale_linters` overrides the default linters instead of merging them.

## Reproducing the bug

1. Add the following config:
```
let g:ale_linters = {
\ 'go': ['gopls'],
\}
```
Expected:
The enabled linters should be `['gofmt', 'golint', 'go vet', 'gopls']`.

Actual:
The enabled linters are `['gopls']`.

### :ALEInfo

```
 Current Filetype: go
Available Linters: ['bingo', 'gobuild', 'gofmt', 'golangci-lint', 'golint', 'gometalinter', 'gopls', 'gosimple', 'gotype', 'govet', 'golangserver', 'revive', 'staticcheck']
   Linter Aliases:
'gobuild' -> ['go build']
'govet' -> ['go vet']
  Enabled Linters: ['gopls']
  Ignored Linters: []
 Suggested Fixers: 
  'gofmt' - Fix Go files with go fmt.
  'goimports' - Fix Go files imports with goimports.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_go_go_executable = 'go'
let g:ale_go_golangci_lint_executable = 'golangci-lint'
let g:ale_go_golangci_lint_options = '--enable-all'
let g:ale_go_golangci_lint_package = 0
let g:ale_go_gopls_executable = 'gopls'
let g:ale_go_gopls_options = '--mode stdio'
let g:ale_go_langserver_executable = 'go-langserver'
let g:ale_go_langserver_options = ''
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 0
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = v:null
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'*': ['remove_trailing_lines', 'trim_whitespace'], 'javascript': ['eslint']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'go': ['gopls']}
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {}
let g:ale_list_vertical = v:null
let g:ale_list_window_size = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_sign_highlight_linenrs = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 1
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) gopls
(started) ['sh', '-c', '''gopls'' --mode stdio']
```

**Comment by kevinclark** [comment]
Pretty sure you can accomplish what you're trying to do with: `add(g:ale_linters.go, 'gopls')`. Does that cover it? You can do more than one with: `extend(g:ale_linters.go, ['gopls', 'some-other-linter'])`.

You're doing VimL assignment, so it's not clear to me what you'd like the plugin to do about it? I guess there could be an alternative API for adding new linters, but I think that'd just be a wrapper around add.

**Comment by itaranto** [comment]
> Pretty sure you can accomplish what you're trying to do with: `add(g:ale_linters.go, 'gopls')`. Does that cover it? You can do more than one with: `extend(g:ale_linters.go, ['gopls', 'some-other-linter'])`.

Got it. Thanks.

> You're doing VimL assignment, so it's not clear to me what you'd like the plugin to do about it? I guess there could be an alternative API for adding new linters, but I think that'd just be a wrapper around add.

According to the [docs](https://github.com/dense-analysis/ale/blob/master/doc/ale.txt#L1517) it should  merge the `g:ale_linters` dictionary with the default one if `g:ale_linters_explicit` is set to 0, which is the default.

**Comment by kevinclark** [comment]
Ahhh, I missed the conflict with the docs, thanks for pointing it out.

**Comment by kevinclark** [comment]
So, I worked up a patch that 'fixes' this, but a number of other tests fail because they assume the existing behavior. I don't know whether fixing it to be correct re: the docs or to maintain existing behavior is more important to the project. I'm going to fix the associated failures and see what happens.

/cc @w0rp

**Comment by w0rp** [comment]
This is the expected behaviour. Setting `'language': ['linter-name']` means only `linter-name` will run for `language`. The setting is for selecting which linters should run. `g:ale_linters_explicit` runs nothing by default if set to `1`. (As if all were set to `[]`.)

**Comment by w0rp** [comment]
I recommend using `b:ale_linters = ['gopls', 'gofmt']` or whatever things you want in `ftplugin/go.vim`. That is used instead of whatever is in `g:ale_linters` or the default List of linters for Go.
