### ISSUE TITLE
Is there a way to print, on CMD, the linter and the fixer that is active?

### ISSUE THREAD

**Issue by hrqmonteiro** [dense-analysis/ale#3511]
I want to know if there is a way to print something using `:echo` that list the current active linter and/or printer

Also, if there's a way to `echo` if there are currently errors waiting to be fixed.

Just a general curiosity. Is it possible?

**Comment by davidatbu** [comment]
`ALEInfo` will print out a detailed list of settings, including the currently activated linters. It also shows the commands being run to lint and fix, so you can see which fixers are active there.

> Also, if there's a way to echo if there are currently errors waiting to be fixed.

Not sure what you mean here, but the following section from the ALE docs should be helpful.

https://github.com/dense-analysis/ale/blob/c69d696e1b63c7797e8696f923856d131f02f5e9/doc/ale.txt#L119-L130

**Comment by hrqmonteiro** [comment]
The ALEInfo tool i was aware about, but it prints a whole bunch of information, including all the variables, like `let g:ale_linters`, `let g:ale_set_signs`, i meant if there was a way to echo just the enabled linter or fixer of something, cause i was creating a Vimscript function to make something for my statusline.

But i guess i could pipe `grep` or `awk` to the ALEInfo and print what i wanted, right?

**Comment by davidatbu** [comment]
The approach I would personally take is to look at the source code for ALE and see which function gives me the output I want, I'd bet what you want is already there.

Also, you might wanna have a look at the [Vim-airline integration](https://github.com/vim-airline/vim-airline/blob/master/autoload/airline/extensions/ale.vim). AFAIK, it shows the number of warnings and errors, as well as if a linter is currently being run for the buffer.
