### ISSUE TITLE
JSON Decode Error when saving file with debug set to true for @babel/preset-env preset in babel.config

### ISSUE THREAD

**Issue by Wongmat** [dense-analysis/ale#3514]
## Information

**VIM version**

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 31 2020 06:25:27)
macOS version - x86_64

Operating System: MacOS Catalina Version 10.15.7 

## What went wrong

Lately, when setting `debug` to true for `@babel/preset-env` under the presets for my `babel.config.js` I've been getting this error every time I've gone to save a file. I have `ale_fix_on_save` enabled:

``Error detected while processing function <SNR>118_VimCloseCallback[11]..<SNR>118_VimExitCallback[22]..function <SNR>118_VimCloseCallback[11]..<SNR>118_VimExitCallback[15]..<lambda>31[1]
..<SNR>114_ExitCallback[28]..<SNR>161_HandleExit[19]..ale#fixers#eslint#ProcessFixDryRunOutput[1]..ale#util#FuzzyJSONDecode:``

``line 8:
E491: json decode error at '@babel/preset-env: `DEBUG` optionUsing targets:{  "android": "86",  "chrome": "86",  "edge": "86",  "firefox": "83",  "ie": "11",  "ios": "13.4",  "opera": "
71",  "safari": "13.1",  "samsung": "12"}Using modules transform: cjsUsing plugins:  proposal-numeric-separator { "ie":"11" }  proposal-logical-assignment-operators { "edge":"86", "ie":
"11", "ios":"13.4", "opera":"71", "safari":"13.1", "samsung":"12" }  proposal-nullish-coalescing-operator { "ie":"11", "samsung":"12" }  proposal-optional-chaining { "ie":"11", "samsung
":"12" }  proposal-json-strings { "ie":"11" }  proposal-optional-catch-binding { "ie":"11" }  transform-parameters { "ie":"11" }  proposal-async-generator-functions { "ie":"11" }  propo
sal-object-rest-spread { "ie":"11" }  transform-dotall-regex { "ie":"11" }  proposal-unicode-property-regex { "ie":"11" }  transform-named-capturing-groups-regex { "ie":"11" }  transform-async-to-generator { "ie":"11" }  transform-exponentiation-operator { "ie":"11" }  transform-temp``

``Error detected while processing function <SNR>118_VimCloseCallback:
line   11:
E171: Missing :endif``

Here's what my `babel.config.js` looks like:
`module.exports = {
  presets: [
    ['@babel/preset-env', {
      modules: 'cjs',
      targets: {
        ie: 11,
        browsers: 'last 2 versions'
      },
      useBuiltIns: 'entry',
      corejs: '3',
      debug: true
    }],
    ['@babel/preset-react', {
      development: true
    }]
  ],
  plugins: [
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-object-rest-spread'
  ]
};`

Setting `debug` to false does indeed fix this issue. After searching around and finding no answers, I believe this issue is related to ALE. If it is related to Babel or my own setup then I apologize and hope someone could give me some tips on how to fix it!

## Reproducing the bug

1. Use the `@babel/preset-env` preset in your `babel.config.js` and set the `debug` option to true
2. Open a `.js` file within the project and save the file with `ale_fix_on_save` enabled.

### :ALEInfo
 Current Filetype: javascript
Available Linters: ['eslint', 'fecs', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint', 'flow-language-server']
  Ignored Linters: []
 Suggested Fixers: 
  'eslint' - Apply eslint --fix to a file.
  'fecs' - Apply fecs format to a file.
  'importjs' - automatic imports for javascript
  'prettier' - Apply prettier to a file.
  'prettier_eslint', 'prettier-eslint' - Apply prettier-eslint to a file.
  'prettier_standard', 'prettier-standard' - Apply prettier-standard to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'standard' - Fix JavaScript files using standard --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'xo' - Fix JavaScript/TypeScript files using xo --fix.
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_importjs_executable = 'importjs'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'json': ['fixjson'], 'javascript': ['eslint', 'importjs'], 'css': ['prettier'], 'python': ['autopep8', 'isort']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'vim': ['ale_custom_linting_rules'], 'terraform': ['tflint'], 'json': ['jsonlint'], 'javascript': ['eslint', 'flow-language-server'], 'css': ['csslint'], 'python': ['flake8', 'pycodestyle']}
let g:ale_linters_explicit = 1
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '❌'
let g:ale_sign_info = '⚠️'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '❌'
let g:ale_sign_style_warning = '⚠️'
let g:ale_sign_warning = '⚠️'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) /Users/wongm/DJRepos/project/node_modules/eslint/bin/eslint.js
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/wongm/DJRepos/project'' && ''/Users/wongm/DJRepos/project/node_modules/eslint/bin/eslint.js'' -f json --stdin --stdin-filename ''/Users/wongm/DJRepos/project/babel.config.js'' < ''/var/folders/0q/3hxy33qs1m93xl32bg2lxnp40000gq/T/v7h6ZXl/7/babel.config.js''']

<<<OUTPUT STARTS>>>
@babel/preset-env: `DEBUG` option

Using targets:
{
  "android": "86",
  "chrome": "86",
  "edge": "86",
  "firefox": "83",
  "ie": "11",
  "ios": "13.4",
  "opera": "71",
  "safari": "13.1",
  "samsung": "12"
}

Using modules transform: cjs

Using plugins:
  proposal-numeric-separator { "ie":"11" }
  proposal-logical-assignment-operators { "edge":"86", "ie":"11", "ios":"13.4", "opera":"71", "safari":"13.1", "samsung":"12" }
  proposal-nullish-coalescing-operator { "ie":"11", "samsung":"12" }
  proposal-optional-chaining { "ie":"11", "samsung":"12" }
  proposal-json-strings { "ie":"11" }
  proposal-optional-catch-binding { "ie":"11" }
  transform-parameters { "ie":"11" }
  proposal-async-generator-functions { "ie":"11" }
  proposal-object-rest-spread { "ie":"11" }
  transform-dotall-regex { "ie":"11" }
  proposal-unicode-property-regex { "ie":"11" }
  transform-named-capturing-groups-regex { "ie":"11" }
  transform-async-to-generator { "ie":"11" }
  transform-exponentiation-operator { "ie":"11" }
  transform-template-literals { "ie":"11" }
  transform-literals { "ie":"11" }
  transform-function-name { "ie":"11" }
  transform-arrow-functions { "ie":"11" }
  transform-classes { "ie":"11" }
  transform-object-super { "ie":"11" }
  transform-shorthand-properties { "ie":"11" }
  transform-duplicate-keys { "ie":"11" }
  transform-computed-properties { "ie":"11" }
  transform-for-of { "ie":"11" }
  transform-sticky-regex { "ie":"11" }
  transform-unicode-escapes { "ie":"11" }
  transform-unicode-regex { "ie":"11" }
  transform-spread { "ie":"11" }
  transform-destructuring { "ie":"11" }
  transform-block-scoping { "ie":"11" }
  transform-typeof-symbol { "ie":"11" }
  transform-new-target { "ie":"11" }
  transform-regenerator { "ie":"11" }
  proposal-export-namespace-from { "ie":"11", "ios":"13.4", "safari":"13.1" }
  transform-modules-commonjs { "android":"86", "chrome":"86", "edge":"86", "firefox":"83", "ie":"11", "ios":"13.4", "opera":"71", "safari":"13.1", "samsung":"12" }
  proposal-dynamic-import { "android":"86", "chrome":"86", "edge":"86", "firefox":"83", "ie":"11", "ios":"13.4", "opera":"71", "safari":"13.1", "samsung":"12" }

Using polyfills with `entry` option:
[{"filePath":"/Users/wongm/DJRepos/project/babel.config.js","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]}]
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/zsh', '-c', '''/Users/wongm/DJRepos/project/node_modules/eslint/bin/eslint.js'' --version']

<<<OUTPUT STARTS>>>
v7.7.0
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/wongm/DJRepos/project'' && ''/Users/wongm/DJRepos/project/node_modules/eslint/bin/eslint.js'' --stdin-filename ''/Users/wongm/DJRepos/project/babel.config.js'' --stdin --fix-dry-run --format=json < ''/var/folders/0q/3hxy33qs1m93xl32bg2lxnp40000gq/T/v7h6ZXl/8/babel.config.js''']
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/wongm/DJRepos/project'' && ''/Users/wongm/DJRepos/project/node_modules/eslint/bin/eslint.js'' -f json --stdin --stdin-filename ''/Users/wongm/DJRepos/project/babel.config.js'' < ''/var/folders/0q/3hxy33qs1m93xl32bg2lxnp40000gq/T/v7h6ZXl/9/babel.config.js''']

<<<OUTPUT STARTS>>>
[{"filePath":"/Users/wongm/DJRepos/project/babel.config.js","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]}]
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/wongm/DJRepos/project'' && ''/Users/wongm/DJRepos/project/node_modules/eslint/bin/eslint.js'' --stdin-filename ''/Users/wongm/DJRepos/project/babel.config.js'' --stdin --fix-dry-run --format=json < ''/var/folders/0q/3hxy33qs1m93xl32bg2lxnp40000gq/T/v7h6ZXl/10/babel.config.js''']
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/wongm/DJRepos/project'' && ''/Users/wongm/DJRepos/project/node_modules/eslint/bin/eslint.js'' -f json --stdin --stdin-filename ''/Users/wongm/DJRepos/project/babel.config.js'' < ''/var/folders/0q/3hxy33qs1m93xl32bg2lxnp40000gq/T/v7h6ZXl/11/babel.config.js''']

<<<OUTPUT STARTS>>>
[{"filePath":"/Users/wongm/DJRepos/project/babel.config.js","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]}]
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/wongm/DJRepos/project'' && ''/Users/wongm/DJRepos/project/node_modules/eslint/bin/eslint.js'' -f json --stdin --stdin-filename ''/Users/wongm/DJRepos/project/babel.config.js'' < ''/var/folders/0q/3hxy33qs1m93xl32bg2lxnp40000gq/T/v7h6ZXl/12/babel.config.js''']

<<<OUTPUT STARTS>>>
[{"filePath":"/Users/wongm/DJRepos/project/babel.config.js","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]}]
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/wongm/DJRepos/project'' && ''/Users/wongm/DJRepos/project/node_modules/eslint/bin/eslint.js'' --stdin-filename ''/Users/wongm/DJRepos/project/babel.config.js'' --stdin --fix-dry-run --format=json < ''/var/folders/0q/3hxy33qs1m93xl32bg2lxnp40000gq/T/v7h6ZXl/13/babel.config.js''']
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/wongm/DJRepos/project'' && ''/Users/wongm/DJRepos/project/node_modules/eslint/bin/eslint.js'' --stdin-filename ''/Users/wongm/DJRepos/project/babel.config.js'' --stdin --fix-dry-run --format=json < ''/var/folders/0q/3hxy33qs1m93xl32bg2lxnp40000gq/T/v7h6ZXl/14/babel.config.js''']
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/wongm/DJRepos/project'' && ''/Users/wongm/DJRepos/project/node_modules/eslint/bin/eslint.js'' --stdin-filename ''/Users/wongm/DJRepos/project/babel.config.js'' --stdin --fix-dry-run --format=json < ''/var/folders/0q/3hxy33qs1m93xl32bg2lxnp40000gq/T/v7h6ZXl/15/babel.config.js''']
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/wongm/DJRepos/project'' && ''/Users/wongm/DJRepos/project/node_modules/eslint/bin/eslint.js'' --stdin-filename ''/Users/wongm/DJRepos/project/babel.config.js'' --stdin --fix-dry-run --format=json < ''/var/folders/0q/3hxy33qs1m93xl32bg2lxnp40000gq/T/v7h6ZXl/16/babel.config.js''']
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/wongm/DJRepos/project'' && ''/Users/wongm/DJRepos/project/node_modules/eslint/bin/eslint.js'' -f json --stdin --stdin-filename ''/Users/wongm/DJRepos/project/babel.config.js'' < ''/var/folders/0q/3hxy33qs1m93xl32bg2lxnp40000gq/T/v7h6ZXl/17/babel.config.js''']

<<<OUTPUT STARTS>>>
@babel/preset-env: `DEBUG` option

Using targets:
{
  "android": "86",
  "chrome": "86",
  "edge": "86",
  "firefox": "83",
  "ie": "11",
  "ios": "13.4",
  "opera": "71",
  "safari": "13.1",
  "samsung": "12"
}

Using modules transform: cjs

Using plugins:
  proposal-numeric-separator { "ie":"11" }
  proposal-logical-assignment-operators { "edge":"86", "ie":"11", "ios":"13.4", "opera":"71", "safari":"13.1", "samsung":"12" }
  proposal-nullish-coalescing-operator { "ie":"11", "samsung":"12" }
  proposal-optional-chaining { "ie":"11", "samsung":"12" }
  proposal-json-strings { "ie":"11" }
  proposal-optional-catch-binding { "ie":"11" }
  transform-parameters { "ie":"11" }
  proposal-async-generator-functions { "ie":"11" }
  proposal-object-rest-spread { "ie":"11" }
  transform-dotall-regex { "ie":"11" }
  proposal-unicode-property-regex { "ie":"11" }
  transform-named-capturing-groups-regex { "ie":"11" }
  transform-async-to-generator { "ie":"11" }
  transform-exponentiation-operator { "ie":"11" }
  transform-template-literals { "ie":"11" }
  transform-literals { "ie":"11" }
  transform-function-name { "ie":"11" }
  transform-arrow-functions { "ie":"11" }
  transform-classes { "ie":"11" }
  transform-object-super { "ie":"11" }
  transform-shorthand-properties { "ie":"11" }
  transform-duplicate-keys { "ie":"11" }
  transform-computed-properties { "ie":"11" }
  transform-for-of { "ie":"11" }
  transform-sticky-regex { "ie":"11" }
  transform-unicode-escapes { "ie":"11" }
  transform-unicode-regex { "ie":"11" }
  transform-spread { "ie":"11" }
  transform-destructuring { "ie":"11" }
  transform-block-scoping { "ie":"11" }
  transform-typeof-symbol { "ie":"11" }
  transform-new-target { "ie":"11" }
  transform-regenerator { "ie":"11" }
  proposal-export-namespace-from { "ie":"11", "ios":"13.4", "safari":"13.1" }
  transform-modules-commonjs { "android":"86", "chrome":"86", "edge":"86", "firefox":"83", "ie":"11", "ios":"13.4", "opera":"71", "safari":"13.1", "samsung":"12" }
  proposal-dynamic-import { "android":"86", "chrome":"86", "edge":"86", "firefox":"83", "ie":"11", "ios":"13.4", "opera":"71", "safari":"13.1", "samsung":"12" }

Using polyfills with `entry` option:
[{"filePath":"/Users/wongm/DJRepos/project/babel.config.js","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]}]
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/wongm/DJRepos/project'' && ''/Users/wongm/DJRepos/project/node_modules/eslint/bin/eslint.js'' --stdin-filename ''/Users/wongm/DJRepos/project/babel.config.js'' --stdin --fix-dry-run --format=json < ''/var/folders/0q/3hxy33qs1m93xl32bg2lxnp40000gq/T/v7h6ZXl/18/babel.config.js''']
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/wongm/DJRepos/project'' && ''/Users/wongm/DJRepos/project/node_modules/eslint/bin/eslint.js'' --stdin-filename ''/Users/wongm/DJRepos/project/babel.config.js'' --stdin --fix-dry-run --format=json < ''/var/folders/0q/3hxy33qs1m93xl32bg2lxnp40000gq/T/v7h6ZXl/20/babel.config.js''']

**Comment by hsanson** [comment]
Vim8.2 changed the error code thrown when the json_decode() method fails to decode the input string as json. This causes a lot of linters to show this error and many CI tests to fail for Vim8.2.  There is a PR #3560 that fixes this but it is big and includes many changes so I do not expect it to be merged anytime soon.

A temporary fix would be to hack the FuzzyJSONDecode() function to catch E491 as this commit https://github.com/dense-analysis/ale/pull/3561/commits/119de5e2d59ebb7671e8faf4aa01d12b2dcdafac does.

**Comment by hsanson** [comment]
This should be solved by #3561

**Comment by Wongmat** [comment]
Thank you!

**Comment by Wongmat** [comment]
Hey @hsanson, just noticed that although the original issue has been fixed, fix on save doesn't work at all now when debug is set to true for @babel/preset-env

**Comment by hsanson** [comment]
@Wongmat better create a separate issue for tracking this. I do not use babel so is difficult for me to debug or attempt a fix but I do have some suspicion on the possible cause.

This particular issue was a result of Vim/Neovim being unable to parse the output of the linter/fixer so I bet that when debug is enabled the tool output is returning something that ALE is not prepared to parse, therefore failing to take proper action.
