### ISSUE TITLE
Feature suggestion: Automatically select first item in auto complete popup

### ISSUE THREAD

**Issue by refaelsh** [dense-analysis/ale#3522]
Hi all,

Feature suggestion: Automatically select first item in auto complete popup, like in coc.nvim/VSCode/any other IDE.

Thanks.

P.S.
I cant say this enough, but thank you all for this excellent plugin.

**Comment by w0rp** [comment]
You can configure how Vim selects completion items with your `competeopt` setting in Vim, and you can set it to automatically insert the only available completion item if you use a keybind to select it.

**Comment by refaelsh** [comment]
I understand. Thank you very much for the replay.
