### ISSUE TITLE
phpstan does not look for symbols in the paths defined in the configuration file

### ISSUE THREAD

**Issue by xoich** [dense-analysis/ale#3539]
## What went wrong

Ale wih phpstan reports as undefined symbols (eg Classes) declared in files different than the current one.

## Cause

Paths defined in the phpstan configuration files are essential for phpstan to know where to look for symbols definitions.

Phpstan cli interface works like this `phpstan analyse <paths>`, but this `<paths>` on the command line completely override those on the config file!

From phpstan manual:

> If you provide analysed paths to PHPStan on the command line and in the config file at the same time, they are not merged. Only the paths on the command line will be used.

Since Ale runs phpstan with a command like this: `phpstan analyse current-file.php`, then there is only one path, phpstan only looks for symbols in the current file and will show a wall of undefined symbols errors that are not present when running `phpstan analyse` on the command line.

**Comment by xoich** [comment]
Solution: Use ScanDirectories in phpstan configuration file instead of paths.

**Comment by ondrejmirtes** [comment]
See the documentation: https://phpstan.org/user-guide/discovering-symbols
