### ISSUE TITLE
Error opening java files appeared out of nowhere

### ISSUE THREAD

**Issue by beauwilliams** [dense-analysis/ale#3546]
Hi guys,

I am trying to figure out what might be causing this bug but not sure where to start or where this line 4 might be to provide me with further ideas as to what is causing the sudden errors to appear.

Any help is much appreciated thanks 😀

## Information

**VIM version**

NVIM v0.5.0-dev+f9b311054
Build type: Release

Operating System: Mac OSX

## What went wrong

I open any java file and now get the below error 'String Required' when trying to parse a function. I suspect its to do with classpath import but its just started out of nowhere.

## Reproducing the bug

Whenever I open a java file, or edit it, I get the below error. Linting still works fine.

Error detected while processing function ale#events#LintOnEnter[5]..ale#Queue[33]..<SNR>89_Lint[20]..ale#engine#RunLinters[4]..<SNR>98_GetLintFileValues[27]..<lambda>14[1]..<SNR>
98_RunLinters[12]..<SNR>98_RunLinter[6]..<SNR>98_RunIfExecutable[19]..ale#linter#GetCommand[3]..ale_linters#java#javac#RunWithImportPaths[1]..ale#maven#BuildClasspathCommand[1]..
ale#maven#FindExecutable:
line    4:
E928: String required

1. I did this.
2. Then this happened.

### :ALEInfo

 Current Filetype: java
Available Linters: ['checkstyle', 'eclipselsp', 'javac', 'javalsp', 'pmd']
  Enabled Linters: ['checkstyle', 'eclipselsp', 'javac', 'javalsp', 'pmd']
  Ignored Linters: []
 Suggested Fixers: 
  'google_java_format' - Fix Java files with google-java-format.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'uncrustify' - Fix C, C++, C#, ObjectiveC, ObjectiveC++, D, Java, Pawn, and VALA files with uncrustify.
 Linter Variables:

let g:ale_java_checkstyle_config = '/google_checks.xml'
let g:ale_java_checkstyle_executable = 'checkstyle'
let g:ale_java_checkstyle_options = ''
let g:ale_java_eclipselsp_config_path = ''
let g:ale_java_eclipselsp_executable = 'java'
let g:ale_java_eclipselsp_javaagent = ''
let g:ale_java_eclipselsp_path = '/Users/admin/eclipse.jdt.ls'
let g:ale_java_eclipselsp_workspace_path = ''
let g:ale_java_javac_classpath = ''
let g:ale_java_javac_executable = 'javac'
let g:ale_java_javac_options = ''
let g:ale_java_javac_sourcepath = ''
let g:ale_java_javalsp_config = {}
let g:ale_java_javalsp_executable = ''
let g:ale_java_pmd_options = '-R category/java/bestpractices.xml'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {}
let g:ale_list_vertical = v:null
let g:ale_list_window_size = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = '●'
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = '.'
let g:ale_sign_highlight_linenrs = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) javac

**Comment by hsanson** [comment]
At some point VIM/NVIM started throwing errors if the input string is empty for some functions such as execute() and fnamemodify(). This causes this issue for people with recent versions of VIM/NVIM.

Resources:
  -  https://github.com/vim/vim/issues/7465
  - https://github.com/vim/vim/releases/tag/v8.2.2117

**Comment by hsanson** [comment]
@beauwilliams if you are not actively using the javac linter then disabling it will solve temporarily the issue for you.

**Comment by beauwilliams** [comment]
Great wonderful, thanks for the information. I might just wait to now and hopefully next time I get around to working on a java file this will be merged
