### ISSUE TITLE
Migrate ALE from Travis CI to Github Actions

### ISSUE THREAD

**Issue by hsanson** [dense-analysis/ale#3548]
Travis-CI.com no longer provides unlimited credits to open source projects:

 - https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works
 
And ALE already ran out of credits, therefore there are many PR's stuck waiting for checks from travis that will never complete. One way to solve this is to migrate from Travis-CI to Github actions:

 - https://fbernutz.github.io/posts/github-actions

Since ALE used Docker to run tests we can use these actions for the migration:

 - https://github.com/marketplace/actions/docker-run-action
 - https://github.com/marketplace/actions/build-and-push-docker-images

**Comment by w0rp** [comment]
I have merged this now, and I updated the project settings to turn off Travis CI checks anywhere I could find them and require the GitHub checks instead.
