### ISSUE TITLE
Support for passing custom analysis options to gopls

### ISSUE THREAD

**Issue by rfwatson** [dense-analysis/ale#3563]
I'm trying to configure ALE to pass custom analyser options to gopls, similar to vim-go:

https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L1821-L1831

For example, to enable or disable individual analysers listed here:

https://github.com/golang/tools/blob/master/gopls/doc/analyzers.md

I can see ALE exposes `g:ale_go_gopls_options` but I don't believe the gopls CLI interface allows the above configuration to be passed. Did I miss something?

**Comment by hsanson** [comment]
Unfortunately gopls in ALE does not support initialization options.  Adding them should not be too difficult by modifying the gopls.vim file to add the `initialization_options` to the ale#linter#Define() call.

Reading the documentation on `:h ale#linter#Define()` should provide details on how to do it.

**Comment by hsanson** [comment]
This is now supported thanks to #3571
