### ISSUE TITLE
tsserver is looking for input from LSP client implementers

### ISSUE THREAD

**Issue by gotgenes** [dense-analysis/ale#3578]
The tsserver maintainers are [looking for input from LSP client implementers for providing LSP support for TypeScript](https://github.com/microsoft/TypeScript/issues/39459#issuecomment-772128021). Although [ALE already supports tsserver integration](https://github.com/dense-analysis/ale/wiki/JavaScript-and-TypeScript-integration#tsserver-typescript), using LSP to interact with tsserver might still be of interest. For example it could allow ALE to remove code that supports tsserver's native protocol if all functionality can be provided over LSP.

**Comment by w0rp** [comment]
Thanks, I'll leave a comment on that issue.
