### ISSUE TITLE
Prevent save if linting errors exist

### ISSUE THREAD

**Issue by andrescuco** [dense-analysis/ale#3592]
I was looking through `:help ale` to see if there was a way to prevent saving a file if errors are yet to be fixed but couldn't find any, I think it's a nice addition (if possible) since It'd prevent unnecessary compiling. 

I've been using `:let g:ale_open_list = 1`, since it forces you to see the errors at all times, however you could still save a file that has errors. With an option to prevent saving, if you really wanted to save the file regardless a confirmation prompt could appear asking if you're sure to save the file even when errors still exists, but the default would let you know that you need to fix the errors before continuing and show you the loclist.

**Comment by w0rp** [comment]
This is something where it's better to let people write their own ways of doing this. I like to provide access to some information from ALE so you can write your own plugins to do whatever you want. I slapped this together pretty quickly as something you can do:

```vim
augroup PreventSavingWithProblems
    autocmd!
    autocmd BufWritePre * if len(ale#engine#GetLoclist(str2nr(expand('<abuf>')))) | throw 'Fix your code!' | endif
augroup END
```

`ale#engine#GetLoclist` is part of the documented public API for ALE. See `:help ale#engine#GetLocList` for more information.
