### ISSUE TITLE
Add option to show virtualtext on all lines that have error/warning/info

### ISSUE THREAD

**Issue by reportaman** [dense-analysis/ale#3666]
Currently ``let g:ale_virtualtext_cursor = 1`` enables showing virtualtext when cursor is on line containing error/warning/info in neovim. The request here is to add an option to show virtualtext on all lines that have error/warning/info. This will be irrespective of cursor movement, and will update whenever lint is run. One advantage is that we can then visualize messages on different lines at once, and make sense whether the messages are related or not.

**Comment by WhiteBlackGoose** [comment]
Bumping this! ALE is working great for me, but this feature feels missing. Or maybe I couldn't find it either.

**Comment by RyanSquared** [comment]
Related: #2962, #4289

**Comment by WhiteBlackGoose** [comment]
Thank you so much. Switched to that fork for now, will switch back to the original repo once the PR is merged XD
