### ISSUE TITLE
Remove `--enable-all` from `g:ale_go_golangci_lint_options`

### ISSUE THREAD

**Issue by kit494way** [dense-analysis/ale#3670]
Currently, `--enable-all` is specified by default. https://github.com/dense-analysis/ale/blob/06f57ca9733aab6e6b67015917fdfd4bf1c70c48/ale_linters/go/golangci_lint.vim#L4
But, as commented [here](https://github.com/golangci/golangci-lint/issues/1878#issuecomment-809646180), `--enable-all` is deprecated.

**Comment by windvalley** [comment]
I ran into the same problem, so I changed `call ale#Set('go_golangci_lint_options', '--enable-all')` to `call ale#Set('go_golangci_lint_options', '') `, then it works.

**Comment by hsanson** [comment]
Fixed with https://github.com/dense-analysis/ale/pull/4488
