### ISSUE TITLE
ansible-lint fails in some cases when redirecting filename to STDIN, --nocolor needs to be used to parse the output correctly

### ISSUE THREAD

**Issue by teklabania** [dense-analysis/ale#3674]
I noticed that ansible-lint has a bug when redirecting a filename to its STDIN:
```
ansible-lint < playbook.yml # this works sometimes
```
For some files it gives output and for some it doesn't even though the output is always produced when a filename is provided as an argument:
```
ansible-lint playbook.yml # this always works
```
I wonder if ALE could change the command line definition to use a filename as parameter instead of redirecting.

```
ansible-lint --version
ansible-lint 5.0.6 using ansible 2.10.7
```
The above has been tested on Linux and Mac.

Additionally i noticed that ALE can't parse ansible-lint output without --nocolor switch on Mac. Setting up custom executable:
```
#!/bin/bash
ansible-lint --nocolor $@ 
```
solves the issue.

**Comment by jamescherti** [comment]
@teklabania This pull request will fix the stdin issue https://github.com/dense-analysis/ale/pull/3786.

**Comment by hsanson** [comment]
@teklabania appreciated if you can test this PR:  #3811

**Comment by henrik-farre** [comment]
The PR fixes it for me
