### ISSUE TITLE
Invalid Ale configuration

### ISSUE THREAD

**Issue by 26chk** [dense-analysis/ale#3685]
I am using Vim8

The following configuration is invalid?

219 let g:ale_sign_error = '✗'
220 let g:ale_sign_warning = '⚠'
221 let g:ale_sign_style_error  = '>>'
222 let g:ale_sign_style_warning  = '>'
223 let g:ale_statusline_format = ['✗ %d', '⚠ %d', '✔ OK']
224 let g:ale_disable_lsp = 1
225 highlight clear ALEErrorSign
226 highlight clear ALEWarningSign

![Screenshot_20210410_063918](https://user-images.githubusercontent.com/61009000/114247359-8131d380-99c7-11eb-9618-18f086138369.jpg)

**Comment by mcmire** [comment]
Looks like your file is getting interpreted as JSX. What does Vim report as the file type for that file?
