### ISSUE TITLE
prefix hints/errors with linter name

### ISSUE THREAD

**Issue by githorse** [dense-analysis/ale#3692]
I have multiple linters running on, say, my javascript file. When I hover over a hint, the message at the bottom of the screen says "semi: missing semicolon". I want to configure my linter to ignore it. But which linter does it come from? Beats me. The only way I know how to figure it out is to manually set `b:ale_linters=['x']` one at a time for each option and see which one still shows the hint.

Some linters print their name before the hint message, but some don't. Could we enforce that all messages are prefixed by the name of the linter? Or include a way to toggle it on or off? Currently even `ALEDetail` doesn't actually tell me the name of the linter(s) the message comes from (at least for some linters).

ALE newbie here so very possibly I am missing the canonical way to do this.

**Comment by hsanson** [comment]
This configuration should do what you want:

> let g:ale_echo_msg_format = '%severity% [%linter%] (%code%) - %s

read the documentation about g:ale_echo_msg_format for more options.

**Comment by hsanson** [comment]
This is already supported and there is no more activity so closing the issue.

**Comment by Crazy-Ginger** [comment]
Sorry for perhaps re-hasing this but is there a way to make this only added to `:ALEDetail`? 
I'm after something like

```
%code: %%s

[%linter%] 
```
