### ISSUE TITLE
Can not jump into jar content with javalsp

### ISSUE THREAD

**Issue by lisongmin** [dense-analysis/ale#3696]
## Information

**VIM version**

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 26 2021 00:21:09)
Included patches: 1-2653
```

Operating System: 

Archlinux

## What went wrong

When I try to jump to the definition in jar, vim do not show the content, but open a new directory

```
"jar:file:///home/lsm/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30-sources.jar!/org/slf4j/LoggerFactory.java" [New DIRECTORY]
```

as i test, vim can open the jar content via the format:

```
zipfile:///home/lsm/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30-sources.jar::org/slf4j/LoggerFactory.java
```

where change the `jar:file` to `zipfile`, and change the `!/` to `::`

## Reproducing the bug

1.  Open a java file, 
2. move to the `LoggerFactory` 
3. trigger `ale_go_to_definition`
2. Then this happened.

### :ALEInfo

 Current Filetype: java
Available Linters: ['checkstyle', 'eclipselsp', 'javac', 'javalsp', 'pmd', 'android']
  Enabled Linters: ['javalsp', 'android']
  Ignored Linters: []
 Suggested Fixers: 
  'google_java_format' - Fix Java files with google-java-format.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'uncrustify' - Fix C, C++, C#, ObjectiveC, ObjectiveC++, D, Java, Pawn, and VALA files with uncrustify.
 Linter Variables:

let g:ale_java_javalsp_config = {'java': {'externalDependencies': [], 'classPath': []}}
let g:ale_java_javalsp_executable = '/usr/bin/java-language-server'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'typescript': ['eslint'], 'go': ['gofmt'], 'c': ['clang-format'], 'json': ['prettier'], 'java': ['google-java-format'], '*': ['trim_whitespace'], 'cpp': ['clang-format'], 'rust': ['rustfmt'], 'python': ['autopep8'], 'bash': ['shfmt']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'cpp': ['clangtidy', 'ccls'], 'html': ['tidy'], 'typescript': ['eslint', 'tsserver'], 'kotlin': ['android', 'languageserver'], 'go': ['gopls'], 'bash': ['shfmt'], 'yaml': ['yamllint'], 'python': ['flake8', 'pylint', 'pyls'], 'xml': ['android', 'xmllint'], 'vim': ['vint'], 'c': ['clangtidy', 'ccls'], 'tex': ['chktex'], 'rust': ['analyzer'], 'javascript': ['eslint', 'tsserver'], 'css': ['csslint'], 'dart': ['language_server'], 'java': ['android', 'javalsp'], 'zig': ['zls']}
let g:ale_linters_explicit = 1
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 5
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 1
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_root = {}
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 0
  Command History:

(executable check - success) /usr/bin/java-language-server
(started) ['bash', '-c', '''/usr/bin/java-language-server''']

**Comment by yoshi1123** [comment]
You might be interested in PR #4030.
