### ISSUE TITLE
ALEHover support for non-LSP messages

### ISSUE THREAD

**Issue by jonatan-branting** [dense-analysis/ale#3698]
It seems that the ALEHover feature will only display messages coming from an LSP source.

I'd like to be able to display any message from any linter, configured through `g:ale_linters` using hover. It's possible to display these messages both using virtual text and through echo, but being able to hover them would in my opinion be a better interface.

I'm not entirely sure why there is a distinction between these different feedback mechanisms.

Or it might just be that I'm missing something rather obvious?

**Comment by vimpostor** [comment]
> Or it might just be that I'm missing something rather obvious?

Yes, use `:ALEDetail`.
