### ISSUE TITLE
Vim-8 Popup Windows

### ISSUE THREAD

**Issue by ldelossa** [dense-analysis/ale#3703]
Hello,

I am curious if there are any plans to support vim 8 popup window in addition to nvim's floating windows. Vim-lsp supports this: https://github.com/prabirshrestha/vim-lsp/blob/master/doc/vim-lsp.txt#L298 (not to make a comparison, just to say its feasible).

**Comment by benknoble** [comment]
I would love this. _Theoretically_, with appropriate mods to autoload/ale/floating_preview.vim, it shouldn't be too hard.

**Comment by hsanson** [comment]
Implemented in #3817
