### ISSUE TITLE
Go: vet is disabled by default?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [dense-analysis/ale#3733]
## Information

**VIM version**
8.2, including patches 1-814

Operating System: Linux Gentoo i686

## What went wrong

I see errors from `go fmt` but silence from `go vet`. For example this code contains an error:
```
package main

import "io"

func main() {
	r, w := io.Pipe()
	w.Write("x")
}
```
`go vet` prints this error, but not `ale`.

### :ALEInfo

 Current Filetype: go
Available Linters: ['bingo', 'gobuild', 'gofmt', 'golangci-lint', 'golint', 'gometalinter', 'gopls', 'gosimple', 'gotype', 'govet', 'golangserver', 'revive', 'staticcheck']
   Linter Aliases:
'gobuild' -> ['go build']
'govet' -> ['go vet']
  Enabled Linters: ['gofmt', 'golint', 'govet']
  Ignored Linters: []
 Suggested Fixers: 
  'gofmt' - Fix Go files with go fmt.
  'goimports' - Fix Go files imports with goimports.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_go_go_executable = 'go'
let g:ale_go_golangci_lint_executable = 'golangci-lint'
let g:ale_go_golangci_lint_options = '--enable-all'
let g:ale_go_golangci_lint_package = 0
let g:ale_go_golint_executable = 'golint'
let g:ale_go_golint_options = ''
let g:ale_go_govet_options = ''
let g:ale_go_langserver_executable = 'go-langserver'
let g:ale_go_langserver_options = ''
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '[%linter%] %[code]% %s [%severity%]'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 999
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let b:ale_linters = {'python': ['pylint', 'flake8', 'mypy']}
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {}
let g:ale_list_vertical = v:null
let g:ale_list_window_size = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = {'/Users/vitaly/intelligent-speaker/website/layouts/.*\.html$': {'ale_enabled': 0}}
let g:ale_pattern_options_enabled = v:null
let g:ale_root = v:null
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_sign_highlight_linenrs = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = v:null
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

**Comment by w0rp** [comment]
See if you can get anything to appear in "Command History." It might be that you need to set your `PATH` environment variable for Vim so ALE can run `go vet`.

**Comment by vitaly-zdanevich** [comment]
Please clarify - what is "Command History"? What `PATH` I need for Vim?

**Comment by hsanson** [comment]
I can see govet reports the error on my setup:

>   w.Write("x")  cannot convert "x" (untyped string constant) to []byte 

The ALEInfo you posted shows nothing after "Command History:" line, not sure if you did not copy the whole output or if there is something wrong in your setup that stops ALE from detecting the binaries (e.g. PATH env variable).

On my machine I get this after "Command History" reported by ALEInfo:

```
(executable check - success) gofmt
(finished - exit code 0) ['/bin/bash', '-c', '''gofmt'' -e ''/tmp/nvimPY7AQ7/2/test.go''']
<<<NO OUTPUT RETURNED>>>
(executable check - failure) golint
(executable check - success) go
(finished - exit code 2) ['/bin/bash', '-c', 'cd ''/home/Projects/HelloWorld/go'' && go ve
t  .']
<<<OUTPUT STARTS>>>
# _/home/Projects/HelloWorld/go
vet: ./test.go:7:10: cannot convert "x" (untyped string constant) to []byte
<<<OUTPUT ENDS>>>
```

**Comment by vitaly-zdanevich** [comment]
If in shell I can run `go vet` this is mean that PATH is correct, as I understand.

So what can I try on my end?

**Comment by vitaly-zdanevich** [comment]
This issue still exists :(

**Comment by vitaly-zdanevich** [comment]
Fixed in current version after `go mod init xxx.xx/xx`
