### ISSUE TITLE
Add support for markdownlint-cli2

### ISSUE THREAD

**Issue by craigmac** [dense-analysis/ale#3750]
**Name:** markdownlint-cli2
**URL:** https://github.com/davidanson/markdownlint-cli2

This is the linter CLI behind the VS Code markdownlint plugin, so it's in heavy usage. It supports inheritance of rule configuration files, which original markdownlint-cli does not. It could be as simple as allowing current "markdownlint" linter to specify the executable and allowing user to point to markdownlint-cli2 binary instead, but as of now I can't find a documented way or option to do that.

**Comment by goetzc** [comment]
@craigmac, in the meantime you can use a symlink or rename the executable.

**Comment by craigmac** [comment]
I've just put in `~/.vim/after/ale_linters/markdown/markdownlintcli2.vim`:

```
call ale#linter#Define('markdown', {
\   'name': 'markdownlintcli2',
\   'executable': 'markdownlint-cli2',
\   'lint_file': 1,
\   'output_stream': 'stderr',
\   'command': '%e %s',
\   'callback': 'ale#handlers#markdownlint#Handle'
\})
```

Because it does a few things different than the `markdownlint` linter.
