### ISSUE TITLE
ALERename: unlisted buffers are modified incorrectly

### ISSUE THREAD

**Issue by jeremija** [dense-analysis/ale#3781]
## Information

**VIM version**

NVIM v0.4.4
Build type: Release

Operating System: Linux

## What went wrong

After calling ALERename on certain variable,s, some files would be incorrectly replaced. The whole file would be truncted, and the only changes would be the new variable name.

## Reproducing the bug

I was able to track it down to the following configuration:

```vimscript
let g:ale_linters = {
\  'go': ['gopls', 'golangci-lint'],
\}
```

I then opened a `myfile.go`. In the same folder I had a test file `myfile_test.go`. After renaming a symbol in `myfile.go`, which was also referenced from `myfile_test.go`, the whole `myfile_test.go` would be truncated.

I tracked it down to`bufnr('/path/to/myfile_test.go')` returning number for a file that I never opened, even though the buffer wasn't there. I later noticed that this buffer was actually unlisted (visible only via `:ls!`). So there must be something in the `golangci-lint` linter that opens this file in the background.

### :ALEInfo

I don't think it's necessary since I'll shortly submit an MR that fixes it.

**Comment by hsanson** [comment]
Addressed in #4049
