### ISSUE TITLE
Balloons not functional in terminal vim

### ISSUE THREAD

**Issue by kevr** [dense-analysis/ale#3800]
Revival of https://github.com/dense-analysis/ale/issues/2442, which was never truly addressed.

Please reopen the issue. It is a bug, not a feature.

**Comment by hsanson** [comment]
Please correct me if wrong but now that we have Vim Popups #3817 and NeoVim floating #3470 windows do we still need Vim Baloons?  From my limited research seems that baloons are Vim only feature and very limited in comparison with Popups.
