### ISSUE TITLE
Fixing rust files using `rustfmt` does not recognize cargo project settings

### ISSUE THREAD

**Issue by jmcantrell** [dense-analysis/ale#3814]
## Information

**VIM version**
NVIM v0.5.0
Build type: Release

Operating System: arch linux

## What went wrong

Since ale is simply calling the `rustfmt` executable with whatever options were configured, some options that are crucial to how `rustfmt` works are not being recognized. In particular, when creating a new cargo project, the default edition is 2018, whereas the default edition when running `rustfmt` (as opposed to `cargo fmt`) is 2015. As long as you're not using any language features that are 2018-only, everything appears to work fine.

One solution is to have ale always run `rustfmt` with the later edition (`let g:ale_rust_rustfmt_options = '--edition 2018'`), but that might not be appropriate if you're working on an older rust project.

For now, I'm going to work on making my configuration of ale a little smarter by trying to detect whether or not the context is a cargo project. I'll post any findings here, in case anyone else runs into this.

Even though I'm not convinced this is technically a bug anymore, it's definitely something that's unexpected, and is likely to affect many people, as most rust development is done in a cargo project, and the default edition for new cargo projects is 2018.

## Reproducing the bug

1. install the ale plugin (broken on master and v3.1.0)
2. have an ftplugin (`~/.config/nvim/ftplugin/rust.vim`) defining `b:ale_fixers = ['rustfmt']`.
3. start a new cargo project (specifically edition 2018): `cargo new --edition 2018 foo`
3. edit `src/main.rs`
4. make a change that is fixable in either edition 2015 or 2018 (like indent size)
5. verify that fixing works
4. make a change that is specific to edition 2018 (like define a function declared with the `async` keyword)
4. verify that fixing no longer works
5. add `let g:ale_rust_rustfmt_options = '--edition 2018'` to the ftplugin
6. verify that fixing works again

### :ALEInfo

```
 Current Filetype: rust
Available Linters: ['analyzer', 'cargo', 'rls', 'rustc']
  Enabled Linters: ['analyzer']
  Ignored Linters: []
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'rustfmt' - Fix Rust files with Rustfmt.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_rust_analyzer_config = {}
let g:ale_rust_analyzer_executable = 'rust-analyzer'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'*': ['remove_trailing_lines', 'trim_whitespace']}
let b:ale_fixers = ['rustfmt']
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let b:ale_linters = ['analyzer']
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) rust-analyzer
(started) ['/bin/zsh', '-c', '''rust-analyzer''']
```

**Comment by jmcantrell** [comment]
This has something to do with the content of the file being edited. I noticed it when trying some of the sample code from this article: https://zmedley.com/tcp-proxy.html

Something about this file is causing ale to not work at all, linting or fixing, even though it builds:
https://github.com/ZekeMedley/tcp-proxy/blob/main/src/main.rs

**Comment by jmcantrell** [comment]
I was able to narrow it down to the presence of a function defined with the `async` keyword causing the fixing to fail. There's also no errors or warnings that I can see.

**Comment by jmcantrell** [comment]
The included bit of code will set the rustfmt edition based on the current cargo project setting. If not in the context of a cargo project, it doesn't change anything.

It requires cargo-get `cargo install cargo-get`.

```viml
let b:rust_edition = trim(system('cargo get --edition 2>/dev/null'))
if v:shell_error == 0 && len(b:rust_edition) > 0
    let g:ale_rust_rustfmt_options = '--edition ' .. b:rust_edition
endif
```

This version is similar, but it sets a default if not in a cargo project:

```viml
let b:rust_default_edition = '2018'
let b:rust_edition = trim(system('cargo get --edition 2>/dev/null'))
if v:shell_error > 0 || len(b:rust_edition) == 0
    let b:rust_edition = b:rust_default_edition
endif

let g:ale_rust_rustfmt_options = '--edition ' .. b:rust_edition
```

I'm going to close this, because I no longer feel that this is an actual bug.

**Comment by akiross** [comment]
Same issue. While I'd prefer to have `cargo fmt` as a fixer, another solution is to use `.rustfmt.toml` in the project root with a line like
```
edition = "2018"
```
