### ISSUE TITLE
Add support for cspell 

### ISSUE THREAD

**Issue by pbnj** [dense-analysis/ale#3828]
**Name:** cspell
**URL:** https://github.com/streetsidesoftware/cspell

From their repository:

> A Spell Checker for Code! 

`cspell` is a wildly popular, powerful, and configurable code spelling project with over 2 million downloads on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

The `cspell` CLI is available via npm (e.g. `npm install -g cspell`) and outputs `errorformat` results out-of-the-box. 

Example:

```vim
:cgetexpr system('npx cspell {*,**/*}.md')
```

Supporting `cspell` would allow for developers to share and re-use `.cspell.json` configurations.

**Comment by houstdav000** [comment]
I've been using cspell in VSCode and was wondering where it was in ALE... I might look at adding it if I can also get it added to nixpkgs...
