### ISSUE TITLE
How can I disable ale signs/highlights while I'm in insert mode?

### ISSUE THREAD

**Issue by ayushnix** [dense-analysis/ale#3842]
### Discussed in https://github.com/dense-analysis/ale/discussions/3836

I want to disable all the signs/highlights in the sidebar and the status bar at the bottom while I'm in insert mode/whenever I'm typing something. When I switch to normal mode, I want to see all the signs again.

I tried disabling ALE using autocmd group

```
augroup disable_ale_insmode
    autocmd!
    autocmd InsertEnter * :ALEToggle
    autocmd InsertLeave * :ALEToggle
augroup END
```

however, this also disables `g:ale_sign_column_always` which makes text jump around when switching back to normal mode.

How can I disable all the signs and highlights while I'm in insert mode while keeping the sign column always visible?

**Comment by hsanson** [comment]
This is not possible to do now in ALE. Make an issue with "enhancement" label requesting the feature.
For support inquiries use the discussions instead of creating new issues.
