### ISSUE TITLE
Fire a User event when an LSP starts

### ISSUE THREAD

**Issue by benknoble** [dense-analysis/ale#3861]
Inspired by https://github.com/prabirshrestha/vim-lsp, it would be nice to have the ability to make maps for ALE LSP commands only when the LSP is active. Then I would work as follows:

- use normal `gd` and other vim commands, possibly configured by ftplugins, as an approximation when no LSP is available, ALE is off, etc.
- when LSP is available, have the commands delegate to ALE for a more exact experience

Additionally, I would be able to `setlocal omnifunc=ale#completion#omnifunc` for LSP-enabled buffers, rather than my current `setlocal completefunc` so that I don't lose a good `omnifunc` when I don't have an LSP.

## Technical details

Since the autocmd User event doesn't permit patterns, we have to be careful to fire it for the right buffers. I've left a link that explores that code below.

Possibly useful for implementation: https://github.com/prabirshrestha/vim-lsp/blob/fb0a72306e1fc42c1ce8909aa1e420ddfccf6fbf/autoload/lsp.vim#L345

**Comment by jparise** [comment]
I've been wanting this, too, so I took at crack at it in #3878.
