### ISSUE TITLE
Racket `omni_start_map` should be something like `\k\+`

### ISSUE THREAD

**Issue by benknoble** [dense-analysis/ale#3870]
Racket, being a lisp, has far more than just alpha-numeric identifiers, which is what the default pattern matches. This means when I type `file-name`, invoking completion won't give `file-name-from-path` but completions like `namespace`—it has used only the `name` part. Using `\k\+` seemed to work in cases like this, but I don't have an exhaustive test.

More broadly, and the reason this is an issue and not a PR, is I think the default should be `\k\+`—then it should be effectively scoped to the languages `iskeyword` setting, no?

I also don't understand why `$` is included in the `omni_start_map` pattern: does that only allow completions when there is nothing else on the line? Perhaps word boundaries `\<\>` would be more appropriate?

Looking for feedback here.

---

PS Why not use the lisp pattern? Well, I don't think even it covers all possible lisp or racket identifiers, and `\k\+` is so much easier to read.

**Comment by w0rp** [comment]
I don't know what any of this is, but if you can create a pull request that fixes this without breaking any current functionality in languages like TypeScript, go for it.

**Comment by benknoble** [comment]
I am referring to `s:omni_start_map` in `autoload/ale/completion.vim` (apologies for not being clear). The declaration is around line 139, with sole use at line 311.

It seems like the intent was to allow filetypes to specify patterns to find the start of a word for completion, with a default of
```
\v[a-zA-Z$_][a-zA-Z$_0-9]*$
```

Unfortunately, this doesn't work for some languages. It explicitly disallows `-` in words that should start completion, for example; every lisp I've ever used has `-` in names commonly (some examples are in the original post). This means that trying to complete from a word that already has `-` in it breaks.

My suggestion is to use `\k\+` (possibly with word boundaries)—then the default should work for all filetypes by leveraging their custom `iskeyword` settings (which _define_ in vim what a word is for a filetype). If a filetype has this correctly set (and, _e.g._, racket, scheme, and common lisp should), then it should "just work."

If that's no good, then I'd like to at least add `'racket': '\k\+'` or similar—the issue is that racket is actually a lot of languages, so there are lots of possible filetypes… and other lisps suffer, too, so it would be nice to add them… etc. So then you have this mechanism that controls completion (and breaks it, if not set right) but that is really hard to customize. (By really hard, I mean that the only way is to (a) edit your local copy of ALE and be careful not to lose that when updating or (b) submit a PR and wait for it to merge. That seems untenable in the long-term.)

**Comment by benknoble** [comment]
I've opened 2 different pull requests:

1. One only fixes Racket, which I feel is unsustainable.
2. The other modifies the default to be more precise per-filetype, but I don't know if this will break anything else.

**Comment by benknoble** [comment]
Reviving this, both PR #4186 and #4187 pass tests. It's not clear to me that passing the tests means "*without breaking any current functionality in languages like TypeScript*," but I thought I would mention it.
