### ISSUE TITLE
Default mapping for K and <C-]>

### ISSUE THREAD

**Issue by robbieh** [dense-analysis/ale#3871]
Why not map ALEHover to K and ALEGoToDefinition to <C-]>? The keywordprg function doesn't make a lot of sense for languages that ALE handles. And <C-]> is the default jump-to-definition mapping.

I've been doing this with Rust and find that I quite like it.
```
augroup filetype_rust                                                                                                                                                        
    au!                                                                                                                                              
    au BufRead,BufNewFile *.rs nnoremap K :ALEHover<CR>                                                                               
    au BufRead,BufNewFile *.rs nnoremap <C-]> :ALEGoToDefinition<CR>                                                                            
augroup END                         
```

**Comment by hsanson** [comment]
Quote from [Writing Vim Plugins](https://vimways.org/2019/writing-vim-plugin/):

> if something can be done via a command then it should be made as a command, do not force your mappings on users.Plugins should not define default mappings and leave users to define them:

Also recommended reading: [Mapping keys the correct way](https://stevelosh.com/blog/2011/09/writing-vim-plugins/#s6-mapping-keys-the-right-way)

**Comment by robbieh** [comment]
Yes, and it's great when a plugin offers features using the keybindings users already expect from Vim. That's hardly forcing your mapping on a user. It's using a mapping that doesn't work for the current file and making it work as expected. That makes my life easier. It reduces my cognitive load. I expect K to do a keyword lookup because that's what Vim says it does in the :help docs. That's what works in other files, with other language plugins. It's the principle of least surprise. So make K work right for the current file, instead of defaulting to calling 'man' which just feels broke. Ditto for C-], which doesn't work at all unless it is fixed.

Your document references Tim Pope, who wrote vim-fireplace: https://github.com/tpope/vim-fireplace

> Navigating and Comprehending
>
> I was brand new to Clojure when I started this plugin, so stuff that helped me understand code was a top priority.
> 
>     :Source, :Doc, and :FindDoc, which map to the underlying clojure.repl macro (with tab complete, of course).
> 
>     K is mapped to look up the symbol under the cursor with doc.
> 
>     [d is mapped to look up the symbol under the cursor with source.
> 
>     [<C-D> jumps to the definition of a symbol (even if it's inside a jar file). <C-]> does the same and uses the tag stack.
> 
>     gf, everybody's favorite "go to file" command, works on namespaces.
> 
> Where possible, I favor enhancing built-ins over inventing a bunch of <Leader> maps.

So maybe take a cue from him on this?

But hey, that's just my opinion.
