### ISSUE TITLE
Add support for eslint-plugin-jsonc plugin

### ISSUE THREAD

**Issue by jpesce** [dense-analysis/ale#3872]
**Name:** eslint with eslint-plugin-jsonc plugin
**URL:** https://ota-meshi.github.io/eslint-plugin-jsonc/ 

Linter and fixer for JSON, JSONC and JSON5 files that uses `eslint`. Since `eslint` is already supported for other filetypes, this should be trivial. I'll make a very basic pull request with the minimum required configuration and let me know if it makes sense supporting it so I can improve it. 🐸

Cheers

**Comment by hsanson** [comment]
Try configuring g:ale_linters so json is not linted by eslint.
