### ISSUE TITLE
Error detected decoding JSON from Neovim LSP

### ISSUE THREAD

**Issue by hsanson** [dense-analysis/ale#3886]
## What went wrong

Reported in https://github.com/dense-analysis/ale/issues/3373#issuecomment-895494932 and https://github.com/dense-analysis/ale/issues/3373#issuecomment-910196544. Seems that some language servers (NVIM LSP?) send a list instead of the expected string or list.

Seems to happen with rust-analyzer and PHP LSP.

```
Error detected while processing function ale#completion#HandleUserData[2]..ale#util#FuzzyJSONDecode:
line    5:
E714: List required
```

## Reproducing the bug

???

**Comment by hsanson** [comment]
If someone can provide a configuration that reliably reproduces the issue would greatly help debugging it.  I am unable to get this to happen with any of the LSP I use daily (javalsp, solargraph, pyright).

**Comment by Mte90** [comment]
I am getting with this https://github.com/mte90/dotfiles
I am using also compe (I will switch from that soon) and I don't know if this is part of the issue.

Also I don't see a way to disable ALE to be executed with LSP at all as the globals seems ignored.

**Comment by Mte90** [comment]
I am getting the same error also with coq_nvim.
There is something I can do to help debugging this?

In my case I am not interested in ALE support in completion.

**Comment by hsanson** [comment]
You can try debugging the issue:

  - https://inlehmansterms.net/2014/10/31/debugging-vim/
  
1. Start vim in debug mode "vim -D" using minimal vimrc and file that causes the issue.
2. In the debugger add a breakpoint at the problematic function (e.g. `breakadd func ale#completion#HandleUserData`)
3. Continue using vim as normal (e.g. execute `cont` in debugger prompt).
4. When the function is called and the debugger stops at the breakpoint inspect the value of the argument (e.g. `echo a:completed_item`).
5. If the output is not JSON then we know it will fail latter. Provide the value in this issue to see if we can figure out what it is and where it comes from.

**Comment by hsanson** [comment]
Note that this function is called not only for auto-completion. It is also used to handle LSP CodeActions. That is why this is invoked even if ALE auto-completion is disabled.

**Comment by Mte90** [comment]
Get stopped in that way to that line:
![immagine](https://user-images.githubusercontent.com/403283/132236082-4abaad77-9067-4423-8ee2-8ba5753261fc.png)
If i continue I am getting the usual error.

Added an echo of that variable and is not empty at all:

![immagine](https://user-images.githubusercontent.com/403283/132236695-d12c9cc5-8442-4670-87e9-0b94230ccfe3.png)

Using type on Fuzzyjson is a dictionary and not a list, I am doing a pr for that :-)
