### ISSUE TITLE
Virtual Text Support for Vim

### ISSUE THREAD

**Issue by vimpostor** [dense-analysis/ale#3906]
It would be cool, if the `g:ale_virtualtext_cursor` option would work in vim too. Right now it only works in Neovim:
```
This option only has any effect in NeoVim.
```

Vim does not have virtual text per se, but pretty much the same can be achieved by combining text properties with popup texts: https://github.com/vim/vim/issues/7553

Would you accept a PR, if I implemented this feature using text properties and a popup?

**Comment by blayz3r** [comment]
https://github.com/vim/vim/issues/7553#issuecomment-1206510254

**Comment by vimpostor** [comment]
> [vim/vim#7553 (comment)](https://github.com/vim/vim/issues/7553#issuecomment-1206510254)

Implemented in #4281
