### ISSUE TITLE
ALEFix is incompatible with isort < 5.7.0

### ISSUE THREAD

**Issue by jmsanders** [dense-analysis/ale#3941]
isort didn't introduce the `--filename` flag until 5.7.0:

- https://github.com/PyCQA/isort/releases/tag/5.7.0
- https://github.com/PyCQA/isort/issues/1596

https://github.com/dense-analysis/ale/pull/3815 introduces `--filename` which makes fixing incompatible with isort < 5.7.0

Perhaps ale should conditionally add the `--filename` flag based on the detected version of isort?

**Comment by hsanson** [comment]
@jmsanders appreciated if you can verify this PR works for you: #3942

**Comment by jmsanders** [comment]
Yep - works for me! Thanks for the quick fix!
