### ISSUE TITLE
[Neovim 0.6 Diagnostic API] ALE as the source of diagnostics to Neovim's new Diagnostic module

### ISSUE THREAD

**Issue by bluz71** [dense-analysis/ale#4005]
Hello ALE developers,

Spawning a new from [my comment](https://github.com/dense-analysis/ale/issues/3528#issuecomment-978915077) in #3528.

Neovim 0.6 was recently released with the main feature being the new [vim.diagnostic](https://neovim.io/doc/user/diagnostic.html) API. Previously diagnostics were a part of the native LSP client; but now it's an extracted stand-alone top level module.

Linting plugins such as [nvim-lint](https://github.com/mfussenegger/nvim-lint) and [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) are now using that API.

Can ALE also be enhanced to do the same? Does the architecture allow for that?

Aka, can ALE be a diagnostic source for display by another diagnostic engine? ALE has long had the option to be end-point for other diagnostic sources (aka CoC feeding it's diagnostics to ALE for display and navigation). But, this issue is wanting to go the other way; use ALE simply as the runner and then feed it's diagnostics to Neovim's new diagnostic module. The benefit for Neovim folks is a single source of display (signs, virtual-text, underlines) and a single set of mappings to navigate diagnostics.

Many thanks.

**Comment by dbalatero** [comment]
This would be awesome to see! I even tried to switch to null-ls but something in how its architected made the linting/fixing lock up the editor on save. ALE at its core feels much more stable than these new Lua reimplementation plugins, at least at this time, so I'd love to keep using this and unify the diagnostics :)

**Comment by w0rp** [comment]
I don't see why we can't support this. It looks like a few simple function calls. We'd just need to check a flag being enabled to send diagnostics to NeoVim's system in `ale#engine#SetResults` instead of calling the various functions there for settings all of the visual elements that ALE does.

**Comment by w0rp** [comment]
I don't use NeoVim myself, but someone who does can open a pull request for this.

**Comment by dbalatero** [comment]
> We'd just need to check a flag being enabled to send diagnostics to NeoVim's system in ale#engine#SetResults instead of calling the various functions there for settings all of the visual elements that ALE does.

Just to iterate on the design a bit before anyone codes…

Are you thinking this flag would be a "one or the other" kind of thing?

e.g.
* If the flag is `true`, send diagnostics only to Neovim
* If the flag is `false`, keep doing the normal stuff ALE does today

**Comment by dbalatero** [comment]
@w0rp Just to clarify, is `ale#engine#SetResults` where any error/info/warning updates flow through?

**Comment by dbalatero** [comment]
Hey @w0rp just wanted to ping you on the questions above, so I can make sure my PR will be shaped in a way that works best for you :)

**Comment by w0rp** [comment]
@dbalatero Yeah, you use that to send all problems to ALE. I started calling the collection of errors, warnings, and info "problems" a while ago.

**Comment by w0rp** [comment]
To clarify, it's an internal function not to be called by other scripts that ALE calls to display everything.

**Comment by dbalatero** [comment]
Thanks!

**Comment by dbalatero** [comment]
I have a PR up with this working: https://github.com/dense-analysis/ale/pull/4135

**Comment by w0rp** [comment]
I and @Angelchev took the work of @dbalatero and @mathstuf and got this done now. There will be tweaks that can be done to make it better later, but the basic functionality works now.
