### ISSUE TITLE
g:ale_go_golangci_lint_options not work well

### ISSUE THREAD

**Issue by jinleileiking** [dense-analysis/ale#4009]
`let g:ale_go_golangci_lint_options = '--disable-all -E errcheck'`

seems runs like  'enable-all'

But:
`let g:ale_go_golangci_lint_options = '--disable-all`

seems runs well.

when option has a space, not work well?

**Comment by hsanson** [comment]
Post the output of ALEInfo to see if we can figure out what is going on.
