### ISSUE TITLE
C++ Linter cannot add linker flags

### ISSUE THREAD

**Issue by JSybrandt** [dense-analysis/ale#401]
The issue is that g++ requires flags such as the -lncurses flag to occur at the end of the command, but the variable 
g:ale_cpp_gcc_options places all command line arguments in the same place.

current attempt:
let g:ale_cpp_gcc_options = '-std=c++14 -Wall -lncurses' 

Is there a  way to do this?

**Comment by w0rp** [comment]
I take it `-l` arguments have to come after `-`? Are there any other types of arguments which need to appear at the end? Maybe we'll just have to add another global variable.

**Comment by JSybrandt** [comment]
I assume. I think any flags for the linter occur at the end.

**Comment by esran** [comment]
I don't think you need -l parameters for linting. They're for linking surely?

**Comment by JSybrandt** [comment]
Well my issue was that without -l ncurses the linter won't recognize any ncurses commands. Is there a way to include that library without the -l flag?

**Comment by w0rp** [comment]
I think @esran might be right. I think `-l` is just for linking with a library, separate from reading header files. I can't remember if there's a "don't link" option for `gcc`, but I think there might be. That might be an answer.

**Comment by w0rp** [comment]
Yeah, the `gcc` command should be doing that already. The `-S` flag is being used, and that means no assembling or linking should be done. https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html#index-S

**Comment by w0rp** [comment]
What errors do you receive?

**Comment by JSybrandt** [comment]
I am getting ".*was not declared in this scope"
![image](https://cloud.githubusercontent.com/assets/2685772/24279359/bbd89fae-101f-11e7-8b11-2995a3472480.png)

This code compiles btw.

**Comment by esran** [comment]
I suspect that when linting it is being stricter than the compiler. Those first four lines (noe shown) would be key. Maybe a missing include for the curses header file?

**Comment by w0rp** [comment]
@esran Yes, I think that makes sense. Maybe GCC is letting you get away without including headers if you link against curses, like an automatic header include. After some quick reading, this does appear to be how GCC works.

I wonder if it might make sense then to add an option for setting linker flags. It might be the easiest way to fix problems like these for some users. It would be nice to somehow configure these settings per-project, or automatically read project settings and set the flags for you.

**Comment by w0rp** [comment]
I can't repeat the issue on my machine and I don't know what to do about it. If anyone has any ideas, open a pull request.

**Comment by w0rp** [comment]
Almost all C/C++ issues with flags should now be discussed in #3276, so a comprehensive solution can be found for most people, for automatically detecting flags.
