### ISSUE TITLE
Add support for `prettier-standard` as a formatter for yaml

### ISSUE THREAD

**Issue by andres-lowrie** [dense-analysis/ale#4020]
Probably mega niche here but I think it would be cool if support for configuring [prettier-standard](https://github.com/sheerun/prettier-standard) as a yaml fixer was added.

Currently for yaml you can run `prettier` (which is awesome) but it would be awsome-er if we could configure `prettier-standard`; this way I could use one tool instead of 2

----

Side note: I use `ftplugin` files for each language, if I can achieve this via some clever vimL then that's cool too

```vimL
" $HOME/.vim/ftplugin/yaml.vim
let b:ale_fixers = ['prettier']
let b:ale_linters = ['yamllint']
```

Would like to do
```vimL
" $HOME/.vim/ftplugin/yaml.vim
let b:ale_fixers = ['prettier_standard'] " Using underscore as per javascript config
let b:ale_linters = ['yamllint']
```

but totally open to hacking to get it to work, just guidance as I'm still learning vimL

**Comment by hsanson** [comment]
Check `:h ale#fix#registry#Add()` for documentation on how to register your own custom fixer. There is an example there with luafmt.

Both ale_fixers and ale_linters should be dictionaries so I think your current configuration is not working. Also there is no need to define them as  all linters/fixers should be enabled if available on your system.

After you define your custom fixer for YAML using prettier_standard you should be able to use it running `ALEFix`,

**Comment by andres-lowrie** [comment]
let me give it a try, ty much

**Comment by andres-lowrie** [comment]
In case someone stumbles upon this in the future:

```vimL
fun! FormatYamlWPrettierStd(buffer) abort
  return {
        \ 'command': 'prettier-standard --parser yaml --stdin'
        \}
endfun
execute ale#fix#registry#Add('yaml_prettier_standard', 'FormatYamlWPrettierStd', ['yaml'], 'Format yaml with prettier-standard')

let b:ale_fixers = ['yaml_prettier_standard']
```
