### ISSUE TITLE
rustc linter should default to using stable interface

### ISSUE THREAD

**Issue by nospam2998** [dense-analysis/ale#4086]
See #1031, #1684 and  [StackOverflow 51485765](https://stackoverflow.com/q/51485765/run-rustc-without-generating-any-files).

While the default options to rustc has been discussed before, the outcome seems a bit misinformed. The statement _people on older versions can change their options appropriately_ suggests a lack of contextual understanding. [Appendix G - How Rust is Made and “Nightly Rust”](https://doc.rust-lang.org/book/appendix-07-nightly-rust.html) should be relevant background reading.

Features hidden behind `-Z` will always be unstable and are inappropriate to use as defaults. Quoting [rustc doc](https://doc.rust-lang.org/rustc/command-line-arguments.html):

> -Z: set unstable options

Once features are stabilized they end up accessible through a stable interface. Ending compilation after generating a mid-level intermediate representation is a more appropriate default. Anyone needing to track _+nightly_ can easily update their options.

Please consider merging [fix/use_stable_rust](https://git.netizen.se/ale/commit/?h=fix/use_stable_rust). I'm reluctant to submit a pull request as my committer and author fields for [PR#4050](https://github.com/dense-analysis/ale/pull/4050) were messed up through that process. [_For web-based Git operations_](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address) that buggy behavior is documented as expected.

**Comment by hsanson** [comment]
@nospam2998 review of #4087 would be appreciated.
