### ISSUE TITLE
README.md invites to non-existent #vim-ale on FreeNode

### ISSUE THREAD

**Issue by nospam2998** [dense-analysis/ale#4091]
## Information

**VIM version**

N/A

Operating System: N/A

## What went wrong

According to [README.md:388](https://github.com/dense-analysis/ale/blob/master/README.md?plain=1#L388-L389) there should be an #ale-vim channel on FreeNode. However [FreeNode essentially is no more](https://en.wikipedia.org/wiki/Freenode#Ownership_change_and_conflict) and thus this information is outdated.

Did the channel move some other network, or should the section in question simply be removed from the file?

**Comment by w0rp** [comment]
I've updated the README to mention the Libera channel I created a while ago, and my bouncer has been lurking in. Something happened with Freenode where I couldn't connect to it any more with ZNC without changing something in my configuration and people moved away from Freenode anyway, so I just moved the channel over. I haven't been visiting IRC too often recently, but I'll keep it open a bit more often.
