### ISSUE TITLE
 g:ale_disable_lsp=1 disables rust-analyzer even as a linter

### ISSUE THREAD

**Issue by laoshaw** [dense-analysis/ale#4095]
ALE uses ale_disable_lsp to disable all LSPs.

However some LSPs are used as a linter, e.g. rust-analyzer. If I disable lsp(so I can use coc solely for auto-completion) rust-analyzer will be disabled.

Can we use LSP as linter while not for auto-completion?

**Comment by hsanson** [comment]
Is possible to disable ALE completion by setting `g:ale_completion_enabled` to zero while still keeping the LSP features.

**Comment by laoshaw** [comment]
Thanks for the tip.
