### ISSUE TITLE
Bug: shellcheck fails for .zsh files

### ISSUE THREAD

**Issue by ds2606** [dense-analysis/ale#4100]
Shellcheck does not recognize zsh, and fails (exit code 4) when ALE attempts to execute `shellcheck -s zsh` on .zsh files, giving no output.

Currently I made a hotfix in my local build by hardcoding the `dialect` to `bash` in `autoload/handlers/shellcheck.vim`

I don't know ALE well enough to make a PR, but it seems that `l:possible_shell` should be restricted to valid dialects recognized by `shellcheck`: `sh, bash, dash`, and `ksh`. 

Currently line 10 reads:
```vim
 let l:possible_shell = ['bash', 'dash', 'ash', 'tcsh', 'csh', 'zsh', 'ksh', 'sh']
```

Therefore, it seems that `tcsh, csh, zsh` and `ash` need to be removed in order to prevent `shellcheck` failure in ALE for zsh (and presumably also the other aforementioned invalid dialects).

**Comment by w0rp** [comment]
`shellcheck` doesn't really support zsh. See this issue: https://github.com/koalaman/shellcheck/issues/809

You can set `ale_sh_shellcheck_dialect` to `'bash'` and it will work on most `zsh` code where it doesn't differ from Bash.

**Comment by ds2606** [comment]
thanks w0rp!
