### ISSUE TITLE
E714 on hover error occurs while editing main.go

### ISSUE THREAD

**Issue by systemmonkey42** [dense-analysis/ale#4139]
## Information

**VIM version**

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  3 2022 13:12:08)
Included patches: 1-4669

Operating System: Ubuntu 20.04

## What went wrong

While editing a "golang" source file, the following message appear;
```
Error detected while processing function <SNR>270_VimOutputCallback[6]..<lambda>14[1]..ale#lsp#HandleMessage[30]..ale#hover#HandleLSPRes
ponse:
line   36:
E714: List required
```

(LSP is `gopls --mode stdio`, visible in the output of `ps`)

This occurs when hovering over a parameter.

I added the following to ale/autoload/ale/hover.vim (after line 224)
```
         echom 'commands='.string(l:commands)
         echom 'lines='.string(l:lines)
         echom 'options='.string(l:options)
```
Which resulted in the following output:
```
"src/main.go" 34L, 582B
commands=[]
lines=['var userInput int']
options={'hover_from_balloonexpr': 0, 'show_documentation': 0, 'column': 31, 'line': 23, 'truncated_echo': 1, 'buffer': 1}
```
Given `options.truncated_echo` is equal to `1`, the error appears to be on line 234 of `autoload/ale/hover.vim` (aka, line 36 `ale#hover#HandleLSPResponse`)
```
               call ale#cursor#TruncatedEcho(join(l:lines[0], '\n'))
```
Here, it attempts to use `join()` to concatenate a string as if it were an array.

Removing the "join()" wrapper solves the issue, however I dont know if `lines[0]` is guaranteed to be a string, or might sometimes be an array..

**Comment by systemmonkey42** [comment]
FYI, this was changed from the original *working* code
```
            call ale#cursor#TruncatedEcho(l:lines[0])
```
to
```
            call ale#cursor#TruncatedEcho(join(l:lines[0], '\n'))
```
two days ago in commit b3d1d6e

**Comment by gmelodie** [comment]
Same here, `Ubuntu 20.04` `NVIM v0.6.1`. Proposed workaround above seems to fix the issue.

**Comment by hsanson** [comment]
@systemmonkey42 would be possible for you to test if #4144 fixes this issue?  This reverts some of the changed made by #3888 that resulted in this issue and #4141.

**Comment by systemmonkey42** [comment]
Thanks, that solves the issue.

**Comment by hsanson** [comment]
The PR #4141 that patches this is merged. Hope it solves the problem.

Note this is a patch and not really a fix. I am not knowledgable enough in that part of ALE to provide a proper fix. I am not sure where that line[0] that caused the issue comes from or if it is always a string or can be an array.
