### ISSUE TITLE
Stuck at "Press enter or type command to enter"

### ISSUE THREAD

**Issue by vicyyn** [dense-analysis/ale#4148]
Pretty annoying that I have to click multiple keys in order to get out of the "Press enter or type command to enter"
Looking for a fix :)) thanks in advance.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/55297234/162082920-4951038b-90a0-430b-a756-ee757e28b74d.png">

**Comment by hsanson** [comment]
Please update your version of ALE to latest master. This was addressed in #4141.
