### ISSUE TITLE
No message when try to use LSP with no project root.

### ISSUE THREAD

**Issue by j0ng4b** [dense-analysis/ale#4155]
This given me many headacher when I was using `clangd` without a project root, simple standalone test file, and noticed that `clangd` doens't even get executed. Then I found this when trying to find the issue on source code:
https://github.com/dense-analysis/ale/blob/607f33a1b0f662d9809d54363e8e81a4965862ce/autoload/ale/lsp_linter.vim#L430-L434

So, if showed some message to user (like me) would be really appreciated, because if I knew this before I wouldn't spent much time to find this "issue".

Please show some warning about this limitation or make possible run lsp without project root like other lsp clients.

**Comment by w0rp** [comment]
I agree. I would like to reveal it probably in `:ALEInfo`. Just something that doesn't nag people.
