### ISSUE TITLE
Add option g:ale_sign_column_never

### ISSUE THREAD

**Issue by christina002** [dense-analysis/ale#4191]
Hi,

I usually trim down my vi/vim sessions to minimum "clutter" and would love to have an option to turn off the gutter for good. I'm fine with error messages popping up in the status line when I move the cursor over the corresponding editor line, no additional feedback needed.

Something like g:ale_sign_column_never=1

**Comment by hsanson** [comment]
I think that setting both `g:ale_set_signs` and `g:ale_sign_column_always` to zero should do what you want. The gutter column (sign column) dissapears and is never shown by ALE.  Other plugins may be enabling it.

**Comment by christina002** [comment]
Yes, indeed - setting g:ale_set_signs = 0 did the trick. Thanks!
