### ISSUE TITLE
Support for ansible-language-server

### ISSUE THREAD

**Issue by morph027** [dense-analysis/ale#4246]
Just dicovered https://github.com/ansible/ansible-language-server/. Tried to add it as source for `ansible_lint` but could not get it working...

**Comment by maxamillion** [comment]
I would also like to request this and have also failed in my attempts to get it working, though that is likely due to my ignorance.

Thank you in advance!

**Comment by maxamillion** [comment]
I would gladly contribute to funding the development of this feature if we can do a bug bounty for it or something. :)
