### ISSUE TITLE
Tell users which linter produced an error

### ISSUE THREAD

**Issue by bkrl** [dense-analysis/ale#4255]
There seems to be no easy way to tell which linter produced a given error message. I think it would be nice if each error message is prefixed with the name of the linter.

**Comment by RyanSquared** [comment]
I have `let g:ale_echo_msg_format = '[%linter%] %s [%severity%:%code%]'` which correctly shows which linter produced an error. You can check the documentation of `:h g:ale_echo_msg_format` to find more info about this option.
