### ISSUE TITLE
Virtual Text Duplication Bug

### ISSUE THREAD

**Issue by amadeus** [dense-analysis/ale#4294]
## Information

**VIM version**
MacVim
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Aug 24 2022 11:13:52)
macOS version - x86_64
Included patches: 1-246  

Operating System: macOS 12.5.1

## What went wrong

When switching between splits of the same filetype, the virtual text error seems to duplicate, I've attached a video showing the issue:

https://user-images.githubusercontent.com/83376/186532231-0dc0f9a2-53c0-474a-9ad8-6d0654123db0.mp4

### :ALEInfo
<details>
  <summary>Expand</summary>

 Current Filetype: typescript.tsx
Available Linters: ['cspell', 'deno', 'eslint', 'standard', 'tailwindcss', 'tslint', 'tsserver', 'typecheck', 'xo']
  Enabled Linters: ['eslint', 'tslint', 'tsserver', 'typecheck', 'xo']
  Ignored Linters: []
 Suggested Fixers: 
  'deno' - Fix TypeScript using deno fmt.
  'dprint' - Pluggable and configurable code formatting platform
  'eslint' - Apply eslint --fix to a file.
  'prettier' - Apply prettier to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'tslint' - Fix typescript files with tslint --fix.
  'xo' - Fix JavaScript/TypeScript files using xo --fix.
 Linter Variables:

let g:ale_typescript_tslint_config_path = ''
let g:ale_typescript_tslint_executable = 'tslint'
let g:ale_typescript_tslint_ignore_empty_files = 0
let g:ale_typescript_tslint_rules_dir = ''
let g:ale_typescript_tslint_use_global = 0
let g:ale_typescript_tsserver_config_path = ''
let g:ale_typescript_tsserver_executable = 'tsserver'
let g:ale_typescript_tsserver_use_global = 0
let g:ale_typescript_xo_executable = 'xo'
let g:ale_typescript_xo_options = ''
let g:ale_typescript_xo_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 0
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 200
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '[%linter%]% (code)% %s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'stylus': ['prettier'], 'c': ['clang-format'], 'typescript': ['prettier'], 'json': ['prettier'], 'javascript': ['prettier'], 'css': ['prettier'], 'python': ['black', 'isort']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'typescript': ['eslint', 'tslint', 'tsserver', 'typecheck', 'xo'], 'javascript': ['eslint', 'fecs', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']}
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '[%linter%]% (code)% %s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_root = {}
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 1
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 0
  Command History:

(executable check - failure) typecheck
(executable check - failure) xo
(started) ['/bin/zsh', '-c', 'cd ''/Users/amadeus/Developer/discord'' && ''/Users/amadeus/Developer/discord/node_modules/.bin/eslint_d'' -f json --stdin --stdin-filename ''/Users/amadeus/Developer/discord/discord_app/uikit/QuickSwitcherResults.tsx'' < ''/var/folders/jw/nq6tnmks7rd61y_4s00cchth0000gn/T/vPrN7nD/52/QuickSwitcherResults.tsx''']
(executable check - failure) tslint
(executable check - failure) typecheck
(executable check - failure) xo
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/amadeus/Developer/discord'' && ''/Users/amadeus/Developer/discord/node_modules/.bin/eslint_d'' -f json --stdin --stdin-filename ''/Users/amadeus/Developer/discord/discord_app/uikit/QuickSwitcherResults.tsx'' < ''/var/folders/jw/nq6tnmks7rd61y_4s00cchth0000gn/T/vPrN7nD/54/QuickSwitcherResults.tsx''']

<<<OUTPUT STARTS>>>
[{"filePath":"/Users/amadeus/Developer/discord/discord_app/uikit/QuickSwitcherResults.tsx","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[{"ruleId":"flowtype/valid-syntax","replacedBy":[]},{"ruleId":"handle-callback-err","replacedBy":[]},{"ruleId":"no-negated-in-lhs","replacedBy":["no-unsafe-negation"]},{"ruleId":"no-new-require","replacedBy":[]},{"ruleId":"no-path-concat","replacedBy":[]}]}]
<<<OUTPUT ENDS>>>

(executable check - failure) tslint
(executable check - failure) typecheck
(executable check - failure) xo
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/amadeus/Developer/discord'' && ''/Users/amadeus/Developer/discord/discord_app/node_modules/.bin/prettier'' --stdin-filepath ''/Users/amadeus/Developer/discord/discord_app/uikit/QuickSwitcherResults.tsx'' --stdin < ''/var/folders/jw/nq6tnmks7rd61y_4s00cchth0000gn/T/vPrN7nD/55/QuickSwitcherResults.tsx''']
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/amadeus/Developer/discord'' && ''/Users/amadeus/Developer/discord/node_modules/.bin/eslint_d'' -f json --stdin --stdin-filename ''/Users/amadeus/Developer/discord/discord_app/uikit/QuickSwitcherResults.tsx'' < ''/var/folders/jw/nq6tnmks7rd61y_4s00cchth0000gn/T/vPrN7nD/56/QuickSwitcherResults.tsx''']

<<<OUTPUT STARTS>>>
[{"filePath":"/Users/amadeus/Developer/discord/discord_app/uikit/QuickSwitcherResults.tsx","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[{"ruleId":"flowtype/valid-syntax","replacedBy":[]},{"ruleId":"handle-callback-err","replacedBy":[]},{"ruleId":"no-negated-in-lhs","replacedBy":["no-unsafe-negation"]},{"ruleId":"no-new-require","replacedBy":[]},{"ruleId":"no-path-concat","replacedBy":[]}]}]
<<<OUTPUT ENDS>>>

(executable check - failure) tslint
(executable check - failure) typecheck
(executable check - failure) xo
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/amadeus/Developer/discord'' && ''/Users/amadeus/Developer/discord/node_modules/.bin/eslint_d'' -f json --stdin --stdin-filename ''/Users/amadeus/Developer/discord/discord_app/uikit/QuickSwitcherResults.tsx'' < ''/var/folders/jw/nq6tnmks7rd61y_4s00cchth0000gn/T/vPrN7nD/58/QuickSwitcherResults.tsx''']

<<<OUTPUT STARTS>>>
[{"filePath":"/Users/amadeus/Developer/discord/discord_app/uikit/QuickSwitcherResults.tsx","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[{"ruleId":"flowtype/valid-syntax","replacedBy":[]},{"ruleId":"handle-callback-err","replacedBy":[]},{"ruleId":"no-negated-in-lhs","replacedBy":["no-unsafe-negation"]},{"ruleId":"no-new-require","replacedBy":[]},{"ruleId":"no-path-concat","replacedBy":[]}]}]
<<<OUTPUT ENDS>>>

(executable check - failure) tslint
(executable check - failure) typecheck
(executable check - failure) xo
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/amadeus/Developer/discord'' && ''/Users/amadeus/Developer/discord/discord_app/node_modules/.bin/prettier'' --stdin-filepath ''/Users/amadeus/Developer/discord/discord_app/uikit/QuickSwitcherResults.tsx'' --stdin < ''/var/folders/jw/nq6tnmks7rd61y_4s00cchth0000gn/T/vPrN7nD/59/QuickSwitcherResults.tsx''']
</details>

**Comment by vimpostor** [comment]
This will be fixed with the first commit of #4289
