### ISSUE TITLE
Add support for ruff linter for python

### ISSUE THREAD

**Issue by TheEdgeOfRage** [dense-analysis/ale#4301]
**Name:** ruff
**URL:** https://github.com/charliermarsh/ruff

Ruff is a new Python linter written in Rust that promises to be 10-100x faster than other linters (They provide benchmarks that seem to prove them correct). It seems like an interesting project and might be worth adding support for in Ale.

**Comment by ssokolow** [comment]
I do effectively all my linting through ALE, so this would be valuable to me.

I'd contribute a patch myself but, at the moment, I've had to put a hold on all new things to focus on clearing out backlogged mess. Someday maybe, given how helpful it'd be to have that speedup.

**Comment by mfurquimdev** [comment]
This was already merged. Should this issue be closed?

**Comment by dvzrv** [comment]
@w0rp: It would be awesome if you could tag a release for this.

We have this plugin available on Arch Linux (and I have just added ruff to the list of official packages as well), but currently the integration is unfortunately not there.
Thanks a lot!

**Comment by hsanson** [comment]
Ruff is already supported by ALE. Closing.

**Comment by dvzrv** [comment]
@hsanson Yes, but for this to arrive in downstream packages, it needs a release. Could you create one? That would be very much appreciated! :)

**Comment by hsanson** [comment]
I see.  Releases are done by @w0rp so we would have to wait until @w0rp has some time to do the release.  Sorry.

**Comment by jgb** [comment]
@yining could it be that there is a bug in https://github.com/dense-analysis/ale/pull/4347 ?
The first time I try to do :ALEFix on a newly opened python file, I get the error `There is no fixer named ruff`.
When I then do an :ALELint, and then retry :ALEFix, the fix works fine.
Repeated this with several python files. Fix won't work until I first run a lint. After the first lint, fix works fine.

My ALE config:

let g:ale_linters = { 'python': ['ruff', ], }
let g:ale_fixers = { '*': ['remove_trailing_lines', 'trim_whitespace'], 'python': ['ruff', 'black'], }

**Comment by yining** [comment]
@jgb could you please help check if the PR #4393 fixed the bug? thanks.
