### ISSUE TITLE
Infrequent Error: E966: Invalid line number: 0

### ISSUE THREAD

**Issue by U1s2e3r4n5a6m7e** [dense-analysis/ale#4331]
## Information

**VIM version**

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Oct  6 2022 13:11:02)
Included patches: 1-669
```

Operating System: `Linux 5.19.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 28 Sep 2022 13:21:25 +0000 x86_64 GNU/Linux`

## What went wrong

```
Error detected while processing function <SNR>74_VimOutputCallback[6]..<lambda>7[1]..ale#lsp#HandleMessage[30]..ale#lsp_linter#HandleLSPResponse[8]..<SNR>70_HandleLSPDiagnostics[20]..ale#e ngine#HandleLoclist[40]..ale#engine#SetResults[23]..ale#virtualtext#SetTexts[13]..ale#virtualtext#ShowMessage:
line   33:
E966: Invalid line number: 0
```

## Reproducing the bug

0. This error is not consistent; sometimes I get, most of the time I don't
1. `vim src/main.rs`
2. make a mistake: like return a number in main function
3. `:up`

### :ALEInfo
<details>
  <summary>Expand</summary>

 Current Filetype: rust
Available Linters: ['analyzer', 'cargo', 'cspell', 'rls', 'rustc']
  Enabled Linters: ['analyzer']
  Ignored Linters: []
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'rustfmt' - Fix Rust files with Rustfmt.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_rust_analyzer_config = {}
let g:ale_rust_analyzer_executable = 'rust-analyzer'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'sh': ['shfmt']}
let b:ale_fixers = ['rustfmt', 'remove_trailing_lines', 'trim_whitespace']
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let b:ale_linters = ['analyzer']
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_root = {}
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 2
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) rust-analyzer
(started) ['/bin/zsh', '-c', '''rust-analyzer''']
</details>

**Comment by w0rp** [comment]
I should have fixed this now.

**Comment by U1s2e3r4n5a6m7e** [comment]
I don't get this error now. Thanks!
