### ISSUE TITLE
Add support for pycln

### ISSUE THREAD

**Issue by w0rp** [dense-analysis/ale#4340]
**Name:** pycln
**URL:** https://github.com/hadialqattan/pycln

pylcn is a simple tool for removing unused import statements from Python code. We could run `pycln -c %t` as the command to look for problems in files to have it function as a linter. `pycln %t` should most likely work as a fixer command to remove the imports. I don't think there's anything about the files on disk it will need to know about other than maybe where a configuration file is.

**Comment by hsanson** [comment]
Added in #4415
