### ISSUE TITLE
Add support for GH workflow linter actionlint

### ISSUE THREAD

**Issue by ligurio** [dense-analysis/ale#4359]
**Name:** actionlint
**URL:** https://github.com/rhysd/actionlint

There are YAML configs for Github workflows [^1].
It would be nice to integrate syntastic with linter for GH workflows format [^2].

[^1]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
[^2]: https://github.com/rhysd/actionlint

Similar issue for syntastic - https://github.com/vim-syntastic/syntastic/issues/2410

**Comment by pixelastic** [comment]
Hello,

It seem that `actionlint` is already supported: https://github.com/dense-analysis/ale/blob/master/ale_linters/yaml/actionlint.vim
