### ISSUE TITLE
Add support for refurb to modernize Python codebases 

### ISSUE THREAD

**Issue by aurelg** [dense-analysis/ale#4362]
**Name:** refurb
**URL:** https://github.com/dosisod/refurb

`refurb` is a tool for refurbishing and modernizing Python codebases. It would be extremely useful to have notifications on the fly, while writing/refactoring code.

**Comment by JonZeolla** [comment]
@hsanson should this be closed now, based on https://github.com/dense-analysis/ale/commit/cad8f8e68338221e157adb1fffbe8eb16c430fe0?
