### ISSUE TITLE
Signs become desynced with content

### ISSUE THREAD

**Issue by CGamesPlay** [dense-analysis/ale#4382]
When ale puts signs on my errors, they quickly lose sync with the contents of the buffer.

- Adding lines above the errors pushes the signs down but the underline remains in the same place.
- Deleting lines with signs does not delete the sign.
- Undo pushes the signs down to be below where the error actually was.

I've included an ASCIInema showing the issue below, but unfortunately the decorations (underline) don't render.

[![asciicast](https://asciinema.org/a/woX6w22FJYRuG9t4YpCOT909X.svg)](https://asciinema.org/a/woX6w22FJYRuG9t4YpCOT909X)

Relevant version numbers:
- Ale 5ce2bf84ca00cee8f375f108952789302980ae57
- MacVim 9.0 (2022 Jun 28, compiled Sep 15 2022 19:27:32), included patches: 1-472

Happy to try some workarounds/fixes, but unfortunately I don't really know anything about VimScript or the sign system in Vim. Thanks for looking into this!

**Comment by w0rp** [comment]
This is probably a "this is how Vim works" thing, but maybe there's a recent change to Vim which means we could do it better in more recent versions. Generally you need to wait for ALE to lint again to update things.

**Comment by w0rp** [comment]
This is pretty much how Vim works. ALE needs to lint again to move the signs.

What I will be doing in future for NeoVim is making using the diagnostics API for displaying problems the default using the same settings everyone is already using to control things like if signs are enabled and which icons they use. That might make things better then.

**Comment by CGamesPlay** [comment]
Sad. Thanks for investigating.
