### ISSUE TITLE
Add option to ignore specific errors or warnings

### ISSUE THREAD

**Issue by massimiliano-della-rovere** [dense-analysis/ale#4385]
Add an option so that a specific error or warning is ignored in the next line/function/class.

Something like a comment (filetype syntax dependant) recognized by ALE:
`#ALEignore token,token,... scope`

example: ignore warning [SC2034] in a BaSh script

`# ALEIgnore [SC2034] line`
`dirname=$(which dirname)`

or

`# ALEIgnore [SC2034] function`
`function test {`
`    local dirname=$(which dirname)`
`}`

etc

**Comment by hsanson** [comment]
This is highly dependant on the filetype and linter tools being used.  For example shellcheck already supports such directives to ignore certain warnings/errors:  https://github.com/koalaman/shellcheck/wiki/Directive

**Comment by massimiliano-della-rovere** [comment]
Thanks,
I never thought to search for these kinds of directives into the linters!

Il sab 10 dic 2022, 10:01 Horacio Sanson ***@***.***> ha
scritto:

**Comment by w0rp** [comment]
I wouldn't ever read code to ignore errors or warnings. That's the job of the linter. shellcheck does actually have syntax for ignoring errors. I have some warnings at work that annoy me too.

I'm going to stick with my principle that clients which run linters should not have options to ignore specific errors or warnings. That will lead to one dev in a team ignoring what everyone else sees, or worse, everyone ignoring something and telling new devs, "Oh yeah, we ignore that. You need to configure your editor this way." The way to deal with problems in code is to either fix them or configure the tool to ignore them so everyone sees the same thing.
