### ISSUE TITLE
Enable virtualtext by default

### ISSUE THREAD

**Issue by w0rp** [dense-analysis/ale#4396]
Vim 9 and recent NeoVim versions have generally pretty good virtualtext support. We could start enabling virtualtext messages by default with clear documentation for how to turn the information off easily so the default experience for new users is that warnings and errors start appearing in their editors in a place that's very easy to view.

The demo GIF in the ALE README could be updated to show virtualtext errors and warnings, plus `:ALEFix`, and maybe some completion being done too.

**Comment by w0rp** [comment]
I might set it so the default is based on a `has` check for new enough Vim and NeoVim versions.

**Comment by yous** [comment]
With `let g:ale_set_highlights = 0`, this causes the error `E970: Unknown highlight group name: 'ALEVirtualTextError'`.

**Comment by marcinn** [comment]
May I suggest disabling this "feature" at default? It generates a mess in a editor window, which reduces code readability. The window with issues / statusline are good enough.
