### ISSUE TITLE
Error after upgrade from v3.2.0 to v3.3.0

### ISSUE THREAD

**Issue by arthurkiller** [dense-analysis/ale#4410]
I'm not sure what this mean and where it comes from.

```
Error detected while processing function <SNR>112_VimOutputCallback[6]..<lambda>14[1]..ale#lsp#HandleMessage[30]..ale#lsp_linter#HandleLSPRespo nse[8]..
<SNR>107_HandleLSPDiagnostics[20]..ale#engine#HandleLoclist[40]..ale#engine#SetResults[23]..
ale#virtualtext#SetTexts[9]..ale#virtualtex t#ShowMessage:

E275: Cannot add text property to unloaded buffer
```

## Information

**VIM version**

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep  1 2022 11:45:02)
Included patches: 1-343

```

Operating System: 

## What went wrong

Something went wrong in specifically this place, and I also searched through both open and closed issues for the same problem before reporting a bug here.

Are you having trouble configuring ALE? Try asking for help on [Stack Exchange](https://vi.stackexchange.com/) or perhaps on [Reddit](https://www.reddit.com/r/vim/) instead. The GitHub issue tracker should be used for reporting bugs or asking for new features.

## Reproducing the bug

1. just highlight some word then find next by press `n`

### :ALEInfo
ale version 
* master 
* v 3.3.0

**Comment by w0rp** [comment]
@arthurkiller I've pushed a fix now to ignore errors from `prop_add` so we just press on if it happens to execute at the wrong time. Let me know if that fixes your issue.

**Comment by arthurkiller** [comment]
> @arthurkiller I've pushed a fix now to ignore errors from `prop_add` so we just press on if it happens to execute at the wrong time. Let me know if that fixes your issue.

cool, it works for me. thx for your reply
