### ISSUE TITLE
Error (Invalid buffer) with fzf-lua

### ISSUE THREAD

**Issue by misaflo** [dense-analysis/ale#4413]
## Information

**VIM version**

    NVIM v0.8.2
    Build type: Release
    LuaJIT 2.1.0-beta3

Operating System: `Debian GNU/Linux 11 (bullseye)`

## What went wrong

No problem when opening a file directly from the command line.

When opening neovim, and using [fzf-lua](https://github.com/ibhagwan/fzf-lua)
to open a file, the command `:ALEToggle` display this error:

    Error detected while processing function ale#toggle#Toggle[10]..ale#engine#CleanupEveryBuffer[10]..ale#engine#Cleanup[14]..ale#engine#RunLinters[4]..<SNR>63_GetLintFileValues[27]..<lambda>26[1]..<SNR>63_RunLinters[26]..ale#engine#SetResults[23]..ale#virtualtext#SetTexts[5]..ale#virtualtext#Clear:
    line    6:
    E5555: API call: Invalid buffer id: 7

I don't see other buffer with `:ls`.

## Reproducing the bug

Use neovim, install plugins `ale` and `fzf-lua.` Open a file with fzf (`:FzfLua
files`), and toggle ALE (`:ALEToggle`).

I can also report this bug in fzf-lua repository if needing.

### :ALEInfo
<details>
  <summary>Expand</summary>

     Current Filetype: ruby
    Available Linters: ['brakeman', 'cspell', 'debride', 'rails_best_practices', 'reek', 'rubocop', 'ruby', 'solargraph', 'sorbet', 'standardrb']
       Linter Aliases:
    'sorbet' -> ['srb']
      Enabled Linters: ['brakeman', 'cspell', 'debride', 'rails_best_practices', 'reek', 'rubocop', 'ruby', 'solargraph', 'sorbet', 'standardrb']
      Ignored Linters: []
     Suggested Fixers: 
      'prettier' - Apply prettier to a file.
      'remove_trailing_lines' - Remove all blank lines at the end of a file.
      'rubocop' - Fix ruby files with rubocop --auto-correct.
      'rufo' - Fix ruby files with rufo
      'sorbet' - Fix ruby files with srb tc --autocorrect.
      'standardrb' - Fix ruby files with standardrb --fix
      'syntax_tree' - Fix ruby files with stree write
      'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
     Linter Variables:
    
    let g:ale_ruby_brakeman_executable = 'brakeman'
    let g:ale_ruby_brakeman_options = ''
    let g:ale_ruby_debride_executable = 'debride'
    let g:ale_ruby_debride_options = ''
    let g:ale_ruby_rails_best_practices_executable = 'rails_best_practices'
    let g:ale_ruby_rails_best_practices_options = ''
    let g:ale_ruby_reek_executable = 'reek'
    let g:ale_ruby_reek_options = ''
    let g:ale_ruby_reek_show_context = 0
    let g:ale_ruby_reek_show_wiki_link = 0
    let g:ale_ruby_rubocop_executable = 'rubocop'
    let g:ale_ruby_rubocop_options = ''
    let g:ale_ruby_ruby_executable = 'ruby'
    let g:ale_ruby_solargraph_executable = 'solargraph'
    let g:ale_ruby_solargraph_options = {}
    let g:ale_ruby_sorbet_enable_watchman = 0
    let g:ale_ruby_sorbet_executable = 'srb'
    let g:ale_ruby_sorbet_options = ''
    let g:ale_ruby_standardrb_executable = 'standardrb'
    let g:ale_ruby_standardrb_options = ''
     Global Variables:
    
    let g:ale_cache_executable_check_failures = v:null
    let g:ale_change_sign_column_color = 0
    let g:ale_command_wrapper = ''
    let g:ale_completion_delay = v:null
    let g:ale_completion_enabled = 0
    let g:ale_completion_max_suggestions = v:null
    let g:ale_disable_lsp = 0
    let g:ale_echo_cursor = 1
    let g:ale_echo_msg_error_str = 'Error'
    let g:ale_echo_msg_format = '%code: %%s'
    let g:ale_echo_msg_info_str = 'Info'
    let g:ale_echo_msg_warning_str = 'Warning'
    let g:ale_enabled = 0
    let g:ale_fix_on_save = 0
    let g:ale_fixers = {'puppet': ['puppetlint'], '*': ['remove_trailing_lines', 'trim_whitespace'], 'ruby': ['rubocop']}
    let g:ale_history_enabled = 1
    let g:ale_history_log_output = 1
    let g:ale_keep_list_window_open = 0
    let g:ale_lint_delay = 200
    let g:ale_lint_on_enter = 1
    let g:ale_lint_on_filetype_changed = 1
    let g:ale_lint_on_insert_leave = 1
    let g:ale_lint_on_save = 1
    let g:ale_lint_on_text_changed = 'normal'
    let g:ale_linter_aliases = {}
    let g:ale_linters = {}
    let g:ale_linters_explicit = 0
    let g:ale_linters_ignore = {}
    let g:ale_list_vertical = 0
    let g:ale_list_window_size = 10
    let g:ale_loclist_msg_format = '%code: %%s'
    let g:ale_max_buffer_history_size = 20
    let g:ale_max_signs = -1
    let g:ale_maximum_file_size = v:null
    let g:ale_open_list = 0
    let g:ale_pattern_options = v:null
    let g:ale_pattern_options_enabled = v:null
    let g:ale_root = {}
    let g:ale_set_balloons = 0
    let g:ale_set_highlights = 1
    let g:ale_set_loclist = 1
    let g:ale_set_quickfix = 0
    let g:ale_set_signs = 1
    let g:ale_sign_column_always = 0
    let g:ale_sign_error = '>>'
    let g:ale_sign_info = '--'
    let g:ale_sign_offset = 1000000
    let g:ale_sign_style_error = '>>'
    let g:ale_sign_style_warning = '--'
    let g:ale_sign_warning = '--'
    let g:ale_sign_highlight_linenrs = 0
    let g:ale_statusline_format = v:null
    let g:ale_type_map = {}
    let g:ale_use_global_executables = v:null
    let g:ale_virtualtext_cursor = 'all'
    let g:ale_warn_about_trailing_blank_lines = 1
    let g:ale_warn_about_trailing_whitespace = 1
      Command History:
    
    (executable check - failure) brakeman
    (executable check - failure) cspell
    (executable check - failure) debride
    (executable check - failure) rails_best_practices
    (executable check - failure) reek
    (started) ['/bin/zsh', '-c', '''rubocop'' --format json --force-exclusion  --stdin ''/opt/path/to/my/file.rb'' < ''/tmp/nvim.login/pHRc0e/5/file.rb''']
    (finished - exit code 0) ['/bin/zsh', '-c', '''ruby'' -w -c ''/tmp/nvim.login/pHRc0e/6/file.rb''']
    
    <<<NO OUTPUT RETURNED>>>
    
    (executable check - failure) solargraph
    (executable check - failure) srb
    (executable check - failure) standardrb
</details>

**Comment by w0rp** [comment]
I've fixed this now and cherry-picked the fix to the branch for the coming 3.3.1 release.

**Comment by misaflo** [comment]
Thanks!
