### ISSUE TITLE
LSP does not init with content format markdown, so Hover/Detail remains unhiglighted

### ISSUE THREAD

**Issue by WooterTheTroubleshooter** [dense-analysis/ale#4450]
## Information

**VIM version**

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan 12 2023 11:41:18)
Included patches: 1-1182

Operating System: Arch Linux

## What went wrong

AleHover/AleDetail never contains markup. Although #3274 suggested this should have been supported.

## Reproducing the bug

1. `:ALEHover` any variable or type
2. Even though source documentation contains markdown, plaintext is shown in preview window or floating popup.
3. Wrap ale commands.
4. Notice  `"hover":{"dynamicRegistration":false,"contentFormat":["plaintext"]}`
5. Change `Lsp.vim` to send ['plaintext`, `markdown`] instead.
6. Try `:ALEHover` again.
7. Preview window is now colored and highlighted.

### :ALEInfo
<details>
  <summary>Expand</summary>
  Current Filetype: rust
Available Linters: ['analyzer', 'cargo', 'cspell', 'rls', 'rustc']
  Enabled Linters: ['analyzer']
  Ignored Linters: []
 Suggested Fixers:
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'rustfmt' - Fix Rust files with Rustfmt.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:
let g:ale_rust_analyzer_config = {'rust-analyzer.diagnostics.enable': v:true}
let g:ale_rust_analyzer_executable = 'rust-analyzer'
 Global Variables:
let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = '~/.vim/ale-command-wrapper.sh'
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = v:null
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'rust': ['rustfmt']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'rust': ['analyzer']}
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_root = {}
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_neovim_diagnostics_api = 0
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 'all'
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - success) rust-analyzer
(started) ['/bin/bash', '-c', '~/.vim/ale-command-wrapper.sh ''rust-analyzer''']
</details>

## Fix
```patch
diff --git a/autoload/ale/lsp.vim b/autoload/ale/lsp.vim
index daaed6fa..0519c798 100644
--- a/autoload/ale/lsp.vim
+++ b/autoload/ale/lsp.vim
@@ -424,7 +424,7 @@ function! s:SendInitMessage(conn) abort
     \                   'completionItem': {
     \                       'snippetSupport': v:false,
     \                       'commitCharactersSupport': v:false,
-    \                       'documentationFormat': ['plaintext'],
+    \                       'documentationFormat': ['plaintext', 'markdown'],
     \                       'deprecatedSupport': v:false,
     \                       'preselectSupport': v:false,
     \                   },
@@ -432,7 +432,7 @@ function! s:SendInitMessage(conn) abort
     \               },
     \               'hover': {
     \                   'dynamicRegistration': v:false,
-    \                   'contentFormat': ['plaintext'],
+    \                   'contentFormat': ['plaintext', 'markdown'],
     \               },
     \               'references': {
     \                   'dynamicRegistration': v:false,
```

**Comment by w0rp** [comment]
Likely a protocol update we need to handle. Feel free to create a PR for this. I might not get to it first.
