### ISSUE TITLE
"E484: Can't open file man syntax/ man.vim" error on symbol hover

### ISSUE THREAD

**Issue by iusmac** [dense-analysis/ale#4505]
ALE fails with the `E484: Can't open file man syntax/ man.vim` error on symbol hover. You can spot a trailing space before the language syntax file name.

This happens with https://github.com/bash-lsp/bash-language-server. A trailing space is intentionally added in https://github.com/bash-lsp/bash-language-server/blob/82d6897972378bc1ade0a79c1a26435878137bbc/server/src/server.ts#L810

This is still a valid extended Markdown syntax and must be handled on the ALE side.

**Comment by w0rp** [comment]
I've fixed this now with a test for it. Instead of trimming the string I edited the regex to not capture the spaces.
