### ISSUE TITLE
Is it asciidoc or asciidoctor?

### ISSUE THREAD

**Issue by mkschreder** [dense-analysis/ale#4510]
I see that ale defines linters for asciidoc files but Neovim defines filetype as asciidoctor. Should ale define asciidoctor filetype as well and register linters for it or is there a better solution?

**Comment by hsanson** [comment]
The file format (filetype) is [Asciidoc](https://asciidoc.org/). 

[Asciidoctor](https://asciidoctor.org/) is a  text processor (tool), written in Ruby language, that is able to parse and process Asciidoc files and converts them to other formats such as HTML, ePub, PDF, etc.   Similarities in names may or may not be coincidence...

**Comment by hsanson** [comment]
To have ALE work fine with asciidoctor filetype I have this in my configuration:

```
let g:ale_linter_aliases = {
      \ 'asciidoctor': 'asciidoc'
      \}
```

**Comment by mkschreder** [comment]
@hsanson perhaps it makes sense to set this alias by default?

**Comment by hsanson** [comment]
> @hsanson perhaps it makes sense to set this alias by default?

I don"t think ALE should have such workarounds to fix issues on other projects.  The proper thing to do is to report the issue to the project and have it fixed there (note: I see you created the issue already :+1: ).
