### ISSUE TITLE
Enforce C++ LLVM Linter use LLVM standard library

### ISSUE THREAD

**Issue by firejox** [dense-analysis/ale#4522]
If there are more C++ standard libraries exist in system, some C++ linter may not find the library properly. For example, both `g++` and `clang++` are installed, and system default library is `g++`. Then `clang++` and `clang-check` may not use LLVM standard library properly. [-stdlib](https://libcxx.llvm.org/UsingLibcxx.html#using-libc-when-it-is-not-the-system-default) option can make them use LLVM standard library. This could resolve #354 problem because `clang++` and `clang-check` will use LLVM standard library.

**Comment by pbnj** [comment]
Hi @firejox - 

According to ale docs:

```text
g:ale_c_cc_executable                                   *g:ale_c_cc_executable*
                                                        *b:ale_c_cc_executable*
  Type: |String|
  Default: `'<auto>'`

  This variable can be changed to use a different executable for a C compiler.

  ALE will try to use `clang` if Clang is available, otherwise ALE will
  default to checking C code with `gcc`.
```

Can you share the results of `:ALEInfo` once you open a C++ file in vim?

**Comment by w0rp** [comment]
I don't want to second guess the defaults clang itself uses here. If not using libc++ on some systems is the default, there's probably a good reason for it. As ever, you can set options per project to configure the compilers as needed.
