### ISSUE TITLE
Cannot enter insert mode after installing ALE

### ISSUE THREAD

**Issue by pstahlhofen** [dense-analysis/ale#4524]
## Information

**VIM version**

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov  5 2022 00:19:23)
macOS version - arm64

Operating System:
MacOS Ventura 13.1

## What went wrong

I installed ALE by downloading it and moving it to `~/.vim/plugin`. I also followed the instruction on setting up `:help ale` to show the correct output. However, every time I open a file I cannot enter insert mode. I ran `:map` and saw that all keys that would usually enter insert mode are mapped to `<Nop>`, i.e. they do nothing at all. Any ideas on how to resolve this?

## Reproducing the bug

1. Download ALE
2. Move it to `~/.vim/plugin`
3. Open an arbitrary file

### :ALEInfo
<details>
  <summary>Expand</summary>
  
 Current Filetype: python
Available Linters: ['bandit', 'cspell', 'flake8', 'flakehell', 'jedils', 'mypy', 'prospector', 'pycln', 'pycodestyle', 'pydocstyle', 'pyflakes', 'pylama', 'pylint', 'pylsp', 'pyre', 'pyright', 'refurb', 'ruff', 'unimport', 'vulture']
  Enabled Linters: ['flake8', 'mypy', 'pylint', 'pyright', 'ruff']
  Ignored Linters: []
 Suggested Fixers: 
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autoflake' - Fix flake issues with autoflake.
  'autoimport' - Fix import issues with autoimport.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'pycln' - remove unused python import statements
  'pyflyby' - Tidy Python imports with pyflyby.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'reorder-python-imports' - Sort Python imports with reorder-python-imports.
  'ruff' - A python linter/fixer for Python written in Rust
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:

let g:ale_python_auto_pipenv = '0'
let g:ale_python_auto_poetry = '0'
let g:ale_python_auto_virtualenv = 0
let g:ale_python_autoflake_executable = 'autoflake'
let g:ale_python_autoflake_options = ''
let g:ale_python_autoflake_use_global = 0
let g:ale_python_autoimport_executable = 'autoimport'
let g:ale_python_autoimport_options = ''
let g:ale_python_autoimport_use_global = 0
let g:ale_python_autopep8_executable = 'autopep8'
let g:ale_python_autopep8_options = ''
let g:ale_python_autopep8_use_global = 0
let g:ale_python_black_auto_pipenv = 0
let g:ale_python_black_auto_poetry = 0
let g:ale_python_black_change_directory = 1
let g:ale_python_black_executable = 'black'
let g:ale_python_black_options = ''
let g:ale_python_black_use_global = 0
let g:ale_python_flake8_auto_pipenv = 0
let g:ale_python_flake8_auto_poetry = 0
let g:ale_python_flake8_change_directory = 'project'
let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
let g:ale_python_isort_auto_pipenv = 0
let g:ale_python_isort_auto_poetry = 0
let g:ale_python_isort_executable = 'isort'
let g:ale_python_isort_options = ''
let g:ale_python_isort_use_global = 0
let g:ale_python_mypy_auto_pipenv = 0
let g:ale_python_mypy_auto_poetry = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_ignore_invalid_syntax = 0
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_show_notes = 1
let g:ale_python_mypy_use_global = 0
let g:ale_python_pyflyby_auto_pipenv = 0
let g:ale_python_pyflyby_auto_poetry = 0
let g:ale_python_pyflyby_executable = 'tidy-imports'
let g:ale_python_pyflyby_options = ''
let g:ale_python_pyflyby_use_global = 0
let g:ale_python_pylint_auto_pipenv = 0
let g:ale_python_pylint_auto_poetry = 0
let g:ale_python_pylint_change_directory = 1
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
let g:ale_python_pylint_use_msg_id = 0
let g:ale_python_pyright_auto_pipenv = 0
let g:ale_python_pyright_auto_poetry = 0
let g:ale_python_pyright_config = {}
let g:ale_python_pyright_executable = 'pyright-langserver'
let g:ale_python_pyright_use_global = 0
let g:ale_python_reorder_python_imports_executable = 'reorder-python-imports'
let g:ale_python_reorder_python_imports_options = ''
let g:ale_python_reorder_python_imports_use_global = 0
let g:ale_python_ruff_auto_pipenv = 0
let g:ale_python_ruff_auto_poetry = 0
let g:ale_python_ruff_change_directory = 1
let g:ale_python_ruff_executable = 'ruff'
let g:ale_python_ruff_options = ''
let g:ale_python_ruff_use_global = 0
let g:ale_python_yapf_executable = 'yapf'
let g:ale_python_yapf_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_root = {}
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_neovim_diagnostics_api = 0
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 'all'
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code -1) ['/bin/zsh', '-c', '''pylint'' --version']

<<<NO OUTPUT RETURNED>>>

(executable check - success) flake8
(finished - exit code -1) ['/bin/zsh', '-c', 'cd ''/Users/paulstahlhofen/Documents/Water_Futures/lsp-extended/src/experiment_scripts'' && ''flake8'' --version']

<<<NO OUTPUT RETURNED>>>

(executable check - failure) mypy
(executable check - success) pylint
(finished - exit code -1) ['/bin/zsh', '-c', 'cd ''/Users/paulstahlhofen/Documents/Water_Futures/lsp-extended/src/experiment_scripts'' && ''pylint'' --version']

<<<NO OUTPUT RETURNED>>>

(executable check - failure) pyright-langserver
(executable check - failure) ruff
(finished - exit code -1) ['/bin/zsh', '-c', 'cd ''/Users/paulstahlhofen/Documents/Water_Futures/lsp-extended/src/experiment_scripts'' && ''flake8'' --format=default - < ''/var/folders/2h/0t1dc8jd2ksc2_ds03wl4qxm0000gr/T/v9fEbty/3/plot_lsp.py''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code -1) ['/bin/zsh', '-c', 'cd ''/Users/paulstahlhofen/Documents/Water_Futures/lsp-extended/src/experiment_scripts'' && ''pylint'' --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/Users/paulstahlhofen/Documents/Water_Futures/lsp-extended/src/experiment_scripts/plot_lsp.py'' < ''/var/folders/2h/0t1dc8jd2ksc2_ds03wl4qxm0000gr/T/v9fEbty/4/plot_lsp.py''']

<<<NO OUTPUT RETURNED>>>

</details>

**Comment by pbnj** [comment]
Hi @pstahlhofen - 

After downloading ale, you should move into `~/.vim/pack/my_plugins/start/`. Then in your vimrc, make sure you put `packloadall` to load packages.

- See [`:h packages`](https://github.com/vim/vim/blob/4c0089d696b8d1d5dc40568f25ea5738fa5bbffb/runtime/doc/repeat.txt#L597).
- See [`:h :packloadall`](https://github.com/vim/vim/blob/4c0089d696b8d1d5dc40568f25ea5738fa5bbffb/runtime/doc/repeat.txt#L329)

**Comment by pstahlhofen** [comment]
Okay, thank you!
This resolved my issue
