### ISSUE TITLE
[ALE v4 Suggestion] Consider providing an ALE command for installing LSPs, linters, and fixers.

### ISSUE THREAD

**Issue by pbnj** [dense-analysis/ale#4537]
One very convenient feature I miss from other LSP plugins is the ability to install LSP servers through the vim plugin, like [`mason.nvim`](https://github.com/williamboman/mason.nvim#commands) and [`vim-lsp-settings`](https://github.com/mattn/vim-lsp-settings) plugin on top of `vim-lsp`.

These LSP plugins provide a command to install the LSP or prompt the user to pick from multiple LSP options to be installed based on filetype of the current buffer.

This is extremely useful in remote development setups, like [`devcontainer`](https://containers.dev/), [`devpod`](https://github.com/loft-sh/devpod), [codespaces](https://github.com/features/codespaces), ...etc. 

With `vim-lsp` or `mason.nvim`, getting started is as quick as syncing/cloning the (n)vim config into the container and running `:LspInstallServer` or `:MasonInstall`.

It would be a phenomenal experience if ALE were to have a similar feature (e.g. `:ALEInstall`) to install/update LSPs, linters, and fixers.

**Comment by w0rp** [comment]
I think this is best managed through a companion plugin. Ideally a plugin that can also work with Neovim's built in LSP configuration and maybe other plugins also. If you want to build it, I'll host it in the Dense Analysis organization.

**Comment by pbnj** [comment]
Agreed.

**Comment by w0rp** [comment]
@pbnj If you create a plugin for this, let me know. I would happily host it under the dense-analysis organisation.
