### ISSUE TITLE
Support `--target-dir` with `rust-analyzer`

### ISSUE THREAD

**Issue by mathstuf** [dense-analysis/ale#4557]
`rust-analyzer` currently locks the default build directory. It'd be nice to be able to use a different directory to avoid `cargo` commands blocking `rust-analyzer` and vice versa. I've tried adding things to `g:ale_rust_analyzer_config`, but I wasn't able to plumb through the `--target-dir` setting.

**Comment by pbnj** [comment]
Seems related to this https://github.com/rust-lang/rust-analyzer/issues/6007

Some notable take-aways from that thread:

- Try setting the config option `{ "rust-analyzer.server.extraEnv": { "CARGO_TARGET_DIR": "target/analyzer" } }`
- Set `rust-analyzer.check.extraArgs` configuration option to use the same target directory, like: `["--target-dir=target/analyzer"]` (see [rust-analyzer configuration docs](https://rust-analyzer.github.io/manual.html#configuration) for details)

Have you tried these first?

**Comment by mathstuf** [comment]
Ah, I missed the extra layer there. I had tried:

```vim
let g:ale_rust_analyzer_config = {
\  'rust-analyzer.server.extraEnv': {
\    'CARGO_TARGET_DIR': 'target/analyzer'
\  }
\}
```

**Comment by mathstuf** [comment]
That works, thanks. I'll see if I can improve the docs for that instead of just being "Dictionary with configuration settings for rust-analyzer.".
