### ISSUE TITLE
Add support for `ruff format`

### ISSUE THREAD

**Issue by JaRoSchm** [dense-analysis/ale#4609]
**Name:** ruff
**URL:** https://github.com/astral-sh/ruff/

In their last release ruff added a new formatter option. The style is intended to be compatible with black.
The documentation of the formatter can be found here: https://github.com/astral-sh/ruff/blob/main/crates/ruff_python_formatter/README.md

**Comment by treyhunner** [comment]
`ruff format` was in alpha. It's now in beta and [the ruff team has deemed it production-ready](https://astral.sh/blog/the-ruff-formatter).

It would be great to see support for this!

**Comment by crimsonknave** [comment]
#4645 added the `ruff_format` fixer. This issue should be resolved.

**Comment by JaRoSchm** [comment]
Thanks!
