### ISSUE TITLE
Floating window borders not visible in neovim

### ISSUE THREAD

**Issue by jmcantrell** [dense-analysis/ale#4615]
## Information

**VIM version**

NVIM v0.9.2
Build type: Release

Operating System: 
arch linux
Linux 6.5.4-arch2-1 x86_64

## What went wrong

Floating window borders are not visible, regardless of a custom setting.
The same configuration works for vim.

## Reproducing the bug

1. Ensure `g:ale_floating_window_border` has the default or valid value.
2. Use a command that activates a floating window, like `:ALEHover`

### :ALEInfo
<details>
  <summary>Expand</summary>
  

 Current Filetype: ale-info
Available Linters: []
  Enabled Linters: []
  Ignored Linters: []
 Suggested Fixers:
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 
 Global Variables:
let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_disable_lsp = 'auto'
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'*': ['remove_trailing_lines', 'trim_whitespace']}
let g:ale_history_enabled = 1
let g:ale_info_default_mode = 'preview'
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 1
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_root = {}
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_sign_highlight_linenrs = v:null
let g:ale_type_map = {}
let g:ale_use_neovim_diagnostics_api = 1
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
 
  Command History:

  
  
</details>

**Comment by w0rp** [comment]
Could you attach a screenshot for this? That will make it easier to tell what's going on. You could also try this: https://asciinema.org/ That could help to figure this out.

**Comment by jmcantrell** [comment]
Ok, this is strange. I recorded the problem, but after viewing it on asciinema, the border is visible. I have no idea why, but the border was not visible when recording.

https://asciinema.org/a/5sMk68nEOo394qT847KiFMz5u

**Comment by jmcantrell** [comment]
Hopefully this will show that I'm not insane.

![Screen Shot 2023-09-28 at 6 41 11 PM](https://github.com/dense-analysis/ale/assets/33200/468e6997-aa75-4899-bb34-508894ba621d)

**Comment by jmcantrell** [comment]
Closing, as this turned out to be due to the definition of `hi-VertSplit` (linked to `hl-FloatBorder` via `hl-WinSeparator`), which my colorscheme was setting to `hi VertSplit ctermfg=0 ctermbg=0 cterm=NONE`.
