### ISSUE TITLE
Add fixer for `golangci-lint`

### ISSUE THREAD

**Issue by davidjb** [dense-analysis/ale#4616]
**Name:** `golangci-lint`
**URL:** https://github.com/golangci/golangci-lint

This was previously reported at https://github.com/dense-analysis/ale/issues/2864:

> GoLangCI-lint has a fixer now: `golangci-lint run --fix ./...`
>
> The ALE fixer will have the same issues we're having with the ALE linter.

This original issue was to add a fixer for `golangci-lint` and there may have been some confusion as the issue was closed on account of `golangci-lint` as a _linter_ already existing.

As best I can tell and from what I've tried, `golangci-lint` isn't available as a fixer (e.g. it's not visible in `:ALEFixSuggest` nor has a file listed at https://github.com/dense-analysis/ale/tree/master/autoload/ale/fixers or visible elsewhere in the codebase).

**Comment by sigmavirus24** [comment]
@w0rp if there are some docs on how to contribute this easily, I'd be happy to give it a shot. I also think I'm seeing that there's no way to configure `goimports` with a local prefix.

**Comment by sigmavirus24** [comment]
I think #4853 fixes this. It's my first vim plugin contribution but as far as I can tell, it's passing tests.
