### ISSUE TITLE
ale-info ftplugin doesn't set b:undo_ftplugin

### ISSUE THREAD

**Issue by benknoble** [dense-analysis/ale#4624]
https://github.com/dense-analysis/ale/blob/14350dbb0d265ef87d1c7d420d89fb4165a2b131/ftplugin/ale-info.vim#L1

It is crucial that ftplugin authors set `b:undo_ftplugin` to commands that revert the ftplugin. See the distributed runtime files for examples. My own script generates the following for this plugin:
```vim
let b:undo_ftplugin = get(b:, 'undo_ftplugin', 'execute') . ' | setlocal synmaxcol< | execute "silent! nunmap <buffer> q" | execute "silent! nunmap <buffer> <space>" | delfunction! ALEInfoOpenHelp'
```

I haven't looked at the other ftplugins, but I imagine they are missing similar items.

**Comment by w0rp** [comment]
Thanks for reporting this! I'll fix this eventually, if someone else doesn't fix it first.

**Comment by benknoble** [comment]
I'll add it to my todos. I'm hoping to have some time in a few hours to blitz through some open-source stuff on my list.
