### ISSUE TITLE
Add support for biome

### ISSUE THREAD

**Issue by w0rp** [dense-analysis/ale#4674]
**Name:** biome
**URL:** https://github.com/biomejs/biome

Because JavaScript cannot survive without yet another way of doing things: there's yet another way of doing things. Biome offers support for fixing and formatting code via the CLI and is mostly compatible with `prettier`. It offers a language server for checking code. It shouldn't be difficult to integrate it with ALE.

**Comment by CHeavyarms** [comment]
This probably supersedes #3280 since Biome is the successor to Rome:
https://biomejs.dev/blog/annoucing-biome/

For reference, Biome just won the bounty that Prettier put out for a Rust-based alternative:
https://prettier.io/blog/2023/11/27/20k-bounty-was-claimed
