### ISSUE TITLE
Multiple node processes with large RAM usage on opening file

### ISSUE THREAD

**Issue by Ewan-Roberts** [dense-analysis/ale#4736]
## Information

**VIM version**

NVIM v0.9.5

Operating System: 

MacOs 14.3.1 (23D60)

## What went wrong

As new files are opened in each window a node process starts and increases in RAM usage up to about 4gig of ram each. After about 6 files I run out of RAM

<img width="1728" alt="Screenshot 2024-03-07 at 19 42 37" src="https://github.com/dense-analysis/ale/assets/6106045/78dc9a68-ebd5-419f-b96e-538e64436094">

Here is a screenshot of the node processes. If i close nvim or run ALEDisable the node processes stop 

This is my ALE config
```
let b:ale_fixers = ['prettier', 'eslint']
let g:ale_sign_error  = '>'
" let g:ale_fix_on_save = 1
autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue PrettierAsync
```

## Reproducing the bug

1. I open up nvim
2. I open multiple files
3. many node processes are started

(started) ['/bin/bash', '-c', '''/Users/ewan/Dropbox/Development/application-v3/services/betta/node_modules/.bin/tsserver''']
(executable check - failure) typecheck
(executable check - failure) xo
(executable check - failure) deno
### :ALEInfo
<details>
  <summary>Expand</summary>
 Current Filetype: typescript
Available Linters: ['cspell', 'deno', 'eslint', 'standard', 'tslint', 'tsserver', 'typecheck', 'xo']
  Enabled Linters: ['cspell', 'deno', 'eslint', 'standard', 'tslint', 'tsserver', 'typecheck', 'xo']
  Ignored Linters: []
 Suggested Fixers:
  'biome' - Apply biome (ex. rome) check to a file.
  'deno' - Fix TypeScript using deno fmt.
  'dprint' - Pluggable and configurable code formatting platform
  'eslint' - Apply eslint --fix to a file.
  'prettier' - Apply prettier to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'tslint' - Fix typescript files with tslint --fix.
  'xo' - Fix JavaScript/TypeScript files using xo --fix.
 
 Linter Variables:
let g:ale_typescript_standard_executable = 'standard'
let g:ale_typescript_standard_options = ''
let g:ale_typescript_standard_use_global = 0
let g:ale_typescript_tslint_config_path = ''
let g:ale_typescript_tslint_executable = 'tslint'
let g:ale_typescript_tslint_ignore_empty_files = 0
let g:ale_typescript_tslint_rules_dir = ''
let g:ale_typescript_tslint_use_global = 0
let g:ale_typescript_tsserver_config_path = ''
let g:ale_typescript_tsserver_executable = 'tsserver'
let g:ale_typescript_tsserver_use_global = 0
let g:ale_typescript_xo_executable = 'xo'
let g:ale_typescript_xo_options = ''
let g:ale_typescript_xo_use_global = 0
 
 Global Variables:
let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_disable_lsp = 'auto'
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_info_default_mode = 'preview'
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_root = {}
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = '>'
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_sign_highlight_linenrs = v:null
let g:ale_type_map = {}
let g:ale_use_neovim_diagnostics_api = 1
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 'all'
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
 
  Command History:

(executable check - failure) cspell
(executable check - failure) deno
(finished - exit code 143) ['/bin/bash', '-c', 'cd ''/Users/ewan/Dropbox/Development/application-v3/node_modules/.pnpm/eslint@8.55.0'' && ''/Users/ewan/Dropbox/Development/application-v3/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/bin/eslint.js'' -f json --stdin --stdin-filename ''/Users/ewan/Dropbox/Development/application-v3/services/betta/src/pages/Performance/constants.ts'' < ''/var/folders/rf/8_mxq4_d74v573715qm7xlth0000gn/T/nvim.ewan/W1e8UX/15/constants.ts''']

<<<NO OUTPUT RETURNED>>>

(executable check - failure) standard
(finished - exit code 0) ['/bin/bash', '-c', 'cd ''/Users/ewan/Dropbox/Development/application-v3/services/betta/src/pages/Performance'' && ''tslint'' --format json ''/var/folders/rf/8_mxq4_d74v573715qm7xlth0000gn/T/nvim.ewan/W1e8UX/16/constants.ts''']

<<<OUTPUT STARTS>>>
[]
<<<OUTPUT ENDS>>>

(started) ['/bin/bash', '-c', '''/Users/ewan/Dropbox/Development/application-v3/services/betta/node_modules/.bin/tsserver''']
(executable check - failure) typecheck
(executable check - failure) xo
(executable check - failure) cspell
(executable check - failure) deno
(started) ['/bin/bash', '-c', 'cd ''/Users/ewan/Dropbox/Development/application-v3/node_modules/.pnpm/eslint@8.55.0'' && ''/Users/ewan/Dropbox/Development/application-v3/node_modules/.pnpm/eslint@8.55.0/node_modules/eslint/bin/eslint.js'' -f json --stdin --stdin-filename ''/Users/ewan/Dropbox/Development/application-v3/services/betta/src/pages/Performance/constants.ts'' < ''/var/folders/rf/8_mxq4_d74v573715qm7xlth0000gn/T/nvim.ewan/W1e8UX/25/constants.ts''']
(executable check - failure) standard
(finished - exit code 0) ['/bin/bash', '-c', 'cd ''/Users/ewan/Dropbox/Development/application-v3/services/betta/src/pages/Performance'' && ''tslint'' --format json ''/var/folders/rf/8_mxq4_d74v573715qm7xlth0000gn/T/nvim.ewan/W1e8UX/26/constants.ts''']

<<<OUTPUT STARTS>>>
[]
<<<OUTPUT ENDS>>>

</details>

**Comment by hsanson** [comment]
This happens when ALE is unable to figure out the project root folder. Looking at the code it looks for a `tsconfig.json` file. Try creating a [tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) file in the same or parent folder where the source files are located.  This should cause ALE to start a single node instance for the project instead of for each file.

**Comment by Ewan-Roberts** [comment]
Ah yes that did it thanks!!
