### ISSUE TITLE
Add linter for Purescript

### ISSUE THREAD

**Issue by craigdallimore** [dense-analysis/ale#495]
It would be nice to have a linter for [Purescript](http://www.purescript.org/).

**Comment by d-navas** [comment]
That would be awesome. This is the editor support server that PureScript provides.
https://github.com/FrigoEU/psc-ide-vim

**Comment by w0rp** [comment]
I'll have to do some experimenting with communicating with the TypeScript server. I bet whatever I discover in tinkering with that will be useful here.

**Comment by blueyed** [comment]
Just for reference: https://github.com/neomake/neomake/pull/1194

**Comment by dakom** [comment]
Also, I believe this might be an extension of https://github.com/w0rp/ale/issues/517 due to:

https://github.com/nwolverson/purescript-language-server

**Comment by dakom** [comment]
Started a PR for this: https://github.com/w0rp/ale/pull/1737

It's not working for me yet, but not crashing either ;)

**Comment by mathiajusth** [comment]
Hi, 
if I may ask @w0rp, do you still plan on adding the purescript support?

**Comment by w0rp** [comment]
I haven't ever planned on adding support for it myself. Someone else can pick it up some time if they are interested. I just review pull requests, manage issues, and mostly work on the core of ALE itself.

**Comment by hdgarrood** [comment]
I think this can be closed now that #2572 has been merged?

**Comment by w0rp** [comment]
Sure. Thanks!
