### ISSUE TITLE
Wrong elements highlighted when using tabs instead of spaces (at least on LaTeX)

### ISSUE THREAD

**Issue by jackgu1988** [dense-analysis/ale#723]
This seems a bit obvious but I did not find any related reports. I am suspecting I may have missed something or have something wrong in my .vimrc. Here is my .vimrc: https://github.com/jackgu1988/dotfiles/blob/master/vimrc

When I am using tabs on LaTeX and there is an error or a warning on a line, the wrong element is highlighted. For example here, the opening parenthesis bracket should have been highlighted because there is no space before it (line 88):

![untitled](https://user-images.githubusercontent.com/1506732/27824119-469e6d5c-60a3-11e7-9645-59927815e3fc.png)

When I replace tabs with spaces it works just fine.
Is it my fault, or is it a bug?

**Comment by w0rp** [comment]
Maybe the LaTeX linter converts tabs into spaces before it presents the column numbers.

**Comment by jackgu1988** [comment]
A dirty solution is to create a `.chktexrc` file in the project's directory and add this line: `TabSize = 1`. Not perfect, but does the job.

**Comment by w0rp** [comment]
I would like to propose a solution for this.

1. Before returning the command for `chktex`, run through the lines in the file and store information about indentation for every line in a buffer variable, and the setting for `TabSize` from the configuration file, which can default to `8`.
2. When handling the errors, adjust the column number with the information stored before.

It would take some tinkering, but it would be easy to cover with tests.

**Comment by jackgu1988** [comment]
This could slow vim down if the LaTeX file is huge (not uncommon). To me it sounds more like an issue that needs to be fixed in `chktex` and not here. However the development on that side seems to be very slow, and implementing such thing could take time as it affects many parts of the program.

**Comment by w0rp** [comment]
There probably wouldn't be a noticeable performance hit. Add a call to copy the lines in the file, which is pretty quick, and then only compute the offset for lines with problems.

**Comment by jackgu1988** [comment]
It depends on the writing style. Many people prefer writing a paragraph per line, and very often there are tens of warnings per line. I have also seen many people who get warnings almost on every line (many don't use `chktex` so they make common mistakes, like writing 'etc.' instead of 'etc.\', or not putting '~' before a citation or a reference). Warnings will not prevent the file from compiling, and usually won't even be noticeable unless you look really closely on the PDF.

Very often working on LaTeX means collaborative work. Fixing all the warnings that someone else who is not using a linter left is too time consuming and they keep accumulating. So, if for each warning the offset has to be computed, the performance cost might not be that low.

**Comment by w0rp** [comment]
If you see warnings you don't intend to fix, you should disable them. If you intend on fixing them, then you should fix them, and you should force your colleagues to check the files for the same warnings.

**Comment by jackgu1988** [comment]
The problem with LaTeX is that most people are working on Overleaf when collaborating, which gives you very few warnings, so people usually don't even realise that something is wrong. Fixing them is really hard because of how Overleaf works (if you have used it offline while people are working online you will know). LaTeX is a tricky one. Everyone seems to be using a different writing style and no one is willing to change it.
