### ISSUE TITLE
Add support for sass

### ISSUE THREAD

**Issue by andrewminer** [dense-analysis/ale#926]
I see that there is already support for a variety of CSS / SASS linters, but I can't find anything which actually validates the validity of the SCSS code itself.  For example, even with the various `sass` linters installed, the following wouldn't trigger any errors, even though the `$font-foo` variable is undefined and causes a SASS parsing error:

``` scss
body {
    font-family: $font-foo;
}
```

The SASS executable does have a `--check` option to only validate (no emitting CSS), so I would expect (from what I can tell) that it shouldn't be a difficult integration.

**Comment by w0rp** [comment]
> ... I would expect (from what I can tell) that it shouldn't be a difficult integration.

Famous last words.

**Comment by dakom** [comment]
Would this be possible via the LanguageServer support here? https://github.com/Microsoft/vscode-css-languageservice

Would that bring auto-completion too?

**Comment by realestninja** [comment]
How exactly do I enable linting for sass files?

**Comment by realestninja** [comment]
How exactly do I enable linting for sass files?

**Comment by neersighted** [comment]
All supported linters are enabled by default, if installed. Check `:help ale-sass` for more details on what is supported.

GitHub issues is not really the proper place for tech support. Feel free to hop on gitter to get help with configuring ALE, or ask a question on Stack Exchange if your problem is more with Sass linters in general.

**Comment by realestninja** [comment]
Thanks for your quick response. I checked again today and noticed that 6days ago there was a [commit](https://github.com/w0rp/ale/commit/2760cf7018893b42c4ae5c750a7f1d38669aa821) that made my settings work. I just had to update my ALE. That commit might solve this issue in general. 

PS: Great Plugin!

**Comment by eredi93** [comment]
I was wondering if there was any updates on this. If someone could give me a few pointers I could try to put a PR together

**Comment by andrewminer** [comment]
Stylelint (and several other options) are supported at this point.  Just open a `.scss` file with ALE installed and run `:ALEInfo`.  You should see a few lines like this at the very top:
```
Available Linters: ['sasslint', 'scsslint', 'stylelint']
  Enabled Linters: ['sasslint', 'scsslint', 'stylelint']
```
The first shows those which are supported, and the second those which are currently turned on.  If you have any of those available on your path, ALE will run them for you.
