### ISSUE TITLE
Add clangcheck to the pure c linters

### ISSUE THREAD

**Issue by gagbo** [dense-analysis/ale#976]
As of today, I added `clang-check` support only for cpp files, because I didn't feel the need for it in c files, and because all [the example on llvm's website](http://clang.llvm.org/docs/ClangCheck.html) did not hint towards use for C files.

I don't know if the tools are really meant to be used for C (but I see no reason why not), so porting the tool to C is mostly harmless I guess.

TODO : 
- Create the `ale_linters/c/clangcheck.vim` file from the `cpp` version
- Change the last call to define to add a c linter instead of a cpp linter
- Change the naming of the options accordingly
- Write the doc

I'll do it when I have time and/or if it becomes really important somehow. But this will surely comes after finishing with #725

**Comment by tbodt** [comment]
clangcheck is indeed intended to be used for both C and C++.
